### ISSUE TITLE
want to see  flows from a particular host that send flows 

### ISSUE THREAD

**Issue by talassa2004** [ntop/ntopng#105]
Hello guys i have configured ntopng  as a collector  only  to receive  flows from all  network device
how can i see flow only  from a  selected device   
 
in other words i  don't know how to  to  tell the system  to  show me   a particular  flows that comes from a specific   network  device that send the flows 

my config is  like that  

nprobe --zmq "tcp://*:5556" -i none -n none --collector-port 3002 -V 5 -b 2 
ntopng -i tcp://127.0.0.1:5556
     
any help will  be approciate

**Comment by lucaderi** [comment]
In nProbe you can add to your template (-T) the information element(s)
[130] %EXPORTER_IPV4_ADDRESS      %exporterIPv4Address      	Exporter IPv4 Address
[131] %EXPORTER_IPV6_ADDRESS      %exporterIPv6Address      	Exporter IPv6 Address

so that in ntopng you can see how has sent you the flow. Currently in ntopng there is no way to filter flows per collector device.

What I suggest is
1. start multiple nprobe instances on different collection ports, where each nProbe collects flows from a single device
2. add in ntopng multiple -i tcp://.... ingress devices so that you can split traffic per interface. If you want to have a global aggregated view in ntopng, you can use the view:... interface.
