### ISSUE TITLE
Enhance Host Pool Stats

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1097]
The /lua/pool_stats.lua should be enhanced by adding further stats (that ntopng keep internally) such as nDPI stats and time stats. 

This is useful to understand what happens and to debug issues, in inline mode, when specific thresholds are reached.

**Comment by emanuele-f** [comment]
In order to keep a consistent look (e.g. with the networks), the stats will be implemented as a separate tab in the pool_details.lua, which is accessed by the graph icon of the pool. The tab will only be available in inline mode and it will show in a simple table with the following columns: protocol/category, time and time quota, bytes and bytes quota.

A pool overview page will not be provided in this implementation.

**Comment by emanuele-f** [comment]
What about this? I've added simple breakdown bars to represent the situation. The red text spots a quota limit reached.

![quotas](https://cloud.githubusercontent.com/assets/5488003/24453052/90482cd6-1486-11e7-9bd1-50e42e476675.png)

**Comment by emanuele-f** [comment]
Implemented with 42904dd0344a9a9a37e1c651cea0004357fe5a96
