### ISSUE TITLE
Quota Buttons are Disabled

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1110]
![screen shot 2017-04-01 at 09 01 36](https://cloud.githubusercontent.com/assets/4493366/24576300/d66cfa90-16b9-11e7-9378-9cbf17896a4b.png)

1. On the default protocols no quota buttons should be displayed
1. On on-default protocols quota buttons are disabled

**Comment by emanuele-f** [comment]
Quota buttons are disabled for non-default protocols only in the "Not Assigned" Host Pool. In manually created pools, they are enabled.

In order to enable quota for "Not Assigned" Host Pool, we also have to compute the "Not Assigned" Host Pool statistics, which currently are not available. Moreover, since the quota statistics are accessed by the graph icon on the Host Pools page, we should also enable the "Not Assigned" Host Pool statistics dump to redis to keep things consistent with other Host Pools.

**Comment by emanuele-f** [comment]
Implemented in d8d0d4e3817f4f82c0cfa7897a95fad34f002047
