### ISSUE TITLE
Add Traffic Direction in Network Interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1114]
In ntopng all traffic does not have a direction as libpcap (used in case of no other means work) does not report traffic direction (RX or TX with respect to the interface). 

It is requested to add RX/TX as property to each packet so that we know if this is ingress or egress traffic. PF_RING has this feature of knowing traffic direction. In case were are not aware of the direction we assume RX.

See http://stackoverflow.com/questions/14454077/finding-the-direction-of-packets-while-sniffing for more details.

Done this, the chart in the ntopng footer must be changed to RX vs TX, and add a breakdown in the interface chart (and likely hosts and MACs too)

**Comment by emanuele-f** [comment]
With libpcap it's only possible to know the direction of the packets in linux cooked mode (see https://github.com/the-tcpdump-group/libpcap/issues/127, see `tcpdump -e -n -i any`). Since PF_RING already provides this information, in my opinion we should suggest the installation of the PR_RING module for community users (packed versions already have this), make the footer always show in and out directions as reported by pf_ring or, where the PF_RING module has not been installed by the community users, the footer chart should be hidden.

**Comment by simonemainardi** [comment]
- create a method iface->supportsTXRX().
- change the footer double graph to chart TX and RX if iface->supportsTXRX() else hide it
- replace the clouds with text TX and RX to make it clear what is the chart referring to
- see if tx and rx can be red from /proc when not available

**Comment by simonemainardi** [comment]
recall that interfaces have the option "Mirrored traffic"

![image](https://user-images.githubusercontent.com/3397663/50912981-a7a4e500-1433-11e9-8a01-f332ee72a4b6.png)


in this case the TX/RX must be obviously missing.

**Comment by emanuele-f** [comment]
Implemented in 123743d49c3690c4cbe3abd517b5c3552b864b27 and 08a8c67966a5f7397faa2190d1a9f9bab519a850
