### ISSUE TITLE
1Month report results for top local hosts totals incorrect

### ISSUE THREAD

**Issue by thegeodave** [ntop/ntopng#1123]
Reports totals for 1Month or more are incorrect.  See attached below.

My true need here is to have a report of ALL LOCAL HOST TRAFFIC totals for a 30 day period or the last 30 days. (not just the top 10 local hosts). Seems it would be best to implement this on the main menu's Hosts/Hosts report page.   But this would probably be considered a request vs a bug. I can say that when I restart ntopng, it resets all the traffic totals on the Hosts/Host output to ZERO. It would be nice to not have it reset the totals  and instead allow to choose the beginning time period instead whatever its doing now (last seen or total since the program started)

![hour](https://cloud.githubusercontent.com/assets/25374047/24674185/72d07d86-192f-11e7-8d04-accdcfeaa272.png)
![week](https://cloud.githubusercontent.com/assets/25374047/24674197/7d2ca34a-192f-11e7-932e-6a2227f173c3.png)
![month](https://cloud.githubusercontent.com/assets/25374047/24674198/7f4569e6-192f-11e7-8e2a-0a2f9c1ac3e4.png)

**Comment by simonemainardi** [comment]
@thegeodave, we did some changes recently to the top talkers so the issue should be fixed now. The fact that you are experiencing issues with week and month reports may be due to the fact that that data has been crunched and stored BEFORE the latest changes.

So here you have two options:
- wait a few days and see if weekly/monthly reports start generating properly
- send us the top talkers database /var/tmp/ntopng/45/top_talkers/top_talkers.db for inspection -- substitute 45 with the interface id of interest
- by the way, are you generating reports from an interface view?

-----------

As per your question, if you want an exhaustive, exact, and not heuristically-approximated list of top talkers, you have the following options
- enable MySQL export and drill down data through the historical data explorer.
- get an enterprise license demo and generate daily/weekly/monthly reports for each local hosts

**Comment by simonemainardi** [comment]
@thegeodave do you have any feedback?

**Comment by simonemainardi** [comment]
Possible solutions given. No feedback received in 16 days. Closing.
