### ISSUE TITLE
Misleading Host Pool Report Implementation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1138]
![screen shot 2017-04-06 at 13 17 14](https://cloud.githubusercontent.com/assets/4493366/24751840/6081c5d4-1acb-11e7-8812-62e69381de12.png)
Inside the  host pools definition window (see attachment) I expect to 
- see a gauge that reports (in case of quota defined) the remaining percentage of allowed traffic 
- an icon with an hyperlink to the host pool quota/details 

As of today, users can be confused as it's a hard to find feature (if working at all as reported in #1137)

**Comment by emanuele-f** [comment]
Changes implemented into 73528f792775ef67158efe07d7b6497bc2f300ef.

![screenshot at 2017-04-11 20-35-48](https://cloud.githubusercontent.com/assets/5488003/24924948/ed979f1e-1ef6-11e7-8cf4-33f770b9aabd.png)

Please reopen if necessary.

**Comment by simonemainardi** [comment]
* The unit of measurement is missing (looks like it wraps):

![image](https://cloud.githubusercontent.com/assets/3397663/25006247/7c08881a-205c-11e7-8cd6-5df2b5b7bb59.png)

* The current quota used text is poorly aligned (it should not wrap)

![image](https://cloud.githubusercontent.com/assets/3397663/25006293/acb7a572-205c-11e7-9768-f3737dafdd81.png)

* When selecting a protocol/category from the dropdown, the ajax should start refreshing the quota bars, even if quotas are not set.

* Possibly change "Daily traffic quota" with "Daily Traffic" and split it in two subcolumns, namely, "Current" and "Quota". Same for "Daily Time Quota."

**Comment by emanuele-f** [comment]
With commit 2657357ab82f54a3fbf6f07552aef3e0ae4ddd55 I've done the following improvements:
- quota text has been added above the bar since unwrapping the text inside is not possible
- bars are filled with statistics even if no quota is set for the given protocol (your 3rd point). This only applies to protocols which have been seen by ntopng (those who have an entry into the ndpistats, see 3rd vs 4th line in the screenshot)

![screenshot at 2017-04-13 20-06-24](https://cloud.githubusercontent.com/assets/5488003/25017621/c4afb8fe-2084-11e7-8e54-89fe1729cfd7.png)

Splitting into more columns will take up too much space, we should avoid it.

**Comment by simonemainardi** [comment]
how can you fill the bars,  I quote,  "with statistics even if no quota is set for the given protocol"?

To progressively fill a bar you need a maximum. What is the 100% of an unset quota?

**Comment by emanuele-f** [comment]
I mean, the statistics are shown above the bar, not inside the bar. When no quota is set, "unlimited" is shown next to the current traffic (see time quotas in the screenshot above)

**Comment by emanuele-f** [comment]
So, can this be closed?

**Comment by simonemainardi** [comment]
yes
