### ISSUE TITLE
traffic policy: protocol priority 

### ISSUE THREAD

**Issue by ValentinaViscarelli** [ntop/ntopng#1142]
The policy applied to a protocol should have priority over the default policy.
If you apply the configuration reported in the screen shot the http traffic doesn't pass. 
![welcome to ntopng - google chrome_038](https://cloud.githubusercontent.com/assets/13115771/24810910/584a941e-1bc4-11e7-9c20-d892cefc9c31.png)

**Comment by simonemainardi** [comment]
Issue has been fixed by waiting the completion of protocol detection before issuing a drop verdict for a flow.

Indeed, what was happening was that nDPI wasn't able to detect HTTP at the first packet so the flow wasn't able to go through.

Also note that, in order to have HTTP working, you should also have at least DNS/SSL enabled as well or the normal web navigation would very likely be affected in a negative way.

![image](https://cloud.githubusercontent.com/assets/3397663/24854150/a5ab34dc-1ddd-11e7-892d-11b8b4815457.png)
