### ISSUE TITLE
Timestamp from "pcapng" files are wrong

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1222]
When reading the packets from a .pcapng file, the timestamps extracted in PcapInterface.cpp are wrong.
To reproduce set a Breakpoint in PcapInterface: static void* packetPollLoop(void* ptr) and check the values of the "hdr.ts" after call to 'pcap_next_ex' (please see the picture attached)
![pcapng_wrong_ts](https://cloud.githubusercontent.com/assets/28054776/25800478/d4143464-33e9-11e7-9c67-2e40d8135712.jpg)

Since the timestamps of all the packets are wrong, this will also create a crash when sending the flow to ElasticSearch.

Testing under Ubuntu 16.04.1. Debugging with NetBeans.
Ntopng: ntopng x86_64 v.2.4.170508 - (C) 1998-2016 ntop.org

**Comment by emanuele-f** [comment]
I can you provide a pcapng file? On latest ntopng version (2.5.170509) I'm not able to reproduce the issue with a sample pcapng I've created.

**Comment by ghost** [comment]
Hi Emmanuele, thanks for your fast response, it seems it happens only with certain pcapng files like the one I am trying to include here but it does not allow me, can you provide me an email address to send it?
I am testing it in the latest stable release of ntopng (2.4.stable)
The problem seems to come from libpcap.

**Comment by emanuele-f** [comment]
Hi, please send me the pcap at faranda@ntop.org

**Comment by ghost** [comment]
Ok I already sent you an email with the pcapng file to test it

**Comment by emanuele-f** [comment]
With the provided pcap file, the function `pcap_open_offline` from libpcap returns the error `Invalid interface capture length 4294967295, bigger than maximum of 262144`. See https://github.com/the-tcpdump-group/libpcap/issues/527 for a similar issue.

Since opening the pcap file with wireshark actually works and packet data can be read properly, I give you the same advice as reported in the link above: ask you pcap-generating program vendor to fix the exporting format.

I've also notice that if I load the provided pcapng file with wireshark and then export it to a standard pcap file, the exported pcap can be read without any problems, so you can perform this additional step before feeding the pcap to ntopng to bypass the problem.

**Comment by ghost** [comment]
Thanks for your help Emmanuele. The problem seems to be somewhere in the pcapng header, however it doesnt seem to be the Snaplen as pointed in the link above. I will further investigate.
Best regards
