### ISSUE TITLE
"Top Application Traffic Last Day View" empty

### ISSUE THREAD

**Issue by mahescho** [ntop/ntopng#1265]
For me "Top Application Traffic Last Day View" does not get updated. The graph area is empty.

ntopng Pro [Small Business Edition] v.2.5.170524

**Comment by emanuele-f** [comment]
Hi, can you your full ntopng log from startup? If you run ntopng as a service, it should be located at `/var/log/ntopng/ntopng.log`

**Comment by mahescho** [comment]
Sorry :-) you want me to send my ntopng.log to you, right?

**Comment by emanuele-f** [comment]
Yes, sorry I've missed the "post" word :)

**Comment by mahescho** [comment]
sent by mail

**Comment by emanuele-f** [comment]
I've just committed a patch to the error shown in the log, which is the cause of your issue.
A new build will be available in one hour, please update, restart ntopng and check the new log file for this error:
```
26/May/2017 06:45:01 [Lua.cpp:6078] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:1806: attempt to index local 'alert_source' (a nil value)]
```

If you don't see it any more, then the problem is fixed and since tomorrow you will be able to see last day view correctly updated.

**Comment by mahescho** [comment]
error is gone, I will report back tomorrow about the data

**Comment by mahescho** [comment]
"Top Application Traffic Last Day View" shows the first data. Problem solved, thanks!

**Comment by emanuele-f** [comment]
Thank you
