### ISSUE TITLE
Update hangs for ever

### ISSUE THREAD

**Issue by mahescho** [ntop/ntopng#1342]
I've upgraded NtopNG and now I get for ever:

Database schema migration in progress, waiting for database ntop to become operational. You will be redirected as soon as the database is ready. Depending on the size of the existing database, this operation can take a long time. Migrations are performed only once and only during major version upgrades.

At first I found MySql to use 60 to 80% CPU but for about 2 hours this has stopped and nothing special happens on the machine.

**Comment by simonemainardi** [comment]
@mahescho that happens only the first time after a major update and it is due to internal mysql schema changes.

Please, make sure the machine has at disk space available al least equal to 2x the current size of the MySQL database. Indeed, mysql requires to copy the tables when performing `ALTER`s.

You can check the operations currently performed in MySQL simply by logging into a mysql shell and issuing a `SHOW PROCESSLIST`

**Comment by mahescho** [comment]
Disk space was the issue, thanks.

**Comment by simonemainardi** [comment]
thanks for reporting
