### ISSUE TITLE
Add per host time series with number of active flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1375]
As we have num_flows.rrd per network interface, it is requested to create the same num_flows.rrd time series per host that will contain the number of active flows for each host

**Comment by simonemainardi** [comment]
implemented.

**Comment by lucaderi** [comment]
The code seems to be bugged as the RRD num_flows.rrd is a GAUGE with ever increasing values instead of a COUNTER.

**Comment by simonemainardi** [comment]
thanks for reporting.

Actually GAUGE is correct as we want to chart that number of active flows. The bug was that the total number of host flows was used rather than the number of its active flows.

![image](https://user-images.githubusercontent.com/3397663/28851116-dbf6cda2-7720-11e7-911b-dde58907215f.png)


I also noticed (and fixed) some wrong RRA specifications in rdd creation functions that were leading to larger-than-necessary files:

```
Simones-MacBook-Pro:ntopng simone$ ls -lha /var/tmp/ntopng_old/10/rrd/num_*.rrd
-rw-rw-rw-  1 simone  wheel   695K Aug  2 00:02 /var/tmp/ntopng_old/10/rrd/num_devices.rrd
-rw-rw-rw-  1 simone  wheel   695K Aug  2 00:02 /var/tmp/ntopng_old/10/rrd/num_flows.rrd
-rw-rw-rw-  1 simone  wheel   695K Aug  2 00:02 /var/tmp/ntopng_old/10/rrd/num_hosts.rrd
-rw-rw-rw-  1 simone  wheel   695K Aug  2 00:02 /var/tmp/ntopng_old/10/rrd/num_http_hosts.rrd
Simones-MacBook-Pro:ntopng simone$ ls -lha /var/tmp/ntopng/10/rrd/num_*.rrd
-rw-rw-rw-  1 simone  wheel    31K Aug  2 00:06 /var/tmp/ntopng/10/rrd/num_devices.rrd
-rw-rw-rw-  1 simone  wheel    31K Aug  2 00:06 /var/tmp/ntopng/10/rrd/num_flows.rrd
-rw-rw-rw-  1 simone  wheel    31K Aug  2 00:06 /var/tmp/ntopng/10/rrd/num_hosts.rrd
-rw-rw-rw-  1 simone  wheel    31K Aug  2 00:06 /var/tmp/ntopng/10/rrd/num_http_hosts.rrd
```

**Comment by simonemainardi** [comment]
references are
cdb4235380a0f1d4f5c681cdbb18661c5fff4e98
9918a14dc25a030a275d32ada1eaf28b89b014f3
