### ISSUE TITLE
Missing time series from graphs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1377]
A given device has many L7 timeseries but on the drop-down menu only a few protocols are listed. Tested with the current ntopng 3.1.170726

<img width="1084" alt="screen shot 2017-07-26 at 17 59 35" src="https://user-images.githubusercontent.com/4493366/28631056-45787392-722c-11e7-8311-aa159e494102.png">
<img width="829" alt="screen shot 2017-07-26 at 17 59 23" src="https://user-images.githubusercontent.com/4493366/28631057-458ea6bc-722c-11e7-9917-aef1f2572a9a.png">

**Comment by simonemainardi** [comment]
@lucaderi by design, only RRDs that have a last_update greater than or equal to the chart start time are listed. 

see this line:
https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/graph_utils.lua#L111

In your particular example, it means that those listed in the screenshot are the only protocols which have used during the last 10 minutes.

I think this is the right approach as we don't pollute the UI with selectable entries that will lead to blank charts.

However, if you want to change this choice, please indicate how.

**Comment by lucaderi** [comment]
@simonemainardi Please add a note that describes this behaviour are the way it is implemented is misleading
