### ISSUE TITLE
Upgrading to newest version of ntopng, ndpi

### ISSUE THREAD

**Issue by Kazz3r24** [ntop/ntopng#1384]
I've been meaning to look into this issue for a long time, I just keep forgetting about it.

Right now I'm running an ancient version of ntopng, I believe that my pfring, nprobe, and nbox are reasonably up-to-date (don't take my word for it), I was only ever able to successfully get ntopng on my distro version with the older ntopng. I'd like to upgrade it if possible without breaking everything including what's already set up elsewhere on my system.

Ubuntu 14.04 x64
ntopng v.1.2.1 (r1.2.1)

Is there a command that can be used to upgrade ntopng? Or is the community version I'm using as good as it gets for Ubuntu 14.04 support?

Thank you again, brilliant piece of software!

**Comment by simonemainardi** [comment]
Many things have changed in ntopng since version 1.2.1. So there may be minor compatibility issues when upgrading to 3 or 3.1, especially with reference to the RRD stored in the system and with the MySQL database that will require an update.

Apart from that, it should be safe to upgrade. If you are using a packaged ntopng version just run apt-get update && apt-get upgrade.
If you are building from source you can run make uninstall && ./autogen.sh && ./configure && make install with an updated sources tree.
