### ISSUE TITLE
ERROR: Cannot complete local hosts RRD dump in 5 minutes

### ISSUE THREAD

**Issue by anilkumarnaik** [ntop/ntopng#1389]
below errors are filling the log file..how to fix this? 

[@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.

**Comment by simonemainardi** [comment]
You have to reduce the number of local hosts defined and there is not enough time to dump statistics for all the monitored local hosts. Typically, no more than 100 hosts can be dumped per second due to the RRD i/o bottleneck. We will leave rrds in the future.

please use the search before posting new issues: https://www.google.it/search?hl=it&q=%22Cannot+complete+local+hosts+RRD%22+site%3Ahttps%3A%2F%2Fgithub.com%2Fntop%2Fntopng&meta=
