### ISSUE TITLE
Can't login at web interface

### ISSUE THREAD

**Issue by henriqueps** [ntop/ntopng#1409]
Hi,
After server reboot I'm no able to login at ntopng web interface.
I start the service, the web page load, but when I type my login and password nothing happens.
I've already upgraded it to last version 3.1.170821, but nothing change.
Any suggestion what is going on?
Thanks in advance

**Comment by emanuele-f** [comment]
What browser are you using? Do you have any javascript blocking plugin enabled? Please try to flush the browser cache and retry.

**Comment by henriqueps** [comment]
I tried to access from different computers and at all of them I was not able to login.
Also I tried to create a new mysql database, but didn't work.
I enabled debug mode, when I try to login, it shows me this logs:
``
22/Aug/2017 09:21:08 [Lua.cpp:5541] ntop_lua_http_print() called
22/Aug/2017 09:21:08 [Lua.cpp:5541] ntop_lua_http_print() called
22/Aug/2017 09:21:08 [Lua.cpp:5541] ntop_lua_http_print() called
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/bootstrap/css/bootstrap.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/bootstrap/css/bootstrap-theme.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/font-awesome/css/font-awesome.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/jquery-ui.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/dc.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/rickshaw.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/flags.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/pie-chart.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/cal-heatmap.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/nv.d3.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/c3.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/bootstrap-duallistbox.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/bootstrap-slider.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/bootstrap-nav-wizard.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/ntopng.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/bootstrap-datetimepicker.css
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/jquery.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/jquery-ui.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/bootstrap/js/bootstrap.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/bootstrap-datatable.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/bootstrap3-typeahead.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/datatable_utils.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/d3.v3.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/jquery.peity.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/rickshaw.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/pie-chart.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/gauge.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/crossfilter.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/validator.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/dc.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/cal-heatmap.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/springy-ntop.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/springyui-ntop.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/c3.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/nv.d3.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/ays_utils.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/jquery.are-you-sure.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/jquery.bootstrap-duallistbox.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/bootstrap-slider.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/moment.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:723] [HTTP] Serving file /usr/share/ntopng/httpdocs/js/bootstrap-datetimepicker.js
22/Aug/2017 09:21:08 [HTTPserver.cpp:407] [HTTP] redirect_to_login()
22/Aug/2017 09:21:08 [HTTPserver.cpp:701] [HTTP] /lua/login.lua [/usr/share/ntopng/scripts/lua/login.lua]
22/Aug/2017 09:21:08 [Lua.cpp:3964] ntop_get_dirs() called
22/Aug/2017 09:21:08 [Lua.cpp:3964] ntop_get_dirs() called
22/Aug/2017 09:21:08 [Lua.cpp:258] getCurrentInterface() called
22/Aug/2017 09:21:08 [Lua.cpp:108] NULL interface: did you restart ntopng in the meantime?
22/Aug/2017 09:21:08 [Lua.cpp:3964] ntop_get_dirs() called
22/Aug/2017 09:21:08 [Lua.cpp:2836] ntop_get_ndpi_protocols() called
22/Aug/2017 09:21:08 [Lua.cpp:2854] ntop_get_ndpi_categories() called
22/Aug/2017 09:21:08 [Lua.cpp:4017] ntop_get_info() called
22/Aug/2017 09:21:08 [Lua.cpp:5541] ntop_lua_http_print() called
``

**Comment by emanuele-f** [comment]
Please try to reset the password to the default:

1) stop ntopng: `sudo killall ntopng`
2) `redis-cli del ntopng.user.admin.password`
3) start ntopng
4) try to login with user "admin" and password "admin"

**Comment by henriqueps** [comment]
It worked!!!
Thanks a lot emanuele!!

Have a nice week

**Comment by emanuele-f** [comment]
Glad it worked. Bye :)

**Comment by myfingerhurt** [comment]
I'm working on a VPS, because I don't want to expose the ntopng port:3000 to the outer-world,  so I use zerotier to secure it. But I can not login at the web insteface except the external IP. And I saw lots of people had the same problem without a solution. 

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

I have two networks: 
`ens3` with IPv4 and IPv6,  `150.x.x.x` , `2400:8500:1302:844:150:xx:xxx:xx`
`zt0` (zerotier). `10.9.8.10`

First I tried `sudo apt-get install ntopng`  

Access from external IPV4 `150.x.x.x` is good, haven't tested on IPv6, can log in with default user and password admin/admin.
Access from zerotier network can open the page but can not log in. 
I thought that version v2.3 was too old, so I uninstalled it by `sudo apt-get remove --purge ntopng`

And did everything as here said: `http://packages.ntop.org/apt-stable/`

Now I'm using this version.
```
~$ sudo ntopng -V
v.3.0.170826 [Enterprise/Professional Edition]
GIT rev:   3.0-stable:8e2a7438a8be70a2209f08cd44940d93bd018230:20170826
Pro rev:   r1101
System Id: A862BE2100030821
Built on:  Ubuntu 16.04.3 LTS
```

Start ntopng listen to the localhost,
`~$ sudo ntopng  -w:3000 --verbose 6`

add a forward rule to iptables 
`sudo iptables -t nat -A PREROUTING -d 10.9.x.x -p tcp --dport 3000 -j DNAT --to-destination 127.0.0.1:3000`

The same thing happens,
`http://10.9.8.10:3000`
zerotier network can open the page but can not log in with default user and password admin/admin. 

Here is the log
[ntopng_localhost_3000.txt](https://github.com/ntop/ntopng/files/1255198/ntopng_localhost_3000.txt)

--------------------------------------------------------

Start ntopng again listen to all address,
`~$ sudo ntopng  -w 3000 --verbose 6`
Delete iptables forwarding rules
`sudo iptables -t nat -D PREROUTING -d 10.9.x.x -p tcp --dport 3000 -j DNAT --to-destination 127.0.0.1:3000`

`http://150.x.x.x:3000`
Can log in with default user and password admin/admin.
`http://10.9.x.x:3000`
Can open the page but can not log in


Here is the log with --verbose 6, about the LICENSE ERROR --community, I have tried that too, but ntopng outputs blank and nothing.
[ntopng_all_3000.txt](https://github.com/ntop/ntopng/files/1255199/ntopng_all_3000.txt)

**Comment by mickgb256** [comment]
@emanuele-f 
Thank god for your post. 
2hrs ago I started this battle with ntopng looking through article after article then I find your post here and it works. 8yrs on its still solid advice! You are appreciated.
