### ISSUE TITLE
Packages for Debian

### ISSUE THREAD

**Issue by mmonka** [ntop/ntopng#144]
It would be very great to have an nprobe binary version for debian version wheezy/7.x

I tried to install the ubuntu deb packages, but their are to few dependencies.

**Comment by lmangani** [comment]
Note taken Markus, we are working on this - meanwhile closing this nprobe request to keep ntopng tracker clean.

**Comment by lucaderi** [comment]
They are now available (nightly builds) at http://packages.ntop.org/apt/

**Comment by emailhoc** [comment]
Dear Sir
My server is running debian 7. Could you help me the repository link of nprobe for debian 7?

thanks all

**Comment by mmonka** [comment]
Hi,

You need debian 8/ jessie.

Best regards
 Markus

**Comment by iber-mi** [comment]
Hello, there is no way nProbe when installing Debian 7/ wheezy? It would be very necessary, thank you.

**Comment by lucaderi** [comment]
You can use this http://packages.ntop.org/debian/jessie/x64/nprobe/nprobes

**Comment by iber-mi** [comment]
This is not a .deb I install debian 7?

**Comment by lucaderi** [comment]
it is a static binary. Please use it or move to v8

**Comment by iber-mi** [comment]
Thanks, i've already run with ./nprobes, it seems to run fine and tells me good collection of Flow collection, but I can not visualize it in ntopng as nProbe are different commands to use? The ntopng indicates 0 flows.

14/Mar/2016 09:51:11 [nprobe.c:2596] Flow collection: [collected pkts: 31][processed flows: 643]

**Comment by iber-mi** [comment]
I mark this error: ./nprobes: unrecognized option '--zmq', and when the nProbe is installed appears this:

14/Mar/2016 11:07:51 [util.c:4012] Initializing ZMQ as server
14/Mar/2016 11:07:51 [util.c:4055] Succesfully created ZMQ endpoint tcp://*:5557

seems not nprobes server does not start ZMQ, you have any idea how to fix it?

**Comment by iber-mi** [comment]
nprobes --zmq not recognize the option, making a --help not seem that option, however in nProbe if. For serving nprobes then? Is there any way to activate --zqm binary nprobes?

**Comment by lucaderi** [comment]
ZMQ is supported in Debian packages. 

> ./nprobe --help|grep zmq
> --plugin-notify                     | In case plugin(s) are enabled and --zmq is used
> --zmq <socket>                      | Deliver flows to subscribers connected to the specified endpoint.
> --zmq-probe-mode                    | By default nProbe in ZMQ mode acts as a server with subscribers
>                                     | reverted (i.e. use ntopng --zmq-collector-mode).
> ./nprobe --version

Welcome to nProbe v.7.3.160314 (r4935) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-16 ntop.org

Build OS:      Debian GNU/Linux 8.2 (jessie)
SystemID:      12F54F8A00000789
License:       Invalid nProbe license (/etc/nprobe.license) [Missing license file]

I think you are missing the license for the export plugin or you have nProbe with non-pro license. If you want to test this option, please move the probe license (in case you have one) on a safe place, so nprobe will work in demo mode.

**Comment by iber-mi** [comment]
You told me to download this file: http://packages.ntop.org/debian/jessie/x64/nprobe/nprobes

and I do not appear this, look:
 ./nprobes --help | grep ZMQ
--json-labels                       | In case JSON label is used (e.g. with ZMQ)

./nprobes --version

Welcome to nProbe v.7.3.160314 (r4935) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-16 ntop.org

Build OS:      Debian GNU/Linux 8.2 (jessie)
SystemID:      3BDE719076066AF2
License:       Invalid nProbe license (/etc/nprobe.license) [Missing license file]

It is the correct version? Because ZMQ appears to you and not me?

**Comment by lucaderi** [comment]
The static binary does not have ZMQ support only the packaged version. This because on Debian 7 there is no ZMQ3 package.

**Comment by iber-mi** [comment]
I think he is wrong, not since when, but we are the ZMQ3 packages for Debian 7 I have installed but not yet detected the ./nprobes ZMQ me, I can do to make me work on Debian 7? I can not actaulizar to version 8 because I would stop working some php servers in Debian 8 does not work yet.

Look, ZMQ3 packages for Debian 7 Official: https://packages.debian.org/source/wheezy-backports/zeromq3

**Comment by lucaderi** [comment]
Let me repeat it one more time. We support only Debian 8. Please upgrade.

**Comment by iber-mi** [comment]
ZMQ3 already Debian 7, there is nothing to do for nprobe in wheezy?

**Comment by lucaderi** [comment]
Sorry we have no resources to support Debian 7 with ZMQ.

**Comment by iber-mi** [comment]
And there is another package of nprobe to run this? I can not believe that Debian 7 being a version that is not old, not work with any of this.
