### ISSUE TITLE
ntopng to monitor multiple remote Netflow devices simultaneously

### ISSUE THREAD

**Issue by learnhub17** [ntop/ntopng#1444]
I am able to run centralized ntopng which is successfully monitoring  WAN end(router) by enabling netflow over cisco-router.  
Config ntopng:   
-i=tcp://127.0.0.1:5555  
Config nprobe:   
nprobe --zmq "tcp://*:5555" -i none -n none --collector-port 2055 &  

Now among 20 servers I want to monitor 10 server, where the 10 servers traffic will send to the same centralized ntopng server. which is quite difficult for me, kindly help me in this.

**Comment by emanuele-f** [comment]
Hi, you can create virtual interfaces based on the router ip address. Please check out the Network Interfaces section of the ntopng preferences.

**Comment by simonemainardi** [comment]
You can separate every single router in ntopng by means of virtual interfaces.

Select Probe IP from the preferences and restart ntopng:

![image](https://user-images.githubusercontent.com/3397663/30421206-53ba8d0a-993c-11e7-9390-98df7fb11b29.png)


Please, note that you have to tell nProbe to add field `%EXPORTER_IPV4_ADDRESS` in the template. This is the field that will be used by ntopng to logically separate the incoming flows.
 
A working template example is this:

```
sudo ./nprobe -i none -n none --collector-port 2055  T="%IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_SRC_MASK %IPV4_DST_MASK %L4_SRC_PORT %L4_DST_PORT %IPV6_SRC_ADDR %IPV6_DST_ADDR %IPV6_SRC_MASK %IPV6_DST_MASK %IP_PROTOCOL_VERSION %SRC_TOS %PROTOCOL %ICMP_TYPE %INPUT_SNMP %SRC_AS %DST_AS %IPV4_NEXT_HOP %IPV6_NEXT_HOP %TCP_FLAGS %OUTPUT_SNMP %IN_BYTES %IN_PKTS %OUT_BYTES %OUT_PKTS %MIN_TTL %MAX_TTL %FIRST_SWITCHED %LAST_SWITCHED %SRC_VLAN %DST_VLAN %DOT1Q_SRC_VLAN %DOT1Q_DST_VLAN %EXPORTER_IPV4_ADDRESS %IN_SRC_MAC %IN_DST_MAC" --zmq tcp://*:5556
```

**Comment by juniorr44** [comment]
![Cap](https://user-images.githubusercontent.com/55981328/226442981-7525852d-43d2-4e39-93a7-9e815b69a29e.JPG)

**Comment by juniorr44** [comment]
Hello team !!!

**Comment by juniorr44** [comment]
Hello I installed ntopng in an intranet-type network made up of several remote sites connected by interconnections from different ISPs.
the infrastructure is made up of cisco 4200 routers and 2960 switches. My concern is that I managed to see the addresses of the routers and switches because I activated the SNMP protocol in these equipments but alas I do not see all the IP addresses of this network. I have done several searches but I can't find any solution. Need help please
![Cap](https://user-images.githubusercontent.com/55981328/226446689-06cae7f5-6368-4466-a3b9-a43bc6c02dbe.JPG)

**Comment by juniorr44** [comment]
![2](https://user-images.githubusercontent.com/55981328/226446913-8c982679-d52d-4228-ad85-d915821dc02a.JPG)
