### ISSUE TITLE
Implement Ingress/Egress Stats

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1452]
The EthStats has been updated and it can now provide ingress and egress stats (in addition to accumulate stats as it has always been).

- EthStats::lua now reports ingress/egress bytes/packets
- NetworkInterface::areTrafficDirectionsSupported reports if a given interface supports traffic directions (e.g. pcap interfaces do not, PF_RING do)

For interfaces that support traffic directions it is requested to report this information in the GUI and create RRDs for the directions.

Moreover it would be nice to rethink for such interfaces the footer graph/stats to report RX/TX info.

**Comment by emanuele-f** [comment]
Linked to #1114.

Right now the interface timeseries data has only 1 column, bytes. In order to preserve existing data, we could rename the column bytes to bytes_rcvd and assume rx if interface has no direction. Renaming in InfluxDB requires duplicating data into a new table. In RRD, the rrd_tune api could be used (similar to https://oss.oetiker.ch/rrdtool/doc/rrdtune.en.html).

Moreover, we must decide if we want to support both the gui visualizations for bytes only and bytes_sent+bytes_rcvd, e.g. if the interface chart should show "bytes" if the given interface does not support rx/rx directions. The change affects other gui elements, for example the traffic reports.

**Comment by simonemainardi** [comment]
to avoid breaking things or doing migrations:

- leave the existing schema for bytes (iface:traffic) untouched
- create an additional schema (e.g., iface:traffic_txrx) with two columns, one for the tx bytes and the other for rx bytes
- add another entry in the interface charts page, say "Traffic TX/RX", which pulls the data from the new schema and shows the stacked RX and RX bytes for the interface.
