### ISSUE TITLE
How to reset password on ntopng?

### ISSUE THREAD

**Issue by Drewshg312** [ntop/ntopng#153]
Hi!
I was changing my password and forgot it)
How do I reset my pass? The username is admin.

    redis-cli del user.admin.password

Did not help. Neither reinstallation helps (using homebrew on os x 10.10.5) ((

**Comment by lmangani** [comment]
Hi,

Please try using ```redis-cli SET user.admin.password <MD5>```

If you want to drop all data and use redis for ntopng exclusively use ```redis-cli flush all ```

**Comment by Drewshg312** [comment]
I've tried `redis-cli SET user.admin.password MD5_of_newpass`  too. No results.
and 

```
$ redis-cli flush all
(error) ERR unknown command 'flush'

what am I doing wrong?

**Comment by lucaderi** [comment]
https://www.ntop.org/guides/ntopng/faq.html#cannot-login-into-the-gui

**Comment by Drewshg312** [comment]
I've already read it and done everything like it says with no luck… That's why I'm asking you here

**Comment by Drewshg312** [comment]
There you go! 
Found the answer here **(in comments)**:

http://blog.redbranch.net/2013/12/12/reset-ntopng-admin-password/

"I tried the above commands without any luck. I determined the user account above was not correct by running strings /var/lib/redis/dump.rdb | grep admin which showed a key for ntopng.user.admin.password. I was able to reset the password then by doing

redis-cli SET ntopng.user.admin.password ea847988ba59727dbf4e34ee75726dc3

**It should also be noted that ntopng does not allow special characters in the passwords and silently fails. This is how I got locked out of the UI**"

This should be added to https://github.com/ntop/ntopng/blob/dev/doc/README.ntopng … if anyone cares…

**Comment by lucaderi** [comment]
Please send us a merge request for the read me and open an issue for the issue you identified

**Comment by lmangani** [comment]
Docs updated by ntop team

**Comment by Drewshg312** [comment]
would be great to have some hint in an actual application - would save a lot of time…

**Comment by lmangani** [comment]
I honestly believe the README does suffice for this sort of information as the go-to document. 
Feel free to submit a pull request with any proposal of course.

**Comment by Drewshg312** [comment]
check the behavior of the application after changing the password to something like "34$#2"… Looks really buggy… just saying…

**Comment by lmangani** [comment]
Our instructions do indicate how to RESET the password to its defaults, and not how to change it to a bad string. As said, improvements and contributions are super welcome any time!

**Comment by Drewshg312** [comment]
lol ok

**Comment by lmangani** [comment]
@kYroL01 we could extend the new password input field with a regex filter in scripts/lua/inc/change_user_password_form.lua:

```<input id="new_password_input" type="password" name="new_password" value="" class="form-control" pattern="[a-zA-Z0-9-]+" />``` 

(untested)

**Comment by kYroL01** [comment]
@lmangani Try to do it

**Comment by Elefontman** [comment]
BTW, the default username & pwd (supposedly admin) don't work, on your Latest version.
Even resetting it doesn't work.
Worked on this for hours. Giving up. Really pathetic.

**Comment by simonemainardi** [comment]
Rather than writing those comments (also see https://github.com/ntop/ntopng/issues/479#issuecomment-274878873) that are just a waste of time, if you really want to get help from the community, you should post useful information that will allow the others to understand IF and WHERE is the problem

**Comment by mikepaxton** [comment]
In order to get past the admin password issue I had to shutoff ntopng password usage all together.  To do this I used:
sudo ntopng -l 1
You can find the details of this under ntopng's man pages.
After doing this I rebooted ntopng using:
sudo service ntopng restart

Hope this helps.

EDIT:  The only way I could seem to make this work on a perminant bases was to add the -l 1 option to ntopng's .conf file.
sudo nano /etc/ntopng.conf
then add to the file
-l=1
Then restart the service.

**Comment by emanuele-f** [comment]
@mikepaxton do you access ntopng web interface directly? Did the issue came out after an update?

**Comment by spylife** [comment]
I installed v.2.4.170215 on 3/3, setup a password for admin but couldn't login today. tried the cli update Drewshg312 listed (for ntopng.user.admin.password) but that didn't work (made sure no symbols in password).  I found i could launch ntopng with -l 1 and from the ui tried resetting the password and even created a new user account, but neither account could login still.   Any other ideas? 

also i installed on security onion with this script https://raw.githubusercontent.com/branchnetconsulting/so1404-ntopng-installer/master/install_ntopng_on_so

I've done the same security onion + ntopng setup 4 times previously but this is the first time i can't login

**Comment by simonemainardi** [comment]
@spylife 

the proper way to reset the admin password is the following:

- shutdown ntopng
- run command: redis-cli del ntopng.user.admin.password
- restart ntopng and now the admin password has been reset to admin

regarding securityonion you should try and check out with them

**Comment by spylife** [comment]
@simonemainardi 

that worked, i also discovered what was probably my issue all along, in chrome if i tried to login, once i hit login, the login page would reload, never letting me in. i noticed incognito COULD login. I made sure i had all extensions off and still no dice. i cleared 5 cookies from the ntopng page and THAT fixed it. something in my cookie data was preventing my login.  Hopefully this helps anyone else that experiences this.

**Comment by simonemainardi** [comment]
@spylife thanks for reporting your experience. Yes extensions can be the source of issues and sometimes one may blame the software for something that is actually caused by the extension itself.

**Comment by khaukha** [comment]
Just enter these following commands (for Debian, Ubuntu Systems)
Stop ntopng service
service ntopng stop

Enter this command: 
- redis-cli del user.admin.password, this is to reset to defaults of username: admin Password: admin
restart ntopng service  and now it's set to defaults
service ntopng start

Go to the web browser and enter your server ip like 192.168.1.20:3000
Login as admin and admin (Username and Password), hope it helps

Regards

**Comment by akatrevorjay** [comment]
@simonemainardi That doesn't sound like extensions to me. It sounds like a cookie is being set that it's relying upon. CSRF? Some kind of salt perhaps?

**Comment by akatrevorjay** [comment]
The reason why I came here:  i don't know why but I can't reset a password either on a brand new install. I remember the length being awfully restrictive; I've ran into that before here, as well as the bug with special characters. This time however even lowering to 16 characters didn't help.

I haven't had time to look into it yet, but I wanted to at least make sure it was already in an issue somewhere. I'll report back when I get time to look into it later this week.

**Comment by dagbdagb** [comment]
https://github.com/ntop/ntopng/blob/dev/doc/README.md shows the current procedure for resetting the admin password.

**Comment by seandex** [comment]
> https://github.com/ntop/ntopng/blob/dev/doc/README.md shows the current procedure for resetting the admin password.

It does not work. I tried everything. Last option I have is to delete the database

**Comment by emanuele-f** [comment]
Please check out https://www.ntop.org/guides/ntopng/faq.html#cannot-login-into-the-gui

**Comment by seandex** [comment]
> Please check out https://www.ntop.org/guides/ntopng/faq.html#cannot-login-into-the-gui

my link also included that one and tried them all
after googling about 6 hours, someone who found the md5 method noticed his password was changed after |md5 
since it is so suspicious i googled about hacking redis and found this
https://github.com/Avinash-acid/Redis-Server-Exploit
https://www.exploit-db.com/exploits/44973
I just tried ntopng for 3 days v 3.8
and i really hope my server is not compromised..
i probably should remove the db and if it does not work.. i guess ntopng is somewhat hard to maintain with my knowledge..

**Comment by emanuele-f** [comment]
The password reset method should work as long as you can run commands in your system. Can you report the exact command sequence you are using to reset the password?

In general you should never expose services to open ports into the internet. Setting a redis password is also a good idea, please check out this for more security advices: https://www.ntop.org/ntopng/best-practices-to-secure-ntopng

**Comment by seandex** [comment]
> The password reset method should work as long as you can run commands in your system. Can you report the exact command sequence you are using to reset the password?
> 
> In general you should never expose services to open ports into the internet. Setting a redis password is also a good idea, please check out this for more security advices: https://www.ntop.org/ntopng/best-practices-to-secure-ntopng

Both bound to 127.0.0.1 with raw mangle and filter on. 

I gave up it just worked at the fresh install then after 3 days one yum update took me 10 hours of no sleep on troubleshooting. it upgraded to premium 10 minutes demo, however, i can't even log in.
also, test if reboot really brakes the login as well since I can't go back to the state when it worked.

redis-cli 3.2.12
ntopng v.3.8.191104 [Enterprise/Professional build]	
2.6.32-042stab140.4 Centos 6.10 (Final)

service ntopng stop
ps aux|grep ntopng
redis-cli -s /var/run/redis/redis.sock DEL ntopng.user.admin.password
(integer) 1
service ntopng restart
[  OK  ]
Successfully connected to redis /var/run/redis/redis.sock@0
now, chrome - delete full cache and data even passwords - incognito mode, no addons - admin / admin - no error message, it just resets it. 

I also tried on that stressful OS Windows 10, using legacy internet explorer that I never use. disabled all addon, no luck


the solution below should be the straight-forward solution, right? and the result is not working.

> @simonemainardi
> 
> that worked, i also discovered what was probably my issue all along, in chrome if i tried to login, once i hit login, the login page would reload, never letting me in. i noticed incognito COULD login. I made sure i had all extensions off and still no dice. i cleared 5 cookies from the ntopng page and THAT fixed it. something in my cookie data was preventing my login. Hopefully this helps anyone else that experiences this.


if I grep the password from the db file, i get the right md5
"21232f297a57a5a743894a0e4a801fc3"   decrypts admin. ok good.

however, in redis some funky md5 was there, mismatch the file admin md5.
this part gotta be revealed. it's not only me and I only use 2 awesome strength passwords in my whole life. 1 hacked? 2 my mistake? (maybe) 3. code is wrong?

so I change it to admin to try
redis-cli GET ntopng.user.admin.password
"21232f297a57a5a743894a0e4a801fc3"

MD5 set also didn't work, 


i really hope not my server got compromised.. 


it was one of the very rare experiences that I could not troubleshoot. I maybe could achieve it if I try more hours but I think it's worth it for me to end up here.

about flushing DB, the manual needs to be updated, redis updated commands.
Anyways, I flushed and nuked the both DB, and then reinstalled it. i had to choose, re-compile or yum.
i chose yum. but still the same thing. that HTTPserver.cpp got to be fixed as the 'product'.. it requires an insane amount of time. 

I really gotta go, spent 12 hours already but maybe this could be a hint or not 

1. in HTTPserver.cpp there is the part of auth check and then relocates the user back to log-in page. 
2. there is a .js file i don't even want to look at it now. 

Anyways good luck guys. I learned many interesting features in two days. 

I think I provided enough for 3 days of use.

**Comment by emanuele-f** [comment]
I'm sorry you've spent so much time debugging this. If you still want to do a last try and you don't mind losing ntopng data you can try a full reset:

1. `sudo systemctl stop ntopng`
2. `sudo rm -rf /var/lib/ntopng /var/tmp/ntopng`
3. `redis-cli flushall`
4. `sudo systemctl restart ntopng`
5. Login with `admin` username and `admin` password

This will reset *all* the ntopng data and clear redis. If it still does not work after this, you can be almost sure that this is a browser problem. You can double check by using the cli: https://github.com/ntop/ntopng/tree/dev/doc#accessing-ntopng-urls-from-command-line-tools-no-web-browser

**Comment by saifullahsohail123** [comment]
Worked in a flash for me !

https://techexpert.tips/ntopng/ntopng-password-recovery/
