### ISSUE TITLE
#1496 Not solved! 

### ISSUE THREAD

**Issue by antoniovalenzuela** [ntop/ntopng#1548]
#1496 Not solved!
RPI3

Setting up ntopng (3.1.171016-3574) ...
Rebuilding ld cache...
Adding the ntopng startup script [configure]
Synchronizing state for ntopng.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d ntopng defaults
Executing /usr/sbin/update-rc.d ntopng enable
(Re)Starting ntopng...
Failed to restart ntopng.service: Unit pf_ring.service failed to load: No such file or directory.
dpkg: error processing package ntopng (--configure):
subprocess installed post-installation script returned error exit status 6
Setting up wpasupplicant (2.3-1+deb8u5) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Errors were encountered while processing:
ntopng
E: Sub-process /usr/bin/dpkg returned an error code (1)

Remove nprobe and reinstall:

W: Failed to fetch http://packages.ntop.org/apt/8.0/x64/Packages  404  Not Found
W: Failed to fetch http://packages.ntop.org/apt/8.0/all/Packages  404  Not Found

Broken links....

cat /etc/apt/sources.list.d/ntop.list

deb http://packages.ntop.org/apt/8.0/ x64/
deb http://packages.ntop.org/apt/8.0/ all/

**Comment by lucaderi** [comment]
On x64

root@debian8:/tmp# dpkg -i apt-ntop.deb 
Selecting previously unselected package apt-ntop.
(Reading database ... 74919 files and directories currently installed.)
Preparing to unpack apt-ntop.deb ...
Unpacking apt-ntop (2.5-853) ...
Setting up apt-ntop (2.5-853) ...
Adding ntop key to apt keyring
OK
root@debian8:/tmp# cat /etc/apt/sources.list.d/ntop.list 
deb http://packages.ntop.org/apt/jessie/ x64/
deb http://packages.ntop.org/apt/jessie/ all/


On RPI3
You need to do what specified in http://packages.ntop.org/RaspberryPI/, namely
echo "deb http://apt.ntop.org/stretch_pi armhf/" > /etc/apt/sources.list.d/ntop.list
echo "deb http://apt.ntop.org/stretch_pi all/" >> /etc/apt/sources.list.d/ntop.list

whereas you are using the release number (8.0) instead of the release name (stretch_pi).

Please fix accordingly and it will work

**Comment by antoniovalenzuela** [comment]
@lucaderi 

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ntopng : Depends: librrd8 but it is not installable
          Depends: libzmq5 but it is not installable
          Depends: libssl1.1 but it is not installable
          Depends: libhiredis0.13 but it is not installable
          Recommends: ntopng-data but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I do not understand your solution ... I have the license, I can not use ntopng/nprobe, with raspberry jessie (x86)

Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie


Before the last updates I had no problems

**Comment by antoniovalenzuela** [comment]
@lucaderi 

Please answer, for something buy a license. What happens with the respositories for RPI Jessie 8 (x86).

**Comment by simonemainardi** [comment]
@antoniovalenzuela RPI has ben upgraded to the new stable stretch
