### ISSUE TITLE
Ntopng Not Detect protocol client

### ISSUE THREAD

**Issue by resturiani** [ntop/ntopng#1550]
I install ntopng and connect it with the traffic flow mikrotik. ntopng and nprobe I install on the same machine. and I check the client's network, his ip sometimes detect sometimes not. but the protocol that client ip accessed is not detect in ntopng. looks always like below. does anyone know the solution?

![screenshot from 2017-11-04 16-30-04](https://user-images.githubusercontent.com/22189485/32404181-80d5271e-c17d-11e7-94e3-a6d42df6b195.png)

**Comment by emanuele-f** [comment]
Hi, can you give us more information about the undetected traffic? For example, from the Flows or Ports tab.

**Comment by resturiani** [comment]
below this topology I use:
![screenshot from 2017-11-11 17-12-18](https://user-images.githubusercontent.com/22189485/32688452-8e53359e-c703-11e7-8651-bfa403ec1c9b.png)

I use traffic flow from Mikrotik to server, and I try to detect IP client. I got that IP, but ntopng not detect what client acces on browser. below is the proof:
![screenshot from 2017-11-11 16-56-03](https://user-images.githubusercontent.com/22189485/32688507-796c07f4-c704-11e7-8b92-bb99d67161ed.png)

**Comment by emanuele-f** [comment]
Hi, please consider that flows take some time to reach the nProbe and then the ntopng instance. If you go into the graphs page (chart icon in the host toolbar) and wait 10 minutes after surfing the internet with the test client, can you see any http traffic?

**Comment by resturiani** [comment]
No sir. It's just showed app protocol like i screenshoot before. It didnt record what client access like facebook, google, github, etc. If we look on test client that ports and flows menu just showed like this: 
![screenshot from 2017-11-15 19-51-27](https://user-images.githubusercontent.com/22189485/32837221-3f92298a-ca3f-11e7-91aa-f97084837b7b.png)
![screenshot from 2017-11-15 19-54-52](https://user-images.githubusercontent.com/22189485/32837263-6e559a7c-ca3f-11e7-964a-52e2e5ecf3d8.png)
i have access google, fb. github on test client, look on below. It is not record app protocol like google, fb, github  :
![screenshot from 2017-11-15 19-41-15](https://user-images.githubusercontent.com/22189485/32837294-9080ba46-ca3f-11e7-9469-19e75dd10b61.png)

**Comment by simonemainardi** [comment]
It is technically not possible to perform nDPI inspection when ntopng and nProbe are used to collect and visualize netflow traffic, either from a Mikrotik or from any other NetFlow source. When nProbe is used to collect netflow traffic, basic port-based protocol detection is performed and this explains why you are not seeing Facebook, Youtube, etc.

This is not a limitation of ntopng. It is merely not possible to run deep packet inspection with netflow as, by construction, it does not carry any packet but just flows.

So, according to your topology diagram, if you want to perform deep packet inspection, you should not collect flows from the Mikrotik. You should rather connect the ntopng/nProbe box to a switch mirror port in order to deliver real traffic packets.
