### ISSUE TITLE
How to Connect Ntopng to Mikrotik?

### ISSUE THREAD

**Issue by resturiani** [ntop/ntopng#1575]
how to monitor in ntopng using mikrotik?
I really need your help.

**Comment by emanuele-f** [comment]
Hi, please check out the following links:

- https://www.ntop.org/ntopng/how-to-analyse-mikrotik-traffic-using-ntopng/
- http://www.ntop.org/nprobe/advanced-flow-collection-with-ntopng-and-nprobe/

**Comment by resturiani** [comment]
I have followed the steps. but still not working.
do you have a solution?

**Comment by emanuele-f** [comment]
Please see my email response.

**Comment by emanuele-f** [comment]
Discussion will continue via email.

**Comment by resturiani** [comment]
Hiemanuele. let's start discussing it from the beginning. my goal is monitoring client using ntopng which is assisted with mikrotik (traffic flow). This is my network server (ubuntu 16.04).

first I have installed ntopng on the server. from the tutorial, I also edited the ntopng.conf file. what's next step? this is all in order to avoid misunderstanding.

**Comment by resturiani** [comment]
Hi emanuele, 
Let's start discussing it from the beginning. My goal is monitoring client using ntopng which is assisted with mikrotik (traffic flow). 
This is my network server (ubuntu 16.04):
![picture 1](https://user-images.githubusercontent.com/22189485/33408188-b577de92-d5a7-11e7-9a09-15f083072189.png)

First I have installed ntopng on the server. from the tutorial, I also edited the ntopng.conf file. 
or something to be configured again in ntopng besides ntopng.conf?
What's next step? This is all in order to avoid misunderstanding.

**Comment by emanuele-f** [comment]
You have to configure nprobe to receive the Mikrotic flows and send them to ntopng.

```
sudo nprobe -i none -n none --collector-port 2055 --zmq "tcp://127.0.0.1:5556"
sudo ntopng -i "tcp://127.0.0.1:5556"
```

Then tell your mikrotic to export flows to 192.168.10.253 port 5556. Try it and if you have troubles please send be your ntopng/nprobe configuration / logs

**Comment by resturiani** [comment]
Thank you,

I've configured the nprobe.conf file.
and I have also run as you say.
for nprobe -i none -n none --collector-port 2055 --zmq "tcp://127.0.0.1:5556", the result as below:
![screenshot from 2017-11-30 16-52-18](https://user-images.githubusercontent.com/22189485/33425979-f12f7ab2-d5f2-11e7-9d8b-f19b474d0736.png)

and for ntopng -i "tcp://127.0.0.1:5556", the result is as below:
![screenshot from 2017-11-30 16-52-53](https://user-images.githubusercontent.com/22189485/33425993-ff30d606-d5f2-11e7-9825-74bc02e2433f.png)

and mikrotik I have configured as below:
![screenshot_4](https://user-images.githubusercontent.com/22189485/33426217-a7f1077a-d5f3-11e7-8775-1484b7d27252.png)

and still not detected. instead the flow interface tcp://127.0.0.1:5556 does not work. it looks like this:
![screenshot from 2017-11-30 17-19-01](https://user-images.githubusercontent.com/22189485/33426126-5e106a10-d5f3-11e7-94f2-4f2fd15b45a0.png)

**Comment by emanuele-f** [comment]
The nprobe error above appears because you have other nprobe instances running on the system. You can find nprobe config files under /etc/nprobe. Please stop them when performing command line tests: `systemctl stop nprobe@none` or `killall nprobe`. Otherwise you can change the "5556" port in ntopng and nprobe to something else

**Comment by resturiani** [comment]
I have followed your instructions. and now nprobe has started. 
![screenshot_5](https://user-images.githubusercontent.com/22189485/33481942-4d5583aa-d6c9-11e7-9ec4-2d448f3a0808.png)

And I have also changed port 5556 to 5557, but ntopng still not detect what is access by the client. and interface 127.0.0.1:5556 there is no incoming traffic flow. looks like this:
![screenshot_6](https://user-images.githubusercontent.com/22189485/33481947-51c6d038-d6c9-11e7-88ec-717189b1e05f.png)

any idea?

**Comment by simonemainardi** [comment]
From the pics enclosed I can see the ntopng is connected to nprobe. Indeed, Interface RX Updates are increasing.

The real issue here is that you configured your mikrotik to export on port 5556
![image](https://user-images.githubusercontent.com/3397663/33486272-af28a320-d6a9-11e7-99d9-438fd039889f.png)

while you told nProbe to collect flows on port 2055
![image](https://user-images.githubusercontent.com/3397663/33486292-c17153c4-d6a9-11e7-9488-0ebfdb797824.png)

just fix this and it will work.

**Comment by resturiani** [comment]
Thankyou sir,
Ya, it works. But not everything my client accessed was detected. eg youtube, wikipedia, skype, my ntopng didn't detect it. He just detects google, facebook, twitter and amazon. 
What is the problem?
Please give me solution

**Comment by emanuele-f** [comment]
In this setup, ntopng cannot parse per-packet information (e.g. SSL certificate), which is needed for full protocol detection. If you need full protocol detection you would need to place ntopng inline with the traffic, please see https://github.com/ntop/ntopng/blob/dev/doc/README.inline for more information

**Comment by resturiani** [comment]
from what I've read, https://github.com/ntop/ntopng/blob/dev/doc/README.inline does not match the topology.
in the present case, ntopng directly i connect with mikrotik without switch. is there any way to still be able to display all the protocols of the client if it remains directly connected with mikrotik.

**Comment by simonemainardi** [comment]
https://github.com/ntop/ntopng/blob/dev/doc/README.inline has nothing to do with this issue.

Deep packet inspection technology is only available when monitoring raw packets. It is technically not possible to do it on Miktotik NetFlow because it does not contain raw monitored traffic packets.

So if you want to perform deep packet inspections, use a mirror port of the switch and deliver the mirrored traffic to the ntopng.
