### ISSUE TITLE
Get TCP seq and ack number displayed on lua web page

### ISSUE THREAD

**Issue by pleoeter** [ntop/ntopng#1669]
I want to display tcp seq num and tcp ack number on lua web  , please tell me how to extract the fields from flow.cpp and flow.h files and display.

**Comment by emanuele-f** [comment]
Hi, the sequence numbers change during the flow lifecycle, so you could want to display the fist seq and ack or the last ones. For the latter case, the flow.cpp class already provides such information, please see `tcp_stats_s2d.last` field. In order to display it on the gui you should add a new entry to the flow::Lua method like this:

```
lua_push_int32_table_entry(vm, "last_seq_cli2srv", tcp_stats_s2d.last);
```

Now that it is exported to lua, you can print a new line in flow_details.lua , e.g. `print(flow["last_seq_cli2srv"])`

**Comment by pleoeter** [comment]
@emanuele-f  I want to display it on flows stats lua table in a separate column, please provide the code snippet

**Comment by pleoeter** [comment]
if(flow["last_seq_cli2srv"] ~= nil and flow["last_seq_cli2srv"] > 0) then
   print("<tr><th width=30%>"..i18n("flow_details.application_seq").."</th><td colspan=2>"..(flow["last_seq_cli2srv"]).."</td></tr>\n")
   end

I always get empty or null value, as per me every application /packet should show a sequence and acknowledgment number

**Comment by emanuele-f** [comment]
Have you modified Flow.cpp as stated above and recompiled ntopng?

Moreover, if you don't mind localization please just `print(flow["last_seq_cli2srv"]).."\n")`. You can debug the actual lua table content with `tprint(flow["last_seq_cli2srv"])`, it will print the field content on the command line output.

**Comment by pleoeter** [comment]
yes I recompiled ntopng , and then print it, and it give me null value quite often

**Comment by pleoeter** [comment]
emanuele-f please tell me the field for acknowledgment number , i am done with the sequence number

**Comment by emanuele-f** [comment]
I think I've already provided the appropriate suggestions to implement the feature. Please refer to the source code for any other specific detail.
