### ISSUE TITLE
Dropped flows...hoping for a more technical discussion here.  

### ISSUE THREAD

**Issue by CDawson1** [ntop/ntopng#1672]
Yes, there have been a few threads on this issue, but not one has actually indicated a guide to address it other than referencing some configuration to change.  

However, some of us, not being DB types, probably have no idea where to start.  

So, in this case, I too am dropping about 13% of flows...

![drops](https://user-images.githubusercontent.com/32870121/36591257-5114b234-1889-11e8-8af6-d40b6d3b1d03.png)
![drops2](https://user-images.githubusercontent.com/32870121/36591260-54b8998c-1889-11e8-9508-a735dc3cb648.png)

[Issue 830](https://github.com/ntop/ntopng/issues/830) references tuning some parameters, however, I don't even know where to begin.  

For example, one parameter is myisam_max_sort_file_size, to which mine is set to 9223372036853727232.  That means nothing to me.  

As for the rest of my settings:

```
| key_buffer_size | 16777216 |

| key_cache_age_threshold | 300   |

| key_cache_block_size | 1024  |

| key_cache_division_limit | 100   |

| max_allowed_packet | 16777216 |

| max_connections | 151   |

| max_delayed_threads | 20    |

| myisam_mmap_size | 18446744073709551615 |

| myisam_sort_buffer_size | 8388608 |
```

Now, I'm pretty sure that our host is just old and generally the disks can't keep up as I see this more often than not...

```
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  util
sda               0.00  1509.50   39.50 4823.00   162.00 41124.00    16.98    72.98   15.04   24.56   14.96   0.20  98.40
dm-0              0.00     0.00   39.50 6324.00   162.00 41122.00    12.98    75.56   11.87   24.56   11.80   0.15  98.40
```

I also see a lot of IO wait...
```
%Cpu0  : 25.7 us, 12.9 sy,  0.0 ni, 10.0 id, 51.0 wa,  0.0 hi,  0.5 si,  0.0 st
%Cpu1  : 38.8 us, 18.0 sy,  0.0 ni,  7.3 id, 32.6 wa,  0.0 hi,  3.4 si,  0.0 st
%Cpu2  : 17.5 us, 11.2 sy,  0.0 ni,  0.0 id, 70.4 wa,  0.0 hi,  0.8 si,  0.0 st
%Cpu3  :  0.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,100.0 si,  0.0 st
```
As well as some other issues.  

It's a Dell R610, with 4 cores (1 socket, 4 cores) of a L5640 given, 8GB RAM, and 6x 10k 1.2TB disks in R5.  The disk controller is Logic Parallel.  I suppose there may be some efficiencies by using a different controller?  

Whether I need to tune mysql better or simply throw some HW at it I've not yet determined, but my guess is the latter.  I just need to get the evidence to justify HW.

**Comment by emanuele-f** [comment]
Hi, just some general notes about MySQL export. With MySQL you could experience the following limitations:

1) Mysql inherent limits, which you could improve by tweaking the Mysql db options
2) Disk write limits, due to slow disks writes
3) Ntopng export limit. Regarding this, if you are using the community or pro version you can get a 5x improvement by migrating to the enterprise version as it provides an optimized algorithm

**Comment by CDawson1** [comment]
I should have mentioned, we're running the enterprise version.  

I appreciate the suggestion of tweaking MYSQL, but that's exactly what this thread is about as the suggestion to improve that doesn't have any detail behind it.  While I also appreciate it's not a one size fits all, there has to be at least some primer as the load, and how the data is written is known, for the most part, regardless of deployment.  I'd assume it scales almost linearly, thus at such and such a load, change this, that and the other thing.  

As for disk limits, I don't know what the theoretical cap is for our host.  

What I'm ultimately looking for is a little guidance on discovering where our bottleneck is.  The host's stats don't necessarily suggest there's a limitation, but then again, I don't know where it would top out to indicate there was an actual limitation.

**Comment by CDawson1** [comment]
Any suggestions?

**Comment by juesor** [comment]
Ok so not to piggy back on this trouble but look at both of my ntopng enterprise servers.

![image](https://user-images.githubusercontent.com/14931420/38751440-be6596a4-3f1d-11e8-8686-cdd0422cd18e.png)

I am waiting for an update to ntopng.  I was told they are optimizing the DB and moving away from mysql.  This i was told will help my dropped flows.

**Comment by juesor** [comment]
I forgot to put my second server.

![image](https://user-images.githubusercontent.com/14931420/38752132-bde3ec6a-3f1f-11e8-9869-8346cc15a407.png)


I was having issues getting nprobe to send traffic this afternoon and forgot i made a config change a while back.  But as you can see it's only up for 8 minutes and 1.8million dropped flows.

**Comment by simonemainardi** [comment]
@juesor you are definitely monitoring a significant amount of traffic, I would not expect mysql to be able to keep up with that speed. 

According to our experiments, an out-of-the-box mysql installation supports the following rates of insertion:
* ~2k flows/sec (ntopng community, professional)
* ~10k flows/sec (ntopng enterprise)

A fine tune of MySQL could allow you to reach even higher insertion speeds, but I would not expect orders-of-magnitude gains, at least on single-node installations. The story is different if you have an highly replicated MySQL cluster with sharding and replication. However, we don't have experimental results in such environments.

@CDawson1 The tuning of MySQL should involve at least the following:
* `key_buffer_size`: typically, this is set to 30-40% of the available RAM memory. Ideally, the sum of the sizes of all the .MYI files should be smaller than `key_buffer_size` but this is not always doable nor practical. Default size is just 8M so an increase would definitely be beneficial.
* `sort_buffer_size`: this can have positive effects on the search queries rather than on the insertion. The status variable `sort_message_passes` is the only one that uses `sort_buffer_size`. You should check the `sort_message_passes` and if it is a large number then an increase in the `sort_buffer_size` will have a positive effect.

We understand that insertion speeds reachable with mysql are too low to be useful for multi-Gpbs traffic monitoring. We also believe that it is not always feasible, nor necessary, to set up clustered databases. They cost to much and also their maintenance is a pain. This is why we are working on an high-performance flow database to handle flow insertions speeds in the order of the hundred thoudsands per second on a single-node. We can promise this will revolutionize the present.

**Comment by CDawson1** [comment]
@simonemainardi 
Thanks!  I've increased key_buffer_size from the default 16M to 3200M (only have 8G allocated to the VM) with no appreciable difference.  

I don't see any value for sort_message_passes, but I do have sort_merge_passes, which is at 0.  I don't see any reference anywhere to sort_message_passes.  Is that the correct variable?

I've just truncated the flowsv4 table and after a 2 day uptime, dropped 22.7m flows (Currently 22%). 

Current exported flows is at about 1882/sec.  Collected anywhere from 1k-10k (sometimes infinity?).  I'm looking to see at what point it records drops.  

EDIT:

Just saw exported flows skyrocket instantaneously from the above, to over 24k/sec, then settle back to about 2100/sec, and not change a lot.  

![24k](https://user-images.githubusercontent.com/32870121/39568748-1966d8cc-4ebb-11e8-9407-61194086c0cb.png)


That suggests something is queuing up and then doing a massive write, which my system can't keep up, then drops.  Any way to confirm this behavior?

**Comment by emanuele-f** [comment]
You can use `iotop` to verify which program is writing to disk and `top` to check the overall io wait. Anyway, do you have a fast SSD, right?

**Comment by CDawson1** [comment]
Read my OP.

**Comment by emanuele-f** [comment]
So you have high io waits on the cpus. I think we can't improve these answers further. Please try with a faster disk or wait for the new database implementation.
