### ISSUE TITLE
ntopng: undefined symbol pfring_open

### ISSUE THREAD

**Issue by queuedvariable** [ntop/ntopng#1684]
Hi all,

Getting an undefined symbol error trying to start ntopng on a centos 7 box:

./ntopng: symbol lookup error: ./ntopng: undefined symbol: pfring_open

This is all built (without errors) with autoconf based on git clones of todays stables.   (ntopng v.3.3.180306, PF_RING 7.1.0).     

looks like pfring_open is defined in the pfring packages and autoconf found it where I cloned & compiled it.   Not sure why it's not loading.     I am getting some warnings about autoconf version mismatches.

Anybody else having this issue?

**Comment by emanuele-f** [comment]
Hi, the 3.3.x and 7.1.x are not the stable version but the dev ones. Can you post the commands you are using to configure and compile pfring and ntopng?

**Comment by simonemainardi** [comment]
If you are building from sources, you should make sure pfring is not installed as a package. So make sure to remove any installed version (e.g., apt-get remove pfring) to allow the autoconf to use the cloned&compiled version.

**Comment by markathomas** [comment]
I have the same issue.  Built fine but won't start

**Comment by amastelek** [comment]
My ntopng has been working on debian jessie and the latest update has resulted in

ntopng: symbol lookup error: ntopng: undefined symbol: pfring_open

and ntopng failing to start

**Comment by emanuele-f** [comment]
What is the output of `apt-cache show pfring`?

**Comment by cardigliano** [comment]
@amastelek are you installing from packages or compiling from source code? What ntopng version are you running exactly? Thank you.

**Comment by amastelek** [comment]
> 
> 
> What is the output of `apt-cache show pfring`?

Package: pfring
Architecture: amd64
Version: 7.6.0-2851
Priority: optional
Section: free
Maintainer: Luca Deri <deri@ntop.org>
Installed-Size: 20290
Depends: ndpi (= 3.2.0-2286), net-tools, kmod, ethtool
Recommends: pfring-dkms (= 7.6.0)
Filename: x64/./pfring_7.6.0-2851_amd64.deb
Size: 1453526
MD5sum: 39168af69d171921e84cd349575e67de
SHA1: cf3bc9ba44f1d9a34b3d6a36f82e3efa61d89b2c
SHA256: c6c9c07674577f0c06e07707810abbea86a2799207f1d0d39c3d90d8f14c7e43
SHA512: 30652d3c37a2a61721026a7e0565c8f26146df25ca71922113b19471c555250867059458ed020d5c5afdd84ca509249dd83ba3c2ae0cac4eb16c4c34e38355a3
Description: PF_RING (http://www.ntop.org/pf_ring/) [7.6.0-stable:bd75dd82405def5efc76819e892cce458f7760e5]
Description-md5: b8ceaff5db3627cefc253fc62e237ffb

**Comment by amastelek** [comment]
> 
> 
> @amastelek are you installing from packages or compiling from source code? What ntopng version are you running exactly? Thank you.
http://apt-stable.ntop.org/jessie/all/apt-ntop-stable.deb

v.3.8.200224    [Enterprise/Professional build]
GIT rev:        3.8-stable:47772a761f3f44693e407824fe23414c5109f17b:20200224
Pro rev:        r2191
Built on:       Debian GNU/Linux 8.11 (jessie)
System Id:      1D624FCC7DB7A805
Platform:       x86_64
Edition:        Enterprise
License Type:   Time-Limited [Empty license file]
Validity:       Until Wed Feb 26 06:33:23 2020

**Comment by amastelek** [comment]
BTW it is only ntopng that fails - pf_ring is fine: 

● pf_ring.service - PF_RING service
   Loaded: loaded (/etc/systemd/system/pf_ring.service; disabled; vendor preset: enabled)
   Active: active (exited) since Tue 2020-02-25 21:47:27 AEDT; 8h ago
  Process: 1240 ExecStartPost=/bin/sh -c if [ -x /etc/pf_ring/post ]; then /etc/pf_ring/post; fi (code=exited, status=0/SUCCESS)
  Process: 1229 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) pf_ring StartPost" >> /var/log/ntop-systemd.log (code=exited, stat
 Main PID: 833 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/pf_ring.service

Feb 25 21:47:26 fbsa09-amastelekthreefourtwo systemd[1]: Starting PF_RING service...
Feb 25 21:47:27 fbsa09-amastelekthreefourtwo pf_ringctl[833]: PF_RING kernel module not installed, please install pfring-dkms:
Feb 25 21:47:27 fbsa09-amastelekthreefourtwo systemd[1]: Started PF_RING service.

**Comment by cardigliano** [comment]
I just installed the same version on a fresh debian8 installation, and it's working for me.. are you able to provide access to this system?

**Comment by amastelek** [comment]
> 
> 
> I just installed the same version on a fresh debian8 installation, and it's working for me.. are you able to provide access to this system?
Yes, I just need a white list IP and I'll give you access.  How did I message you privately?

**Comment by cardigliano** [comment]
Please drop an email to cardigliano at ntop.org

**Comment by amastelek** [comment]
I waited a few minutes and then did systemctl restart ntopng.service

It started...

ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-02-27 04:53:25 AEDT; 3s ago
  Process: 4157 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPost" >> /var/log/ntop-systemd.log (code=exited, sta
  Process: 4152 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|^[ ]*--pid.*/s/^/#/" /etc/ntopng/ntopn
  Process: 4142 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-con
  Process: 4138 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPre" >> /var/log/ntop-systemd.log (code=exited, statu
 Main PID: 4156 (ntopng)
   CGroup: /system.slice/ntopng.service
           └─4156 /usr/local/bin/ntopng /run/ntopng.conf

Feb 27 04:53:25 ci34hq-datacallonefiveseven ntopng[4156]: [NtopPro.cpp:468] WARNING: [LICENSE] ntopng will now run in enterprise
Feb 27 04:53:25 ci34hq-datacallonefiveseven ntopng[4156]: 27/Feb/2020 04:53:25 [NtopPro.cpp:468] WARNING: [LICENSE] ntopng will n
Feb 27 04:53:25 ci34hq-datacallonefiveseven ntopng[4156]: [NtopPro.cpp:470] WARNING: [LICENSE] before returning to community mode
Feb 27 04:53:25 ci34hq-datacallonefiveseven ntopng[4156]: 27/Feb/2020 04:53:25 [NtopPro.cpp:470] WARNING: [LICENSE] before return
Feb 27 04:53:25 ci34hq-datacallonefiveseven ntopng[4156]: [NtopPro.cpp:472] WARNING: [LICENSE] You can buy a permanent license at
Feb 27 04:53:25 ci34hq-datacallonefiveseven ntopng[4156]: [NtopPro.cpp:474] WARNING: [LICENSE] or run ntopng in community mode st
Feb 27 04:53:25 ci34hq-datacallonefiveseven ntopng[4156]: 27/Feb/2020 04:53:25 [NtopPro.cpp:472] WARNING: [LICENSE] You can buy a
Feb 27 04:53:25 ci34hq-datacallonefiveseven ntopng[4156]: 27/Feb/2020 04:53:25 [NtopPro.cpp:474] WARNING: [LICENSE] or run ntopng
Feb 27 04:53:25 ci34hq-datacallonefiveseven ntopng[4156]: 27/Feb/2020 04:53:25 [NtopPro.cpp:475] WARNING: [LICENSE] ntopng --comm
Feb 27 04:53:25 ci34hq-datacallonefiveseven ntopng[4156]: [NtopPro.cpp:475] WARNING: [LICENSE] ntopng --community
