### ISSUE TITLE
nProbe runs for 10 minutes then stops

### ISSUE THREAD

**Issue by gillmore-ac** [ntop/ntopng#1692]
Hey all,

I'm having an issue with one of my nProbe instances where it will stop running after 10 minutes, as if it was in demo mode. 

This nProbe instance is running on the same server as ntopng. It collects NetFlow data and forwards it to ntopng. My nProbe boxes were running fine up until I updated to v.8.2.180306 and then they were having license issues reporting an invalid format. After updating to nProbe v.8.2.180308 the licensing is fine, however one nProbe box is still having problems. 

I just renewed my licensing as the update to 180306 caused me to realized that my maintenance had expired, so the license is valid, but it still stops after 10 min. 

I'm at a loss.
-Andrew

`nprobe -v `

> Welcome to nProbe v.8.2.180308 (r5998) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-17 ntop.org
> 
> Build OS:      CentOS Linux release 7.4.1708 (Core)
SystemID:     XXXXXXX
GIT rev:       8.2-stable:3c384754769ba7acafb144252ed86e6aa18e521c:20180308
Edition:       nProbe Pro
License:       XXXXXXX [valid license]
License Type:  Permanent License
Maintenance:   Until Thu Mar  7 16:04:11 2019 [363 days left]

`nprobe-none.conf`
> --online-license-check
--zmq="tcp://127.0.0.1:5560"
--zmq-probe-mode
--collector-port=2055
--collector=none
--interface=none

**Comment by vvraciu** [comment]
Hi all,

We have similar situation, for nprobe and ntopng, but academic licenses. Information about version and some logs are below. Licenses were generated some time ago, since then I did several updates to nprobe and ntopng, so initial version is not anymore in place. 
After reading FAQ :)  I changed configuration for both ntopng and nprobe so license check to be done on-line (--online-license-check). After this change, ntopng seems to be ok, but nprobe not.

-----------------------------------
[root@stud-s4 ntopng]# nprobe -v

Welcome to nProbe v.8.2.180306 (r5996) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-17 ntop.org

Build OS:      CentOS Linux release 7.4.1708 (Core)
SystemID:      8CE6ACBA9207AB27
GIT rev:       8.2-stable:0442769f56e055cb7ec198279051d0d92c254d31:20180306
License:       Invalid nProbe license (/etc/nprobe.license) [License format error]

nProbe is subject to the terms and conditions defined in
the LICENSE and EULA files that are part of this package.

nProbe also contains third party code:
Radix tree code - (C) The Regents of the University of Michigan
                      ("The Regents") and Merit Network, Inc.
sFlow collector - (C) InMon Inc.
------------------------------------------------------
nprobe config

-n=none
-i=eno1
-G=
#--dump-path=/var/log/nprobe/
#--dump-frequency=300
--in-iface-idx=1
--out-iface-idx=2
#--dont-nest-dump-dirs=
--syslog=nprobe-stud-s4
--flow-version=9
--hash-size=131072
--biflows-export-policy=1
#-T=%IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_NEXT_HOP %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %IN_BYTES %FIRST_SWITCHED %LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %SRC_TOS %SRC_AS %DST_AS %IPV4_SRC_MASK %IPV4_DST_MASK
#--dump-plugin-families=
--zmq=tcp://127.0.0.1:2504
-b=2
--online-license-check=
-------------------------------------------------------
ntopng config:

-e=
-w=3004
-d=/var/log/nprobe
-S=all
-i=tcp://127.0.0.1:2504
-m # prefixes removed
--online-license-check=
-------------------------------------------------------
(logs below are before adding --online-license-check)

Mar  7 09:51:07 stud-s4 ntopng: 07/Mar/2018 09:51:07 [NtopPro.cpp:223]
[LICENSE] Reading license from /etc/ntopng.license
Mar  7 09:51:07 stud-s4 ntopng: 07/Mar/2018 09:51:07 [NtopPro.cpp:136]
[LICENSE] /etc/ntopng.license: unable to validate Enterprise license
[License format error]
Mar  7 09:51:07 stud-s4 ntopng: 07/Mar/2018 09:51:07 [NtopPro.cpp:136]
[LICENSE] /etc/ntopng.license: unable to validate Professional license
[License format error]
Mar  7 09:51:07 stud-s4 ntopng: 07/Mar/2018 09:51:07 [NtopPro.cpp:221]
[LICENSE] Reading license from Redis
Mar  7 09:51:07 stud-s4 ntopng: 07/Mar/2018 09:51:07 [NtopPro.cpp:300]
WARNING: [LICENSE] Invalid or missing license
Mar  7 09:51:07 stud-s4 ntopng: [NtopPro.cpp:300] WARNING: [LICENSE]
Invalid or missing license
Mar  7 09:51:07 stud-s4 ntopng: 07/Mar/2018 09:51:07 [NtopPro.cpp:321]
WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
Mar  7 09:51:07 stud-s4 ntopng: [NtopPro.cpp:321] WARNING: [LICENSE] You
can buy a permanent license at http://shop.ntop.org
Mar  7 12:54:31 stud-s4 nprobe: 07/Mar/2018 12:54:31 [nprobe.c:3785]
ERROR: Invalid nProbe license (/etc/nprobe.license) [License format error]
Mar  7 12:54:31 stud-s4 nprobe: 07/Mar/2018 12:54:31 [nprobe.c:3794]
ERROR: **  Switching to DEMO MODE (missing valid license) **
Mar  7 12:54:31 stud-s4 nprobe: 07/Mar/2018 12:54:31 [nprobe.c:3796]
ERROR: **  Purchase your nProbe license at                **
Mar  7 13:31:04 stud-s4 ntopng: [NtopPro.cpp:300] WARNING: [LICENSE]
Invalid or missing license
Mar  7 13:31:04 stud-s4 ntopng: [NtopPro.cpp:321] WARNING: [LICENSE] You
can buy a permanent license at http://shop.ntop.org

**Comment by gillmore-ac** [comment]
Hey @vvraciu 
I am also running the academic licensing, and that is the problem that I had started with. 
I see that you are running v.8.2.180306. Try and run another update so that you are running v.8.2.180308. That version fixed my issues with the "License format error" and got my other nProbe box up and running.

**Comment by vvraciu** [comment]
Thank you, issues solved now :)

**Comment by simonemainardi** [comment]
Thanks for reporting. That was due to a glitch in license verification that as has been quickly resolved.

**Comment by gillmore-ac** [comment]
I'm sorry, but my issue is still not fixed.

**Comment by simonemainardi** [comment]
@gillmore-ac, I quote you

> That version fixed my issues with the "License format error" and got my other nProbe box up and running.

So what else is happening? If your maintenance is expired after the update this is not related to license verification...

**Comment by gillmore-ac** [comment]
It's as I said in the original post. I had some licensing issues, but that was fixed with the update. Now I have one of my nProbe instances that will only run for about 10 minutes even though it has valid licensing.

The comment that you quoted was a reply to  vvraciu about their issues, which is what I had experienced just prior to the issue that I posted about.

Sorry for the confusion.

**Comment by gillmore-ac** [comment]
@simonemainardi 
Can this issue be reopened as the issue described in the original post was never addressed? I have updated to the latest (v8.2.180312) but nProbe is still exiting after 10min.

**Comment by simonemainardi** [comment]
@gillmore-ac are you sure the maintenance is still valid? We believe we have sorted out the issue. Send me your order id privately (mainardi ntop org) so I can check

**Comment by gillmore-ac** [comment]
If I run `nprobe -v` or `nprobe -v --online-license-check` it shows a valid license with maintenance until March 7 2019. 

I sent you the order id.

**Comment by deslone** [comment]
Even for a trial product,  A 10 minute trial period is unreasonable.  I cannot even get a good idea of its usefulness in that time.  Given all of the complaints I've seen from many sources regarding licensing problems,  I cannot see how customers can trust this product.  I wish that Ntop could be a little more reasonable to potential users.

**Comment by cardigliano** [comment]
@deslone please note that we provide trial/evaluation licenses for longer periods, you just need to send us an email asking for a trial (please write to mallegro at ntop.org)
