### ISSUE TITLE
MAC changing between real and router's address

### ISSUE THREAD

**Issue by pfruh** [ntop/ntopng#1694]
Hey,

I'm using ntopng together with nprobe to monitor sFlow from 2 switches with the following setting in nprobe:

```
-V=10
-T=%L7_PROTO %IPV4_SRC_ADDR %IPV4_DST_ADDR %L4_SRC_PORT %L4_DST_PORT %IPV6_SRC_ADDR %IPV6_DST_ADDR %IP_PROTOCOL_VERSION %PROTOCOL %IN_BYTES %IN_PKTS %OUT_BYTES %OUT_PKTS %FIRST_SWITCHED %LAST_SWITCHED %IN_SRC_MAC %OUT_DST_MAC %DIRECTION %TCP_FLAGS %SAMPLING_INTERVAL
```

This works so far, however when looking at IP's in host_details.lua or other parts of ntopng, I see their MAC constantly change between their real MAC and the routers MAC. When searching for the Routers MAC I can see it is currently assigned to 298 Hosts, this number fluctuating up and down. Is there a way to fix this?

**Comment by emanuele-f** [comment]
Can you create a pcap file with the sflow traffic so that we can reproduce the problem?

**Comment by pfruh** [comment]
We changed the switch config to only monitor egress traffic on all interfaces (hoping that would fix the issue), but it didn't help.

The pcap is with this current config. Can I send it to you via mail? Don't really want to post it in public

**Comment by emanuele-f** [comment]
Please send it at faranda@ntop.org

**Comment by pfruh** [comment]
Done :)

**Comment by emanuele-f** [comment]
Thank you, what's the mac address of your router?

**Comment by pfruh** [comment]
3C:8A:B0:8D:DD:70

**Comment by emanuele-f** [comment]
Hi, I've sent you a stripped pcap with two sflow packets which reproduce the behaviour you are describing. The problem is inherent to sflow itself. If you sample a packet on a "lan" interface facing the host, the packet will have the host mac address. If you sample a packet on a "wan" interface facing the outside, the packet will have the router own mac address as it is acting as a router.

In ntopng we assume that the latest mac we see for a given IP is associated to that IP, this is why you get such a constantly mac swapping. Possible solutions:

1) Remove the mac address from the nprobe template
2) Enable `Disaggregation` in the `Network Interfaces` ntopng preferences. This will split the traffic based on the ingress interface and it will create many virtual interfaces.

**Comment by pfruh** [comment]
Thanks for the info - would it help to remove the sampling from the uplink interfaces (one per switch) and sample only the other interfaces?

**Comment by emanuele-f** [comment]
Yes of course, if you exclude uplink the traffic (the one with router mac addresses) you should solve this

**Comment by pfruh** [comment]
I'll give that a try, thank you very much for your help!
