### ISSUE TITLE
No Recently Active Flows

### ISSUE THREAD

**Issue by mhercek** [ntop/ntopng#1761]
Recently switched from softflowd to pmacct and after that I have no recently active flows. I can browse them through Historical Explorer though. Time is synced.
What's the logic behind recently active flows?

![1](https://user-images.githubusercontent.com/20775751/39346554-12a21c0c-49ef-11e8-885b-db8a4c0a5617.png)

![2](https://user-images.githubusercontent.com/20775751/39346475-9358b1f4-49ee-11e8-9917-0516bc95c1fc.png)

**Comment by emanuele-f** [comment]
Hi, the Flows view shows the flows wich are currently sending/receiving traffic. When a flow does not see traffic for a while, the flow is considered expired. The timeout for this is the `Flow Idle Timeout` from the ntopng Cache settings.  Since you are capturing remote flows, both your exporter and nprobe apply delay to the flow, so by the time it reaches ntopng the idle timeout could be triggered. If you have little traffic, the `--disable-cache` and `--zmq-disable-buffering` nprobe options can help you reduce the nprobe export delay.

**Comment by emanuele-f** [comment]
@mhercek any news?

**Comment by mhercek** [comment]
`--disable-cache` and `--zmq-disable-buffering` helped to solve my problem.

However ntopng shows me _recently active flows_ when nprobe is in collector mode and exporter is Cisco device (not ASA), but not when exporter is pmacct, even the traffic is heavy.
