### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by jpbourke** [ntop/ntopng#1771]
Our engineers would like to be able to be able to view a customer's traffic (one IP address per customer) at high resolution, going back one hour.  High resolution is at 6 second ticks, which is 600 ticks an hour, with four data points - RX/TX bytes/packets is 2400 data points per customer, 50,000 customers gives us 12m data points in a database.  

Put another way, we'll have 50,000*4 data points every 6 seconds, which is a 200k data points.  12m data points is not a big database, but a snapshot of 200K data points ever 6 seconds would seem quite extreme.

So it comes down to getting this quantity of data out of ntopng ?  I'm not sure if this is even a realistic thing to ask of ntopng.  If ntopng had a streaming mechanism we could do the rest.

**Comment by emanuele-f** [comment]
Hello, ntopng periodically (every 5 minutes) saves per-ip traffic data on RRD. RRD is responsible for calculating the derivate between the old and new value. In order to implement the high resolution data export, you should move away from RRD and use a dedicated data processing framework instead.

You can implement customized *poll* scripts to extract data from ntopng. As an example, you can look at how prometheus integration works:

https://github.com/ntop/ntopng/blob/dev/scripts/lua/metrics.lua
https://github.com/ntop/ntopng/blob/dev/doc/README.prometheus

**Comment by emanuele-f** [comment]
Information given, closing the issue for now.

**Comment by jpbourke** [comment]
We had another thought.  We could  hack flow.cpp to change the tdiff_msec to 6000 in order to get 6 second throughput.  We'll have to break our RX and TX into separate counters,

Is this a hack too far, will it have knock on effects elsewhere ?

**Comment by jpbourke** [comment]
In fact could we then write a period user script to export that via a low level TCP connection, something very light weight ?

**Comment by simonemainardi** [comment]
We have very recently introduced per-second measurements in our other software nProbe. Have a look at https://www.ntop.org/nprobe/introducing-per-second-measurements-in-nprobe-flow-exports/ for discussion and examples.

We believe that increasing the samples resolution is good and we will also add this to ntopng at some point.
