### ISSUE TITLE
can i export all visited websites per IP using NTOPNG?

### ISSUE THREAD

**Issue by ryemanalaysay** [ntop/ntopng#1775]
i want to see all the websites visited of my users per day, and is it there a report on this?

is this possible in ntop? thank you

**Comment by emanuele-f** [comment]
Hello, ntopng only shows the top visited sites since startup (you need to enable "Top HTTP Sites" from preferences, then go into the "http" tab into an host page).

As an alternative, you can manually process sites yourself by querying the "Export Host Data" page (see `https://github.com/ntop/ntopng/tree/dev/doc` for cli access) and look at the `sites` json field.
