### ISSUE TITLE
no pf_ring.h file

### ISSUE THREAD

**Issue by FOSquare** [ntop/ntopng#1790]
I test the pfcount –i  eth2. It works, but pfcount –i  zc:eth2 does not work. It says “pfring_open error [no such device] (pf_ring not loaded or interface zc:eth2 is down ?)”. When I use the “make” command in the ixgbe-5.3.7-zc/src folder, it says: fatal error: pf_ring.h: No such file or directory #include “pf_ring.h”. I check the files below the /src, there is no pf_ring.h file. Why the file is lost? How can I fix it?

**Comment by FOSquare** [comment]
Use zcount –h can not get the pf_ring version. It says “No command ‘zcount’ found, did you mean …”. I check from the internet, and I use cat /proc/net/pf_ring/info to get the version of pf_ring, is shows the version is 7.1.0. However, when I use this to generate the license, it told me that “Please check the version Id format”. And after I get the license, how should I use it? Thanks a lot.

**Comment by cardigliano** [comment]
@FOSquare are you using packages or compiling from source code?
As of the error with zc:eth2, it seems that the ZC driver has not been loaded, please read the instructions at http://www.ntop.org/guides/pf_ring/get_started/packages_installation.html
As of the error with zcount, it seems it is not installed, installing our packages should fix it, or you can run it from PF_RING/userland/examples_zc if you are compiling from sources. 
In order to compile the drivers from sources please run "cd PF_RING/drivers/intel/; ./configure; make"
