### ISSUE TITLE
SNMP Support in Professional Edition

### ISSUE THREAD

**Issue by Alestor** [ntop/ntopng#1806]
Hello,

since https://github.com/ntop/ntopng/issues/1794 remains unanswered, I'll try it by opening a new request. I'm pretty upset about how features are handled by the ntopng team. When I purchased ntopng professional it was definitely with snmp support AND upgrades included. The code for SNMP becomes rewritten, suddendly moved up to enterprise and professional remains without SNMP Support at all. Why do you not leave the old SNMP Feature in Professional?
If "upgrades" stays this way, I'm sure this time I won't extend my Licenses at the End of July.

Kind regards

**Comment by lucaderi** [comment]
Hi, we have moved SNMP from the pro edition as due to design changes in ntopng, it was not possible to keep them in the pro edition. As we acknowledge this can be a problem, I encourage you to contact me (deri@ntop.org) and I will give you a enterprise upgrade at no cost. We apologise for the inconvenience.

**Comment by Alestor** [comment]
Thank you @lucaderi. I've wrote you an email.
