### ISSUE TITLE
Info regarding non web based applications

### ISSUE THREAD

**Issue by ruchi09** [ntop/ntopng#1828]
While monitoring the ftp transactions, although ntopng gives different flows for different file transactions, it does not tell which file is getting transferred. Also, for mysql queries (server client transactions) it only shows one flow.

 Is it possible to get query wise details (knowing which query took how much time) and also the file name in ftp transactions.

**Comment by emanuele-f** [comment]
Hi, your requests are very specific to the ftp and mysql protocols, please consider checking out [nDPI](https://github.com/ntop/nDPI), which is responsible for the packet deconding.

In the ftp case, since the flows are different, ntopng could display such information in a consistent way. On the other hand, for mysql the db connection actually consists of a single network flow, so it's normal that ntopng only shows one flow.

I suggest you to look at [bcc/ebpf](https://github.com/iovisor/bcc/tree/master/tools) which is more appropriate to extract this kind of information, in particular the [mysqld_qslower.py](https://github.com/iovisor/bcc/blob/master/tools/mysqld_qslower.py) should provide the details you need.

**Comment by emanuele-f** [comment]
Closing for now.
