### ISSUE TITLE
User details in a flow

### ISSUE THREAD

**Issue by prasanthi97** [ntop/ntopng#1846]
In a particular flow I'm able to get the ip-address and mac address of the user. As well can we get the user name for the respective user.
How can we identify whether the user is VDI user or a Citrix user or Desktop/laptop user.

**Comment by emanuele-f** [comment]
Usually you can identify virtual hosts by the MAC address manufacturer

**Comment by prasanthi97** [comment]
I'm able to identify the host. 
Can we get the user name?

**Comment by emanuele-f** [comment]
ntopng already extracts host name from different protocols (e.g. MDNS, Bootp, NetBios) and operating system as well (e.g. from HTTP requests). But if the virtual host is NAT-ted, name information is not available because such packets do not reach the network interface. Please note that I'm referring to the machine name, not the "user name". The actual "user name" would require some sort of probe into the system in order to be extracted.
