### ISSUE TITLE
Pie Chart more information not working as expected. 

### ISSUE THREAD

**Issue by MatinDeWet** [ntop/ntopng#1857]
On most of the pie charts, they state that one can click on them to view more information.  When I try to do so, nothing happens. I am running ntopng on PFsense. I am using a free package.

**Comment by emanuele-f** [comment]
Hello, can you specify what charts in particular are producing the issue? I can see it on the "Top Flow Talkers: Live" chart for example.

**Comment by emanuele-f** [comment]
Top Flow Talkers and Top ASN links fixed with 8af027d93b3bae97736c9f7e49f15f35b6cd3943

**Comment by MatinDeWet** [comment]
- dashboard, and interfaces:
-Hosts (top hosts sned and receive)
- ports (top cliend and server ports)
- Applications ( top application protocols) 
- top ASNs talkers not showig at all

**Comment by simonemainardi** [comment]
I can confirm it works using the latest ntopng dev:

> dashboard, and interfaces:
-Hosts (top hosts sned and receive)

just double-click on the ip addresses and you will be redirected to the host page

> ports (top cliend and server ports)

double-click on the port number and you will be redirected to a page that shows all the active flows with that given port as source or destination

> Applications ( top application protocols)

same as for the ports. Just double-click on the application name.

> top ASNs talkers not showig at all

same for the ports. Just double-click on the AS name.


I think you just have to double- (rather than single-) click on the item of interest.

**Comment by MatinDeWet** [comment]
Thanks (Facepalms). "I think you just have to double- (rather than single-) click on the item of interest."
