### ISSUE TITLE
Predictable Idle purge

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1901]
Based on traffic conditions (e.g. heavy traffic), idle host/flows purge does not happen periodically as it should. It is requested to review the code for all interfaces (pcap, PF_RING...) and make sure that in no case, idle purge is delayed under heavy traffic. Failure to purge idle items leads to misbehaviour.

Note that  NetworkInterface::dissectPacket() already calls 
  setTimeLastPktRcvd(h->ts.tv_sec);
  purgeIdle(h->ts.tv_sec);

**Comment by simonemainardi** [comment]
Purge is performed by `NetworkInterface::purgeIdle` that walks the hash table of flows (`NetworkInterface::purgeIdleFlows`) and all the other hash tables (`NetworkInterface::purgeIdleHostsMacsASesVlans`).

Regardless of the number of calls to `NetworkInterface::purgeIdle`:

- The hash table of flows is purged no more than one time every `FLOW_PURGE_FREQUENCY=2` seconds.
- All the other hash tables are purged in more than one time every `HOST_PURGE_FREQUENCY=2` seconds.


`NetworkInterface::purgeIdle` is called every time a packet is processed in `NetworkInterface::dissectPacket`, regardless of the instantiated interface type. So under heavy traffic conditions we can assume to always hit this function and thus to execute the idle purge.

The other calls are performed depending on the interface type as follow.

----
`PcapInterface`

- When no packet has been received from `pcap_next_ex` within the timeout of 1 second.
- When the interface is idle(), one time every second.

CONCLUSION: for `PcapInterface` the idle purge is always performed. When packets are not coming by the `PcapInterface` as well as when the packets are coming by `NetworkInterface::dissectPacket`.

----

`PF_RINGInterface`

- `pfring_recv` is called in an unblocking fashion, that is, it returns immediately when no packet is available. When `pfring_recv` returns but no packet is available, the interface sleeps for an amount of time between 100 and 1000 microseconds and then the idle purge is always performed.

CONCLUSION: for `PF_RINGInterface` the idle purge is always performed both under heavy load and during idle periods.

----

`CollectorInterface`

-  The idle purge is always performed after `MAX_ZMQ_POLLS_BEFORE_PURGE=1000` calls to `zmq_poll` or after a maximum time of `FLOW_PURGE_FREQUENCY=2` seconds. This is true regardless of the number of messages received.

CONCLUSION: Also for `CollectorInterface` the idle purge is always performed.

----

`DummyInterface`

- Is never idle as it artificially generate flows continuously.

CONCLUSION: purge is always done in NetworkInterface packet dissection

----

`ViewInterface`

- This interface is just a wrapper of other types of interfaces so it uses for purge the logic of the other interfaces discussed.

----

`ZCCollectorInterface`

- The idle purge is always called at most every second when `pfring_zc_recv_pkt` returns no packet.

CONCLUSION: purge always performed.


----

The last thing to consider is that the idle purge evaluates virtual function `idle()`. For both hosts and flows this boils down to the call to `GenericHashEntry::isIdle`:

```
bool GenericHashEntry::isIdle(u_int max_idleness) {
  return(will_be_purged
         || (((u_int)(iface->getTimeLastPktRcvd()) > (last_seen+max_idleness)) ? true : false));
}
```

An host/flow is not purged when `iface->getTimeLastPktRcvd()` and `last_seen` stay close. This happens when there's heavy traffic activity for that host/flow but can also happen when the interface gets idle so both stops updating. Indeed:

The interface last packet received is updated in `NetworkInterface::dissectPacket()`.

Last seen is updated as follow:
- Flow last_seen is updated every time a packet is received
- Host last_seen is update in periodic activities (`Flow::update_hosts_stats`) assuming there's traffic 

Hence what can happen is that active flows/hosts of an interface that becomes idle are not purged but it cannot happen that under heavy load conditions purge idle are not performed.
