### ISSUE TITLE
"Export Host Data" only exports ifid 1 hosts

### ISSUE THREAD

**Issue by boisgada** [ntop/ntopng#1916]
Using the /lua/export_data.lua in the enterprise edition of ntopng appears to only export ifid 1 data.  Multiple tests using various commandline arguments to attempt to for other ifid host data to be exported failed.

Please advise.

Additional information:
Server: ntopng Enterprise Edition v.3.4.180726
Sensors: nProbe v.8.5.180802 (r6234) [Embedded]

**Comment by emanuele-f** [comment]
Some notes about the bug on stable:
1. ifid is never selected, so the first available interface is always returned
2. Ntop::getNetworkInterface is bugged, as it does not properly check the allowed interface. This means that a user may get data which is not supposed to be able to access.

One more note about the dev version: it uses _POST instead of _GET and there is not reason for this. This prevents data fetch via command line (because of CSRF checks), so this should be fixed.
