### ISSUE TITLE
When possible use a data directory other then /var/tmp

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1930]
The /var/tmp/ntopng default is not optimal as "tmp" stands for temporary whereas ntop data is persistent (and thus not temporary at all). Without making complicated choices, it is required to move from /var/tmp to another directory that could be for instance /var/lib/ntopng. Furthermore ideally packages should create a ntopng user with no privileges, and write onto the selected directory using this user rather than nobody.

It is required to analyse the problem and its implications with packaging and then implement the fix.

**Comment by lucaderi** [comment]
For instance in MySQL this is the layout they use (note the username)

# ls -l /var/lib/mysql
total 188476
-rw-r----- 1 mysql mysql       56 Jul  8  2017 auto.cnf
-rw-r--r-- 1 mysql mysql        0 Jul 31 06:54 debian-5.7.flag
-rw-r----- 1 mysql mysql      851 Aug  1 00:01 ib_buffer_pool
-rw-r----- 1 mysql mysql 50331648 Aug  1 00:02 ib_logfile0
-rw-r----- 1 mysql mysql 50331648 Jul  8  2017 ib_logfile1
-rw-r----- 1 mysql mysql 79691776 Aug  1 00:02 ibdata1
-rw-r----- 1 mysql mysql 12582912 Aug  1 00:02 ibtmp1
drwxr-x--- 2 mysql mysql     4096 Feb 28 10:30 icinga
drwxr-x--- 2 mysql mysql     4096 Jul 31 06:54 mysql
-rw-r--r-- 1 mysql mysql        6 Jul 31 06:54 mysql_upgrade_info
drwxr-x--- 2 mysql mysql    12288 Sep 14  2017 ntopng
drwxr-x--- 2 mysql mysql     4096 Jul 31 06:54 performance_schema
drwxr-x--- 2 mysql mysql    12288 Jul  8  2017 sys

**Comment by cardigliano** [comment]
Proposal:

Data directory path:
/var/lib/ntopng seems to be the best choice according to the standard.
On startup, if the data folder has not been specified, ntopng checks for /var/tmp/ntopng:
- if it exists, it keeps using /var/tmp/ntopng to avoid moving all data 
   to the new path (it could be that the user mounted a volume on /var/tmp/ntopng
   and it is preferable not to move the data). Display a warning in the footer.
- if it does not exist, it uses /var/lib/ntopng

ntopng User:
The package creates the 'ntopng' user during the installation.
On startup, ntopng checks for /var/tmp/ntopng
- if it exists and the user has not been explicitly set, it keeps using the 'nobody' user
- otherwise, ntopng runs as 'ntopng' (if it exists, 'nobody' otherwise), unless a different user is specified

**Comment by cardigliano** [comment]
Implemented migration to /var/lib/ntopng with user and group ntopng, according to the proposal.
