### ISSUE TITLE
Flows are not categorized correctly regarding Client and Server

### ISSUE THREAD

**Issue by Netw0rkGuy** [ntop/ntopng#1978]
Flows are sent from multiple flow exporters to a nprobe instance.

```
/etc/nprobe/nprobe.conf
-i=none
--zmq="tcp://127.0.0.1:9999"
-n=none
-3=9995
-T="@NTOPNG@ %INPUT_SNMP %OUTPUT_SNMP %EXPORTER_IPV4_ADDRESS"
## @NTOPNG@ expanded to " %L7_PROTO %IPV4_SRC_ADDR %IPV4_DST_ADDR %L4_SRC_PORT %L4_DST_PORT %IPV6_SRC_ADDR %IPV6_DST_ADDR %IP_PROTOCOL_VERSION %PROTOCOL %IN_BYTES %IN_PKTS %OUT_BYTES %OUT_PKTS %FIRST_SWITCHED %LAST_SWITCHED %SRC_VLAN  %INPUT_SNMP %OUTPUT_SNMP %EXPORTER_IPV4_ADDRESS"
--lifetime-timeout=90
```

ntopng running on the same system collects the flows from nprobe via loopback (zmq).

```
/etc/ntopng/ntopng.conf
-d=/data/ntopng
-i="tcp://127.0.0.1:9999" 
--http-port=0
--https-port=10.1.4.23:443
--local-networks="10.0.0.0/0,2001:xyz:1000::0/43"
--dump-flows=es;ntopng;ntopng-%Y.%m.%d;http://localhost:9200/_bulk;
--dump-hosts=local
--max-num-flows=400000
--max-num-hosts=200000
--sticky-hosts=local
```

Result: Almost 80% of the flows are not categorized correctly regarding the traffic direction (client and server).

```
Appl    Client                                           Server
SSL      www.somedomain.org:https       10.8.1.127:49620
```

Wireshark captures right in front of nprobe show that the origin device reports the correct src and dst ip addresses and ports.

Is this caused by nprobe or ntopng? Bug or config error?

**Comment by Netw0rkGuy** [comment]
I did some further research and analyzed the wireshark capture in more detail. The netflow source (a fortigate firewall) does indeed send two flow packets for one session. One for each direction with the number of sent and received bytes and packets:
![image](https://user-images.githubusercontent.com/42970280/45103124-75a30f80-b12f-11e8-8d14-ae82898b08b2.png)

The netflow collector should match both packets and display/process only one flow but extract the sent and received values. 
Being able to correctly detect the traffic direction is the reason, why we added %INPUT_SNMP %OUTPUT_SNMP to the V9 template.

I'm still not sure if this is a ntopng or a nprobe issue.

**Comment by simonemainardi** [comment]
can you send us a short pcap capture of the netflow that contains both data and templates, as well as the output of nprobe with the supposedly inverted flows?

My guess is that the *"srv to cli"* part of the bi-directional flow arrives before the *"cli to srv"* part (as shown in your picture) so nprobe is tricked into thinking the server is actually the client. Note that this is not a limitation of nProbe, there is nothing contained in the received flows that could tell nProbe which is the client and which is the server of a bidirectional flow that is sent in two parts. Input and output snmp are not useful because, as you can see from the picture, they are swapped as well.

**Comment by Netw0rkGuy** [comment]
Your guess seems to be right. FortiGate firewalls do behave like stupid routers when processing and generating netflows!

Despite the fact that we instructed the device to look only for RX traffic, which is in my opinion only traffic that belongs to a session initiated outside of the interface (ingress sessions), it does not seem to take this information into consideration.

It's sad that there is no configuration option to use the internal session table as a source for netflows. I will probably never manage to get this right. I'm thinking about capturing the firewall traffic with a probe to get better results.

Thanks for your time.

**Comment by simonemainardi** [comment]
If you want, I could try and implement an heuristic so that the client and the server of a flow are determined using port values.

The rationale is that the higher among the two ports it is more likely to be an ephemeral port and thus we can take it as the client.

In the case of your example above:
- port 4443 < 53417  so `srcAddr` is considered to be the server and `dstAddr` is assumed to be the 
client when creating a flow.

I could make this heuristic off by default and add a toggle in the ntopng preferences to turn it on.

What do you think?

**Comment by Netw0rkGuy** [comment]
Hey that could indeed solve this timing issues and correct most of those flows.
But I must mention that I am running the stable builds of ntopng on our productive system, so testing is a bit difficult for me.

**Comment by Netw0rkGuy** [comment]
Hey that could indeed solve this timing issues and correct most of those flows.

Maybe you can implement it that way, that one can define a maximum port number which is treated as a service port. If both port numbers are higher than that, leave the flow as it is.
If that is too complicated to document/implement a simple on/off switch would do it too. ;-)
 
But I must mention that I am running the stable builds of ntopng on our productive system, so testing is a bit difficult for me.

**Comment by Netw0rkGuy** [comment]
In which time frame or build could this enhancement be implemented?
I do not get any reasonable feedback from Fortinet.

**Comment by simonemainardi** [comment]
I can't tell you a time frame now as we're focusing on other tasks. If you are interested in an expedited development please contact us privately and we will arrange that.

**Comment by lucaderi** [comment]
@simonemainardi This has been solved already right?

**Comment by simonemainardi** [comment]
this heuristic has still to be implemented

**Comment by simonemainardi** [comment]
@lucaderi @Netw0rkGuy this issue is now implemented.

An extra preference under the "Network Interfaces" page is available as of the latest ntopng 3.9

![image](https://user-images.githubusercontent.com/3397663/58189478-dd4bbb80-7cba-11e9-8403-4b05383e8729.png)

You just have to turn it to ON to make sure the heuristic described above is applied.

@Netw0rkGuy please, give it a try and let me know. Hold on one hour - new builds are being generated - and update ntopng to the latest 3.9. Thank you.

**Comment by flyersa** [comment]
I have the same with flows from an Juniper SRX300, but i cant find this option in ntopng 4.x ?...

update: nvm. i set sampling for input AND output ;) issue solved by only specifying input sampling on the interface

**Comment by simonemainardi** [comment]
yes, it's available on 4.x as well:

![image](https://user-images.githubusercontent.com/3397663/82371585-b8e40580-9a1a-11ea-9791-ad5139b59a90.png)

**Comment by lucaderi** [comment]
In order to address this Fortinet bug please use "-p 1.1/1/1/1/0/1/1/0/0" on nProbe and it will ignore the POST octet bytes/packets. thee's nothing to change on the ntopng side.
