### ISSUE TITLE
Increase packet shapers list

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2030]
It is request to increase the number of packet shapers so that we have the ability to have at least 5 of them, better if the list is configurable

**Comment by simonemainardi** [comment]
This boils down to extending the three shapers (PASS, SLOW_PASS, SLOWER_PASS) to a generic number.

**Comment by simonemainardi** [comment]
After internal review, we have decided not to increase the packet shapers list in nEdge for the time being.

The reason is that users who want to have an higher number of shapers to policy the traffic, can use nProbe in IPS mode combined with netfilter. Indeed, nProbe in IPS mode can be instructed to mark packets with an arbitrary number of packets that can then be policed in the kernel with multiple shapers, using per-user or per-application policies.

Documentation is at https://www.ntop.org/guides/nprobe/ips_mode.html

A youtube video that describes the use of nProbe IPS combined with kernel's netfilter is available at https://www.youtube.com/watch?v=0Pn2kS4NvFY

A blog post is available as well https://www.ntop.org/nprobe/introducing-nprobe-ips-10-gbit-ndpi-based-traffic-policer-and-shaper-opnsense-pfsense/
