### ISSUE TITLE
Scaling Problem with nprobe/ntopng and Cisco ASR1006 with Netflow 9

### ISSUE THREAD

**Issue by fantasio82** [ntop/ntopng#2049]
Hi,

I have the following Setup:

nprobe on Server A
ntopng on Server B
Cisco ASR 1006 Router with Netflow 9 (no Sampling) configured to send Flows to Server A

Server A has no Issues (Top, iostat etc. looks fine)
Server B has Perfomance Issue. It takes long to open the Websites and I verified that there are ZMQ Drops. I'm also hitting the Alert for "Server A has too many Flows/Hosts please Extent -x/-X Parameter" 

I'm running in more and more Perfomance Issues (iostat 100%) When I extend the -x/-X Parameter to 100.000 and 3.000.000. Please advice me with further Scaling/Configuration Parameters.

Specs Server A
2 vCore VM
8 Gbyte RAM
Virtual Disk on a High Perfomance SAN

Specs Server B
12 Core Intel CPUs
96 Gbyte RAM
10.000 RPM HDD

Router Specs
Cisco ASR 1006
WAN Speed 10Gbit Up/Down

Site Specs
Round about 60.000 Hosts
Round about 2.000.000 Sessions through the Internet
Campus has multiple 10G Backbone and Two Data Centers with 40G/100G Network.

Kind Regards,

Vasco

**Comment by lucaderi** [comment]
As of -X/-x you need to set them so that they are (likely) double the peak you have. So do -X 4000000 -x 1024000 (if you have 60k local hosts let's assume you have 512k hosts in total so 1M peak). This as of ntopng -h

[--max-num-flows|-X] <num>          | Max number of active flows
[--max-num-hosts|-x] <num>          | Max number of active hosts

This for the scaling issue.
As of the performance issue, one solution is to partition traffic on the router. Example support your network is partioned in network A (1.2.0.0/16) and networkB (1.3.0.0/16). Suppose you have nProbe running on host 1.2.3.4. You need to tell the router to send  network A traffic to port 2055 and network B to 2056 of nprobe. In ntopng you can configure two ZMQ interfaces (for collecting flows) and one view interface for merging them. Each network A and B must be added to

[--local-networks|-m] <local nets>  | Local nets list (default: 192.168.1.0/24)
                                    | (e.g. -m "192.168.0.0/24,172.16.0.0/16")


nprobe -i none -n none -3 2055 --zmq tcp://ntopng_host:1234
nprobe -i none -n none -3 2056 --zmq tcp://ntopng_host:1235

ntopng -i  tcp://ntopng_host:1234 -i tcp://ntopng_host:1235 -i view:tcp://ntopng_host:1234,tcp://ntopng_host:1235

**Comment by lucaderi** [comment]
I have forgot to say that you should (on interface preferences) to disable timeseries generation for ZMQ interface and let timeseries to be generated only for the view interface (so you have a single consistent view). I close this ticket, shall you need further support please re-open it. Thanks
