### ISSUE TITLE
Implement remote-remote alarms

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2057]
It is requested ntopng to implement an alert (to be enabled from preferences) when a host that is non local (according to the ntopng configuration) sends traffic towards non local addresses. This should not happen on a LAN (but for an ISP is normal) and thus it should trigger an alert. This alert is similar to the MAC address alert but it has to be triggered the first time such host appears on network. It is compulsory to report in the alert both the IP and MAC address (likely also the ethernet port it is connected to if readable via SNMP)

**Comment by simonemainardi** [comment]
Implemented as requested.

Remote-to-remote alerts were already present.

![image](https://user-images.githubusercontent.com/3397663/46721014-50e01180-cc72-11e8-8e39-2d63f968fb93.png)

![image](https://user-images.githubusercontent.com/3397663/46721451-4f631900-cc73-11e8-9821-352ce99ec151.png)

Commit https://github.com/ntop/ntopng/commit/ddf49ef106607ebfcdc26989ca0dcbbe92f234e7 adds the same kind of alerts for the hosts, so that one is not overwhelmed by flow alerts and can quickly browse the alerts for an host to immediately know if it has undergone a remote-to-remote activity.

This is what one gets now for the hosts. As requested both the ip address and the mac address are reported. There's also a link that points to the flow alerts page to continue the drill-down. The mac address can also be used in the search box to look into SNMP devices (when present).

![image](https://user-images.githubusercontent.com/3397663/46729045-84c43280-cc84-11e8-8ad6-9070ea5d0cce.png)
