### ISSUE TITLE
Invalid localisation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2059]
Alert localisation is mixed
<img width="1142" alt="screen shot 2018-09-25 at 11 02 41" src="https://user-images.githubusercontent.com/4493366/46004212-9b7a5f00-c0b2-11e8-8a30-7022db27378e.png">

**Comment by emanuele-f** [comment]
There are two problems here:

1. The ground problem is that alert messages are written as messages to the alerts db. They should be written as json data instead so that further post-processing (e.g. localization) could be applied during query time.

2. Since language is a per-user concept and not a global instance concept, the language of a periodic script generating the alert is always english. This could be temporary patched to apply the admin language instead.

**Comment by lucaderi** [comment]
As interim solution 2 can work, in the long run 1 is the solution to implement
