### ISSUE TITLE
MAC/IP association alert are not working as they should

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2060]
As shown in screenshot of #2059, when an IP address changes the MAC association, the alerts are not reported properly. In fact I would expect to see IP/MAC hopping instead as shown in the screenshot alerts are only mono-directional (i.e. ntopng seems to remember the original MAC and does not update the association as it changes)

**Comment by emanuele-f** [comment]
Alert is working as expected:
![2018-09-25_18-28](https://user-images.githubusercontent.com/5488003/46028440-1f970b80-c0e0-11e8-98fa-fc7afa4d6507.png)
This is the relevant line which records the new association: https://github.com/ntop/ntopng/blob/dev/src/NetworkInterface.cpp#L6567

The following sequence of events could trigger the situation in the original screenshot:
1. 40:f2:e9:f9:9f:93 connects via DHCP. ntopng records the mapping
2. 40:f2:e9:f9:9f:93 goes offline
3. a8:20:66:41:04:1e connects to the network by setting a static address. ntopng genaretes alerts
4. a8:20:66:41:04:1e goes offline
5. 40:f2:e9:f9:9f:93 connects via DHCP. ntopng records the mapping, but it *does not* generate the alert since the new association is stated into the DHCP reply

**Comment by emanuele-f** [comment]
Closing as it seems to work properly.
