### ISSUE TITLE
Split housekeeping thread implementation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2071]
The housekeeping thread is carrying over many activities
- timely activity (e.g. timeseries and stats calculation)
- batch activity (e.g. aggregated flow export)

It is requested to split these two families of activities into two threads

**Comment by simonemainardi** [comment]
Missing data points when using high-res l7 at 10 seconds where due to the slow, unoptimized lua code used to store data points. Commits on Oct 12, 2018 have addressed this.

The housekeeping activities (in C++) were correctly and timely executed by ntopng.

For this reason, there's no need to spawn another thread to separate timely and batch activities so far. Note also that the only 'batch' activity performed in the C++ housekeeping thread is the aggregated flow export, performed only one time every 5 minutes.
