### ISSUE TITLE
Add the possibility to count only the "active" hosts

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#2091]
This is the list of hosts we can see into the Network window of ntopng:

![screenshot_20181009_154503](https://user-images.githubusercontent.com/14093378/46673922-3149da00-cbdb-11e8-8e16-973318410381.png)

The column that contains the number of hosts, however, contain some strange value for us: for instance we don't have 7655 real hosts into the first /19 network!
We tried to understand this value and we discovered that this number is not related to the "active" IP ("active, for us, is an IP assigned to a device that generates traffic) but to all generic IP seen into the analyzed traffic.
An IP added to this column could be related to a single SYN packet sent from an external IP to an unused internal IP as shown here:
![screenshot_20181009_154013](https://user-images.githubusercontent.com/14093378/46674537-a8cc3900-cbdc-11e8-86d5-59d95cea4434.png)

Then, could you add the possibility to count only the internal (and external) hosts that send at least a packet (in the last 24h, 1 week, 1 month, since ntopng started)? This values could be useful to understand how many *real* IP are used inside our network or in Internet and to understand how many *real* IP are generating all the *real* traffics.
The current values are interesting but they are not useful for statistics...

What do you think?

Thanks...

**Comment by simonemainardi** [comment]
> "active, for us, is an IP assigned to a device that generates traffic

Unfortunately, *your* definition of active isn't general enough for us to justify a change in all the tables that have a column with the host count.
We believe is is important to show any host in such counts as otherwise potentially relevant hosts could be hidden only because the've not received traffic.

However, being able to highlight one-way traffic hosts is still an important task. For this reason we've added an extra dropdown filter on the hosts page that allows you to select hosts with only one-way traffic

![image](https://user-images.githubusercontent.com/3397663/46865621-7578ec80-ce1e-11e8-9da9-bf519ca67a1f.png)



![image](https://user-images.githubusercontent.com/3397663/46865362-97be3a80-ce1d-11e8-9d20-3746d0bd808e.png)

Keep in mind that this function is already available on the flows page.

> Then, could you add the possibility to count only the internal (and external) hosts that send at least a packet (in the last 24h, 1 week, 1 month, since ntopng started)

Keep an eye at https://github.com/ntop/ntopng/issues/1054 as we are already discussing this.
