### ISSUE TITLE
MySQL - Dropped Flows

### ISSUE THREAD

**Issue by juesor** [ntop/ntopng#2095]
I have a user that is debating the exported data from the historical report.

Installed Packages
ntopng.x86_64                                                                       3.7.181010-4980                                                                        @ntop

If i run the report i get more data then he does.  

Is there anything to look at for queries?

Are you looking to move away from mariadb this year still?  Something like elasticsearch might be better.

**Comment by simonemainardi** [comment]
Is that user restricted to certain 'allowed networks'? If he does, then he will see only the traffic for his allowed networks.


> Are you looking to move away from mariadb this year still? Something like elasticsearch might be better.

We are developing a special-purpose high-perf flow database, our efforts are focused on it, we are not planning to move away from mariadb.

**Comment by simonemainardi** [comment]
@juesor did you have a chance to verify what I've suggested above?

**Comment by juesor** [comment]
I have LDAP setup and where do i see allowed networks.  I am in the same LDAP group as he is.  It feels like ntopng is having a hard time going through the DB and pulling data while inserting data.

![image](https://user-images.githubusercontent.com/14931420/46953151-a04b8680-d052-11e8-9c4e-8150120301b8.png)

We've look at Dropped flows int he past but this is just crazy.

**Comment by juesor** [comment]
Here is a comparison between two different users.  Top is the user that reports data missing.

![image](https://user-images.githubusercontent.com/14931420/46959345-6d5cbf00-d061-11e8-8e6f-2dc2818adfdf.png)

Below is my search for that data and yes its more but we have a cacti graph that shows that that /24 is using 250MB/s over that 1 hour range.  I am pointing out dropped flows because my thoughts is that is the problem.

![image](https://user-images.githubusercontent.com/14931420/46959353-7352a000-d061-11e8-855b-43472fff0cfb.png)

**Comment by simonemainardi** [comment]
Correct, the reason is that you have a HUGE number of dropped flows.

Your MySQL installation isn't able to ingest all the flows generated by ntopng. You can try and tune MySQL for performance (see older issues about this topic) but it is unlikely you'll get a fast-enough MySQL at you traffic speed. This is why we are focusing on the development of a special-purpose database aimed at working with hundreds of thousands flows per second.

See this comment for an in-depth discussion https://github.com/ntop/ntopng/issues/2067#issuecomment-425983436
