### ISSUE TITLE
Add Ubuntu 18.04 LTS support

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2106]
Currently nEdge supports only Ubuntu 16.06 LTS. It is requested to make changes to also support Ubuntu 18.04 LTS

**Comment by victorhooi** [comment]
Will nEdge currently install on Ubuntu 18.04 or 18.10?

Is this simply a case of it not being officially supported, or does it actually not work?

**Comment by emanuele-f** [comment]
@victorhooi there is currently no package for the Ubuntu 18 version. Moreover, there are some modifications to handle in the device configuration, for example Ubuntu 18 uses netplan instead of /etc/network/interfaces for network configuration

**Comment by victorhooi** [comment]
Is there indication on ETA for this support please?

(I see there's a 3.8 milestone - but I'm not sure when 3.8 will be release?)

Thanks! Victor

**Comment by emanuele-f** [comment]
This has been postponed, it will not be part of the 3.8 release (release soon within this month)

**Comment by victorhooi** [comment]
Oh, got it thanks for the update.

Hmm, shame about it not making 3.8. This means we need to keep using Ubuntu
16.04 for now right?

Is there any indication on when the work for 18.04 compatibility will be?

On Dec 13, 2018 21:48, "Emanuele Faranda" <notifications@github.com> wrote:

This has been postponed, it will not be part of the 3.8 release (release
soon within this month)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ntop/ntopng/issues/2106#issuecomment-446924719>, or mute
the thread

**Comment by emanuele-f** [comment]
nEdge now runs fine on Ubuntu 18, we are testing it right now

**Comment by emanuele-f** [comment]
Ubuntu 18 support is now official. https://www.ntop.org/announce/introducing-ubuntu-18-support-for-ntopng-edge-nedge/
