### ISSUE TITLE
Implement log of activities

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2143]
For administrative actions such as
- change preferences
- reconfigure XXX
- download/extract pcap
- user login
...

it is compulsory to create a log file of these activities in human readable format.

**Comment by simonemainardi** [comment]
Activities include:
- add/remove snmp devices
- any file download (pcap, flows, JSON...)
- preference changes (this if it is human readable so that we understand what it has been changed and not a computer-like log)
- logins: both failed and successful 
- user password changes
- addition/deletion of users
- remote assistance activation / deactivation (even automatically after 24H)
- alert settings changes/disable/enable
- delete hosts data / interface data / alerts

A possible solution is to `track` certain function calls in lua. To demonstrate the feasibility I've drafted a few lines of code that intercept `resetUserPassword` function call and print it along with its arguments

```
local function tracker(f)
   return function(...)
      local f_name = debug.getinfo(1, "n").name

      local args_print = {}
      for k, v in pairs({...}) do
         args_print[k] = tostring(v)
      end

      local fmt = string.format("%s(%s)\n", f_name, table.concat(args_print or {}, " "))
      io.write(fmt)

      local result = {f(...)}

      return table.unpack(result)
   end
end

local fns = {"resetUserPassword"}
local mt = getmetatable(ntop).__index

for _, fn in pairs(fns) do
   if mt[fn] and type(mt[fn]) == "function" then
      mt[fn] = tracker(mt[fn])
   end
end
```

The code should always be executed (similar to http_lint).

Implementation should:
1. Log the events in a json using the existing ntopng alert facilities
2. use localised strings to print the event

All activities MUST be formatted in a way a human can understand. Example "user X logged in" is ok, "ntopng.prefs.en0.speed changed to 10" is not good as it's not clear what happened.

**Comment by cardigliano** [comment]
Implemented:
- PCAP download
- live extraction
- host JSON downlaod
- flows data download
- alerts enable/disable/changes
- alert endpoints changes
- delete alert data
- failed/successful logins
- user add/remove
- user password change
- remote assistance activation / deactivation
- traffic recording activation / deactivation
- delete host/interface data
- add/remove snmp devices

Missing:
- preference changes: this is limited to alerts now, making this human readable for all settings and still make it maintainable requires a major code rework

**Comment by Gelob** [comment]
I'd like to note that currently in 3.7.181204 - Enterprise Edition if you have LDAP enabled and a user who attempts to login but doesn't exist in AD in you see the following message in the logs which may not make sense. If a new human readable message is already implemented it might be a good idea to remove this one.

[LdapAuthenticator.cpp:385] ERROR: no matching memberOf attribute found for any privileged/unprivileged group

**Comment by emanuele-f** [comment]
I've changed it to trace level info, thank you for reporting
