### ISSUE TITLE
nEdge errors under heavy load

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2156]
With high traffic (e.g. 700 Mbit)

Traffic stops flowing after 20 minutes or so and the log reports
14/Nov/2018 19:30:40 [NetfilterInterface.cpp:476] ERROR: nfq_handle_packet() failed: [len: 52][rc: -1][errno: 0]
14/Nov/2018 19:30:40 [NetfilterInterface.cpp:476] ERROR: nfq_handle_packet() failed: [len: 52][rc: -1][errno: 0]
14/Nov/2018 19:30:40 [NetfilterInterface.cpp:476] ERROR: nfq_handle_packet() failed: [len: 52][rc: -1][errno: 0]
14/Nov/2018 19:30:40 [NetfilterInterface.cpp:476] ERROR: nfq_handle_packet() failed: [len: 52][rc: -1][errno: 0]
14/Nov/2018 19:30:40 [NetfilterInterface.cpp:476] ERROR: nfq_handle_packet() failed: [len: 52][rc: -1][errno: 0]
14/Nov/2018 19:30:40 [NetfilterInterface.cpp:476] ERROR: nfq_handle_packet() failed: [len: 52][rc: -1][errno: 0]
14/Nov/2018 19:18:15 [NetfilterInterface.cpp:476] ERROR: nfq_handle_packet() failed: [len: 52][rc: -1][errno: 0]
14/Nov/2018 18:51:59 [NetfilterInterface.cpp:476] ERROR: nfq_handle_packet() failed: [len: 52][rc: -1][errno: 0]
14/Nov/2018 18:47:17 [NetfilterInterface.cpp:476] ERROR: nfq_handle_packet() failed: [len: 52][rc: -1][errno: 0]

@emanuele-f + @cardigliano: putting nEdge under heavy traffic might help to troubleshoot this issue

**Comment by simonemainardi** [comment]
references having the same issue with 52-bytes packet causing `nfq_handle_packet` to fail:

- https://www.spinics.net/lists/netfilter/msg54954.html
- https://stackoverflow.com/questions/20954110/netfilter-queue-spurious-packets

Should be fixed in the latest build that includes better error handling, retries and uses  `MSG_DONTWAIT`  in the recv().
