### ISSUE TITLE
ZMQ flows stop being seen randomly when high traffic is found

### ISSUE THREAD

**Issue by juesor** [ntop/ntopng#2157]
I have proven to Simone that zmq traffic is not being seen in ntopng or nprobe randomly.

![image](https://user-images.githubusercontent.com/14931420/48685040-022f6c80-eb7a-11e8-90e8-c58c480c6718.png)
![image](https://user-images.githubusercontent.com/14931420/48685051-08bde400-eb7a-11e8-983b-ad6997572704.png)

I ram a tcpdump -i any port 5556 and tcpdump showed 0 KB over 5 minutes proving no traffic on that port.

**Comment by simonemainardi** [comment]
waiting to jump on the system as soon as the issue occurs to debug

**Comment by lucaderi** [comment]
@juesor Is the problem solved?

**Comment by juesor** [comment]
No i did was we talked about over telegram and it did not resolved the issue.  i have added a crontab to nightly restart ntopng and it hasn't crashed since then.

I figured since i am looking at the new DB i'd hold off doing this for now.

**Comment by juesor** [comment]
This happened again last night. I have the system in a failed state if you would like to troubleshoot.

**Comment by simonemainardi** [comment]
So it turned out that keepalives were not honored for the tcp socket used by zmq. The connection was dead but the client, without keepalives, was considering it active. This can also be seen from the following `netstat` output.

Client:
```
[root@ntopng ntopngsrc]# netstat -polenta | grep 5556
tcp        0      0 192.168.3.8:60300       108.59.105.49:5556      ESTABLISHED 0          76135532   12921/ntopng         off (0.00/0/0)
```

Server:
```
[root@nprobe ~]# netstat -polenta | grep 5556
tcp        0      0 0.0.0.0:5556            0.0.0.0:*               LISTEN      0          31580346   15988/nprobe         off (0.00/0/0)
[root@nprobe ~]#
```

My commits in ntopng and nprobe use `zmq_setsockopt` to request keepalive support from the kernel. This allows the client to detect a "dead" connection and perform a reconnection.
