### ISSUE TITLE
Post pcap for Security Analysis

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2225]
In case of an alert, it is requested to add the ability to extract a pcap that triggered the alert and (optionally) to post it to a security endpoint. Examples of endpoints include cloudshark and Security Onion

**Comment by lucaderi** [comment]
Think how to add the ability, in case of n2disk integration, to extract a pcap for selected alerts when possible.

**Comment by cardigliano** [comment]
A  PCAP download button in the Drilldown column has been added for Flow Alerts (when recording is enabled)

**Comment by cardigliano** [comment]
In order to push the pcap to Cloudshark, we need to schedule an extraction task that will use HTTP POST to upload it as in the below example. Username, password, token, should be configured at least.

curl -k -u <username>:<password> -F file=@/storage/1605197313.pcap  http://192.168.56.103/api/v1/<TOKEN>/upload
