### ISSUE TITLE
Delete host data is not flexible

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2257]
<img width="567" alt="screenshot 2018-12-18 at 23 52 43" src="https://user-images.githubusercontent.com/4493366/50187931-1785eb00-0320-11e9-86e0-04f42c5fb5ad.png">

Passing a network/mask makes this feature more useful

**Comment by emanuele-f** [comment]
This features requires very complex operations due the fact that ntopng does not possibly now all the hosts it has to delete (since hosts are cached for about 1 hour in redis and querying influxdb for such information returns a lot of results). This would probably require to implement a "delete by pattern" operation on the backends, for example on redis, influxdb and rrd. In influxdb a tag match by pattern could be used for simple cases (e.g. `192.168.1.0/24` can be turned into `host =~ /^192.168.1./`) but more complex cases do not fit this (e.g. `192.168.1.123/27`).

**Comment by lucaderi** [comment]
Deleting a /24 and /32 network would be enough.
