### ISSUE TITLE
Manage Stored Data not working as expected

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2258]
After having deleted data most host X with "Manage Stored Data", going to host X in the GUI and displaying for instance protocol statistics, it shows that past stats are still present contrary to what expected

**Comment by lucaderi** [comment]
The data in memory needs to be also cleaned.

**Comment by emanuele-f** [comment]
In order to completely clean the host data, the following steps should be taken:
1. Host should be "flagged" by the lua code (e.g. by putting it into a linked list / hash)
2. The packet capture thread should check for flagged hosts, destroying them (calling destructor and removing from the hosts hash table) and removing the redis serialization keys

A simpler solution would be to perform the persistent data cleanup at ntopng startup, before the in-memory data is populated. This would require restarting ntopng in order to perform a stored data reset.

**Comment by lucaderi** [comment]
Please implement a C++ method (e.g. cleanup()) that cleans up host counters, stats etc. and do NOT call it in the meantime. Done this we'll decide how to call it.

**Comment by emanuele-f** [comment]
Initial work implemented in 8cdf051d779a684fe25aee4d8e18a4d0315e70a8

**Comment by simonemainardi** [comment]
implemented both for mac addresses and l3 hosts
