### ISSUE TITLE
Remote hosts are not serialized when sticky option is set

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2323]
When setting sticky hosts to `remote` or `all` it is expected to dump and restore remote hosts. This does not happen right night now as the `Host::serialize2redis` is empty (only local hosts can be serialized and restored).

**Comment by simonemainardi** [comment]
Sticky hosts refer to the ntopng ability to prevent hosts from expiring from memory and this works OK.

The serialization/deserialization functionality is not directly related to this. By design, the serialization/deserialization is always done only for local hosts as it could be uncontrollably costly to perform such tasks for all the hosts.
