### ISSUE TITLE
Unknown traffic type sourced by "other" and received by "other"

### ISSUE THREAD

**Issue by vladola** [ntop/ntopng#2363]
Can somebody help me understand how come the majority of the traffic reported is effectively unknown and generated by 'others' ? Please see image.

![](https://i.imgur.com/AiTCXgH.png)

**Comment by emanuele-f** [comment]
Please re-post the image on github, the link is not accessible. Are you capturing traffic from a physical interface or Netflow/sFlow? Please post your /etc/ntopng/ntopng.conf

**Comment by vladola** [comment]
This is from netflow.

This is the config:

```
#Dub-Office
-i=tcp://10.19.0.250:5564
#311-Office
-i=tcp://10.19.0.250:5565
#AWS-AMER
-i=tcp://10.19.0.250:5566
#AZU/SL/AWS_OOB/AWS_Legacy AMER
-i=tcp://10.19.0.250:5567
#GCE-AMER
-i=tcp://10.19.0.250:5568
-i=ens3
--pid-path=/var/tmp/ntopng.pid
--daemon
--http-port=3000
--local-networks="64.16.224.0/19,192.76.120.0/24,10.0.0.0/12,10.16.0.0/12,10.32.0.0/12,172.16.0.0/12"
--dns-mode=1
--data-dir=/data/var/lib/ntopng
--disable-autologou
-e
```

**Comment by emanuele-f** [comment]
Which ntopng and nprobe version are you using? `ntopng -V`.
Since you are capturing from a netflow exporter, nProbe can only perform port based traffic identification (no DPI), so this could be normal. Can you inspect the active flows and possibly post a screenshot of the unknown flows?
Regarding the "Other" elements, it means that the network traffic is not generated by some top hosts but by many hosts. A useful feature to analize the past traffic is to enable flows dump to nIndex. Please check out https://www.ntop.org/ntopng/say-hello-to-nindex-personal-big-data-system-for-network-flows/ and https://www.ntop.org/guides/ntopng/historical_flows.html for more information

**Comment by vladola** [comment]
Hi Emanuele, here's my version:

```
v.3.8.190111	[Enterprise/Professional build]
GIT rev:	3.8-stable:3c2d3bfbe360ca27299ccfd5cdcad1c90db5aeab:20190111
Pro rev:	r2170
Built on:	Ubuntu 18.04.1 LTS
System Id:	8E50630A<SNIP>
Platform:	x86_64
Edition:	Professional
License Type:	Permanent
Maintenance:	Until Fri Jan 24 10:40:19 2020 [345 days left]
License:	B3E7953CB3<SNIP>
```
Is the historical data only in the enterprise edition? I think we have the professional edition. BTW, if 'other' is all other flows not 'in the top' how can I actually see them? They account for most of the traffic.

And here is an unknown flow:

![](https://i.imgur.com/R0U3ZXN.png)

**Comment by emanuele-f** [comment]
nIndex is only suggested with the dev version (3.9) and in pro will only keep 3 days of data (enterprise version does not have such limit). Anyway, the flow above has non standard ports 8084 and 49813 so nprobe can do very little to identify the protocol. Moreover, if the flow has mono-directional traffic the netflow exporter configuration may be wrong. If you want full layer 7 visibility, you should use a mirror/tap, please check out https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools .

**Comment by emanuele-f** [comment]
Question answered. If you have other questions please open a new ticket.
