### ISSUE TITLE
Improve SNMP/MAC correlation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2373]
![screen_shot_2019-02-13_at_20_44_16](https://user-images.githubusercontent.com/4493366/52739103-7a1dff00-2fd0-11e9-9c61-14eb68d9d3d0.png)
SNMP alerts are not properly correlated to devices. For instance in the above examples, SNMP devices do not show the ports that have been affected by alerts. it would be nice to have a count of alerts per device/port instead of having them uncorrelated in the alert list. Please have a look at #2223.

**Comment by simonemainardi** [comment]
Implemented. Now alerts are shown grouped with a count of events on a per-device-per-port basis so that is is possible to retrieve the interfaces and devices that are generating most errors

![image](https://user-images.githubusercontent.com/3397663/56366781-2e681b80-61f4-11e9-9814-602f1600259f.png)
