### ISSUE TITLE
Bad flow formatting code in ICMP

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2389]
![screen_shot_2019-02-16_at_11_58_15](https://user-images.githubusercontent.com/4493366/52898779-4b777280-31e2-11e9-9b0e-9c0199e2a62c.png)

The "ICMP refer to flow" feature does not format flows properly. For instance in the above example the blacklist icon is missing from the ICMP info field, but it is present in the flow peers. This means also that the code you have written does not use a function or formatting the flow, but you have written the code twice. This is also bad as code duplication should not be promoted.

**Comment by simonemainardi** [comment]
No code has been duplicated. Function `getFlowLabel(icmp["unreach"]["flow"], true, true)` has been used to print the flow ALSO in the ICMP info row.

Missing Icon was just due to the fewer details with which the flow in the ICMP info was requested.

Requesting the flow with higher details automatically solves.

![image](https://user-images.githubusercontent.com/3397663/52939273-0418ef80-3364-11e9-9dc6-9c55cef746da.png)
