### ISSUE TITLE
Invalid DNS over TCP dissection

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2400]
![532](https://user-images.githubusercontent.com/4493366/52966425-88d92d00-33a7-11e9-8c67-725f4665a79b.png)
![531](https://user-images.githubusercontent.com/4493366/52966426-8971c380-33a7-11e9-8fd8-c108e2acb87e.png)

**Comment by simonemainardi** [comment]
this is normal. The fact that you are seeing strange characters in the DNS query is very likely due to an infected host or an attack. This is why the alert says 'Invalid DNS query" and reports it as suspicious activity.

**Comment by lucaderi** [comment]
No this is an invalid DNS over TCP dissection. Please gather a pcap file for reproducing it

**Comment by emanuele-f** [comment]
TCP DNS dissection fixed in https://github.com/ntop/nDPI/commit/ab3833a708fbd56e7edc72169563d26dffeb14de, now working properly. Please reopen if necessary.

**Comment by lucaderi** [comment]
Not sure your fix will solve the bug

**Comment by simonemainardi** [comment]
fixed with: https://github.com/ntop/nDPI/commit/59f683858b2b8f28e88b9348b75fef5164665964

Issue was due to mono-directional DNS over TCP flows. Such flows were seen as monodirectional due to asymmetric routing and nDPI was tricked into thinking that the TCP header was actually the DNS response, yielding spurious data.
