### ISSUE TITLE
Implement Allowed Interfaces with LDAP and Radius authentication

### ISSUE THREAD

**Issue by laurentduru** [ntop/ntopng#2489]
Today it's possible to allow access to a specific interface for local authenticated user.

I propose 2 enhancements :
1) Allow multiple interfaces selection per user
2) Extend to LDAP and Radius authentication

The use case is to share a Ntopng instance with multiple interfaces corresponding to multiple nprobe in ZMQ to multiple entity in a company and to limit visibility for specific user whereas admin can have access to all interfaces statistics.

**Comment by emanuele-f** [comment]
Please consider using the view interfaces (e.g. `-i view:eth0,eth1`) to create logical groups of interfaces which can be assigned to users.

Regarding the second part of the request, since the users which authenticate through LDAP/Radius are separate from the "local users" that you can configure in ntopng, I think this should be addressed via an additional attribute to be exposed by the LDAP server in a similar way as this information is provided in the HTTP authenticator https://github.com/ntop/ntopng/blob/dev/doc/README.HTTP_AUTHENTICATOR

**Comment by laurentduru** [comment]
"View" will concatenate counters, my proposal is to have access to multiple "independant" interfaces with independants counters.

Today in LDAP authentication mode we can define a user group or admin group. 
I think there is multiple ways to provide the function : 
1) extend ldap attribute as you propose, but it's sometime difficult to ask LDAP administrators to extend attributes for a specific application
2) add "users group" in Ntopng, a group of users corresponds to a LDAP group and in the ntopng configuration we associate interfaces, network, admin/user status, ... to the users group.
3) manage all users accounts and permissions in ntopng, LDAP is only used to validate login/pwd (extends the principle of local users to LDAP)

**Comment by emanuele-f** [comment]
Please open a separate request for the multiple interfaces support.
For solutions 2 and 3, ntopng still needs a way to associate ldap/radius users (which are dynamic and not known in advance by ntopng) to the corresponding ntopng users. This is the main problem with such approaches. I think that a `(n) ldap users -> (1) ntopng user` mapping is not enogh in this case, a `(n) ldap users -> (n) ntopng users` mapping would be more suitable

**Comment by emanuele-f** [comment]
Closing for same motivations as #2525. Please contact us if you are interested in implementing this.
