### ISSUE TITLE
Extend SSL Alerts with expired and self-signed certificates

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2513]
Add Alerts when:

- The SSL certificate is expired
- The SSL certificate is self-signed

**Comment by emanuele-f** [comment]
The certificate expiration could be verified from the `validity` field in the certificate itself:
<img src="https://user-images.githubusercontent.com/5488003/57690116-6c5c3200-7630-11e9-9564-0c1348f8155f.png" data-canonical-src="https://user-images.githubusercontent.com/5488003/57690116-6c5c3200-7630-11e9-9564-0c1348f8155f.png" width="450" />

In order to verify if the certificate is valid in general (e.g. not self signed), we must do some work. Here are some important concepts to keep in mind:

## Certificates background
- Within a single SSL handshake, the server can provide many certificate, not only one. This forms the certification chain
- The first certificate of the chain is the actual certificate used by the client
- The last certificate of the chain is the root certificate, which must be signed by a valid CA
- There can be intermediate certificates in the middle

Here is an example for repubblica.it:

![2019-05-14_12-00](https://user-images.githubusercontent.com/5488003/57690418-23f14400-7631-11e9-906b-981959c0361f.png)

Here we can see two certificates in the chain. The root certificate is the one of letsencrypt. The intermediate certificate for kataweb  has been issued by letsencrypt . In order to verify this:

From wireshark, export the root certificate as binary data in root.der, then the intermediate certificate in cert1.pem. Now convert the certificates to pem:
```
$ openssl x509 -inform der -in cert1.der -out cert1.pem
$ openssl x509 -inform der -in root.der -out root.pem
```
If we try to directly verify the intermediate certificate we fail because it's not signed by a trusted CA:
```
$ openssl verify cert1.pem
CN = *.kataweb.it
error 20 at 0 depth lookup: unable to get local issuer certificate
error cert1.pem: verification failed
```
Instead, we need to verify all the certificate chain, starting from the root cert (signed by a trusted CA) and going up until the first certificate:

```
$ openssl verify root.pem
root.pem: OK

$ openssl verify -verbose -CAfile root.pem cert1.pem
cert1.pem: OK
```

## Proposal
I propose the following:
- use openssl for certificate verification (here is an example https://stackoverflow.com/questions/2756553/x509-certificate-verification-in-c)
- nDPI should have a flag to enable certificate verification. This however adds a dependency on openssl for nDPI.
- when the flag is active, nDPI extracts the the certificates and validates all the chain via openssl. N validations are needed, where N is the number of certificates of the certification chain
- then nDPI reports the validation result in the flow structure
- possibly the certificates may be spread across multiple packets, this must be handled

**Comment by simonemainardi** [comment]
For the expired certificates it is requested to use the newest nDPI TLS certificate validity (notAfter/notBefore) extension.

**Comment by simonemainardi** [comment]
TLS alerts for expired certificates implemented. All the TLS alerts supported are now the folowing

![image](https://user-images.githubusercontent.com/3397663/73072975-9ef44500-3eb6-11ea-99de-91b8401411df.png)
