### ISSUE TITLE
Replace JSON with more efficient format when using ZMQ

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2562]
While JSON is a versatile format for sending traffic information between nProbe and ntopng, the use of it is becoming a performance bottleneck when decoding it. While JSON format should be supported for compatibility reasons, a more efficient format needs to be implemented. Possible options
- http://bsonspec.org
- https://msgpack.org
- https://cbor.io

**Comment by xtrilla** [comment]
Hi,

While doing some tests, we have realized the performance is also related to the amount of timeseries enabled in ntopng. If we disable almost all of them, keeping only the Local Hosts traffic timeseries, it can hold with up to 6K - 8K ZMQ messages per second with a single thread.

I'm not sure if this is related to the JSON parser -as more information might be collected during the parsing for the timeseries- or is related to something else.

I just thought you may find this information useful.

EDIT: After some more testing I'm not 100% confident this performance difference is 100% related to the timeseries or because we had influxdb as storage instead of RDD. During the tests we moved to RDD storage and now I have to run more tests to be sure if the performance increase is related to disabling several timeseries or not using InfluxDB (Or both)

Thanks.

**Comment by simonemainardi** [comment]
Timeseries are calculated in another thread which is independent from the thread which performs ZMQ parsing so that should not be related to the collection performance.

However, if you have not enough cores in the system, then the thread which writes timeseries may be contending a core with the thread which does the parsing and that could have a negative impact.

Try to use core pinning (see option `--core-affinity`) and make sure the capture thread can run on a core which is free.

**Comment by simonemainardi** [comment]
look at the mongodb json format as well as the one by lemire

**Comment by cardigliano** [comment]
TLV (a binary format) support has been implemented (both in ntopng as consumer and nProbe/Cento as producers). This is the default export format in nProbe now. ntopng supports both legacy JSON and TLV.
