### ISSUE TITLE
SMBv1/Telnet Alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2567]
Implement an alert for SMBv1/telnet (and other very insecure protocols) flows that are used by many malware applications.
In general the nDPI insecure characterization should be enough

**Comment by emanuele-f** [comment]
Alerts implemented in https://github.com/ntop/ntopng/commit/81a9963e465fa7aee7c4cb87e07b51732ce1c3dd . The NDPI_PROTOCOL_POTENTIALLY_DANGEROUS protocol breed is checked in order to generate such alerts.

![2019-08-07_14-28](https://user-images.githubusercontent.com/5488003/62622960-2a7d1800-b90f-11e9-9f46-51225b2b1302.png)

Regarding telnet, I think it's current classification as NDPI_PROTOCOL_UNSAFE is more correct than NDPI_PROTOCOL_POTENTIALLY_DANGEROUS

**Comment by emanuele-f** [comment]
With cc66bf86e716573c44f4ae8e1226e46e94bd969c now ntopng uses the NDPI_PROTOCOL_DANGEROUS classification, which is currently set only for smbv1 . Other protocols will be added in the future
