### ISSUE TITLE
Discrepancies between 1d & 1h timeseries charts

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#2608]
Ubuntu eoan 19.10
ndpi: 2.9.0-1539-53119e7
ntopng: 3.9.190523 - Community Edition
mysql-server 5.7.26-0ubuntu1

**Max sent in 1 day graph**:
![ntopng 1d chart](https://user-images.githubusercontent.com/13176858/58278671-d4cbb180-7d9c-11e9-992c-09a4604cbdae.png)

**Max sent in 1 hour graph for the same host on the same interface**:
![ntopng 1h chart](https://user-images.githubusercontent.com/13176858/58278728-f3ca4380-7d9c-11e9-8d44-7ecbcc698984.png)

8.52 Mbits/s vs 32.2 Mbits/s for the exact same peak in time.

**Comment by emanuele-f** [comment]
Hello, this is expected as ntopng performs sampling to reduce the amount of visualized data. In order to see the actual data you should drill down to the maximum resolution, see this example from pro charts:

![Peek 2019-05-24 15-38](https://user-images.githubusercontent.com/5488003/58331742-4f421300-7e29-11e9-9e04-d5c8732a74e3.gif)

**Comment by jean-christophe-manciot** [comment]
On the community edition, the zoom you perform with your mouse does not work: it leads to tn empty graph.
