### ISSUE TITLE
Unless I set the alert thresholds very high, I get thousands of flood messages

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2617]
I am not sure this is working as designed, but unless I set the thresholds very high I am getting thousands of alert messages like these:

![image](https://user-images.githubusercontent.com/48565067/58560084-59ca2700-81f2-11e9-8a85-13a4173face1.png)

At the moment my thresholds are large enough not to get thousands of these messages,, but I was wondering, if the defaults for these alerts are set for a typical enterprise network, or for a small office? If they are set for an enterprise network, am I getting an atypical amount of flows?

Thank you ...

**Comment by emanuele-f** [comment]
The exact thresholds are specific to your network and hosts. For example, if you have a host which provides a service (e.g. a DNS or HTTP server) then it can have an high number of flows. So you have to know your network in order to set proper thresholds. We want to extend the alerts to be more dynamic and maybe find a baseline for a network to detect anomalies but this will take time. Static thresholds is all we have right now.
