### ISSUE TITLE
ntopng scan (SYN_SENT) public/LAN IP

### ISSUE THREAD

**Issue by tuantmb** [ntop/ntopng#2650]
I see many *SYN_SENT* from ntopng (one by one) also public & internal IP of my Office this triggers my IDS so much (SCAN alert). So this is a feature of ntong or my misconfiguration

The destination of SYN_SENT request also are public & my LAN IPs:
```
watch -n 1 "netstat -ntp | grep -v 127.0.0.1 | grep ntopng"
tcp        0      1 x.x.x.x:6874     210.145.38.38:80        SYN_SENT    22936/./ntopng
```

*My ntopng information as below:*
```
v.3.9.190601	[Community build]
GIT rev:	dev:5d634c493df3820c137c3741e1429427fb4f373b:20190601
```

*My ntopng commandline:*
```
./ntopng -e -i enp6s0 -i enp2s0 -s -r 127.0.0.1:6379@1 -d /data/ntopng/ -w :3000 -l 1 -F es;flows ntopng-%Y.%m.%d http://localhost:9200/_bulk
```

**Comment by emanuele-f** [comment]
I cannot reproduce this. In order to drill down the problem, please ensure that:

- Automatic Network Discovery is disable from the preferences
- Disable all the category lists https://www.ntop.org/guides/ntopng/advanced_features/category_lists.html
- Do a `grep -r 210.145.38.38` into the ntopng source directory if running from git

**Comment by tuantmb** [comment]
Thanks @emanuele-f ! Maybe "Network Discovery" is the reason, I just disable it and haven't seen any alert in an hour.
```
Toggle the periodic discovery of network devices using multiple techniques that include ARP scan, MDNS and SSDP.
```
