### ISSUE TITLE
[nIndex] Invalid bandwidth calculation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2668]
![image](https://user-images.githubusercontent.com/4493366/59901809-b76e1f80-93fc-11e9-82aa-6c4c0213c3db.png)
it's impossible that a 60 bytes packet can map to 74 Kbit/sec

**Comment by emanuele-f** [comment]
Timeseries bandwidth is properly calculated as shown in the iperf 1Mbit/s test below.

![2019-06-26_13-48](https://user-images.githubusercontent.com/5488003/60181604-16bf9b80-9812-11e9-964e-157174c387e9.png)

Queries like `from t1 to t2` only return flows having first_seen > t1 and last_seen < t2, so some flows are not shown, however this is not the case for the issue above (verified on the original data). Since flow data is often lost during a forced shutdown, this is hard to debug and reproduce. I would postpone this issue after solving the outlined issues.

**Comment by cardigliano** [comment]
I ran a few tests and I was only able to reproduce a bad calculation in case of flows with high throughput (a new issue has been opened at https://github.com/ntop/ntopng/issues/2979), as @emanuele-f said it is likely this was due to a shutdown and some data was missing.
