### ISSUE TITLE
Improve InfluxDB stats

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2682]
![Screen Shot 2019-06-28 at 08 56 35](https://user-images.githubusercontent.com/4493366/60323561-b4d27380-9982-11e9-88a4-f83df3b12527.png)

the above page contains several items that need to be improved
1. Add small help/description that describe what are the items about. For instance RAM is the memory used by Influx (I mean a separate process) or used by ntopng for talking/caching with Influx?
2 Export means an attempt of ntopng to send a metric to Influx or it means that the metric has been accepted and stored by Influx?
3. What does dropped point means? Are they lost forever?
4. Since when the exports, drops... are accounted? Since ntopng startup?
5. Please add a HTML anchor so that if you click on drops you are diverted to the second page to the corresponding timeseries
6. in the graph page what is the RTT about? Between who?
7. Why in the graph the 5m button disappears when selecting RTT?
8. Why in the 5min view there are only 3 metrics and when changing to 1h there more metrics?
9. Beside all the items you reported in the page, can you please put one (q.ty 1) single field that if is green says we're good with influx, yellow degraded, red we're in trouble? 
10. All these low-level details discussed in 9. are useless unless you can summarise in one word the status of the system that must be reported at the bottom of the page with a coloured icon (currently you have this only when Influx is in trouble). For instance if Influx is using too much memory compared to the available one, this is a problem. Reporting RAM just to fill up the screen, won't help. And in the RAM chart you need to put a line with the available system memory and used memory to let people understand what were talking about.

**Comment by simonemainardi** [comment]
> 1. Add small help/description that describe what are the items about. For instance RAM is the memory used by Influx (I mean a separate process) or used by ntopng for talking/caching with Influx?

Done

> 2 Export means an attempt of ntopng to send a metric to Influx or it means that the metric has been accepted and stored by Influx?

Means ntopng has successfully exported the metric to InfluxDB and has received a 200 OK from it. Documented.

3. What does dropped point means? Are they lost forever?

Lost forever. Documented.

4. Since when the exports, drops... are accounted? Since ntopng startup?

Since startup. Documented.

5. Please add a HTML anchor so that if you click on drops you are diverted to the second page to the corresponding timeseries

Done.

![image](https://user-images.githubusercontent.com/3397663/60671225-f11a3e00-9e72-11e9-91de-0fbede126f4c.png)

7. Why in the graph the 5m button disappears when selecting RTT?

Fixed.

8. Why in the 5min view there are only 3 metrics and when changing to 1h there more metrics?

Fixed.

9. Beside all the items you reported in the page, can you please put one (q.ty 1) single field that if is green says we're good with influx, yellow degraded, red we're in trouble? 

Done.

10. All these low-level details discussed in 9. are useless unless you can summarise in one word the status of the system that must be reported at the bottom of the page with a coloured icon (currently you have this only when Influx is in trouble). For instance if Influx is using too much memory compared to the available one, this is a problem. Reporting RAM just to fill up the screen, won't help. And in the RAM chart you need to put a line with the available system memory and used memory to let people understand what were talking about.

Done.

![image](https://user-images.githubusercontent.com/3397663/60671391-49e9d680-9e73-11e9-8948-c00cab3e6457.png)


Documentation available at: https://www.ntop.org/guides/ntopng/basic_concepts/timeseries.html#influxdb-driver
Also added an anchor to the InfluxDB page.
