### ISSUE TITLE
flows not show up 

### ISSUE THREAD

**Issue by radyphan** [ntop/ntopng#2783]
Dear All,

I have an issue regarding flows data not show up, but traffic dashboard or hosts are fine.

 I have configure on both server and cisco router as bellow:

```
ip flow-export source GigabitEthernet0/1
ip flow-export version 9
ip flow-export source 10.0.0.10
ip flow-export destination 10.0.0.2 2055
```

Configure on ntopng.config only enable ip bellow:
```
-i=tcp://10.0.0.2:5556
```
Configure on nprobe.config:

```
--zmq=tcp://10.0.0.2:5556
#
#       -3|--collector-port
#       Specifies the port that is being used by a NetFlow exporter to send NetFlow to nProbe.
#       Multiple NetFlow exporters can symultaneously send data to nProbe using the same port.
#       In case no NetFlow exporter is sending data it is safe to skip this option.
#
-3=2055
#export netflow version 9
#-V=9
```

Unfortunatly, I have follow all instruction from ntop document, but I still can't get flows data.

If anyone face with this issue please kindly help I'm really appricated.

Thank you,
Rady
![8-23-2019 4-45-07 PM](https://user-images.githubusercontent.com/47866186/63629199-94f7ae80-c5c5-11e9-8943-4354052bf2fc.png)

**Comment by emanuele-f** [comment]
The flows are probably expiring due to timeout. Please ensure that the cisco flow export timeout is not too long and that the clock of the cisco router and the clock of the ntopng host are in sync. You can add the `--disable-cache` and `--zmq-disable-buffering` option to nprobe to ensure that nprobe is not responsible for the delay. You can also extend the "Flow Idle Timeout" from the ntopng preferences

**Comment by radyphan** [comment]
Hi,

The issue was fixed after follow your instruction.

Thank you,
Rady

**Comment by emanuele-f** [comment]
You are welcome
