### ISSUE TITLE
Internet trafic only

### ISSUE THREAD

**Issue by Ajowan84** [ntop/ntopng#2797]
Hi,
I installed ntopng on my pfsense firewall.
Is it possible to monitor only Internet traffic and not display network traffic?
Thank you,

**Comment by emanuele-f** [comment]
You can filter the active flows to only show "local client remote server" for flows directed to the internet:
![2019-09-02_12-07](https://user-images.githubusercontent.com/5488003/64119261-ef90c780-cd88-11e9-8d28-4d69889ddd7a.png)

Otherwise you will need to set a BPF filter by using the ntopng `-B` option with a "src net/dst net" expression, please check out https://biot.com/capstats/bpf.html for BPF syntax.

**Comment by Ajowan84** [comment]
Thank you for your quick reply.
The picture is not displayed ...

**Comment by emanuele-f** [comment]
Re-attached

**Comment by emanuele-f** [comment]
Closing this, if you have other questions please open a new issue.
