### ISSUE TITLE
ntopng saying there is ghost networks when it's a registered domain

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2800]
Ntopng saying there is "ghost domains" when these domains are clearly listed in the networks tab of eth0

![image](https://user-images.githubusercontent.com/48565067/64177172-f40ebc00-ce2c-11e9-8a36-a5614e73f551.png)

![image](https://user-images.githubusercontent.com/48565067/64177046-adb95d00-ce2c-11e9-8449-33149378fd02.png)

![image](https://user-images.githubusercontent.com/48565067/64177098-c295f080-ce2c-11e9-85d3-f7d7eb088fca.png)

**Comment by simonemainardi** [comment]
as you have highlighted a broadcast domain `10.10.13.0/24` which is not in the broadcast domain of your network interface which has ip `10.210.8.1`, I'm assuming you are sending mirrored traffic to the interface and you have checked the 

![image](https://user-images.githubusercontent.com/3397663/64248580-ca7b9080-cf11-11e9-83c4-f62b329f43ba.png)


from the interface config page.

Otherwise you would have seen a red ghost icon next to the highlighted broadcast domain.

My commit fixes an issue which was preventing ntopng from skipping ghost broadcast domains when monitoring interfaces with mirrored traffic. This should solve your issue.

**Comment by StewAlexander-com** [comment]
Not quite, the 10.10.13/24 is visible and pingable from the network interface

**Comment by simonemainardi** [comment]
Look at the ip address of your interface, it's 10.210.8.1. How it can be in the same broadcast domain of 10.10.13/24? - Pingable doesn't mean you are on the same broadcast domain.

Is the interface receiving mirrored traffic or not?

**Comment by StewAlexander-com** [comment]
Didn't clearly understand the response, anyway ~~closing this~~, thanks
