### ISSUE TITLE
NetworkInterface::periodicStatsUpdate() requires cleanup

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2954]
The above method is not just updating statistics as the name says. Instead it also purges entries. Said that its name should change as misleading, on flow-based interfaces the call frequency to this method depends on the flow timeout. While this is acceptable for updates, it is wrong for purging and script callbacks as this needs to be done regardless of the update frequency.

A minimal solution is to call idle at a different frequency. The good solution is to avoid walking the whole hash searching for idle hosts, but rather to accumulate the idle hosts on a vector and thus purge them up without walking.

**Comment by simonemainardi** [comment]
implemented.

vector-based purging implemented at: https://github.com/ntop/ntopng/commit/955eed4b50e370a95bcd12a124d12fef66c8f885

periodicStatsUpdate refactored so that purge idle is always performed every 5 seconds whereas the stats update freq depends on the type of interface: https://github.com/ntop/ntopng/commit/00f8c7d681069e05f9d629769396e3bf30b25b41
