### ISSUE TITLE
Severe startup drops due to hosts deserialization

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2965]
When ntopng creates a new host (hence this is a typical activity that happens at startup when the memory cache is empty) it has to speak with redis for restoring serialised data. This causes severe drops at startup and also whenever a nasty activity such as a network scan happens.

This practice needs to be changed in order to both avoid drops and avoid that a nasty user activity will produce negative effects on ntopng monitoring features.

**Comment by simonemainardi** [comment]
options are:
- perform at most X deserializations per second and allow hosts deserialization to be deferred. Deserialization functions then should be changed to sum values rather than setting them. Unless an host has not been deserialized, it should be hidden from the UI and from the timeseries
- start another thread which is in charge of deserializing hosts. Pass to this thread the keys of the hosts that needs deserialization and let this host do the work. Then, inline, when the deserialization is ready the deserialized values should be added to the actual values. This has the drawback of requiring a lof of code to be written for the sum
- move JSON to TLV for serialized hosts. This only resolves when the JSON is the bottleneck. In case of slow disks, this won't be of any help.

**Comment by lucaderi** [comment]
We have decided that host serialization is not compatible with performance and is misleading, so this feature has been pulled off ntopng
