### ISSUE TITLE
Integrate ntopng with pfsense

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#297]
pfsense.org is a popular FreeBSD-based firewall. ntopng can be integrated with pfsense to acts as a passive flow classifier so that the firewall can know the application protocol and thus implement security policies based on it.

**Comment by lucaderi** [comment]
Work in progress, almost ready. See https://github.com/ntop/ntopng/blob/dev/doc/README.pfsense for more info

**Comment by MrBrax** [comment]
Less ready?

**Comment by TheLinuxGuy** [comment]
I wonder if anyone has tried to release a newer FreeBSD package? that would automatically fix pfsense. It currently works but its just a very old version (ntopng v.1.2.1 (r8205) )

https://www.freshports.org/net/ntopng/

**Comment by lucaderi** [comment]
Hi guys I can complete the pfSense implementation is there is somebody willing to help both with packaging and some pfSense basics. Volunteers please contact me.

**Comment by overcookedTOFU** [comment]
I don't know how much I can help with packaging, but I do know some pfSense basics.  What can I do to help?

Also, is there any hope for an updated FreeBSD package? That may be the quickest route!

**Comment by UbuntuRunner** [comment]
Hi, lucaderi, just wanted to encourage you to go on with your work (though I am afraid I am not able to help you), cause we use ntopng almost daily on our pfsense-boxes.

Thanks for your work !

**Comment by overcookedTOFU** [comment]
@lucaderi, just wanted you make sure you are aware that in pfsense 2.3 (currently in beta), there are a number of significant changes to the way packages work.  The short version is that pfsense packages will be more closely aligned with freeBSD packages.  Seems like this a perfect time to look at getting ntopng and pfsense working together.  Again, please let me know what I can do to help.

Thanks!

Documentation: https://doc.pfsense.org/index.php/Developing_Packages

**Comment by grandrivers** [comment]
also this might help 
https://forum.pfsense.org/index.php?topic=103481.0

**Comment by jdillard** [comment]
Getting ntopng back into FreeBSD ports is the best route. It was removed because it didn’t work with current ndpi version that ports has.

**Comment by rbgarga** [comment]
Yeah, the first step is to get ntopng available on FreeBSD ports again. It was deleted from ports tree in last Feb:

https://github.com/freebsd/freebsd-ports/commit/90ba00fe27138b51500de75fe5b123f38e3cf82d

The reason it was removed is anyone worked on the port to update it to a recent version, the version that was available at that time was too old and didn't run with current ndpi version.

**Comment by rbgarga** [comment]
I would be glad to help to get it committed to the FreeBSD ports tree, if anyone has a patch please contact me

**Comment by lucaderi** [comment]
I have compiled ntopng under the latest FreeBSD several times. It works. I am unsure about older versions, so in essence I think we've done our homework.

**Comment by rbgarga** [comment]
OK, I'll attempt to ressurrect the port as soon as I have some spare time and will let you know the results

**Comment by madpilot78** [comment]
Hi,

I'm a FreeBSD committer and I was also going to look at the port, on Luca's request.

I can help you and, if you get something working, I can test it and commit it to the official tree once ready.

Please keep me informed!

P.S. I just noticed you are also a committer. Anyway I can help!

**Comment by madpilot78** [comment]
I have created a fixed port based on the old deprecated one. It build and packages fine here, but I have not run tested it.

A few notes:
It's getting the 2.2 tarball from sourceforge

I've configured it to use the bundled nDPI library, since the one in ports/net/ndpi is an older version which has different defines for at least one of it's structures. We should choose if we want to keep the net/ndpi port and update it and use that or just go for the bundled one.

I have not touched the included startup script, it should be tested by someone actually using it. I did not touch the included ntopng-geoipupdate.sh script either.

You can find the port here:

http://www.madpilot.net/~mad/ntopng_port.txz

just extract it while in /usr/ports/net and you should get the new port in there ready for testing.

**Comment by gonzopancho** [comment]
getting that to garga@ will result in a lot more chance of it going directly into pfsense.

**Comment by numeronove** [comment]
I have built ntopng 2.2 on OpenBSD 5.9, where thanks to the `divert-packet` action, one could feed ntopng to do some serious traffic shaping, by leveraging nDPI capabilities.

Now here is what I'm missing: _how does ntopng mark packets_ in order for pf ( packet filter ) to do its traffic shaper job?

I guess that ntopng implements some queueing mechanism, and feeds back packets to the firewall at set speed... Am I right?

**Comment by lucaderi** [comment]
@numeronove You need to use the 2.3 code for latest changes. What we do is mark traffic with the nDPI protocol ID but this is not probably what people need/want. In essence we need your feedback on this so that we can complete the development (unless somebody wants to contribute)

**Comment by numeronove** [comment]
@lucaderi I gave a look to **DivertInterface.cpp**, to find how ntopng sends back packets: it calls `sendto()` in the same way as the OpenBSD [divert(4)](http://man.openbsd.org/OpenBSD-current/man4/divert.4) man page sample program does.

Just a few lines before it calls `dissectPacket()`, where the last argument is a pointer to nDPI protocol number, defined in **ndpi_protocol_ids.h**. That protocol number plus `0x1000`, is used to replace the value in `sin.sin_port` field.

From here, the packet is back in the firewall, where it could be assigned to one of the queues, with a match rule based on the sin_port value. I'm not sure that it can be done this way, because divert(4) man page also reads "Writing to a divert socket [...] will skip [pf(4)](http://man.openbsd.org/OpenBSD-current/man4/pf.4) filters to avoid loops" ( be diverted again ).

I hope I'm wrong.

**Comment by lucaderi** [comment]
I am not familiar with OpenBSD. I have tested it on FreeBSD and it works as expected. The point is that you cannot set a queue per nDPI protocolID but the configuration must be simpler IMHO, and this is where I need input.

**Comment by numeronove** [comment]
The two of them, FreeBSD ipfw and OpenBSD pf, are quite different.
In pfSense the main firewall is [pf(4)](https://www.freebsd.org/cgi/man.cgi?query=pf&sektion=4&apropos=0&manpath=FreeBSD+10.3-RELEASE), while [ipfw(4)](https://www.freebsd.org/cgi/man.cgi?query=ipfw&apropos=0&sektion=0&manpath=FreeBSD+10.3-RELEASE&arch=default&format=html) is used with [dummynet(4)](https://www.freebsd.org/cgi/man.cgi?query=dummynet&sektion=4&apropos=0&manpath=FreeBSD+10.3-RELEASE) to shape traffic, in OpenBSD the traffic shaper is embedded in pf(4), since a post-ALTQ refactoring in version 5.5.
With the new shaper, one could define easily a queue per nDPI protocolID, and shape traffic with `match` rules, but they haven't a chance to match packets back from a `divert-packet` journey.
Unfortunately there isn't something like the [ipfw(8)](https://www.freebsd.org/cgi/man.cgi?query=ipfw&sektion=8&apropos=0&manpath=FreeBSD+10.3-RELEASE) utility in OpenBSD, with that behavior.

**Comment by Andrew17856** [comment]
Thanks for your work on this.  It looks from this issue that the intention is to integrate ntopng with pfsense so that ntopng's packet inspection can be used in firewall rules. 

That's useful but I can see there's a fair amount of work in it,  hence it being fed into the ntopng 2.3 release. 

At  the moment, the ntopng package is completely missing from pfSense due to the earlier dependency issue.  From what I can tell, that issue has been fixed already. 

Would it be possible please to compile an earlier stable release of ntopng so at least the package is available again in pfSense?  As and when ntopng 2.3 is available (which I imagine might be a while longer) it can be pushed out as an update to the package. 

Thanks

**Comment by soutieslak** [comment]
I read this: "ntopng package was removed from FreeBSD ports because it no longer compiled. That issue has recently been fixed, and the package will return soon."
Source: https://doc.pfsense.org/index.php/2.3_Removed_Packages

Then I found this thread! Thank you so much for your work! Really can't wait for it to come back to pfsense... Is there any news on its ETA?

**Comment by lucaderi** [comment]
@soutieslak We need assistance on how to integrate ntopng with the pfSense configuration. In essence ntopng will work but for the integration we need support from the pfSense community

**Comment by Andrew17856** [comment]
@lucaderi   I'm happy to help in any way I can.  What assistance do you
need?

How far off true integration are we (i.e. ntopng marking packets that
pfSense can subsequently filter according to its own rules)?

If it's a long way (I can see some complications in marking the packets
in a way that pfSense can subsequently filter) then, as mentioned above,
one option is to leave that feature as part of the ntopng 2.3 release
but in the interim reinstate the last stable release of the ntopng
package (2.2 presumably) back into pfSense.  At the moment, the package
is completely missing because of the dependency issue but it looks like
you've already fixed that (per your comment of 18 March).

Would that work please?  Thanks for all your help and dedication to ntopng.

------ Original Message ------

**Comment by soutieslak** [comment]
@lucaderi what integration is still required in order to make it official? Have you asked for help on twitter yet? pfsense seems quite active there? Agreed with @Andrew17856, thanks for your help and dedication.

**Comment by lucaderi** [comment]
I see that there are people taking care of the package such as @madpilot78. I need feedback on the integration side. My idea is to use ntopng for both monitoring and traffic detection, so that you can use it as a drop-in replacement for ipfw-classifyd. This tool (ipfw-classifyd) has a configuration file which specifies how to mark traffic based on the protocol. I need to understand how the pfsense community would like to do this integration. Do I need to behave exactly as ipwf-classifyd (for traffic marking) or there is something else to do. Do you want to use this config file or can we use something better. These are the questions. I have not asked on twitter as I do not think is the right place. If somebody could update/help/code github is the place.

**Comment by soutieslak** [comment]
@lucaderi I hear you man. I just think that of the 7000 twitter followers, there must be members who could assist, and they might not be aware of this github page. So if we post it there, they might get exposed to this page, and that could increase the productivity.

Unfortunately I have not worked with the development of these tools before, so for me to try assist will slow down productivity.

Sounds like @Andrew17856 can help you :-)

**Comment by Andrew17856** [comment]
I think the best way forward is to open an issue/feature request on the pfSense bugtracker, so the pfsense development team can work with Luca on the best way to integrate ntopng with pfsense.  I'll do that and post a link back here.

They'll know what packet marking approach will be best to use for ntopng to identify traffic.  For example, I think ipfw-classifyd uses Layer 7, which was removed in pfSense 2.3.

My feeling is that full integration is still a while away, particularly as the pfSense dev team are very busy following the recent rollout of pfSense 2.3.  It would be great if, in the meantime, ntopng could be reinstated as a package on pfSense 2.3, even if it's without the full integration envisaged here.

**Comment by Andrew17856** [comment]
Here's the link to the pfSense bugtracker - hopefully a dev from the pfSense team will get in touch!

https://redmine.pfsense.org/issues/6204

**Comment by gonzopancho** [comment]
@Andrew17856 we already know.

**Comment by Andrew17856** [comment]
Ok, thank you.

**Comment by soutieslak** [comment]
@Andrew17856 I also think that just bringing it back as a package that one can install is a good first step. Then the integration after that.

**Comment by madpilot78** [comment]
I have made a new version of the port, anyone interested in testing it can download the files from here:

http://www.madpilot.net/~mad/ntopng_port.txz

The port installs today's snapshot from github, from branch 2.2. It also includes this patch I sent a pull request for:

https://github.com/ntop/ntopng/pull/533

If anyone tests this please report back.

Thanks!

**Comment by lucaderi** [comment]
Pull requests have been merged in the dev branch.

**Comment by madpilot78** [comment]
Thanks!

**Comment by arrmo** [comment]
Hi,

FYI, downloaded and tried to install the txz file above => got the following error message,

pkg: ntopng_port.txz is not a valid package: no manifest found
Failed to install the following 1 package(s): ntopng_port.txz

Did the install work for others?

**Comment by madpilot78** [comment]
I should have explained better, that file isn't a binary package, it's an archive of the port directory. You should extract it in /usr/ports/net, it will create an ntopng directory you can switch to and run "make install" into.

I'm interested in testing of the port.

Anyway, if you want to, and you're ok with running binaries from me I can create a binary package for you, I just need to know which FreeBSD version you're running and the architecture (output from "uname -a" will do).

**Comment by Andrew17856** [comment]
@madpilot78.   Thanks for this.  Can I check: is this a bare port of ntopng or a specific build for pfSense?  The ntopng version running on pfSense 2.2.x had a user interface within pfSense (in addition to the user interface of ntopng itself).

**Comment by arrmo** [comment]
Hi,

I kinda wondered if that was what it was. I can try to build it, but I'm on pfSense ... not sure there are many / any build tools. I know my way around Linux quite well, not so much with BSD ... :(.

It's 10.3-RELEASE, does that help?

Thanks!

**Comment by madpilot78** [comment]
This is a plain FreeBSD port.

The ntopng port was removed a little while ago and I wanted to bring it back. I have no experience building packages for pfsense. But in the past having a FreeBSD port was a requirement for pfsense packages, I don't know if that's still the case.

**Comment by Andrew17856** [comment]
Yes it is.  There needs to be a working port before it can be released as a pfSense package.  Thanks.

**Comment by soutieslak** [comment]
I have been following this thread, and am very excited. The progress you guys are making is unreal! Keep it up! 

I can help test if it is released as a pfSense package.

**Comment by Andrew17856** [comment]
@arrmo @madpilot78 There aren't any build tools on pfSense - see here:  https://doc.pfsense.org/index.php/Can_I_compile_software_on_pfSense

So I can't build the port in the pfSense environment.

I don't mind installing a binary on my test pfSense box, if that would help testing.

@lucaderi @gonzopancho Do you know if the ntopng UI has been converted to bootstrap within pfSense yet please?

Thanks.

**Comment by lucaderi** [comment]
@Andrew17856 The problem is not to test it on pfSense but to integrate it with pfSense so that shaping, dropping etc happens in pfSense rather than in ntopng. So thus is NOT a porting problem but rather an integration problem with pfSense. As this question is floating for more than 6 months now, I am not sure if  there is interest in the pfSense community. As of the other question, ntopng has been integrated with bootstrap since day 1, so I am not sure I understand your question.

**Comment by Andrew17856** [comment]
@lucaderi  I understand you're trying to integrate it.  My point (per my 18/4 post) is that is going to take a while to do simply because it involves joining up two dev teams (as you say, the question has been out there for six months).

If the pfSense ntopng UI has already been converted to bootstrap and you have a bare port of ntopng that works on FreeBSD,  that's all you need to get it back onto pfSense 2.3.

My suggestion is don't bother with integration for now - just get the ntopng package back on pfSense as it was on pfSense 2.2.x. 

Thanks

**Comment by lucaderi** [comment]
@Andrew17856 Ok if this is all you need then I think I am done on my side.

**Comment by Andrew17856** [comment]
@lucaderi  Thanks. Are you going to push ntopng into the FreeBSD ports repository please?  That's the first step in getting the existing package back onto pfSense.

**Comment by madpilot78** [comment]
@Andrew17856 Hi, I'm working on the FreeBSD port.

I'm almost done with that, I'm waiting for feedback from a pair of persons who are helping me test it.

I'm going to commit it as soon as I'm sure it works fine.

If you want to test the FreeBSD port you can grab what I have done here:

http://www.madpilot.net/~mad/ntopng_port.txz

Please note that this also needs adding a user in /usr/ports/UIDs and /usr/ports/GIDs to work:

```
> grep ntop UIDs GIDs 
UIDs:ntopng:*:288:288::0:0:ntopng daemon user:/nonexistent:/usr/sbin/nologin
GIDs:ntopng:*:288:
```

**Comment by Andrew17856** [comment]
@madpilot78 Thank you - very much appreciated.  I only have a pfSense test VM at the moment (which lacks build tools) but I'll set up a FreeBSD VM when I have a moment and give any feedback. It sounds like you're almost there anyway.

**Comment by madpilot78** [comment]
For people wanting to test I have modified the URL to reflect that now tha port is also updating the nDPI port. Here is the new URL:

http://www.madpilot.net/~mad/ndpi-ntop.txz

Please remove the net/ndpi port before extracting this archive in net.

You also still need to modify UIDs and GIDs:

```
> grep ntop UIDs GIDs 
UIDs:ntopng:*:288:288::0:0:ntopng daemon user:/nonexistent:/usr/sbin/nologin
GIDs:ntopng:*:288:
```

**Comment by madpilot78** [comment]
I have just committed the restoration of the  ntopng port to the FreeBSD ports tree:

http://www.freshports.org/net/ntopng/

**Comment by Andrew17856** [comment]
Great,  thank you very much for fixing and restoring the port.  Much appreciated.

**Comment by Pimmetje** [comment]
@madpilot78 Thx for fixing. Is anyone planning to get the package back in pfSense? In the mean time whats the best way to test it?

**Comment by Andrew17856** [comment]
Now it's in the FreeBSD ports tree it should find it's way back into the pfSense ports repository then back into pfSense. There's a thread on it here : https://forum.pfsense.org/index.php?topic=109839

**Comment by Andrew17856** [comment]
p.s. re your comment on testing, see here:  https://doc.pfsense.org/index.php/Installing_FreeBSD_Packages under pfSense 2.3

It's possible to install native FreeBSD ports into pfSense, but it may break things.  Probably safest to wait for the devs to push it out as an official pfSense package.

**Comment by rbgarga** [comment]
Thank you @madpilot78. Since pfSense uses quarterly branch of the ports tree, I'll cherry-pick the commit to the tree to make it available on pfSense repo

**Comment by rbgarga** [comment]
Done

**Comment by MrBrax** [comment]
Just curious, will this new version/port support HTTPS on pfSense?
I know the regular version does so

**Comment by lucaderi** [comment]
Do you mean HTTPS detection or access the interface via HTTPS? Both are supported

**Comment by MrBrax** [comment]
@lucaderi sorry, interface access. The 2.2 (old) version of pfSense has some old build and (probably because of the implementation) only has HTTP.

**Comment by Pimmetje** [comment]
We there be remote storage support? I haven't been able to find it, And most pfSense boxes won't have big disks.

**Comment by madpilot78** [comment]
The ndpi version in the FreeBSD port is 1.8.

The ntopng port at present installs a recent snapshot of ntop, commit a92a08d7be7fcb8ad707544ae11d008ca552816e, from May 28th.

So it's not the old 2.2 from the port before it was removed from the tree.

**Comment by JSTYL** [comment]
Is there an ETA as to when this should be available in pfSense now that it's ported?

**Comment by soutieslak** [comment]
Great work guys, can't wait to use it again.

I would also like to know if there is an ETA for when this will appear under the packages available in pfSense?

**Comment by Pimmetje** [comment]
@soutieslak Thats something i think u should ask the people of pfSense. But as far as i could get nobody is willing to give a estimate. So unless u have a pfSense gold subscription the only thing we can do is hope and wait.

**Comment by rbgarga** [comment]
@soutieslak please keep track of pfSense changes at https://redmine.pfsense.org/issues/6443

**Comment by JSTYL** [comment]
Not sure how many others are testing the ntopng package now that it's available in pfSense 2.3 when using the development update branch. (aka - Not for production)

My recent testing rig came to stumbling halt after the HDD filed up with 12gb's of data from ntopng alongside my squid cache.  I had the "keep historical data" checkbox disabled in the ntopng settings however that did not seem to work.  I'm not sure if this would be done from your end or from the pfSense devs, feel free to direct me if needed.

Could there a way to configure a set amount of usable storage space so that it simply overwrites the oldest data (similar to squid) as needed?

On Jun 7, 2016, at 4:19 PM, Renato Botelho <notifications@github.com<mailto:notifications@github.com>> wrote:

@soutieslakhttps://github.com/soutieslak please keep track of pfSense changes at https://redmine.pfsense.org/issues/6443

##

**Comment by Andrew17856** [comment]
I think the configuration options in ntopng have moved on quite a bit since the older version on which the pfSense UI was modelled.  There are various options in the ntopng UI itself (see the preferences) which relate to the storage of RRD data.  You can switch those to off,  or set retention periods. 

The most important thing in the pfSense UI is to be able to set the password etc for the ntopng UI.  Rather than try to keep the pfSense UI in line with the ntopng one as it changes,  one option might be just to pare it back and let people configure ntopng directly in its own interface.

**Comment by JSTYL** [comment]
Well, I had already changed the password through the ntopng UI, however I never saw any options for retention settings or a preferences button.

On a side note, another small issue I noticed was that if using a hostname alias in the pfSense > Advanced Settings it fails to connect to ntopng over http using the alias hostname, it keeps trying to redirect to https://hostname:3000

An https login would be great though!

On Jul 18, 2016, at 12:42 PM, Andrew17856 <notifications@github.com<mailto:notifications@github.com>> wrote:

I think the configuration options in ntopng have moved on quite a bit since the older version on which the pfSense UI was modelled. There are various options in the ntopng UI itself (see the preferences) which relate to the storage of RRD data. You can switch those to off, or set retention periods.

The most important thing in the pfSense UI is to be able to set the password etc for the ntopng UI. Rather than try to keep the pfSense UI in line with the ntopng one as it changes, one option might be just to pare it back and let people configure ntopng directly in its own interface.

##

**Comment by Andrew17856** [comment]
It's under Gear icon > Preferences > Traffic Metric Storage 

There's also Top Talkers Storage and Stats RRDs

**Comment by JSTYL** [comment]
Yeah, I assumed that's where it would likely be.  The only options I have in the pfSense package when clicking the gear icon in the ntopng UI is "Change Password" & "Export Data".

pfSense Base: 2.3.2.a20160718.0928
Ntopng version: 2.3.160705

Tried a full uninstall and reinstall, still no change.

On Jul 18, 2016, at 1:22 PM, Andrew17856 <notifications@github.com<mailto:notifications@github.com>> wrote:

It's under Gear icon > Preferences > Traffic Metric Storage

There's also Top Talkers Storage and Stats RRDs

##

**Comment by Andrew17856** [comment]
That's the same ntopng version I'm running. 

Are you logged into ntopng as admin? 

I have Manage Users, Preferences and Export Data under the gear icon.

**Comment by JSTYL** [comment]
Yes, I was logged in as the ntopng admin.

 I actually have to setup a couple new servers that arrived today (1 using the dev branch) so I'll see if that install shows up correctly.  If so, I'll try a fresh rebuild in a day or two and that clears up the missing UI options.

On Jul 18, 2016, at 2:44 PM, Andrew17856 <notifications@github.com<mailto:notifications@github.com>> wrote:

That's the same ntopng version I'm running.

Are you logged into ntopng as admin?

I have Manage Users, Preferences and Export Data under the gear icon.

##

**Comment by Andrew17856** [comment]
@JStyleT Not sure if you solved the missing preference menu issue, but I have also experienced it.  The fix is here:  https://forum.pfsense.org/index.php?topic=121067.0

@lucaderi Is there any news please on the integration of ntopng with pfSense please (i.e. to allow pfSense to use the nDPI protocol classifications in firewall rules)?

Thanks.

**Comment by N4Z1T** [comment]
any chance to apply this update in pfsense?

https://github.com/ntop/ntopng/commit/ca83eb48a77c17b82fa2b22e26f74be021922507

**Comment by kuljule** [comment]
I have pfsense 2.3.2 and ntopng 0.8.5. I figured out how to export the bandwidth information to mysql and then I created a php script that emails me the user's name, mac address, and date/time when they reach 1GB and stay above that for 15 minutes. Check it out! 
[https://github.com/kuljule/ntopngbandwidthnotifier](url)
-Julian

**Comment by luckman212** [comment]
@jdillard Are you the pkg maintainer for ntopng on pfSense? I am trying to find out who that maintainer is. Having lots of core dumps with v2.4.2016.10.14 on 2.4 snapshots and wanted to see if someone could merge the new [2.4.2017.01.20_1](https://www.freshports.org/net/ntopng/) version that has landed in Freshports?

**Comment by ScottBrenner** [comment]
Any plans to update the pfSense plugin version? 2.4 is latest on pfSense while 3.0 is publicly available.

**Comment by madpilot78** [comment]
The FreeBSD port already has 3.0. I don't know exactly how dependencies are pulled in by pfsense packages, but you should push for the pfsense guys to pull in the new version.

Their packages are based on FreeBSD ports.

**Comment by Andrew17856** [comment]
It's available already on the nightly build release channel.

**Comment by ScottBrenner** [comment]
Odd, the latest version of the ntopng plugin my pfSense is seeing is 0.8.10, which includes ntopng-2.4.2017.01.20_1. Thanks for the quick reply!

**Comment by madpilot78** [comment]
the pfsense specific port is just a skeleton which contains the php and xml files required to integrate in the pfsense gui and configuration. It depends on the actual FreeBSD net/ntopng port.

The pfsense guys keep a few "release branches" of the ports tree, from which actual release packages are built.

In the latest release branch the pfsense package port has been updated to the latest version, while the ntopng port is still behind.

If you install the latest pfsense release you get packages from the release branch. You can install the development version of pfsense and get packages from the devel branch, which include ntopng 3.0.

You can try lobbying with the pfsense guys and see if they can merge the latest update to ntopng in their release branch.

**Comment by tylerszabo** [comment]
I was able to get version 3 installed on PFSense 2.3.4-RELEASE-p1 by doing the following:

`pkg install libunistring-0.9.7`
`pkg add -f http://packages.ntop.org/FreeBSD/x64/ntopng/ntopng-3.1.170604.txz`

The version in the 2.4/devel repo would segfault on me, as would the version from FreeBSD 10 ports.

Hope this helps.

**Comment by glego** [comment]
@tylerszabo , I'm running **2.3.4-RELEASE-p1** with **ntopng 0.8.10**, did you first **uninstall** the existing packages and then manually installed the FreeBSD binaries or did you install the binaries over the existing installation? 

Thanks,
/Glenn

**Comment by tylerszabo** [comment]
@glego I removed all previous versions when I was experimenting with different packages, but none of them worked until I installed version 3. I'm not sure how to go from a working older version to version 3; I'd suspect an uninstall would be enough.

**Comment by EmilioMoreno** [comment]
Hi! I know this is an old post, but can anyone clarify if is it possible to tag a packet using Ntopng in pfsense and then apply firewall rules to it? as DPI in pfsense has been removed, this would be great for traffic shaping or other rules.

**Comment by lucaderi** [comment]
@EmilioMoreno I suggest you to use https://www.ntop.org/products/traffic-analysis/ntopng-edge/

This said, as we have no control over pfSense the best we can do is to support the FreeBSD community but we do cannot go beyond this as like I have said we have no control over pfSense nor how packets are marked. For this reason I now close this ticket, that can be reopened if necessary.

**Comment by madpilot78** [comment]
Just for informative purposes I'm going to update the FreeBSD ports of nDPI and ntopng to the latest branches shortly (after testing).

pfsense tracks FreeBSD "quarterly" ports, next quarterly will be branched at the start of October. Shortly after pfsense will merge those changes and after recompiling and testing will release new package sets for pfsense. This is their policy, we have no control on that.

At that time they will merge whatever version is in the ports tree at the time. I try to keep the FreeBSD port up to date with the latest stable branch.
