### ISSUE TITLE
Invalid not assigned traffic count

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2991]
In nEdge hosts set as "not assigned" accumulate traffic counters. This is wrong as we count ingress traffic instead of egress traffic (nEdge is a bridge/router) and thus the counters should be 0 as this traffic never flows on the network

**Comment by emanuele-f** [comment]
Documentation:

http://www.lt.netfilter.org/projects/libnetfilter_conntrack/doxygen/libnetfilter__conntrack_8h_source.html

**Comment by emanuele-f** [comment]
conntrack does not seem to provide such counters. An idea is the following. Since we know the flows with a drop verdict, we may stop accounting the traffic for such flows (Flow::setPacketsBytes). However this is risky, as some flowing traffic may not get accounted. Another option would be to bring up all the flows in the netfilter queue, however this will greatly decrease performance.

**Comment by emanuele-f** [comment]
Due to the nature of Conntrack, it is not possible to accomplish this request.
