### ISSUE TITLE
High Redis Activity

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3007]
On large networks a `redis-cli monitor` highlights intense activity with reference to alerts. It is necessary to reduce this activity almost to zero. Among the most requested keys there are those containing `disabled_alerts`.

**Comment by emanuele-f** [comment]
The two repeated redis calls are the followings:
1. `"GET" "ntopng.prefs.alerts.ifid_0.disabled_status.host_1.2.3.4@123"` (keeps a bitmap of the flow status which should not trigger an alert for the host)
2. `"HGET" "ntopng.prefs.alerts.ifid_0" "1.2.3.4@123"` (indicates if the given alertable entity can trigger alerts or not)

Here is my suggested solution to the above access.

For [1]:
- keep a per-interface in memory map `<hostkey -> disabled_bitmap>` (e.g. `<1.2.3.4@123 -> 8>`), which is loaded on startup
- an host will cache its own disabled_bitmap entry
- a shadow map is used to avoid concurrency issues after user modification
- when a user modifies an host disabled status, the map should be reloaded and the host disabled_bitmap cache updated
- A function should be exposed to retrieve an host disabled_bitmap from the in-memory hash

For [2]:
- keep a set `<entity_type, entity_value>` with the disabled entities
- a AlertableEntity will cache its own disabled preference
- when a user modifies an entity disabled preference, the set should be reloaded and the AlertableEntity cache updated
- a shadow set is used to avoid concurrency issues

Other than those, there is also an unnecessary lookup performed only then an alert is to be trigger, which is `"GET" "ntopng.prefs.alerts.ifid_0.disabled_alerts.__1__1.2.3.4@123"` on `alerts_api.isEntityAlertDisabled`. This is not involved into the current performance problem, but could be fixed with an in-memory map as the proposed solution for [1].

**Comment by lucaderi** [comment]
Make sure you implement strict upper-limit checks to avoid creating huge maps. I believe that using bloom filters to check if going to redis would be a great solution both in terms of memory, serialisation and amount of code you have to write. In essence a bloom can report you in case of match if you go to redis to check or not. This because of false positives.

**Comment by emanuele-f** [comment]
A suggested alternative is to move all the alert-related preferences to lua and pre-load them before iterating the hosts/interfaces/networks. The migration requires some work as some C logic currently depends on some preferences (e.g. `Flow::triggerAlert`).

**Comment by emanuele-f** [comment]
Hosts `disabled_status` migrated to lua and optimized in 675adcf90e0d60fd22999bc05e94a8b911919481

**Comment by emanuele-f** [comment]
Disabled alerts bitmap optimized in a96a90b65fda36f1d5cc936cb1d48f7b142a519b

**Comment by emanuele-f** [comment]
Disabled alerts boolean migrated to lua and optimized in 54140b6f1aad41d8c718c2ef7852101edc9c3d17

**Comment by emanuele-f** [comment]
After the fixes above, the new top redis calls are the following:

- DNS cache access (e.g. `GET/EXPIRE ntopng.dns.cache.1.2.3.4`)
- Alerts events queue (e.g. `RPUSH ntopng.cache.ifid_0.flow_alerts_events_queue` / `ntopng.cache.ifid_0.alerts_events_queue`)
- Alerts notifications queue (e.g. `RPUSH ntopng.alerts.notifications_queue`)
- C to lua alert notifications, not so frequent but used for remote to remote alerts (e.g. `RPUSH ntopng.push_alerts_queue`)

As a result, there are still about 1000 accesses to redis per second on a large instance

**Comment by emanuele-f** [comment]
Individual issues have been opened for the remaining problems.
