### ISSUE TITLE
GUI Unresponsive when InfluxDB does not respond 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3075]
In case ntopng has been configured to export data in InfluxDB but the database is down, the user interface is unresponsive.

**Comment by emanuele-f** [comment]
The main issue was a query executed on every page load, fixed in 20ef1a4ebcf5654f29cd69e3cfe8808a25d7a83c . Additionally, in the event of slow InfluxDB queries, 478c97b7437d806947e04a347e20b67de8b0d02b introduces a 1 minute inhibition interval where most of the queries performed during page loads are aborted immediately.
