### ISSUE TITLE
Add multiple flow analysis script/feature

### ISSUE THREAD

**Issue by Stesnyaus** [ntop/ntopng#3099]
Hello.
Is there any chance of adding script/feauture of automatic multi-iteration analysis of the same flow?

**Comment by emanuele-f** [comment]
Hi, can you be more specific about the use case and what are you trying to accomplish?

**Comment by Stesnyaus** [comment]
> Hi, can you be more specific about the use case and what are you trying to accomplish?

Hello!
I need this feature for my little study project. I think I can do simple script for this feature by my self, but if this will be a default feature, it could be a lot better in usability and optimization.
My goal which I want to get from this feature is to analyze efficiency of multiple analysis of one flow. Will this feature take us better or faster results after analysis (e.g. when we run ./ndpiReader -i <file.pcap>) or this will be the same results after all.

**Comment by emanuele-f** [comment]
Is this related to ntopng or nDPI? What do you mean with multiple analysis of one flow? Sorry but this is very abstract information to me, I can't get what you need in practice.

**Comment by Stesnyaus** [comment]
Hi!
My issue is related to both ntopng and nDPI. 
I'm talking about feature/script that checks/analyze selected flow few times in a row. Practice algoritm of this feature will be like this:
1) ntopng/nDPI scans flows from network;
2) User selects the desired flow;
3) ntopng/nDPI analyze that flow and show the results (e.g. protocol, IPs, MACs, ports, maybe App signature & etc.);
4) ntopng/nDPI analyze this flow again maybe 3-5 times and show results;
The goal of this operations is to see: is there some improvement (faster or more accurate) of analysis provided by ntopng/nDPI or there is nothing will be changed at all, after several check/scans/analysis of  the same flow in a row.

**Comment by emanuele-f** [comment]
nDPI reads raw packets from network interfaces and then marks a flow with a protocol and possibly extracts some metadata from it. This "analysis" is carried out automatically by nDPI/ntopng and cannot be controlled by an external user. You can however execute custom lua scripts on flows with users scripts (check out https://www.ntop.org/guides/ntopng/api/user_scripts/index.html but please note that this is subject to change as we are reworking it).

**Comment by simonemainardi** [comment]
The solution proposed with user scripts is what you are looking for.

In particular, have a look at flow user scripts: https://www.ntop.org/guides/ntopng/api/user_scripts/flow_hooks.html and the reported example. Basically, you will be able to execute any custom lua script on each flow, at several stages of the lifetime:

- protocolDetected: called after the Layer-7 application protocol has been detected
- statusChanged: called when the internal status of the flow has changed since the previous invocation. The flow status can be used to detect anomalous behaviours.
-  periodicUpdate: called every few minutes on long-lived flows
-  flowEnd: called when the flow is considered finished
