### ISSUE TITLE
Duplicate pool add

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3119]
In host pools it is possible to associate to two different pools the same host, using (in the first pool) the IP address and in the second pool the MAC.  This has to be prevented as it leads to inconsistencies

**Comment by simonemainardi** [comment]
This is by design. Mac associations win over IP associations so that is the case described the host will be associated to the pool matching its mac address in a consistent way.

It is also not possible to prevent this during host pool configuration. Indeed, for example when an host is offline, ntopng won't be able to know its IP or Mac and consequently it won't also be able to perform any kind of check.
