### ISSUE TITLE
Traffic disaggregation matches unexpected traffic with IPv6 filters

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#3133]
It seems that Custom Traffic Disaggregation (when processing traffic from a network interface) is matching unexpected traffic when IPv6 filters are specified.

**Comment by webernetz** [comment]
Hi @cardigliano 

I have tested the disaggregation with `net 192.168.0.0/27 or net 2001:db8:6d:a1::/64` but after stopping and starting ntopng again, it looks like the filters don't work at all. I can see all hosts everywhere. E.g. at the System -> Interfaces Status:
![grafik](https://user-images.githubusercontent.com/13365684/71088328-72098f80-219e-11ea-8a35-26ae86c73c43.png)

And now I can't even delete those disaggregations at all. ;( To be precise: I can delete them, but after restarting ntopng they are present again. Uhm.

**Comment by cardigliano** [comment]
@webernetz I pushed a fix for the IPv6 match issue, a new package will be available in <1h. Please update and let us know.
As of the delete issue, I am not able to reproduce it. Did you shutdown ntopng gracefully?

**Comment by webernetz** [comment]
Hi @cardigliano. Nice, thanks for that.

To be honest, what is a "graceful shutdown"? I am always doing `sudo service ntopng stop` followed by a `sudo service ntopng start`. Is this graceful?

**Comment by cardigliano** [comment]
Yes, it should, unless there is some crash during the shutdown (this should not happen, however you can double check the service log to make sure)

**Comment by webernetz** [comment]
Hey @cardigliano. It looks much better now with version v.3.9.191219. Yeah!

One thing I've noticed though:
<del>I am getting *some* local IPv4 addresses in the disaggregation that are not part of the filter. In my case, I have a disaggregation of "net 193.24.227.192/27 or net 2001:470:7d:a1::/64" but I am seeing at least two other IPv4 addresses:</del> --> Oh sorry, I am wrong, this is because I am talking to these internal hosts as well, sourcing from my disaggregation network. Hence they are shown.
![grafik](https://user-images.githubusercontent.com/13365684/71160876-a3d73080-2248-11ea-8c8e-496a39289218.png)

So everything is OK now. Thanks a lot!!

This is my Interfaces Status now. Great!
![grafik](https://user-images.githubusercontent.com/13365684/71161166-25c75980-2249-11ea-9c65-4ab2dd908054.png)

**Comment by cardigliano** [comment]
Great! Thank you for the update!
