### ISSUE TITLE
I can't start my ntopng

### ISSUE THREAD

**Issue by richardweiu** [ntop/ntopng#321]
I get this error made me starting fail 

/etc/init.d/ntopng: line 64: [: too many arguments
/etc/init.d/ntopng: line 68: [: too many arguments

my config file ntopng.conf is

-G=/var/tmp/ntopng.pid
-e=
-i=1
-w=3000
-m=192.168.1.0/24
-n=1
-S=
-d=/var/tmp/ntopng
-q=

another file ntopng.start is
 
--local-networks "10.3.59.0/19"
--interface 1

**Comment by cardigliano** [comment]
Please try running and report the output:
cat /etc/ntopng/ntopng.conf | grep -E '\-G=|--pid'|cut -d '=' -f 2

ntopng.start is supposed to be just empty

**Comment by richardweiu** [comment]
thank you, I have install install by code

**Comment by RAiN3RWAhN5iNN** [comment]
The issue seems to be that in (ubuntu)
/etc/ntopng/ntopng.conf
a comment like            #               -G | --pid                            exists.
removing this line makes 
cat /etc/ntopng/ntopng.conf | grep -E '-G=|--pid'|cut -d '=' -f 2
(/etc/init.d/ntopng ,  line 59) return only one value and the
issue the issue is gone...
