### ISSUE TITLE
Cannot reach settings in community mode

### ISSUE THREAD

**Issue by Aesculapius** [ntop/ntopng#3213]
Somehow I'm unable to reach certain pages among which the settings page when the professional license has expired. Using the professional license, everything works (for 10 minutes). The following error is displayed:

 Script "/usr/share/ntopng/scripts/lua/admin/prefs.lua" returned an error:
/var/lib/ntopng/plugins/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>'

Using ntopng Community Edition v.3.9.200109 on an up to date ubuntu 18.04 box.

**Comment by emanuele-f** [comment]
If you plan to work in community mode please add the `--community` flag into the ntopng configuration file (/etc/ntopng/ntopng.conf) or command line. That being said, the problem is that after switching back to community mode we should reload the list of active ntopng plugins, we will discuss this internally.

**Comment by Aesculapius** [comment]
Thanks, that solved my issue. Won't close because of your suggestion to improve.

**Comment by unmanagedtn** [comment]
i added the --community switch but still having problems
