### ISSUE TITLE
Make the user scripts IDs dynamic

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3221]
Both the status and the alert ID should be automatically generated as they are only intended for internal use. The status/alert key should be used instead of the ID to reference a particular status/alert in the API.

**Comment by simonemainardi** [comment]
implemented in

https://github.com/ntop/ntopng/commit/48910b9f871bd6d9cfcbe6b21a3a51a630758fe4
https://github.com/ntop/ntopng/commit/212c449e5b29e8b432abc42c1cc3eba220072902

**Comment by simonemainardi** [comment]
ID are now assigned dynamically upon startup in method https://github.com/ntop/ntopng/commit/48910b9f871bd6d9cfcbe6b21a3a51a630758fe4#diff-f5a9e74caeb3eb8bd9c6005c1f1286f3R215.

Currently, IDs are dynamically assigned for used script constants, namely `flow` and `alert` constants: https://github.com/ntop/ntopng/commit/212c449e5b29e8b432abc42c1cc3eba220072902#diff-7b42fba947b77cb9959c6bbc62a71263R10

IDs for `alert`s range from 0 to 255, whereas IDs for `flow`s range from 1 to 63. The ID 0 is reserved for flows with the meaning of `status_normal`.

`flow` IDs are limited to 64 due to an internal bitmap, so we've decided to recycle previous IDs that are no longer used. This may break historical past data (serialized statuses and alert statuses) so an alert is printed on the screen.

Once the ID are assigned, a getter `function plugins_consts_utils.get_assigned_id` https://github.com/ntop/ntopng/commit/212c449e5b29e8b432abc42c1cc3eba220072902#diff-7b42fba947b77cb9959c6bbc62a71263R184 can be used to retrieve their IDs at runtime. The same getter is used when loading alerts and flows definitions for add assigned it to their respective modules.
