### ISSUE TITLE
ntopng cron job file is defaulted to checking for updates every minute

### ISSUE THREAD

**Issue by noybman** [ntop/ntopng#3397]
Just a few weeks ago, I performed an update to ntopng on my Ubuntu box along with the other available packages. (from ntop.org PPA).

The upgrade writes a new ntop cron job to /etc/cron.d/ with an update request for all the different modes including every minute!

I commented out this entry, and then when I updated again last night, it uncommented it again.

I have notifications setup to generate an email, its rather silly to see update requests stepping on each other since the process is slow - probably because the server is getting hammered.

**Comment by cardigliano** [comment]
@noybman please note that the script called by the cron job is not actually checking for updates online unless the user requests that through the GUI. It does that just overnight, once per day. It also checks if there is another instance of the script running before checking for updates online (in case it has to). At least, this is the expected behaviour. Do you see something else? Thank you for reporting.

**Comment by noybman** [comment]
I have not looked to see if it is talking to the internet once per minute but I have every reason to believe it is. I do have it setup to check for updates. The web gui does not give me an option to tell it to check every minute and every night, but I'm confident that it is indeed doing exactly that.
I commented OUT checking every minute. I then updated it and it was now uncommented.
It is constantly emailing me messages every 2m or 5m or 10 minutes, (always within 10m) telling me "a duplicate process is already checking for updates".
When I turn cron off, or remove the check every minute entry, it stops spamming me.
(I have alert notifications turned on, so it makes sense I'm receiving emails).
It should not default to checking every minute as well as nightly. I vote nightly is more than enough for a default.

**Comment by cardigliano** [comment]
It actually checks nightly by default (and only install updates if automatic updates are enabled). The script is running every minute just to check if there are user requests for checking for updates (this happens when you click on "Check for updates" on the GUI).
However the "a duplicate process is already checking for updates" warning is annoying (it should not happen actually), we will fix this. Thank you.

**Comment by gerhardmpl** [comment]
Same here (ntopng Professional Edition v.3.9.200209 on Debian Buster 10.3). I get the "a duplicate process is already checking for updates" warning for
`/usr/bin/ntopng-utils-manage-updates -a handle-upgrade-requests` and
`/usr/bin/ntopng-utils-manage-updates -a check-updates-on-demand`

I am not aware of checking for updates on the GUI and _Settings - Preferences - Updates - Automatic Updates_ is set to off.

**Comment by noybman** [comment]
I might need to report this separately, but at the same time it is also related to the update/upgrade packages and cron. Everytime I fix this, when I next update and there is an upgrade available, the upgrade breaks this again:
/etc/cron.daily/logrotate:
error: Ignoring disk2n because of bad file mode - must be 0644 or 0444.
error: Ignoring n2disk because of bad file mode - must be 0644 or 0444.
error: Ignoring nprobe because of bad file mode - must be 0644 or 0444.

**Comment by cardigliano** [comment]
The "duplicate process" check has been improved thus this is considered solved. Logrotate configuration files mode has also been fixed.
