### ISSUE TITLE
Implement alerts when periodic scripts are stuck

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3426]
When scripts are stuck, in theory an alert should be reported. Unfortunately only the second script is reported whereas when other scripts are stuck (5 min in the image below)

![Screen Shot 2020-02-14 at 22 34 43](https://user-images.githubusercontent.com/4493366/74569247-3ad71500-4f7a-11ea-86d4-d5d502be4607.png)

![Screen Shot 2020-02-14 at 21 58 45](https://user-images.githubusercontent.com/4493366/74569366-8ab5dc00-4f7a-11ea-9875-c3e61a1e90f5.png)

**Comment by simonemainardi** [comment]
This is implemented.

Alerts for slow periodic activities are implemented, along with periodic activities queued but not executed (due to the lack of threads available for execution).

Interface and system alerts are generated in https://github.com/ntop/ntopng/tree/dev/scripts/plugins/periodic_activities

![image](https://user-images.githubusercontent.com/3397663/75169815-7cf61880-5729-11ea-8a85-518d92f676e2.png)


The above scripts are executed with a `1 minute` granularity in `minute.lua`. As `minute.lua` itself can be slow, an additional mechanism has been implemented which shows a yellow triangle pointing to the periodic activities with issues.


![image](https://user-images.githubusercontent.com/3397663/75169932-a44ce580-5729-11ea-80a4-100b77a42aa1.png)

The code which takes care of placing the triangle is available in https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/periodic_activities_utils.lua
