### ISSUE TITLE
Add disk load timeseries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3427]
As disk load is a core element for storing alert and timeseries, it would be nice to have in the system script a timeseries (and alert) for disk load (or io wait) to report users when such condition happens.

**Comment by emanuele-f** [comment]
The total read/written sectors can be obtained by reading `/sys/block/sda/stat` and then a derivative can be calculated to get the throughput.

https://www.kernel.org/doc/Documentation/block/stat.txt

```
awk '{print $3 " R - " $7 " W"}' /sys/block/sda/stat
```

Note: in order to get the stats given the name of a particular partion, the `/sys/class/block/sda/sda1/stat` can be used. This is useful to get the stats for non standard devices (e.g. `/dev/cciss/c0d0p1`, whose stats should be read from `/sys/class/block/cciss\!c0d0p1/stat`). The `/` is converted to `\!`.

**Comment by simonemainardi** [comment]
Disk load added:
- calculations is done every 5 seconds in: https://github.com/ntop/ntopng/commit/82a01c521a38ff3ee354c195ba96dddb2fd11dc6
- timeseries are written in https://github.com/ntop/ntopng/commit/f6bd1b349382483cd80df2e411379084a40a95b6

So now systems supporting `/proc/stat` will show an additional `iowait` entry in the `system_stats` page, along with a link to the historical chart

![image](https://user-images.githubusercontent.com/3397663/75469138-c6936d00-598e-11ea-87d1-d5b3f80a60ad.png)

![image](https://user-images.githubusercontent.com/3397663/75469181-d7dc7980-598e-11ea-96c1-ea4cc2c23ba3.png)
