### ISSUE TITLE
Usage sort does not work as expected

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3438]
In hosts TLS page, sort on the last column does not work as expected due to the comma (,) used as thousand separator. See lua/host_details.lua?host=A.B.C.D&page=tls

![Screen Shot 2020-02-18 at 00 02 58](https://user-images.githubusercontent.com/4493366/74691202-24cb8d80-51e2-11ea-885a-9317dce6d2f4.png)

**Comment by gabryon99** [comment]
I removed the call to `formatValue` function inside `get_fingerprint_data.lua` so the sort function can compare numbers without any problem.

**Comment by emanuele-f** [comment]
formatValue adds the commas to numeric values throughout the ntopng gui. Removing it makes the page inconsistent.

**Comment by gabryon99** [comment]
Can we use the dot notation to represent numbers bigger than 1K?

**Comment by emanuele-f** [comment]
Right now we use commas as separators, dots are for decimal digits

**Comment by gabryon99** [comment]
Since JavaScript `parseFloat` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat) function doesn't know how to handles strings that represent numbers (bigger than 1K) with a comma, when the `formatFloat` function inside `jquery.tablesorter.js` is invoked I remove all the commas from the strings and I leave the dots. In this way, the floating parsing function can parse the right number from the passed string.

An example:
```
> parseFloat("3,145"); // this number represent 3145
> 3 // wrong output

> parseFloat("3,145".replace(/\,/g, ''))
> 3145 // correct output

```
