### ISSUE TITLE
Domain names limit reached

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#3452]
What does it means?

25/Feb/2020 15:34:33 [startup.lua:141] [lists_utils.lua:627] WARNING: Domain names limit reached (90000 domains). Please disable some lists in order to fix this.

**Comment by simonemainardi** [comment]
The total number of domains loaded using Category Lists exceeds 90000. Loading a number of domains higher than this would be detrimental for the performances and so is prevented.

Very likely this happens because you've enabled every single list. For example, `hpHosts Ad and Tracking` alone has 45k+ domains. Make sure to enable only a subset of lists which is most relevant for you.
