### ISSUE TITLE
Remove Layer-7 Total Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3461]
This preference is cumbersome and needs to be removed or merged with another existing preference 
![Screen Shot 2020-02-27 at 18 34 34](https://user-images.githubusercontent.com/4493366/75469820-ed9e6e80-598f-11ea-89b2-27c1b1ed4191.png)

**Comment by simonemainardi** [comment]
After internal discussion, we have come to the conclusion that this option won't be removed. Indeed, when enabled, this option causes all the l7-applications to be doubled because both the traffic and the number of flows are saved for each l7 application for each host. Given that only a few users actually benefit from this, it is better to be conservative and leave this option as a stand-alone.
