### ISSUE TITLE
Selected interface should be greyed out

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3490]
System is greyed out when selected. Please implement the same behavior also for the selected interface.

![image](https://user-images.githubusercontent.com/3397663/75758590-981de500-5d34-11ea-8c50-6729eabdea46.png)

**Comment by gabryon99** [comment]
Done in this commit: https://github.com/ntop/ntopng/commit/0f7ffad6e1a6d2acb12bca6014bce3688418c349

**Comment by simonemainardi** [comment]
not working

<img width="983" alt="image" src="https://user-images.githubusercontent.com/3397663/75862595-7a698200-5dff-11ea-961e-724fd588f193.png">

**Comment by simonemainardi** [comment]
By the way, rather than greying out the selected interface, which is somehow awkward as it looks disabled, I would use the active state for the dropdown such as

<img width="236" alt="image" src="https://user-images.githubusercontent.com/3397663/75862808-c9171c00-5dff-11ea-868a-6b5ad5967d02.png">

**Comment by emanuele-f** [comment]
@gabryon99 after internal discussion:
- Please remote the gray over color
- Fix the Mbps on new line issue reported by @simonemainardi

**Comment by gabryon99** [comment]
<img width="591" alt="Screenshot 2020-03-05 at 09 28 34" src="https://user-images.githubusercontent.com/14114916/75962340-df86ab80-5ec3-11ea-9d5d-1f9c93240c45.png">

Fixed in the last commit. Please be sure to reload the cache.
https://github.com/ntop/ntopng/commit/13eb3b6c9a389f6be540a2c45829b1725bdfbec1
