### ISSUE TITLE
No Hosts in Individual Interfaces When Part of View 

### ISSUE THREAD

**Issue by Shmythe** [ntop/ntopng#3553]
When interfaces are part of a "View Interface" they show no hosts on their pages.  All the host information is part of the "View".

If I remove the view then they gain host information.

ntopng Enterprise Edition v.3.9.200312

Here is my config:
```
-G=/var/run/ntopng.pid
--daemon=
--interface=eno1
--interface="tcp://127.0.0.1:5556"
--interface="view:eno1,tcp://127.0.0.1:5556"
--w=3000
--local-networks="10.9.0.0/23,10.9.8.0/22,10.9.16.0/24,10.9.18.0/24,10.9.20.0/2$
--data-dir=/var/lib/ntopng
--dns-mode=1
--x=512000
--X=512000
--dump-flows=nindex
```
![ntopng-hosts-in-view](https://user-images.githubusercontent.com/493775/76639449-61ea1d80-650b-11ea-85ae-caf98fd6c91a.jpg)
![ntopng-no-hosts-zc](https://user-images.githubusercontent.com/493775/76639455-657da480-650b-11ea-84fc-1a462e48c5c6.jpg)
![ntopng-no-hosts-eno1](https://user-images.githubusercontent.com/493775/76639460-67dffe80-650b-11ea-8580-adc9d4f4bb98.jpg)

**Comment by emanuele-f** [comment]
This is normal with the new view design and implementation. This choice was necessary to drastically improve the performance.

**Comment by simonemainardi** [comment]
@emanuele-f is right.

Otherwise you would end up in doubled memory to keep the hosts twice. In addition, hosts in the viewed interfaces could be partial as the same host can have some traffic on a viewed interface, and some other traffic on another viewed interface.

Anyway, I don't understand what's the use case for this configuration `--interface="view:eno1,tcp://127.0.0.1:5556"`. Maybe your use case can be solved without views. Please, explain.

**Comment by Shmythe** [comment]
It just used to work so that all the interfaces have hosts, even combined views, and my ntopng service is running on hardware where that was/is not an issue.  That being said, if it has changed, that is fine.  I just liked having a view where everything was put together, and I didn't see in the documentation that it worked differently then that, but I might have missed it.  Thank you for answering my question.
