### ISSUE TITLE
Invalid time on the ZMQ interface connected to nProbe Agent

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3563]
![Screen Shot 2020-03-16 at 10 02 15](https://user-images.githubusercontent.com/4493366/76740004-7168a100-676d-11ea-9b10-6bec28bf8d71.png)
![Screen Shot 2020-03-16 at 10 01 52](https://user-images.githubusercontent.com/4493366/76740007-7299ce00-676d-11ea-8025-71cc14eb1bd3.png)

As you can see the agent interface, running on the same host, is +1h

**Comment by simonemainardi** [comment]
issue is general and not only due to nprobe agent.

![image](https://user-images.githubusercontent.com/3397663/76892177-90a92080-688a-11ea-8640-f59a829f86b1.png)


cause is a wrong upsampling performed in `function normalizeSeriesPoints` that calls `ts_common.upsampleSerie` which screws with timeseries at different steps.
