### ISSUE TITLE
The device/network has `nil` connected

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#3657]
When I'm on Past Alerts I got this
<img width="1440" alt="Screenshot 2020-03-27 at 15 21 50" src="https://user-images.githubusercontent.com/14114916/77765732-f93c8e00-703e-11ea-95f5-6b1db4455c89.png">

**Comment by emanuele-f** [comment]
Such alerts should never be generated on the system interface, it seems like some other alert has been turned into this alert

**Comment by emanuele-f** [comment]
The issue is probably caused by a redis clean up, which has broken the alert IDs associations (in fact the entity_value for the alerts above is `admin`, which is most probably linked to a ntopng "login" event being reported on the system interface. The suggested solution is flush the alerts data from the ntopng preferences.
