### ISSUE TITLE
Some ntopng flows features 

### ISSUE THREAD

**Issue by Guymtrx** [ntop/ntopng#3692]
Hi
we think about new features that you can add to ntopng flows section
1. there is unknown flow that we investigate, we want to know if we can update the database with the real flow. (1 and 2 in the pic)
2. Can we have an option to have a button to a link to the whois lookup from the main flow window, to search the ip address. (3 in the pic)
![ntopng flow1](https://user-images.githubusercontent.com/59534272/78254579-cd1d8300-74fe-11ea-8127-1b7b66050516.jpeg)
3. Can we see old flows?

**Comment by simonemainardi** [comment]
Please check this resource describes how to set custom protocols and categories to the traffic so that you can transform unknown traffic to known: https://www.ntop.org/guides/ntopng/web_gui/categories.html

On the other hand, we won't be able to add a button to the info column which has a semantically different meaning.
