### ISSUE TITLE
Reconcile time

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3732]
Detected alerts (engaged, past, flows) have a UTC timestamp UTC. Doing drill down lists have local time stamp (e.g. CEST).

This needs to be harmonised as all timestamps must be alike 

Example
Detected Alerts->past alerts
In the past alerts table timestamp is UTC,in the drill down event list is CEST
Date/Time	Duration	Count	Severity	Alert Type	Drilldown	Description	Actions
10:05:00	02:00		1	Error	 	Threshold Cross			Minute host_score crossed by host 10.200.1.46 [210 > 200]
in the graph the anomaly interval is between 12:03:00-12:08:00

**Comment by emanuele-f** [comment]
There are multiple inconsistencies in how the timezones are handled:

![2020-04-15_17-46](https://user-images.githubusercontent.com/5488003/79358097-59349f00-7f30-11ea-996a-04015f46daa8.png)

Some of them are now fixed in c6b43f1af3cc4760c53c751a24089aa2a9bbd65a by using the client provided timezone in the time formatting lua functions.

**Comment by simonemainardi** [comment]
this also involves fixing database explorer data, alerts dashboard, etc

**Comment by emanuele-f** [comment]
There are still issues:

- Clicking on the "Search Flow Alerts" button in the alerts explorer shift the time in the dropdowns of one hour
- Same thing happens in the alerts explorer by setting a custom period
