### ISSUE TITLE
Invalid RRD format for active monitoring

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3748]
1) As it is now possible to modify the monitoring frequency, old RRDs must be deleted and recreated and the user warned. Otherwise moving monitoring frequency from 1 min to 5 min will create empty graphs

$ rrdtool info /var/lib/ntopng/-1/rrd/monitored_host/http/__www/ntop/org/http_stats.rrd 
filename = "/var/lib/ntopng/-1/rrd/monitored_host/http/__www/ntop/org/http_stats.rrd"
rrd_version = "0003"
step = 60
last_update = 1584573060
header_size = 1944
ds[ingress].index = 0
ds[ingress].type = "GAUGE"
ds[ingress].minimal_heartbeat = 120
ds[ingress].min = NaN
ds[ingress].max = NaN
ds[ingress].last_ds = "4.334000"
ds[ingress].value = NaN
ds[ingress].unknown_sec = 0
ds[egress].index = 1
ds[egress].type = "GAUGE"
ds[egress].minimal_heartbeat = 120
ds[egress].min = NaN
ds[egress].max = NaN
ds[egress].last_ds = "0"
ds[egress].value = NaN
ds[egress].unknown_sec = 0
ds[inner].index = 2
ds[inner].type = "GAUGE"
ds[inner].minimal_heartbeat = 120
ds[inner].min = NaN
ds[inner].max = NaN
ds[inner].last_ds = "266.014013"
ds[inner].value = NaN
ds[inner].unknown_sec = 0

2) the RRD path is not pleasant with the __ before the host name. This has to be fixed. Another example /var/lib/ntopng/-1/rrd/rtt_host/speedtest/net/speedtest that contains redundant strings

**Comment by emanuele-f** [comment]
Please note that `/var/lib/ntopng/-1/rrd/monitored_host` refers to a path in the old implementation, please remove it with `rm -rf /var/lib/ntopng/-1/rrd/monitored_host`. The current path is `/var/lib/ntopng/-1/rrd/am_host`. When the granularity changes, the old RRD are now deleted (fixed in 4bd04e7e4c82e58d3f850400d6aeefd4d2e3603e). Regarding the repeated "speedtest" string in the RRD path, the path is automatically created based on the timeseries tags ("speedtest" is both the URL and the measure value). This is consistent with the other active monitoring hosts so I would avoid creating an exception for it. Please open a new issue if you don't agree.
