### ISSUE TITLE
get a report where we can see the external traffic for our internal server IPs / hosts, cumulated in GByte per month and IP

### ISSUE THREAD

**Issue by dkomander** [ntop/ntopng#376]
Hi Support,

thanks to the latest update with the new feature "historical graphs" , we now can see the generated traffic for receivers and senders for timeframe x (1 minute, 5 minutes, 1 hour etc.). 

We would like to get a report where we can see the external traffic for our internal server IPs / hosts, cumulated in GByte per month and IP. This should only count the external incoming and outgoing traffic, but not the traffic to any internal networks (i. e. internal network 1, internal network2).

Such a report e.g. could look like this:
## 

Cumulated external traffic from 2016-01-01 to 2016-01-31

Host / Incoming (GB) / Outgoing (GB) / Total (GB)
10.123.234.1 / 18,45 / 136,66 / 155,11
10.123.234.5 / 567,89 / 543,21 / 1111,10
## 

For now, we have the following situation:

http://SERVER-IP:3000/lua/host_details.lua?ifname=2&host=SERVER-NAME&page=historical

In the historical view, we see the evaluated traffic of the host for a specific timeframe (1 minute, 5 minute, 1 hour, 1 day etc. pp.) for different connections. One of them is the connection to outside services but it includes other, internal networks as well. We only want the total incoming and outgoing traffic for internet destinations that are not within our internal networks.
#150

**Comment by simonemainardi** [comment]
feature currently implemented and available for any local host:

![image](https://user-images.githubusercontent.com/3397663/40850529-25ffcac8-65c5-11e8-8085-58ceda6879d2.png)


it is also possible to create traffic profiles for the hosts / subnets of interest in order to get such reports:

![image](https://user-images.githubusercontent.com/3397663/40850625-7132966a-65c5-11e8-8729-36829a150958.png)
