### ISSUE TITLE
[RTT] Disable used unique measurements

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3769]
When a speedtest host is already defined, the speedtest measurement should be disabled in the "Add Active Monitoring Host" dropdown

**Comment by emanuele-f** [comment]
Fixed in 5adfed56058c9ddbc2a97b08cd0dfec1d77066c0

**Comment by simonemainardi** [comment]
not working. de-selecting a re-selecting the dropdowns enable the speedtest again

<img width="779" alt="image" src="https://user-images.githubusercontent.com/3397663/79463921-bcd6cf00-7ff9-11ea-9fa0-b42c395545f6.png">

<img width="786" alt="image" src="https://user-images.githubusercontent.com/3397663/79463935-c2341980-7ff9-11ea-972b-26305034fde0.png">

**Comment by simonemainardi** [comment]
seems this is an issue which occurs on FF for os X

<img width="620" alt="image" src="https://user-images.githubusercontent.com/3397663/79471267-b3059980-8002-11ea-80c4-3417b7b4b826.png">


the entry is disabled (actually I cannot select it) but still the style looks like as if it was enabled.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/3397663/79471353-cd3f7780-8002-11ea-8d4e-da8e6e1f461b.png">

remove the entry rather than showing it in the dropdown.

**Comment by emanuele-f** [comment]
Changes implemented in ab82d57ca42251d01a71eacf257ae10d88a7a06e .

**Comment by simonemainardi** [comment]
Thank you. Now it is OK.
