### ISSUE TITLE
[RTT] Unreachable system is not reported properly

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3777]
![Screen Shot 2020-04-15 at 21 29 15](https://user-images.githubusercontent.com/4493366/79380345-9fa1f200-7f60-11ea-818b-cadde9237c62.png)

This host has been unreachable from 20:09 to 20:26. Looking at the graph this is not obvious. Actually it seems that no measurement was made during that period, but the truth is that the measurement happened and the host was unreachable. This needs to be depicted properly as today it is not clear at all that this was what happened

**Comment by emanuele-f** [comment]
The proposed solution is to add a new metric to the existing `am_host:rtt_min` and related charts called "unreachable". Such metric can be 0 (reachable or unknown) or 1 (unreachable). Then a chart like the following can be created:

![79380345-9fa1f200-7f60-11ea-818b-cadde9237c62](https://user-images.githubusercontent.com/5488003/79461801-2ea51d80-7fe6-11ea-842d-dfceb7f3363b.png)

**Comment by lucaderi** [comment]
How is this implemented? Do you want to have a second timeseries and hide it (so it's a trick in essence)? Or this will be a clean solution that can be used in other active measurement? Please elaborate

**Comment by emanuele-f** [comment]
The `am_host:rtt_min` will have a second metric "unreachable" which is charted like the other metrics. It will use the right chart axis as the y axis. This can be reused in other measurements but will require changes to such measurements. Please note that the proposed approach only works with the Pro charts as custom schemas (see https://github.com/ntop/ntopng/blob/dev/doc/README.charts#L87) are only supported for that. In order to remove such limitation, I would suggest to unify the pro and community charts. The changes required in order to implement this are:

- Add the metric to the schema and write it during the periodic polling
- Define a "custom schema"  and assign the new metric to the right y axis
- Define a new javascript formatting function which translates the unreachable boolean value to a string

**Comment by emanuele-f** [comment]
In 947fee33b2d539e2db5ab6be67e8cb4d55ae51c0 now 0 is written for unreachable hosts. Such data can be obtained by manually querying the timeseries data via the REST endpoint:

http://127.0.0.1:3000/lua/rest/get/timeseries/ts.lua?ts_schema=am_host:value_min&ts_query=ifid:-1,host:ntop.org,measure:icmp&extended=1&no_fill=1&epoch_begin=1587129680&epoch_end=1587133280

or from lua:

```
local ts_utils = require "ts_utils"

tprint(ts_utils.query("am_host:value_min", {ifid=getSystemInterfaceId(), host="ntop.org", measure='icmp'}, os.time()-3600, os.time(), {
   fill_value = 0/0, -- Show unknown values as NaN
}))
```

**Comment by emanuele-f** [comment]
A timeseries can now show the unreachable state by setting the `show_unreachable = true` parameter (the 0 value is interpreted as unreachable). The implementation uses the `d3` api to draw lines rather than providing a new timeseries as the latter approach resulted in multiple scaling and formatting problems.

 ![2020-04-21_15-33](https://user-images.githubusercontent.com/5488003/79874257-a5bc2680-83d7-11ea-9956-dac4d68507b9.png)

**Comment by simonemainardi** [comment]
working as expected

<img width="649" alt="image" src="https://user-images.githubusercontent.com/3397663/81068251-58b07800-8ee0-11ea-8d30-ca7622c9a042.png">
