### ISSUE TITLE
[RTT] Discrepancy in active and passive monitoring results

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3779]
See #3777 for more information about the host unreachability time window. 

During such time window, the monitored host was reachable but unresponsive. However this is the errore reported in the past alerts window.
![Screen Shot 2020-04-15 at 21 41 35](https://user-images.githubusercontent.com/4493366/79381218-ee9c5700-7f61-11ea-821d-ee49c77e7870.png)

As you can see the time window of this alert and of the active monitoring are not alike. This issue should be investigated

**Comment by emanuele-f** [comment]
I don't get the relation between the unresponsive host (www.ntop.org) and the Luca's iMac host, please explain

**Comment by lucaderi** [comment]
On this host I have performed active tests via ntopng right? As theyh have failed for over 25 minutes (see #3777 ) I would expect to see unresponsiveness for about 25 mins and not for 9 mins like in ht picture above.

**Comment by emanuele-f** [comment]
Such test requires a perfectly clean environment as other background HTTP requests may influence the result. Analyzing the information provided above, it seems like the environment is not clean, here is the explanation.

According to the active monitoring page, the host became unreachable at 20:09 . Here is the relevant sequence of events:

1. at 20:09 the host became unreachable
2. at 20:10 runs the requests/replies ratio check, which ideally leads to 4 replies / 5 request so a 80% ratio, which is fine (assuming that the alert threshold is 50% which is the default).
3. at 20:15 runs the requests/replies ratio check, which should have reported a 0 replies / 5 request = 0 % ratio, triggering the alert at 20:15. Since this does not happen, this may be a bug, however (see 4.)
4. at 20:20 runs the requests/replies ratio check, and it triggers the alert that we see in the image. But such alerts shows that the environment is actually not clean as it reports 3 HTTP replies, which is wrong since the host at 20:20 was not responding. This means that there are other background requests taking place.

So the last point shows that the environment is probably not clean. A PCAP would clarify this.

**Comment by emanuele-f** [comment]
Closing for now
