### ISSUE TITLE
Alert: implement alerts collapsing

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3780]
![Screen Shot 2020-04-15 at 21 45 09](https://user-images.githubusercontent.com/4493366/79381522-679bae80-7f62-11ea-982a-a2624e8430e5.png)

In expect all the above alerts to be collapsed (count > 1) into one

**Comment by simonemainardi** [comment]
To collapse flow alerts, a good possibility is to define an aggregation function on a per-alert basis. The aggregation function can the produce a string which can be stored in the alert `alert_entity_val`.

For example, for the alert highlighted in the example, a good aggregation could be: source ip address + tls certificate name.

Also time should be taken into account to avoid aggregating alerts which are too far one from the other in terms of time. Default is 5 minutes for currently performed aggregations.

**Comment by emanuele-f** [comment]
In my opinion the preliminary work for this issue is to reply to these questions:

- Where to declare the aggregation key to use (e.g. associate it to a specific flow status/alert type or inside the alert_entity_value)
- Which flow alerts should be aggregated and their aggregation key to use
- What to show in the aggregated alerts messages (since the aggregation will lead to information loss, e.g. missing ports).
- Ensure that such information loss does not create problems when querying alerts (e.g. in the alerts explorer)

**Comment by simonemainardi** [comment]
Count no longer exists in the latest ntopng 5.0+. Alerts have been reworked with a new database. Aggregation is performed directly on the database and at query time.
