### ISSUE TITLE
No Upstream Flow after upgrading to V4

### ISSUE THREAD

**Issue by ntopnguser** [ntop/ntopng#3803]
Hello - we had been using 3.7 for several months on Ubuntu 18.04 and just upgraded to 4.1.  After the upgrade, the bandwidth graph for our monitored interface shows no outgoing traffic (only incoming).

![Capture](https://user-images.githubusercontent.com/64026525/79767809-df1d6500-82f7-11ea-8e33-53abd64fc952.PNG)

Do we have a misconfiguration somewhere?  Thank you.

**Comment by simonemainardi** [comment]
is this an interface receiving mirrored traffic?

**Comment by ntopnguser** [comment]
Yes - it is receiving a span session.

**Comment by jl-678** [comment]
Funny, I was perusing this forum and just realized that I have the same problem.  I am running 4.1.200413 on 18.04 via a span port.

One update: my 18.04 server has two network interfaces eth0 (spanned) and wlan0 (management).  eth0 is not showing outbound traffic as mentioned by @ntopnguser.  If I change ntopng to view to wlan0, I do see outbound traffic but obviously, much less....

**Comment by simonemainardi** [comment]
Behavior reported is expected. On a port connected to a mirror/SPAN, the traffic is only entering the port so no outbound traffic is present.

In version 3.7 the charts were misleading: they were indicating the local-to-remote and remote-to-local traffic, respectively. This was causing confusion and so that has been removed to what is just TX and RX.

You should visit the interface statistics page and set the 'mirrored traffic' preference for the interface. That will show a single chart at the top of the page.
