### ISSUE TITLE
Periodically refresh pages that require form submission

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3866]
In pages that require form submission such as active measurements (but NOT limited to this one) when the page is on screen inactive for some time, this causes form submission (e.g. add or remove an entry) to fail.

It is requested to avoid this error e.g. via periodic page refresh or other means.

![Screen Shot 2020-04-30 at 13 29 47](https://user-images.githubusercontent.com/4493366/80705454-c1fe4880-8ae6-11ea-8fe7-ea0763ae500d.png)

**Comment by emanuele-f** [comment]
Note: this occurs when the CSRF of the page expires.

**Comment by emanuele-f** [comment]
Here is a description of the problem and the proposed solution.

[From https://owasp.org/www-community/attacks/csrf]
Cross-Site Request Forgery (CSRF) is an attack that forces an end user to execute unwanted actions on a web application in which they’re currently authenticated. CSRF attacks specifically target state-changing requests, not theft of data, since the attacker has no way to see the response to the forged request.

An attacker could create a GET/POST form with the request data he wants the target to send, then use social engineering or other techniques to direct the target to such page and submit the form. The session cookie does not prevent an CSRF attack since cookies are passed in such context (unless the `SameSite: Strict` cookie attribute is set, which would break ntopng integration in other tools).

In order to prevent such attack, currently ntopng generates a per request CSRF token which is bound to the user and which is sent in all the POST requests using the synchronizer CSRF token technique. This is the suggested solution to CSRF attacks (https://owasp.org/www-project-code-review-guide/reviewing-code-for-csrf-issues) but has the drawback to break some functionalities:

- The token expires after some time, so if the user does not refreshes the page the request fails (what this github issue is about)
- If the user duplicates the tab or uses the back button, the subsequent form submission fails again
- It forces ntopng to generate a new token after performing a POST request when the page is not reloaded (e.g. in the user scripts page).

Instead of using a per-request token, ntopng could use a per-session token so that the above problems are addressed. As described in https://www.sjoerdlangkemper.nl/2019/12/18/different-csrf-token-for-each-form , the practical reduction in security of this approach is very small if compared to the usability benefits as exploiting it would require complex attacks (e.g. BREACH). It is important to note that an XSS vulnerability in ntopng would break any CSRF protection, being it a per-request or per-session, so it is not relevant in this discussion.
