### ISSUE TITLE
Flow direction reversed

### ISSUE THREAD

**Issue by RichieB2B** [ntop/ntopng#3934]
Using ntopng 4.0.200513-10203 I receive many "server application" flow alerts like:
```
Server application 'Apple' is not allowed by the configured Multimedia application policy [Flow: 17.253.53.208:443  192.168.1.239:53847] [TCP] [Application: TLS.Apple] 
```
Since I have TLS.Apple whitelisted for client traffic in `Multimedia application policy` it is clear this alert means that 17.253.53.208:443 is considered the client and 192.168.1.239:53847 the server. 192.168.1.0/24 is configured as a local network. How can I make ntopng understand the flow direction should be reversed?

**Comment by simonemainardi** [comment]
Flow direction depends on the first flow packet seen.

When directions are swapped, in general, it happens one of the following things:

- ntopng couldn't see the beginning of the flow because it has been started with the flow already in progress
- ntopng is fed with a mirror port but the mirror is sending only one direction of the traffic

So you should check one of the two things above.

**Comment by RichieB2B** [comment]
Thanks! The second option applied to me. Changing my mirror port from manual to auto negotiation fixed this for me (UniFi switch).
