### ISSUE TITLE
VPN traffic correlation with Fritzbox

### ISSUE THREAD

**Issue by khoshtip2** [ntop/ntopng#3973]
we have some vpn-user who works from outside via vpntracker app (mac) and connect with file server.
how can we check the vpn-traffic from vpntracker app (ip-sec) on the network?
Link: https://www.vpntracker.com/de/index.html

is there a "plugin" specifically for VPN or VOIP users?

best regards
Shahram

**Comment by cardigliano** [comment]
@khoshtip2 could you provide more details about the topology? Do you have a VPN firewall/concentrator? Or the user is connecting to a VPN server running on the file server?

**Comment by khoshtip2** [comment]
Hi,
We have avm fritzbox as Router and VPN Server.
Remote User Connect to Fritzbox.
The Apple fileserver and 3CX Server are local,  behind the Fritzbox.

Best regstes
SH

**Comment by khoshtip2** [comment]
[network.pdf](https://github.com/ntop/ntopng/files/4689916/network.pdf)
the VPN remote clients are not listed.

**Comment by cardigliano** [comment]
@khoshtip2 could you check if:
1. there is a way to configure a syslog server in your Frizbox router
2. the logs contain user login/logout events with the assigned IP, in order to propagate that information to ntopng and tag the traffic (we have a similar integration with other VPN firewalls in ntopng), and in that case send us an example
I see that there is some similar request: https://github.com/mcktr/check_tr64_fritz/issues/41

**Comment by cardigliano** [comment]
@khoshtip2 were you able to check the ability to export syslog in your Fritzbox?

**Comment by cardigliano** [comment]
Closing this for the time being, please reopen if still required
