### ISSUE TITLE
Move Configurations out of User Scripts

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4078]
Configurations allow to specify heterogeneous groups of hosts, local networks, interfaces, snmp devices, etc. Such configurations are currently used to differentiate user scripts execution for each group. Configurations should become a general concept across the whole ntopng as they will be used not only to differentiate user scripts execution, but also to identify notification recipients. Let's call the generalized configurations as 'Behaviors'.

To implement this issue it is necessary to do the following.

--------

Implement a page 'Behaviors' with the following look.

![image](https://user-images.githubusercontent.com/3397663/85530738-752e7e00-b60e-11ea-87b5-7b1711ea5fa8.png)

Each behavior has columns:

- 'Behavior Name'
- 'Apply To'
- 'User Scripts' (not shown above)
- 'Recipients' (not shown above)
- 'Actions'

'Behavior Name' and 'Apply to' are equivalent to the current columns in the user scripts configuration.
'User Scripts' shows the user script configuration of the current behavior (1 and only 1 configuration).
'Recipients' show all the notification recipients of the current behavior (N recipient).
'Actions' has buttons:

- 'Rename'
- 'Delete'
- 'Apply to'
- 'User Scripts'
- 'Recipients'.

'Rename', 'Delete', 'Apply to' are equivalent to the current behavior in user scripts configurations.

'User Scripts' opens a modal and allows to choose one among all the available user scripts configurations. 'Recipients' opens a modal with a multi select and allows to choose zero to many of the available notification recipients.

A 'Default' behavior pointing to the 'Default' user scripts configuration and with a `wildcard` pointing to all recipients is always present.

------

Rework page 'User Scripts' and remove any 'Apply To' functionality (column and button) as they are now part of the behaviors'. Page will look like

![image](https://user-images.githubusercontent.com/3397663/85531825-65636980-b60f-11ea-964f-b49ca801508e.png)

User scripts configuration will only have a name but no 'Apply to'. 'Apply to' is part of the configurations.

------

Examples

behavior 'devmachines', applied to 192.168.2.0/24 has default user scripts configuration and recipients 'simone' and 'alfredo'.
behavior 'devmachineserver' applied to 192.168.2.123 has 'server' user scripts configuration and recipients 'simone', 'alfredo' and 'luca'.
behavior 'devmachineiot' applied to 192.168.2.120 has 'iot' user scripts configuration and recipients 'simone', 'alfredo' and 'gabriele'.

Longest-match wins. One match is allowed. That is 192.168.2.123 will only match to behavior 'devmachineserver'.

---

Note. To handle the active monitoring, an extra entity 'active monitoring' should be added to the behaviors. Each active monitoring entry will be either an ip address or a string (to match for domain names). When adding an active monitored host, the default 'behavior' is matched. An extra 'Behavior' action will appear in the active monitoring, to allow one to change the default behavior.

**Comment by lucaderi** [comment]
This ticket contains some valid points but it does not addresses the problem as a whole. IMHO the starting point are host pools so that we can simplify, and not complicate as proposed here, the application design. Let's recap: host pools define group of hosts that fall under the same administrative domain. In order to bring this concept to user script it is necessary to
create a concept similar to "host pools" for
- device pools
- network pools
- SNMP devices pools
- active measurement pool (for active measurements)

The
- Create a pools menu under which hosts, devices, networks and SNMP pool will be located in the menubar. Each pool will have a default pool to which elements not belonging to each pool will belong.
- In "user scripts" modify the "apply to" button show the list of pools to which the script will be bound

To make things simple, pools won't overlap, meaning that an element will belong at most to one pool. The user interface for  hosts, devices, networks, SNMP, and active measurements will report for each resource, the pool to which a given resource belongs.

**Comment by simonemainardi** [comment]
Information in this ticket has been reviewed and implementation has been done accordingly. Individual tickets have been opened where necessary.
