### ISSUE TITLE
Empty LLDP Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4112]
When a single device is polled and it has no peers to which it connects to, the LLDP page is empty
![Screen Shot 2020-07-06 at 15 33 04](https://user-images.githubusercontent.com/4493366/86598902-21bd1800-bf9e-11ea-8cd9-9495f6e9979a.png)

It is requested
- to report a message so that the user knows that this is not a bug but there are no peers to represent

Note that the area for the map is pretty large, and it should be reduced a bit to render on standard screens

**Comment by gabryon99** [comment]
A message when there are no nodes has been added. When the page loads it checks if there are node with edges, if not the message below will be shown:
<img width="1480" alt="Screenshot 2020-07-07 at 11 02 46" src="https://user-images.githubusercontent.com/14114916/86754731-66e65600-c041-11ea-85f3-f9b5368e44e7.png">
otherwise the topology graph will be shown. Now the canvas is 600px tall.

See these commits:
* https://github.com/ntop/ntopng/commit/526f86a84529f2ceab7388541330cf9856c95ad6
* https://github.com/ntop/ntopng/commit/f057c185e4c0107239bcf4a046c2ad25ffafbe39

**Comment by simonemainardi** [comment]
@gabryon99 can yuu also hide the 'topology' links in the menubar when there are no nodes so the user doesn't end up in an empty page?
