### ISSUE TITLE
[pools] Syslog endpoint test message written in red

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4242]
The successful message is written in red:

![image](https://user-images.githubusercontent.com/3397663/88951569-78183080-d296-11ea-8f34-91ebfa2f6990.png)

**Comment by gabryon99** [comment]
<img width="687" alt="Screenshot 2020-07-31 at 11 33 15" src="https://user-images.githubusercontent.com/14114916/89021993-a131d300-d321-11ea-8d95-83eca3e62053.png">

Fixed thanks to @cardigliano. The problem was in the backend. See the commit: https://github.com/ntop/ntopng/commit/a53f494d4387854219f02f77e3b817c4371043f9
