### ISSUE TITLE
[Pools] Missing OK/Cancel button in Pools

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4245]
When no recipient is configured

![Screen Shot 2020-07-30 at 22 24 05](https://user-images.githubusercontent.com/4493366/88970972-8759a700-d2b3-11ea-8012-10c5f015a709.png)

editing pools the OK/Cancel button are not present

![Screen Shot 2020-07-30 at 22 24 33](https://user-images.githubusercontent.com/4493366/88971004-950f2c80-d2b3-11ea-9564-ad246faaa68b.png)

**Comment by gabryon99** [comment]
<img width="805" alt="Screenshot 2020-07-31 at 11 57 28" src="https://user-images.githubusercontent.com/14114916/89024209-03d89e00-d325-11ea-9dda-5cdef169da55.png">

Fixed, the problem was caused by a missing `</div>`. See the commit: https://github.com/ntop/ntopng/commit/b47fb7212994294251cf9e95200bcbbafd0dd9ad
