### ISSUE TITLE
Custom protocols are not depicted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4289]
![Screen Shot 2020-08-11 at 17 25 28](https://user-images.githubusercontent.com/4493366/89916221-acc1ab80-dbf7-11ea-83ae-4d9c56c68f4c.png)

Creating custom protocols using the -p  <file>switch has a side effect
- protocol are depicted in the web GUI
- they are not depicted in the above picture where all the applications protocols are listed

**Comment by simonemainardi** [comment]
Tried both on linux and OSX. Custom applications are correctly shown, both in the timeseries list and also when doing the drilldown with nIndex.

There were an issue with the ordering, though. Lowercase applications were listed after upper-case applications so that could be the cause of the seemingly missing application. Fixed.

Will follow up privately with the user and do additional changes if necessary.
