### ISSUE TITLE
Put package on hold with expired license

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4294]
Some users complained for https://github.com/ntop/ntopng/blob/dev/packages/ubuntu/debian.ntopng/prerm.in#L20 that breaks ntopng with automatic upgrades or with '-y'. 

A suggestion is to avoid upgrading ntopng (and other ntopng packages) using 
- apt-mark hold ntopng ntopng-base/data
(check if there is a similar mechanism for yum, but I doubt)

Blocking upgrades for expired licenses could prevent software for breaking up.

**Comment by HaleyACS** [comment]
For RPM packages (yum/rpm) one method is to edit the /etc/yum.conf file and add the package into the exclude list.
for example:
`exclude=ntopng*`
would prevent ntopng to be updated by yum.

As general note - the script/upgraded script from ntopng side *(cron-job checking updates) should not update the package if the license date expired and put it on hold in the other package managers.
The system-user however will have to make sure that the cron-job from ntopng runs first so that the package can be set into hold/exclude before the overall system update/upgrade is ran.

**Comment by CyberbreinAirw0lf** [comment]
It looks like I have this problem - license is expired. However, I can not add a new license key because there is no webUI. Tried to revert the config to the community edition => not working.

Please advise - where do we go from here?

**Comment by cardigliano** [comment]
Added note on package installation to warn the user about maintenance expiration and provide commands to hold the package.

**Comment by simonemainardi** [comment]
This is the commit for reference: https://github.com/ntop/ntopng/commit/20a29cf77fb28820fdfb76628a0db40b2b45048f
