### ISSUE TITLE
ntopng and TZSP and filtering out TZSP sniffing traffic

### ISSUE THREAD

**Issue by tpavlin** [ntop/ntopng#435]
It would be nice to be able to filter out TZSP sniffed traffic flows, and only show decoded flows. Since due to my network configuration I can only preform monitor such way. I got loads of flows originating from my router reserved TZSP IP with destionation of dedicated ntopng server. 

Great tool, keep up the good work!

Thank you
Tic Pavlin

**Comment by simonemainardi** [comment]
@tpavlin can you please attach a pcap with TZSP traffic? So we can have a look at it and evaluate possible implementations.

**Comment by lucaderi** [comment]
@tpavlin I close this issue for inactivity. When will you be able to share a pcap we'll reopen it

**Comment by andris** [comment]
@lucaderi - I have this issue as well.  I'm attaching a pcap to hopefully help look at this.  I am sending traffic to the ntopng server via TZSP.  ntopng is showing statistics that include both the outer TZSP connection as well as the inner "real" traffic i am interested in.

In this capture 172.16.30.1 is the TZSP source (a router) and 172.16.30.2 is the ntopng server.

In all metrics in ntopng, it is unfortunate to have the TZSP traffic included because it massively outnumbers all the real traffic volumes and protocols i am interested in.

As you can see from the packet capture - the real traffic of interest is encapsulated in the TZSP so it's not possible to simply use ntopng's --packet-filter option to ignore the TZSP IPs 172.16.30.1 and 172.16.30.2, because that would filter all traffic.

I am also using --dump-flows to export the flows to elasticsearch.  In addition to being included in the ntopng statistics and reports, the TZSP  flows are also included in the elasticsearch exports.  It would be very helpful to exclude the TZSP flows from the exports as well.

Thanks much - please let me know if i can provide any additional information.

[tcpdump_20160628_tzsp.pcap.zip](https://github.com/ntop/ntopng/files/337743/tcpdump_20160628_tzsp.pcap.zip)

**Comment by kitsune0n** [comment]
actual for me too

**Comment by simonemainardi** [comment]
+@lucaderi

**Comment by rileonar** [comment]
Hello,
I have exactly the same environment: a router sending TZSP flow to an interface monitored by ntopng.
I see ntopng can handle TZSP encapsulation since v2.2, but I don't know how to decapsulate traffic from that flow.
Does anyone know how to configure ntopng to do that?
TIA

**Comment by gpetersson** [comment]
@rileonar I had to read the source code to figure this out, it's completely undocumented. Basically you just send the stream to your ntop machine's address on port 37008 (which is hard-coded) and then it automatically decodes it for you.
