### ISSUE TITLE
Host throughput sorting bug

### ISSUE THREAD

**Issue by Romano44** [ntop/ntopng#444]
Greetings. I manage LAN network and decided to try ntopng 2.2 I just got running. Everything work as expected except one strange thing: hosts are not dynamically sorted based on their throughput.:

![sort](https://cloud.githubusercontent.com/assets/17813740/13730068/ed885a56-e944-11e5-8e29-cdcc0326928c.jpg)

As you see on the pic they should be dynamically relocated from top to bottom based on their speed but instead stay where they are. I thought it need some time to register but no, even sustained throughput over period doesnt change their positions.
However, if I reload browser or re-click on the column they do get sorted properly immediately. Thats obviously not good as it would require me to click/reload every few seconds. So dynamic columns sorting doesnt work it only does upon first page load(or reload). 
I knew it could be my browser(Opera) so I also tried both IE and latest Firefox, problem remain so its probably not a browser issue.

Best regards: Romano

**Comment by simonemainardi** [comment]
@Romano44 this is the expected behavior, not a bug. Hosts are sorted according to their throughput measured in the moment when you click on the column name. Then, ntopng dynamically updates hosts information but does not change entries in the table. It would be annoying in terms of experience to change the contents of a multi-column table while a user may be reading it.

If you want to have a real-time list of top talkers you should have a look at the ntopng Pro dashboard that gives you the realtime list of top talkers (see on the left):
![image](https://cloud.githubusercontent.com/assets/3397663/13822201/05ac0c1a-eba5-11e5-98d1-9e067ef6ef70.png)

**Comment by Romano44** [comment]
Dear Simone, first thank you for your reply. 

I have to disagree and say this is wrong app behavior though IMO. Not only would it be **not** annoying to sort table on the fly, it is in fact desired behavior and any other application do it. 

Let me remind you that original Ntop also sorted tables on the fly. Other shell apps like iptraf or iftop do the same and they do it in same realtime speed if not quicker. 

Ntopng is probably fist app that I know to diverge from this "standard". It basically make whole thing 
useless because if you look at my pic for example - and that pic is not even complete but if you have more peers say 100+ on LAN then good luck finding top realtime throughputs without constant manual reload.
Let me also say that pro dashboard is in no way good replacement for proper hosts page and therefore also not an option. 

I will have to revert to old Ntop or use another app then, but I would strongly suggest one more time to you guys to reconsider on this issue and implement proper dynamic sorting in the hosts page.

Best regards: Romano
