### ISSUE TITLE
ntop rrd arrested

### ISSUE THREAD

**Issue by iber-mi** [ntop/ntopng#446]
Hi,
might lead me in because my graphics RDD have stopped suddenly and had only been since yesterday at 6 PM working? The curious that the traffic graph has not stopped, only protocol applications. Attached images.

![config](https://cloud.githubusercontent.com/assets/17645260/13776954/482004d2-eaad-11e5-885a-c2e78789df21.png)
![traffic](https://cloud.githubusercontent.com/assets/17645260/13776955/4821b6d8-eaad-11e5-9726-1eb69d210b76.png)
![applications](https://cloud.githubusercontent.com/assets/17645260/13776956/4822be02-eaad-11e5-99c1-e9035c3d6f30.png)

![historical](https://cloud.githubusercontent.com/assets/17645260/13776991/8831641c-eaad-11e5-99dc-9a6a51b31527.png)

**Comment by simonemainardi** [comment]
ntop development and support has been discontinued. Please consider moving to ntopng -- actually, this is the ntopng issue tracker.

**Comment by iber-mi** [comment]
I know and I've tried for 1 whole week, but I have already discussed in this forum that it is impossible to operate nprobe on Debian 7 and can not update to Debian 8 because I have several servers that php5.5 up do not work as well my only option is ntop and now this happens rrd graphics that are stopped and not because reason, and I would like to use my ntopng, but does not serve me without nprobe ... Any help please?

**Comment by simonemainardi** [comment]
#144

**Comment by iber-mi** [comment]
?

**Comment by iber-mi** [comment]
The latest posts #144 they are mine, I've already tried that and it does not work.

**Comment by simonemainardi** [comment]
I am not sure you can claim it does not work. It works on the supported architectures. Debian 7 is not supported. @lucaderi already said "Sorry we have no resources to support Debian 7 with ZMQ.". You should try and find a way to update php5.5 since it is preventing the update to Debian 8.

We do our best to support as many architectures as possible. Presently the demand to support Debian 7 is too small among the ntopng users community. For this reason we try to concentrate our efforts in developing and supporting other widely used packages so that the most part of users can have a benefit. This is community support.

**Comment by lucaderi** [comment]
Sorry ntop is no longer supported. Please move to ntopng.
