### ISSUE TITLE
Directory alert_definitions seems to be ignored in plugins

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4548]
Suppose to create a plugin named X with the following layout

X/alert_definitions
X/locales
...

The directory alert_definitions seems to be ignored pushing plugin developer to store alert definitions inside the ntopng code base. This has to be fixed

**Comment by simonemainardi** [comment]
it doesn't seem to be ignored:

```
simone@devel:~/ntopng$ mkdir scripts/plugins/alerts/security/blacklisted/alert_definitions
simone@devel:~/ntopng$ mkdir scripts/plugins/alerts/security/blacklisted/status_definitions
simone@devel:~/ntopng$ mv scripts/lua/modules/alert_definitions/alert_flow_blacklisted.lua scripts/plugins/alerts/security/blacklisted/alert_definitions/
simone@devel:~/ntopng$ mv scripts/lua/modules/flow_status_definitions/status_blacklisted.lua scripts/plugins/alerts/security/blacklisted/status_definitions/
```

Restart ntopng and everything is in place:

![image](https://user-images.githubusercontent.com/3397663/95552446-00d8e880-0a0d-11eb-850c-0cd943d7cf63.png)

**Comment by simonemainardi** [comment]
This is resolved. Folders are supported. There was an issue due to an non-defined alert key solved by https://github.com/ntop/ntopng/commit/02323882eb5397848d044ea9a5aa4bfca4e3b027

To use alert keys see https://github.com/ntop/ntopng/blob/01081125da40d4d64db7e321dd7ed569ce9d0a47/scripts/lua/modules/alert_keys.lua#L117
