### ISSUE TITLE
Exporter stats displayed for invalid interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4559]
Exporter stats are shown only for ZMQ-interfaces. Unfortunatlely there are two issues
- disaggregated interfaces have correct stats, whereas main interfaces do not
- if opening exporter stats and changing interface from dropdown menu, the exporter stats is shown also for interfaces 9e.g. the syslog interface) for which they should not be displayed

**Comment by simonemainardi** [comment]
> if opening exporter stats and changing interface from dropdown menu, the exporter stats is shown also for interfaces 9e.g. the syslog interface) for which they should not be displayed

this is fixed in the commit

> disaggregated interfaces have correct stats, whereas main interfaces do not

Seeing the empty exporters table may be normal in the main interface. Exporters will appear in the main interface when flows are not delivered to sub-interfaces or when "Duplicate Disaggregated Traffic" is selected. Hence, to me, it is not correct to hide the page "Exporters" in the main interface.
