### ISSUE TITLE
High CPU Load (> 100%) with Interfaces with no traffic

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4576]
Start ntipng onver multiple interfaces that have no traffic; for instance ntopng -i utun0 -i en1 -i en2. Ideally the load should be almost 0 as there is nothing to do. Unfortunately this is not the caise and the load will exec sometimes 100%.

The bug is probably caused by threads that wake up all at the same time, withouth synchronization, and spike up. In essence it is a design bug not a software bug.

**Comment by DrToxo** [comment]
Ive just upgraded to ntopng-4.1.200609-x64 and things did seem ok, but then I started to see issues and noticed the CPU maced out between this process and system interrupts.   When I now try to login I get:

HTTP/1.1 302 Found Set-Cookie: session=f491bb59349e20d87aab704ae64ae274; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=x.x.x.x%3A3000%2Flua%2Fhttp_status_code.lua%3Fmessage%3Dinternal_error%26referer%3Dx.x.x.x%253A3000%252Flua%252Fadmin%252Fprefs.lua%253Ftab%253Dmisc%26error_message%3DC%253A%255CWindows%255CTemp%255Cntopng%255Cplugins0%255Calert_endpoints%255Cnagios.lua%253A1%253A%2520unexpected%2520symbol%2520&error_message=C%3A%5CWindows%5CTemp%5Cntopng%5Cplugins0%5Cts_schemas%5Cscore%5Cmin.lua%3A1%3A%20unexpected%20symbol%20near%20%27%3C%5C135%3E%27 C:\Windows\Temp\ntopng\plugins0\ts_schemas\score\min.lua:1: unexpected symbol near '<\135>'

Is it possible to remove un-needed interfaces from within a config file so that only the single active interface is shown until this issue is resolved?

Thanks

**Comment by simonemainardi** [comment]
you are using a windows build from june. Wait for the new build. In the meanwhile, if you are a community user, add `--community` to the options.

**Comment by lucaderi** [comment]
verified as fixed

**Comment by DrToxo** [comment]
Great news, thanks...

Sorry for the daft quesiton but how do I actually apply this fix to our windows build?

**Comment by simonemainardi** [comment]
Please, hold on, we are going to release the new stable build within one week. Stay tuned.
