### ISSUE TITLE
Missing restart message after import

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4580]
![Screen Shot 2020-10-13 at 17 15 49](https://user-images.githubusercontent.com/4493366/95880531-e50c7400-0d77-11eb-9724-f7d68792a541.png)

After the import the user MUST be forced to restart ntopng. So after the import you need to display a model dialog where the user is forced is restart ntopng. Until this happen all pages must report a big warning message saying that a restart is required as ntopng is inconsistent.

**Comment by simonemainardi** [comment]
check - and re-use - code in `menu.lua` Restart.

**Comment by gabryon99** [comment]
@simonemainardi I've added the code for the message. When the function `ntop.restartRequired()` is ready you have to remove the stub function (https://github.com/ntop/ntopng/commit/d10e2a56dadae1dfe7cae73a22df8941a9419ae6#diff-c1ed87acb1a3bb8ed2f0a5f2f84a39ed14603758ac3c9c2d868767e052db4d34R179 and https://github.com/ntop/ntopng/commit/d10e2a56dadae1dfe7cae73a22df8941a9419ae6#diff-c1ed87acb1a3bb8ed2f0a5f2f84a39ed14603758ac3c9c2d868767e052db4d34R179) and replace it with the call to the new function.

I've moved the restart code from `menu.lua` to `footer.lua` in order to reuse-it inside the new notification. If you require any details please send me a message. Thanks

**Comment by simonemainardi** [comment]
Please, change the following message which is shown after clicking on "Factory Reset" for "Entire ntopng configuration (includes users, preferences, and all configurations below)"

![image](https://user-images.githubusercontent.com/3397663/96692156-04ae2880-1386-11eb-80ca-80feaf5382c8.png)

The message should say "Factory reset request issued successfully. Restart %{product} to make the configuration factory reset effective."

**Comment by gabryon99** [comment]
The message body has been replaced as suggested.
