### ISSUE TITLE
Issues filter in Periodic Activities tab doesn't work

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#4621]
Without filters:
![Screenshot_20201023_100423](https://user-images.githubusercontent.com/14093378/96972793-402c2c80-1517-11eb-8e4c-c62411e75feb.png)

With "Issues" filter set to "Not Executed" or"Activities with Issues":
![Screenshot_20201023_100555](https://user-images.githubusercontent.com/14093378/96972882-6651cc80-1517-11eb-8872-1b6b9fb82d73.png)

Even if "Not Executed" column is populated for periodic_user_scripts.lua script.

Thanks...

**Comment by simonemainardi** [comment]
periodic activities shown don't have issues at the present time, so if you filter for issues you don't get results. Use historical alerts to see past issues for periodic activities

**Comment by gianogli** [comment]
@simonemainardi if periodic activities shown don't have issues then from the tab is not clear what is an issue and what not. In my opinion by reading the tab I can see a big issue related to the "periodic_user_scripts.lua" activity because it was **not executed** 10 times...
For this reason if I see in the Issues filter menu an entry "Not Executed" I expect to filter only the lines that have a value >=1 in the "Not Executed" column.

This is only my opinion...

Thanks anyway... :-)

**Comment by lucaderi** [comment]
@simonemainardi I think @gianogli was right actually. The way ntopng works is bugged

**Comment by simonemainardi** [comment]
@MatteoBiscosi please explain the fix you have done and also backported to stable.

**Comment by MatteoBiscosi** [comment]
Already fixed the issue into the stable, the issue was the following: the boolean that was checked periodically was resetted when the issue, e.g. "not executed", was instead executed, so even if you had some issue into the specific column, (e.g. 10 "not executed" like into @gianogli 's screenshot) were not filtered because they were "old" issues and the specific boolean was resetted. I fixed the filter, adding even "old" issues because users usually want to check even the old ones by filtering the specific column
