### ISSUE TITLE
lossing ntopng data on reboot or service restart

### ISSUE THREAD

**Issue by narankhetani** [ntop/ntopng#481]
Hello,

So it seems when the server restarts or the ntopng service is restarted all the collected flow data is reset on the UI, is there anyway for us to ensure its retained?

**Comment by simonemainardi** [comment]
hello @narankhetani 

ntopng keeps live flows directly in memory. Since flows are usually short lived entities, we didn't include any serialization mechanism to dump and reload _active_ flows on ntopng restart. Indeed, a flow that is currently active, will be very likely expired by the time you have rebooted the system. Hence, serialization would be of little help.

Serialization/deserialization is featured for hosts that are actually longer-lived entities. Indeed, counters and stats are dumped and reloaded back for every local host.

As a side note, please keep in mind that if you want to retain historical flow data you can dump _expired_ (not active) flows to MySQL / ES.

**Comment by narankhetani** [comment]
Hi @simonemainardi ,

Thanks for the information, however I would like to retain at least 30 days worth of data what would you suggest our data rate is about 2.9Gbps.

**Comment by simonemainardi** [comment]
I think yours is a very interesting problem to solve. To be honest I don't have a recipe to retain 30 day of flows generated at 2.9Gbps. I mean, even if you find a way to dump flows at that speed, search and indexing will become far too slow to be usable.

Just a couple of ideas that I would consider:
- An hadoop cluster with: kafka --> spark --> hbase / cassandra
- A Mysql cluster with a sharded database

**Comment by lucaderi** [comment]
@narankhetani We have plans to adapt the indexing system we have developed for n2disk from packets, to flows. It's months we're working at this. I personally do not believe in big data/big databases (just the idea of serialising in JSON and pushing data out in HTTP is insane per-se) as while they solve the problem, they introduce new problems due to the increased complexity of the system and the number of nodes you have to maintain (in essence you move the problem but do not solve it). In the past we have integrated in our tools indexes based on bitmap databases http://luca.ntop.org/Fastbit.pdf that were (on a single node) way better than any database/big data system. Now we're trying to revamp this idea and polish it a bit, but we need some time. For the time being the best option we can offer you is MySQL. This said: how many flows/sec do you need to store?

**Comment by simonemainardi** [comment]
Big data ecosystems have been designed with the aim of being very scalable horizontally. To scale horizontally you are forced to use well-known protocols in order to ensure maximum interoperability between heterogeneous systems. To me this is the reason behind the big-data engineers common choice of using JSON and HTTP.  We know that JSON is not the best format but it is becoming a de-facto standard. We also know that HTTP is not the best transfer protocol but it is the most widely used.

That said, I totally agree with @lucaderi: JSON over HTTP it's insanely prohibitive, unless you have enough budget to buy expensive HW and tons of RAM. I strongly believe that adapting the n2disk technology will make it possible to dump flows aggregated from multi-10-Gbps lines. This will happen on a single node with real-time indexing. I believe this adaptation has the potential to become the real first big-data technology in the niche of high-speed flow to disk.

**Comment by narankhetani** [comment]
Hi All,

Thanks for the thoughts I like the read of Fastbit, do you have any idea on
timelines?

**Comment by simonemainardi** [comment]
I think it is safe to close the issue as the main object has been addressed in the discussion.

Please follow up with @lucaderi if you are interested in Fastbit.
