### ISSUE TITLE
NTOP-NG MYSQL dump-flow

### ISSUE THREAD

**Issue by behzad-kh** [ntop/ntopng#4864]
Hi
I am assessing the NTOP-NG Professional edition for the billing (security report as an added value).
In my sanity check, I have a 10G file hosting on a web server (2.2.2.13) which is going to be downloaded from the client (10.10.13.1).
It worth mentioning the NTOP-NG is acting as a gateway between these two subnets (as inline-mode).
When I have download the 10G file, the "flows" section of the NTOP-NG shows around 10.5GB which is fine with me (header size included I believe). The image is https://ibb.co/QmgccSw
However as I want to use it as the billing software, I need the historical data of flows.
I have installed mysql on the same machine running nTOP-NG and have configured the ntopng.conf with the following directive
--dump-flows "mysql;127.0.0.1;ntopng;flows;ntopng;PASSWORD"
the data is being inserted in MYSQL as I have check the ntopng database with flowsv4 as the table.
the problem when I am using the trial (10 minutes) edition of Professional L, it shows only 6.5 GB of data for the 10.10.13.1 client where it is 10G (10.5GB of bandwidth usage).
I wonder if someone can help me sort this problem out.
The link for historical data:
https://ibb.co/p0dbKHG

**Comment by simonemainardi** [comment]
The 10GB transfer shown is a long-lived flow, i.e., it has been active for 17+ minutes

![image](https://user-images.githubusercontent.com/3397663/103199638-8a50d600-48eb-11eb-807e-95f52231c5d0.png)

ntopng dumps long-lived flows periodically (say every X seconds), so it is normal if you see the historical dump lagging a bit behind the live data. Just allow some time, let the flow expire (i.e., disappear from the ntopng active flows UI), and the flow will end up in the mysql database entirely.

**Comment by behzad-kh** [comment]
Hi thanks for your respond.
As I have check after a while I have notice that when I have download the 3GB file size the historical data just shows the exact number in the Flows table.
However when I am trying to download 4GB file size, the historical data shows an incorrect data even after 1 hour left.
following is the image proof the matter.
3GB file size flow:
![image](https://user-images.githubusercontent.com/24776390/103352653-0863d700-4abc-11eb-8e2f-f86788d14db2.png)
3GB file historical table:
![3G_historical](https://user-images.githubusercontent.com/24776390/103352678-20d3f180-4abc-11eb-9039-08513fa527f9.jpg)
4GB file Flow:
![4G_flow](https://user-images.githubusercontent.com/24776390/103352686-2af5f000-4abc-11eb-9945-855ebdf30134.jpg)
4GB historical table: (the problem)
![4G_historical](https://user-images.githubusercontent.com/24776390/103352848-9b9d0c80-4abc-11eb-92c0-f16b30f42146.jpg)
Another view of 4GB file size historical table:
![4G_historical2](https://user-images.githubusercontent.com/24776390/103352857-9fc92a00-4abc-11eb-8dbe-a19bd14ee161.jpg)
any help is much appreciated.

**Comment by simonemainardi** [comment]
please, give us exact commands and ntopng configuration used so we can reproduce in our lab

**Comment by behzad-kh** [comment]
Hi @simonemainardi 
I would like to thank you for the support.
Following is the configuration images:
the network topology:
![net_diagram](https://user-images.githubusercontent.com/24776390/103436992-328dd400-4c37-11eb-96a0-17ffe9eda38a.png)
NTOP-NG configuration:
![ntopng conf](https://user-images.githubusercontent.com/24776390/103437012-67019000-4c37-11eb-91c3-7bb8e76c07b1.png)
The Mysql tables:
![mysql-tables](https://user-images.githubusercontent.com/24776390/103437016-754fac00-4c37-11eb-8da9-1990233cfac3.png)
The mysql connectivity from NTOPNG:
![mysql_connectivity](https://user-images.githubusercontent.com/24776390/103437025-80a2d780-4c37-11eb-80cd-cafa14ee6e51.png)
NTOP-NG version: (up-to-dated version as of today)
![NTOP_VERSION](https://user-images.githubusercontent.com/24776390/103437028-8d273000-4c37-11eb-8197-9fad3d63e7d7.png)
OS version:
![OS_VERSION](https://user-images.githubusercontent.com/24776390/103437030-91ebe400-4c37-11eb-8ed5-af7534dbe63e.png)
The web server side (how the 3GB/4GB file is being created):
![WEB_SERVER_FILES](https://user-images.githubusercontent.com/24776390/103437005-53562980-4c37-11eb-9c66-4dc122419678.png)
Restarting the NTOP-NG use the 10 minutes trial version:
![ntopng restart](https://user-images.githubusercontent.com/24776390/103437046-bba50b00-4c37-11eb-8ba0-6d9353f9ed77.png)
3GB file download from client:
![3G client_download](https://user-images.githubusercontent.com/24776390/103437051-c65fa000-4c37-11eb-8d30-05079a6c2465.png)
3GB live flow:
![3G_flow_data](https://user-images.githubusercontent.com/24776390/103437053-ce1f4480-4c37-11eb-8e61-d34a3e13e1b9.png)
3GB historical data:
![3g_historical_data](https://user-images.githubusercontent.com/24776390/103437054-d4adbc00-4c37-11eb-93b3-9a491786e838.png)
![3g_historical_data_2](https://user-images.githubusercontent.com/24776390/103437055-d7101600-4c37-11eb-8f6f-96ffc6f3d18a.png)
4GB file download from client:
![4g_client](https://user-images.githubusercontent.com/24776390/103437063-e3946e80-4c37-11eb-8356-b6dbdc2f76ea.png)
4GB live flow data:
![4g_flow](https://user-images.githubusercontent.com/24776390/103437066-eb541300-4c37-11eb-88e6-5f039c91f0ad.png)
4GB historical data:
![4g_historical_data](https://user-images.githubusercontent.com/24776390/103437069-f3ac4e00-4c37-11eb-8bc5-ab0ba6a0c7b5.png)
![4g_historical_data_2](https://user-images.githubusercontent.com/24776390/103437070-f73fd500-4c37-11eb-9703-79b37f984d4d.png)
thanks for the support.

**Comment by behzad-kh** [comment]
anyone?!

**Comment by simonemainardi** [comment]
All the tests run have completed successfully. Long-lived flows are dumped properly, even if divided into multiple 5-minute long parts. Tests run involved large SSH file transfers, TLS and HTTP download.

Here's an example that you can reproduce as

```
curl  --limit-rate 2m "http://releases.ubuntu.com/20.04.1/ubuntu-20.04.1-live-server-amd64.iso" > /dev/null
```

As you can see from the image, the flow takes more than 5 minutes to complete, so it is cut into two flows, but the overall traffic total matches the actual volume of traffic exchanged.

![image](https://user-images.githubusercontent.com/3397663/103538931-6d8e4280-4e97-11eb-812c-d975c0636121.png)


My guess is that you are not looking at the right flow, that is, you are running a live flow download, then stop it, restart it, look into the database and think that A is actually B. I am arguing this as you are running ntopng in demo mode within 10 minutes, and timestamp make me believe this.

Another issue that could have happened is the following:
1. You've started the download
2. After a while, the download stalled (either the network was too slow, the HTTP server was temporarily blocked from sending the file, or some other reason)
3. ntopng did not see any packet for that flow, considered it idle, dumped it, and removed if from the internal cache
4. The download stalled in 2. restarts but, as the TCP session was already in place, the initial URL wasn't exchanged and the TCP three way handshake was not performed again. So ntopng created a brand new flow.
5. The download finished and ntopng dumped the brand new flow created in 4. without the the initial URL.
6. You used the URL to query for historical flows so you only get a match for the initial part.

To verify my second hypothesis you can use the historical data explorer and query using the IP address rather than the info field (and still wait 2-3 minutes from the moment when the flow is no longer listed under the active flows page). Also make sure to start and work clean:

- Drop mysql database
- Start ntopng with option `-B "host x.y.z.w"`, where x.y.z.w is the ip address of the web server
- Restart the download

**Comment by simonemainardi** [comment]
any news?

**Comment by simonemainardi** [comment]
Any news?

**Comment by behzad-kh** [comment]
sorry for the late response.
I have test the scenario over and over, (I have even update the ntopng to the latest version right now), but still no progress.
I have started the ntopng using the following parameters:
 ntopng -B "host 2.2.2.13" --dump-flows "mysql;10.10.13.79;ntopng;flows;root;PASSWORD"
however, it shows wrong information when downloading file more than 3GB.
As you have lab it up, you have download the iso file which is around 1GB. My problem is when downloading file more than 3GB which in my case is 4GB file.
As you have said, I have dropped the databases and restart the ntop-ng to recreate a new one, but still no change.
your help is VERY much appreciated.

**Comment by behzad-kh** [comment]
I have also use the historical data with the client IP address rather than the URL, but still same result is shown.

**Comment by behzad-kh** [comment]
here is the dump taken from the Mysql:
![image](https://user-images.githubusercontent.com/24776390/105139033-f7cadd80-5b0a-11eb-83f6-0f7a0b2dcce5.png)

Another note that the from number of packets that is being exchanged, if we assume each packet includes 1500 bytes MTU, we can conclude the followings:
2372601x1500=3,558,901,500 ==> for the 3GB file which with headers is around 3.2 GB which is correct.
3166441x1500=4,749,661,500 ==> which is for 4GB file which is correct when calculating the packets numbers.

**Comment by behzad-kh** [comment]
here is the ntopng database dump file attached.
[ntopng.zip](https://github.com/ntop/ntopng/files/5840701/ntopng.zip)

**Comment by cardigliano** [comment]
@behzad-kh I pushed a fix for this (it was related to the bytes column size), a new stable package will be available later today. However since this requires a new table schema, after the update I recommend to stop ntopng, remove your current tables from the db (I guess this is possible as you are still in the evaluation phase, otherwise please let me know), restart ntopng to let it create new tables with the right column size.

**Comment by behzad-kh** [comment]
thank you very much @cardigliano 
I will update and keep you updated with the end result.

**Comment by behzad-kh** [comment]
@cardigliano 
I have tested the scenario one more time and it is working correctly.
another question, what is the maximum byte column size that it can hold?
as you have said earlier, the issue was the column size. It is good to know the current maximum byte column size.

**Comment by cardigliano** [comment]
It's a 64-bit number now, you will not hit a limit again :-)
