### ISSUE TITLE
past alert filter showing unknown alarms

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4918]
Hi
In the current dev version I have "unknown" alarms in the past alert filter drop down: 
<img width="327" alt="Screenshot 2021-01-16 at 14 40 25" src="https://user-images.githubusercontent.com/38549755/104813370-0ebab880-5809-11eb-8857-41f22e34e22f.png">

(I guess this is due to recent adaptions in the alarm / notification part)
most of them are past alarms I can delete, but some still pop up now.
no user plugin activated.

**Comment by simonemainardi** [comment]
Are those "Unknown" guys connected to custom scripts you have developed?

**Comment by simonemainardi** [comment]
@MatteoBiscosi try to reproduce. Add a custom flow alert using `user` alert keys. Then store an HOST alert. Finally, check in the PAST alerts tab (not flows, PAST).

**Comment by martinscheu** [comment]
I had custom scripts, but they crashed with the new alarm concept :-) now is ntop standard, no user / custom scripts from myself, but still unknown alarms arrive. @MatteoBiscosi please contact me on telegram if you need further details. thank you

**Comment by simonemainardi** [comment]
@martinscheu hover the mouse on one of the Unkown alerts. Then, please paste the hyperlnk, e.g., `http://192.168.2.183:3000/lua/system_stats.lua?status=historical&page=alerts&alert_type=53`. We are interested in the numberical `alert_type` id.

Then visit page

![image](https://user-images.githubusercontent.com/3397663/105021584-fa64fe80-5a48-11eb-96c4-d447617dcf68.png)


And look for the integer id in the Alert Key column.

**Comment by simonemainardi** [comment]
@martinscheu please report. Then @MatteoBiscosi can help you in migrating the custom scripts you have.

**Comment by martinscheu** [comment]
I have alert_type=47, 26 and 11. But last entry is form 08.01. and no new entry. it might be that the operators deleted the events. 
But maybe you can check anyway and I will purge old unknown alerts.
thanks

**Comment by MatteoBiscosi** [comment]
Those three alert_types are non longer used, some new alert_types where added and replaced those alert_types for clarity purposes, so you can delete those alerts without problem.

If you want to migrate the custom scripts you had to the new alert, you can do that following the "new_api_demo"; it is under the directory "scripts/plugins/alerts/security/new_api_demo".
If your plugin was a flow alert you need to migrate the alert definition you previously had to the new "alert_definitions/alert_flow_new_api_demo.lua" format, otherwise if it was an host alert follow "alert_definitions/alert_host_new_api_demo.lua".
After that you need to migrate the "user_scripts"; like before, if it was a flow alert follow "user_scripts/flow/new_flow_api_demo.lua", otherwise follow "user_scripts/host/new_api_demo.lua".
Regarding the host alert, the "set_attacker()" and "set_victim()" methods are optional.

For any question don't hesitate to ask.

**Comment by martinscheu** [comment]
thanks for clarification.
