### ISSUE TITLE
Add the ability to suppress specific alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4942]
Some flow alerts are not relevant for specific hosts. For instance a "Obsolete TLS cipher" for an old device that cannot be upgraded can be safely ignored. 

This ticket is to request the implementation of a whitelist for specific alerts for a specific host (either source or destination). In this case such alert will be
- logged with severity info or not logged at all (whatever is doable)
- the host/flow score will not be increased, or it can be shown as non zero value but not accounted (whatever is doable)

This means that
- in the alert window a new icon for adding the exception
- add a new page with exceptions for adding/deleting/modifying them

**Comment by simonemainardi** [comment]
Currently, the concept of "alerts are not relevant for specific hosts" is implemented with pools and script configurations that are associated to pools. So I am not sure how to add this without duplicating what we currently have. I think we should talk together and decide.

**Comment by netsolv** [comment]
My thoughts aren't directly associated with "alerts are not relevant for specific hosts", but more SITE specific. ie: All Windows hosts on a network segment are going to download.windowsupdate.com or officecdn.microsoft.com, the ability to "whitelist or ignore" specific url/domains for specific "scripts or subnets" would be helpful in drilling past false-positives for known network traffic.

**Comment by simonemainardi** [comment]
Aim is to implement exclusion filters for user scripts. We start with flow user scripts. Note that exclusion lists are for user scripts, not alerts. With these exclusion lists, we decide when/when not to execute user scripts.

Filters, used to implement exclusions, are defined in `user_scripts.lua` - see referenced commit - and possibly overridden in the metadata of each user script.

**Backend**

- `user_scripts.getScriptConfig()`: returns also the filters - if set - or nil otherwise
- `user_scripts.updateScriptConfig()`: extended to implement the ability to receive filters
- `user_scripts.getFilterPreset(script_key, subdir, filter)`: return a filter, given the params. Example: `user_scripts.getFilterPreset("blacklisted", "flow", {srv.ip = "1.2.3.4"})` will
  - Check for the validity of submitted filter keys and values according to what is specified in `default_fields`
  - Return the filter (if valid) as a concatenated string with table.tconcat or nil

- `user_scripts.validateScriptFilter(script_key, subdir, filter)` will use the default values to verify the correctness of the filter and will always be called before saving a filter in a configuration
- in scripts/callbacks/interface/flow.lua, before calling the hook, the configuration will be checked: if filters exists, filters will be checked against the current flow for exclusion.


-------------

**UI**

- Add an extra Action in 

![image](https://user-images.githubusercontent.com/3397663/107007518-ecc2af00-6792-11eb-816d-a82caf665081.png)

use user_scripts.getFilterPreset (called with current alert row data) to create a modal with a single input text box populated with default user_scripts.getFilterPreset values. Example

![image](https://user-images.githubusercontent.com/3397663/107007914-707c9b80-6793-11eb-86b0-14e93e71f54b.png)

To create modals with input text boxes see the modal that opens when creating a sub-interface.

- create a rest endpoint `scripts/lua/rest/v1/edit/user_script/filter.lua` called when clicking submit on the modal. Again see The modal that creates sub-interfaces to handle AJAX requests/responses. This endpoint will call `user_scripts.updateScriptConfig()` to add the filter.

- Add an extra input text after the severity in each user script configuration

![image](https://user-images.githubusercontent.com/3397663/107008643-5099a780-6794-11eb-8e7f-5196e3bc0119.png)

The input will contain the exclusion filter saved, one per line, example

![image](https://user-images.githubusercontent.com/3397663/107008880-948cac80-6794-11eb-8193-c6c450b274c4.png)

To handle one-per-line elements, see the implementation of custom application and categories.

**Comment by simonemainardi** [comment]
Migrate the `items` of elephant flows as l7_cat, as follows

![image](https://user-images.githubusercontent.com/3397663/108045629-f7f3c580-7043-11eb-8c83-b6d0143d1957.png)

**Comment by simonemainardi** [comment]
same for long lived

**Comment by simonemainardi** [comment]
Note that default_filters are populated when the configuration is created for the first time as not existing. Then, the user can modify this as he wants.

Also make sure the reset correctly restores the exclusion list

![image](https://user-images.githubusercontent.com/3397663/108045974-620c6a80-7044-11eb-8dfc-41e3af4d7def.png)

**Comment by simonemainardi** [comment]
For the DNS invalid query this is the expected result (current exclusion list on bold will disappear)


![image](https://user-images.githubusercontent.com/3397663/108047759-73ef0d00-7046-11eb-947e-f2a687cb5647.png)

Default becomes

![image](https://user-images.githubusercontent.com/3397663/108047889-a26ce800-7046-11eb-99d3-3aeb97341c8f.png)

**Comment by simonemainardi** [comment]
for the l7 categories, these are the functions to convert ids to names and vice versa

```
interface.getnDPICategoryName(matched_category)
interface.getnDPICategoryId(value)
```
