### ISSUE TITLE
Avoid multiple flow score increments

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4993]
For long lasting flows, the flow score is incremented periodically and thus it creates two problems:
- it is not clear from the screenshot below the discrepancy between the issue detected and the flow score
- long-lasting flows with tiny issues will become big over time

![Screen Shot 2021-01-29 at 16 51 18](https://user-images.githubusercontent.com/4493366/106296644-3b7fbe80-6252-11eb-8ec8-c9db401236c0.png)

It is requested to avoid incrementing multiple times the flow score over the same issue.

**Comment by simonemainardi** [comment]
There are statuses for which it is important to increase the score multiple times (e.g., security-related statuses). This makes it possible to let the score increase with time or with multiple calls.

There are other statuses like the one you have attached that are network based and for which it is pointless to do multiple score increases. Indeed, the one shown is just an harmless long-lived flow that has an high score just because it is long lived.

So I have added an extra param in the alert definition that allows to specify this behavior. Default behavior does not increase the score multiple times. I have let security-based alerts to keep increasing score multiple times, and network-based alerts only one time.

Referenced commit contains comments, explanation, and examples.

**Comment by lucaderi** [comment]
Not fixed as requested

**Comment by simonemainardi** [comment]
Removed multiple increases for zero window and IEC as discussed.
