### ISSUE TITLE
Implement UI templates for User Scripts Configuration

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5002]
Currently, user script configurations don't have UI templates. It is requested to implement them similar to what has been done with recipients and endpoints.

**Comment by gabryon99** [comment]
We decided to create a new page for the configuration of a user script. When a user clicks the edit button of a user script, he will be redirected to the **Edit Page**.

**Backend**
For the backend is requested to create an API to load the filename of the template associated with the user script and the loading of the current values, in order to render it inside the page.

**Frontend**
For the frontend is requested to create the base page with the commons field and the current functionalities that are inside the old user script edit modal.

Here is a summary image:
<img width="1299" alt="Screenshot 2021-02-17 at 19 13 33" src="https://user-images.githubusercontent.com/14114916/108248509-3c6e8680-7154-11eb-81e1-9d3b3101bec9.png">

**Comment by lucaderi** [comment]
This ticket is put on hold until the backend is cleaned-up

**Comment by lucaderi** [comment]
@simonemainardi believes this ticket is now handled in the current template implementation
