### ISSUE TITLE
Importing entire configuration does not import all

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5083]
Hello
When restoring an entire configuration on pool recipients only hosts are imported, others (e.g. flows, host pool) do not get the exported recipient configuration.
thanks.

**Comment by martinscheu** [comment]
Hi Alfredo (@cardigliano )
I realised that from the user scripts, e.g. rogue DNS/NTP/DHCP Server it was not imported neither.
From runtime preferences, e.g. traffic behaviour, I am not sure if that is exported, but is not imported neither.
Thanks, Martin

**Comment by cardigliano** [comment]
@martinscheu both have been addressed, please check latest package and let me know. Thank you.

**Comment by lucaderi** [comment]
![Screen Shot 2021-03-05 at 21 13 52](https://user-images.githubusercontent.com/4493366/110168740-e3f7e400-7df7-11eb-99f6-9a872220fed9.png)

@cardigliano The whole export is partial only a small part is export. Example
{"version":"1.0","modules":{"all":{"ntopng.prefs.default_l7_policy":"00C000090048B2F6B4ACD660B9","ntopng.prefs.intf_rrd_1h_days"...

**Comment by cardigliano** [comment]
The full configuration export and import seems to be working, however please note a ntopng restart is required after importing the configuration to make it effective. A message has been added on import in e86fffcc58911a0c15589d2625eab197d4d47ad9

**Comment by cardigliano** [comment]
@martinscheu the problem with the pools import was due to the fact that ntopng was not importing the configuration for entries already present (this is the case for flows and host pool as they have the default configuration only, nad that was always present), this has been improved by allowing a "merge" of the configuration, which is now importing recipients (and other items) even if the configuration already exists.
As of the "Entire ntopng configuration", please note a restart is required after importing the configuration to make it effective (we added a message now to make it clear), did you try with a restart? Thank you.

**Comment by cardigliano** [comment]
@martinscheu I think I realized what happened to your configuration: I guess it has been exported weeks ago with an older ntopng (dev) version, and you tried to load it with the latest version. The (internal) configuration format has been changed (from v2 to v3) and there was no migration implemented yet. Now ntopng is able to automatically migrate v2 to v3, however since you already created a v3 configuration now, in order to migrate you need to remove the new one and restart ntopng. Instructions:

1. stop ntopng (after importing the old configuration, I guess you already did this)
2. run "redis-cli del ntopng.prefs.user_scripts.configset_v3"
3. start ntopng

**Comment by martinscheu** [comment]
Hi @cardigliano, I exported the config on the 26.02 and imported it on the 03.05. We did all missing changes manually, but thanks for implementing the migration features, other users might run into as well. (Specially when doing setup, then backup and then after long time the backup is needed)
(and yes, restart is all the time the first check if something doen't work.)
Thank you.
