### ISSUE TITLE
Empty exporters page 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5095]
When uBlock is activated in Chrome
https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

the Exporters page (you need to configure ntopng as flow collector via ZMQ) does not render.

**Comment by simonemainardi** [comment]
@MatteoBiscosi please comment why the referenced commit addresses this.

**Comment by gabryon99** [comment]
The Exporters Page didn't render due to the uBlock Plugin that blocks the HTTP request of javascript files that contains specific tokens viewed as ads provider (in our case the file `flowdevices_stats.js` was including the `stats` string in its name). Now the file has been renamed and the problem is gone.

The commit description of https://github.com/ntop/ntopng/commit/6580aa2ac41ba2fe9e55e05bcb792496be5f010e is a bit ambiguous.
