### ISSUE TITLE
How to use shell scripts notification in ntopng 4.3?

### ISSUE THREAD

**Issue by zcy382725** [ntop/ntopng#5102]
I'vd added a shell script in /usr/share/ntopng/scripts/shell/ dir to test the shell notification funcation.
My shell script's logic is like this: ./xxx.sh $1 to send $1 to notification channel.
But it seems not working well. 
I've checked the guide from https://www.ntop.org/guides/ntopng/alerts/available_recipients.html#shell-script 
It's really simple. how do i get  the correct alert body and pass it to shell script?

**Comment by cardigliano** [comment]
Shell script support has been improved in fa723f72aa9a475b140235d2a9a93cbbe981a073 (a new dev package should be already available). The documentation has also been updated https://www.ntop.org/guides/ntopng/alerts/available_recipients.html#shell-script.
In short, I suggest to leave the Options field empty in the recipient configuration, this will provide the full alert in JSON format as stdin to the script, instead of providing selected fields as argument.
Simple script example, logging alerts to file:

#!/bin/bash
cat - >> /tmp/shell-script.log

**Comment by zcy382725** [comment]
thanks @cardigliano that's exactly what i need
