### ISSUE TITLE
[startup.lua:176] [lists_utils.lua:511] WARNING Bad domain name 'https' in list 'Abuse.ch URLhaus'

### ISSUE THREAD

**Issue by antonakv** [ntop/ntopng#5112]
There is some typo:
[startup.lua:176] [lists_utils.lua:511] WARNING Bad domain name 'https' in list 'Abuse.ch URLhaus'

--
Version | ntopng Enterprise M v.4.3.210315 (Raspbian GNU/Linux 10 (buster)) \|
nDPI | 3.5.0-3039-b22cb70a

**Comment by lucaderi** [comment]
At line 456 of the Abuse.ch URLhaus.txt file there is an invalid entry (so the problem is of abuse.ch not ntop) and then the issue. We have added a more explicit warning (https://github.com/ntop/ntopng/commit/146a4b8c9a36b3a9c9bc483994cf3549db93a445) to ease the process of locating the invalid line 


127.0.0.1       htownbars.com
127.0.0.1       https
127.0.0.1       hub.matinal-nominal.pt
