### ISSUE TITLE
Feature request: export of configuration

### ISSUE THREAD

**Issue by lucadistefano** [ntop/ntopng#513]
save all ntopng configuration options and profiles to a text file use /etc/ntopng/ntopng.conf for store all of them.

**Comment by emanuele-f** [comment]
The export of redis configuration is related to the management of ntopng itself, which is something out of the scope of ntopng itself.
This kind of feature should be implemented into a product like nBox, since it requires both ntopng and redis to be stopped to properly read and dump the configuration to a separate file.
