### ISSUE TITLE
Warning during callback load

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5165]
11/Apr/2021 18:49:09 [HostCallbacksLoader.cpp:159] WARNING: Unable to find host callback bytes

**Comment by simonemainardi** [comment]
Then warning was initially hidden and was enabled only for debug purposes.

It basically means there was a callback `bytes` for hosts that no longer exists but its configuration still exists in the JSON configuration file.

This happens for all host callbacks that were present and then are removed. Many of them have been removed due to the recent rework so I would expect the warning to show up, until at least the JSON is cleared with a configuration reset. Anyway, having them is harmless and I suggest to change this warning to a debug message.
