### ISSUE TITLE
Slowdowns with no Internet Access

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5167]
When the host where ntopng is installed has no Internet access (e.g. in a datacenter disconnected from the Internet) the user interface is sluggish as apparently periodically ntopng connects to the Internet, not to mention that the initial list download fails and takes quite some time to startup. This needs to be fixed.

**Comment by simonemainardi** [comment]
Issues seems to be due to slow slow dns resolution, kicked in when using curl. Setting seems to be then env variable `RES_TIMEOUT` that affects this and prevents curl from immediately figuring out there's no internet connection.

I think we could do a short check upon startup to detect if ntopng is running on a system with or without internet, and prevent certain operations from being performed.

**Comment by lucaderi** [comment]
How do you mitigate this in the GUI? Will you prevent from talking with remote sites (e.g. version.ntop.org) too? Please see the hosts we currently contact https://www.ntop.org/support/faq/are-ntop-products-privacy-compliant-do-you-send-data-to-the-cloud-or-third-party/

**Comment by cardigliano** [comment]
Offline mode implemented in af5ded3231d35d6b262e9f065254d81a2d9d8223 15a2a3477148b763fd8860b6a8381deafdeac962 bb297048c78f8664205833bb82add05bc5d33dad b8dcca7fdb8be43d6fb5c50969e9c425c370ecb7
ntopng detects that there is no connection at boot time, switching to offline mode. In offline mode it checks for connectivity every hour. Features like the lists downloading, post updates, telemetry, are disabled in offline mode. 
A plane icon in the header indicated that ntopng is running offline.
