### ISSUE TITLE
Regression: Automatic update does not work

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5241]
As already discussed, automatic updates sometime work, sometime do not work. This is Ubuntu 18.04 LTS tonight
![Screenshot 2021-04-28 at 08 37 08](https://user-images.githubusercontent.com/4493366/116357666-06f1b380-a7fd-11eb-8f1f-aaa2c210f09f.png)
![Screenshot 2021-04-28 at 08 36 56](https://user-images.githubusercontent.com/4493366/116357671-078a4a00-a7fd-11eb-8723-b2eac361a486.png)

**Comment by lucaderi** [comment]
Doing a manual update the installation worked. ntopng did not realise it and it still proposes the package just instal
<img width="1332" alt="Screenshot 2021-04-28 at 10 30 24" src="https://user-images.githubusercontent.com/4493366/116372627-e7628700-a80c-11eb-9158-1466956aada3.png">
led

**Comment by cardigliano** [comment]
I was able to repruduce the update failure, it was due to a missing dependency in other repo which were not updated by our script, fixed in d2bce17c7acaf534b77a50f63d633464e760c981
The GUI issue about the update proposal at the same version after a manual update has been fixed in 28fd3b3516dfd0dba8e2be1a693327d410183ee0

**Comment by cardigliano** [comment]
Logging has also been enabled in b2a6ff60f9306dc7d898b7dd83e72a62a551a457 
Please reopen if experience this again
