### ISSUE TITLE
InfluxDB monitor (or RRD )

### ISSUE THREAD

**Issue by astalush** [ntop/ntopng#5318]
Hy. I cannot seem to find the page where you can see the size of the influxDB database or RRD database. It seems that the script for influxdb monitor is active but it doesn't work. The influxdb is configured and it works but cannot see size. Thanks.

ntopng Enterprise L v.4.3.210511

![image](https://user-images.githubusercontent.com/8401863/117795149-30bfc700-b24e-11eb-8197-50f2e215eace.png)

**Comment by ListenNjoy** [comment]
Same here 
ntopng Enterprise M v.4.3.210511

**Comment by MatteoBiscosi** [comment]
Hi @astalush , thanks for the report, now it's working correctly.
![Screenshot from 2021-05-12 12-59-52](https://user-images.githubusercontent.com/49585191/117964676-2c64de00-b322-11eb-8d58-8fcd172873c6.png)
Now you should be able to see Redis and InfluxDB monitor into the Health submenù (previously they weren't working correctly); new builds are in progress, wait for a few hours, upgrade and the problem is going to be fixed.

**Comment by astalush** [comment]
Version ntopng-data-4.3.210512-13521 
Still now showing : 
![image](https://user-images.githubusercontent.com/8401863/117971727-89649200-b32a-11eb-8a25-2a1b9d0b1eeb.png)


But I've edited myself the two menu.lua from here : https://github.com/ntop/ntopng/commit/323ab56282a8cf6e7040d753dc785a1032e0e2bb and it works.

Thanks!
