### ISSUE TITLE
Unify Button Style

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5330]
With the new alert implementation, a new "white" button style has been introduced. 

![Screen Shot 2021-05-14 at 21 46 36](https://user-images.githubusercontent.com/4493366/118321460-e8c6cb80-b4fd-11eb-890a-f96315d56a7a.png)

This ticket is to request to unify the style of all the other buttons similar to the one above

![Screen Shot 2021-05-14 at 21 46 25](https://user-images.githubusercontent.com/4493366/118321465-e95f6200-b4fd-11eb-8b43-620bc5d567c9.png)

**Comment by simonemainardi** [comment]
The rationale behind the new style I have introduced with the new alert implementation is that a grey badge with a counter is shown on the engaged alerts button. As the badge style is grey, having a grey-badge-on-a-grey-button resulted in unreadable badges. If you prefer to change the badge style and not the button style, please, update badges rather than buttons.

**Comment by simonemainardi** [comment]
example of what it would like with the 'old' style

![image](https://user-images.githubusercontent.com/3397663/120290456-a4d81280-c2c2-11eb-8840-cb8bf0e5eacb.png)

**Comment by lucaderi** [comment]
Whatever you decide to do has to be consistent across all pages. Two styes for the same object is confusing IMHO

**Comment by simonemainardi** [comment]
Style unified

![image](https://user-images.githubusercontent.com/3397663/121021266-803bd900-c7a1-11eb-8168-1e971c0e66e8.png)
