### ISSUE TITLE
Inconsistent Host Alert Score

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5337]
![image](https://user-images.githubusercontent.com/4493366/118358112-a2b14c80-b57d-11eb-9bac-1383a822ebbe.png)

In the picture above it is unclear why 
- hosts with the same problem have different score
- the attacker/victim column is not populated based on the client or server flow score (see #5302)

**Comment by simonemainardi** [comment]
According to the implementation https://github.com/ntop/ntopng/blob/dev/src/host_callbacks/FlowAnomaly.cpp, a flow anomaly can be

- as client
- as server
- both

When anomalies are both as client and as server, the score is x2. This should be made more clear in the UI.

**Comment by lucaderi** [comment]
Until  #5302 is fixed this ticket cannot be reviewed

**Comment by simonemainardi** [comment]
linked ticket is now closed so this can be reviewed.

**Comment by simonemainardi** [comment]
This will be completed after https://github.com/ntop/nDPI/issues/1190

**Comment by simonemainardi** [comment]
message is more clear now

![image](https://user-images.githubusercontent.com/3397663/120011034-23406600-bfde-11eb-915c-ee8db78192c2.png)

will also handle attacker/victim.

**Comment by simonemainardi** [comment]
Attacker/victims handled and completed as well (see https://github.com/ntop/ntopng/commit/9453fca4cb7bde52c37ddf956090c2ae02adb331).

Attacker/victim columns have been removed as already agreed for flows for the sake of space. They are shown as clickable symbols as 

![image](https://user-images.githubusercontent.com/3397663/120171831-bce85d00-c202-11eb-9a95-79ce6294bad0.png)

This allows to show longer descriptions. Also note that now, the message explains that the score 100 is due to the host having both a client and a server anomaly.
