### ISSUE TITLE
Interface dropdown to only show name

### ISSUE THREAD

**Issue by fanciulli** [ntop/ntopng#5505]
As an improvement it would be nice if interfaces can be listed only by names. Longer names are cut. A toggle in the settings (to activate it) can be ok.

<img width="213" alt="Screenshot 2021-06-14 at 17 20 58" src="https://user-images.githubusercontent.com/356041/121917379-58b2b680-cd35-11eb-8a9c-07f2b949f6b1.png">

**Comment by MatteoBiscosi** [comment]
Hi @fanciulli, as requested a new preference can be found into 'Settings->Preferences->User Interface'. If enabled you are going to see just the names of the interfaces (screenshot below). Otherwise you are going to have the interface dropdown names like before ( "Name (tcp://...)" ).
![Screenshot from 2021-08-26 11-56-24](https://user-images.githubusercontent.com/49585191/130942921-7afd3820-742a-4298-8431-acbbf0195793.png)
