### ISSUE TITLE
No Logout Button - unprivileged user

### ISSUE THREAD

**Issue by astalush** [ntop/ntopng#5515]
Hy. Where can I find the logout button?

Using LDAP AUTH I have the logout button when I log in with a user found in LDAP Admin Group

But when I login with a user found in LDAP User Group I cannot find the logout button. 
Bug or not?
![image](https://user-images.githubusercontent.com/8401863/122398584-4f665b80-cf7a-11eb-8064-3e9ad3acf58a.png)

And for non privileged user logged via LDAP I can't see the "Allowed Interface" setting so the user cannot select the interface he wants. If I create a non privileged user via web GUI (and not LDAP login) I have the option.
![image](https://user-images.githubusercontent.com/8401863/122399789-68bbd780-cf7b-11eb-8f16-bd6992763292.png)

**Comment by astalush** [comment]
Hy VasilisTako . Thank you for the intervention. I've just updated NTOPNG and NPROBE and tested the LDAP login with "Non Privileged User". I now have the logout button and this "Non Privileged User" has access to all interfaces. Thank you very much. BUT I do have another question / demand : this "Non Privileged User" cannot access the menu "POLLERS ->> INFRASTRUCTURE" where I entered all my ntopng instances for a faster access. It's possible to add a shortcut for "ADMINS" and "Non Privileged User" to that menu for a faster access? Thanks.
![image](https://user-images.githubusercontent.com/8401863/123434138-73561c80-d5cc-11eb-84f4-9a69cb48bdad.png)

**Comment by simonemainardi** [comment]
@astalush infrastructure is currently accessible only to ADMINS.

> And for non privileged user logged via LDAP I can't see the "Allowed Interface" setting so the user cannot select the interface he wants. 

Non-admins logged in remotely, i.e., with a Radius or LDAP account, don't have an allowed interface by design as this would require reading the allowed interface from LDAP or Radius. Currently, we are focused on giving priority to other activities that are beneficial for a larger number of ntopng users. If interested in having this feature, please contact us privately and we will discuss a custom development.
