### ISSUE TITLE
{Score,Flow} Anomaly Alerts - Anomalous Values

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5548]
All my score alerts are always 1 above the expected range. I am no sure this can be due to pure chance:

![image](https://user-images.githubusercontent.com/3397663/122791277-60380980-d2b9-11eb-81ed-11eb7ad1ee6a.png)

![image](https://user-images.githubusercontent.com/3397663/122791542-9a091000-d2b9-11eb-8cd5-6fcfa4059e05.png)

How is the expected range calculated? A README or a link to some documentation would be beneficial.

Same for flow anomaly alerts

**Comment by MatteoBiscosi** [comment]
As explained in the documentation I added, these values are calculated by nDPI using SES, DES and TES algorithms so probably there are some approximation that cast float/double to integers (you cannot have decimals for score or traffic) and this causes your case above of having for instance 149 instead of 150 but this is it's normal behavior

**Comment by simonemainardi** [comment]
Thanks for adding the documentation. However, this doesn't respond to the original issue

> All my score alerts are always 1 above the expected range

**Comment by MatteoBiscosi** [comment]
I did some fix and as you can see from the screenshots below, you should have anymore the "problem". It could still come out if you quit ntopng and reopen multiple times, because to work correctly it should have enough time to learn the "behavior", so it is not a bug but it is just that the algorithm did not have enough time to learn the "right behavior" of the hosts 
![Screenshot from 2021-06-28 11-42-25](https://user-images.githubusercontent.com/49585191/123616225-5e64cd80-d806-11eb-962f-25951091b7a9.png)
![Screenshot from 2021-06-28 11-42-32](https://user-images.githubusercontent.com/49585191/123616231-5f95fa80-d806-11eb-9df8-3e12ddead2a0.png)
 of the hosts
