### ISSUE TITLE
init scripts don't properly work on Ubuntu 16.04

### ISSUE THREAD

**Issue by Queeq** [ntop/ntopng#555]
ntopng 2.3.160513-1233
nprobe 7.3.160513-5162
Ubuntu Server 16.04

Seems like systemd intercepts init scripts. Here's what it looks like:

```
➜ /etc/init.d/ntopng start
Starting ntopng (via systemctl): ntopng.service.
```

As a result, it doesn't start.
`service ntopng start` command has no output and doesn't start the daemon either.

nProbe init.d start works though, but `service nprobe start` does not:

```
➜ /etc/init.d/nprobe start 
Starting nProbe if1
Starting nProbe if2
Starting nProbe if3
Starting nProbe if4
Starting nProbe if5
Starting nProbe if6
```

nProbe stopping doesn't work, it hangs indefinitely after this message:

```
➜ /etc/init.d/nprobe stop
Stopping nProbe if1

```

**Comment by lucaderi** [comment]
@Queeq Can yon please attach the configuration files we can use to reproduce this issue?

**Comment by Queeq** [comment]
There are 6 .config and .start files in `/etc/nprobe/` that have names like these:

```
nprobe-xx-xx-xx1_FPC1.conf
nprobe-xx-xx-xx1_FPC1.start
```

The content of config files is identical except of port numbers:

```
--collector-port 2063
--zmq tcp://127.0.0.1:5564
--daemon-mode
-n none
-i none
--aggregation 0/1/1/1/0/0
--sample-rate @4096:1
#--disable-startup-checks
```

There are `/etc/ntopng/ntopng.conf` and `/etc/ntopng/ntopng.start` files, config being this:

```
-G=/var/tmp/ntopng.pid
--daemon
--community

# Listen on localhost:3000 only
--http-port=:3000

# Use prefix due to nginx proxy
--http-prefix="/ntopng"

# Everybody's admin
#--disable-login=1

# Do not resolve any names
--dns-mode=3

# Limit memory usage
--max-num-flows=200000
--max-num-hosts=250000
--sticky-hosts=none

# Dump flows to MySQL
--dump-flows=mysql;localhost;ntopng;flows;ntopng;xxx

# Dump hosts to sqlite files
--dump-hosts=all

#--verbose


###################### Single Ntopng process, multiple nprobes ######################


-i=tcp://127.0.0.1:5556

-i=tcp://127.0.0.1:5557
-i=tcp://127.0.0.1:5558
-i=tcp://127.0.0.1:5559

-i=tcp://127.0.0.1:5562

-i=tcp://127.0.0.1:5564


# Views configuration
-i=view:tcp://127.0.0.1:5557,tcp://127.0.0.1:5558,tcp://127.0.0.1:5559,tcp://127.0.0.1:5562

# all
-i=view:tcp://127.0.0.1:5556,tcp://127.0.0.1:5557,tcp://127.0.0.1:5558,tcp://127.0.0.1:5559,tcp://127.0.0.1:5562,tcp://127.0.0.1:5564
```

**Comment by simonemainardi** [comment]
@Queeq please checkout nProbe manual http://www.ntop.org/support/documentation/documentation/ that explains how to control nProbe start/stop daemon

**Comment by Queeq** [comment]
@simonemainardi I was acting pretty much according to manual, as I described in my penultimate post. The only difference is that I didn't specify interfaces explicitly, but that shouldn't matter as the interface name is an optional parameter anyway.

**Comment by simonemainardi** [comment]
@ValentinaViscarelli could you please look at this.

**Comment by ValentinaViscarelli** [comment]
@Queeq 
I have made some fixes.
Please update and give it a try. Thanks.

Anyway make attention because there is something of wrong in your configuration files.

In ntopng:
1) replace this row "--http-port=:3000" with "--http-port=3000" (without ':' character).
2) remove "--daemon".  You are running ntopng as a service. you don't need to put this parameter.

In nprobe:
1) remove "--daemon". the same reason as ntopng
2) Add "-g" parameter. This is mandatory when you have to run nprobe as a service. (For instance: "-g=/var/run/nprobe-if1.pid")
3) When you run nprobe with a configuration file please use '=' in order to assign value to key, how you did in ntopng configuration file (for instance: "--collector-port=2063" and not "--collector-port 2063")  

I close the issue. If you have still the problem, please open it again.

**Comment by Queeq** [comment]
@ValentinaViscarelli Thank you for the advice. I put a colon before the port number for ntopng to listen only on loopback, according to its manual.
I modified my config files as you said. Are your fixes going to be included in the nearest nighly?

**Comment by ValentinaViscarelli** [comment]
If the manual is wrong we will correct it. 
No if you want you can try now. I have already built the packages.
Let me know if it works.
Thanks.

**Comment by Queeq** [comment]
@ValentinaViscarelli 
I don't think the manual is wrong as it works as expected.
I found a problem in nprobe init script. You consider only short options and that is why in my scenario `stop` function didn't work. Here is how it should look like (line 122):

```
PID_FILE=$(cat /tmp/nprobe-${INTERFACE_NAME}@${ID}.conf | grep -E '^\-g=|^\-\-pid\-file='|cut -d '=' -f 2)
```

I modified `grep` to match `--pid-file=` string in addition to `-g`. I also added `^` for it not to match commented lines.

Init scripts still don't work for ntopng, but I haven't had time to look deeper into the matter. I'm also unable to reopen the issue so please do it yourself.

**Comment by ValentinaViscarelli** [comment]
@Queeq
ok for pid-file. It's true it isn't currently managed for init.d file, but I analyzed the configuration files you gave us in your previous messages and in nprobe configuration there is not the "--pid-file" parameter and I said what was missing in configuration file order to work the service.
The ntopng configuration file that you gave us can work for me (apart from "--http-port" and "--daemon" parameters).
Can It work for you? Are you using a different configuration file? 
Please give me the exact ntopng configuration file and I will check why it doesn't work for you.
Thanks

**Comment by Queeq** [comment]
@ValentinaViscarelli
I have attached the complete config file.
[ntopng.conf.txt](https://github.com/ntop/ntopng/files/300832/ntopng.conf.txt)

**Comment by ValentinaViscarelli** [comment]
@Queeq 
It can work for me. What error do you have? Try also to see the log (/var/log/ntopng/ntopng.log).

antonio@ubuntu16:~$ sudo /etc/init.d/ntopng start
[ ok ] Starting ntopng (via systemctl): ntopng.service.
antonio@ubuntu16:~$ sudo /etc/init.d/ntopng status
● ntopng.service - LSB: Start/stop ntopng web
   Loaded: loaded (/etc/init.d/ntopng; bad; vendor preset: enabled)
   Active: active (running) since Mon 2016-06-06 19:37:05 CEST; 2s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5048 ExecStop=/etc/init.d/ntopng stop (code=exited, status=0/SUCCESS)
  Process: 5738 ExecStart=/etc/init.d/ntopng start (code=exited, status=0/SUCCESS)
    Tasks: 29
   Memory: 167.1M
      CPU: 456ms
   CGroup: /system.slice/ntopng.service
           └─5751 /usr/bin/ntopng /etc/ntopng/ntopng.conf

Jun 06 19:37:04 ubuntu16 systemd[1]: Starting LSB: Start/stop ntopng web...
Jun 06 19:37:04 ubuntu16 root[5745]: ntopng start
Jun 06 19:37:04 ubuntu16 ntopng[5738]:  \* Starting ntopng
Jun 06 19:37:05 ubuntu16 ntopng[5738]:    ...done.
Jun 06 19:37:05 ubuntu16 systemd[1]: Started LSB: Start/stop ntopng web.
antonio@ubuntu16:~$ sudo /etc/init.d/ntopng stop
[ ok ] Stopping ntopng (via systemctl): ntopng.service.
antonio@ubuntu16:~$

**Comment by Queeq** [comment]
This is strange. I have this:

```
root@coreman:/etc/ntopng ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
➜ /etc/init.d/ntopng start
Starting ntopng (via systemctl): ntopng.service.
root@coreman:/etc/ntopng ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
➜ /etc/init.d/ntopng status
● ntopng.service - LSB: Start/stop ntopng web
   Loaded: loaded (/etc/init.d/ntopng; bad; vendor preset: enabled)
   Active: active (exited) since Tue 2016-05-31 21:32:41 EEST; 5 days ago
     Docs: man:systemd-sysv-generator(8)

May 31 21:32:36 coreman ntopng[12903]:  * Starting ntopng
May 31 21:32:41 coreman ntopng[12903]:  * Unable to start ntopng
May 31 21:32:41 coreman ntopng[12903]:    ...fail!
May 31 21:32:41 coreman systemd[1]: Started LSB: Start/stop ntopng web.
May 31 21:33:25 coreman systemd[1]: Started LSB: Start/stop ntopng web.
Jun 05 13:52:56 coreman systemd[1]: Started LSB: Start/stop ntopng web.
Jun 05 13:53:10 coreman systemd[1]: Started LSB: Start/stop ntopng web.
Jun 05 14:47:40 coreman systemd[1]: Started LSB: Start/stop ntopng web.
Jun 06 21:05:24 coreman systemd[1]: Started LSB: Start/stop ntopng web.
Jun 06 21:12:54 coreman systemd[1]: Started LSB: Start/stop ntopng web.
```

Last log is dated May 31st. I guess my installation might be broken somehow.

**Comment by Queeq** [comment]
You know what... I've just tried to stop it (even though it wasn't running) and it began working. Looks like something was stuck inside systemd. I haven't tried to look at its status before you showed me and it gave me a clue. Thanks and sorry for taking so much time.

I hope you wouldn't forget to include the modified `grep` line in nprobe's init script.

**Comment by ValentinaViscarelli** [comment]
@Queeq 
I have just made the change of nprobe script. You can find it in tomorrow release.
