### ISSUE TITLE
Partial URL in Suspicious File Transfer

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5596]
When ntopng detected a Suspicious File Transfer, in the generated alert the URL
- is cut instead of being full
- it does not have a HREF anchor
-

**Comment by MatteoBiscosi** [comment]
Implemented as requested. However due to a previous bug we fixed, I have to put a number of max characters to the url (128) because if the url is too long the table is going to break down, however @VasilisTako added a tooltip so it is possible to check the full url of the suspicious file transfer
(e.g.)
![Screenshot from 2021-07-02 10-37-43](https://user-images.githubusercontent.com/49585191/124249248-fa9f1500-db23-11eb-8868-236c4c72b09f.png)

**Comment by lucaderi** [comment]
Not sure how to reproduce it while #5627 is open

**Comment by lucaderi** [comment]
Verified as fixed
