### ISSUE TITLE
Invalid Alert VLAN Tags 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5632]
![image](https://user-images.githubusercontent.com/4493366/124503335-a31fd400-ddc5-11eb-8a55-296a66cb9e50.png)

As you can see from this picture
- top hosts have no VLAN tags
- flow hosts sometimes have tags
- sometimes the tag is mapped to a string, sometimes it is not

**Comment by simonemainardi** [comment]
to simulate on a non-VLAN environment yon can use `--simulate-vlans`

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/124603576-5b06bd00-de6a-11eb-936b-a895b3351645.png)
Better but still bugged

**Comment by MatteoBiscosi** [comment]
Fixed both into pro and community repo

**Comment by simonemainardi** [comment]
Fix is invalid. The first parameter of `hostVisualization`  has been abused, i.e., the parameter must be an IP address but the function has been called using the first parameter either as an IP address or as a label.

Examples:

- https://github.com/ntop/ntopng/commit/744a5e53
- https://github.com/ntop/ntopng/commit/68fe3e4369fb68787eb9e807c9fd1440c375b910

This must be fixed in community and pro.

**Comment by lucaderi** [comment]
Still flawed

![image](https://user-images.githubusercontent.com/4493366/124765216-09c3ff80-df36-11eb-952a-af121d02aca9.png)

**Comment by lucaderi** [comment]
This is fixed and it will be closed when #5647 will be closed
