### ISSUE TITLE
Historical Flow Explorer Issues

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5652]
The issues below can be reproduced with Ubuntu 18.04 packages
- Adding a host filter is not working until the page is refreshed
- The same applies when changing the number of rows displayed
- Sorting (in particular by time) is disabled
- Hostnames and ASN can be pretty long and need to be shortened. For ASN "62041 (Telegram Messenger Inc)" -> 62041 (Telegram Mess...)" and not "62041 (Telegram Mes..."

**Comment by MatteoBiscosi** [comment]
(Partial) Sorting implemented, names shortening added and loading during page changes (prev, next page) added. Regarding the page refresh try to change browser and let me know, because it seems sometimes boostrap library doesn't work perfectly fine with Chrome browser and when you click the browser `Go Back` button it crashes and you need to reload the page to work fine again.

**Comment by lucaderi** [comment]
Given the above limitations, please remember to sort columns s discussed in order to have the key fields always visible (5 tuple).

**Comment by lucaderi** [comment]
Verified as fixed
