### ISSUE TITLE
Implement upper-limit boundaries in collection mode

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5667]
Currently, ntopng does not check any upper limit in terms of a number of collectors. Potentially place where the system will break include (but are not limited to)

- the interface page (only a few probes are reported)
- the flow page (super long list)
- the collectors page (ever-increasing list)

Also, make sure that the code limits the number of collectors to an upper bound to prevent memory overflow

![Screen Shot 2021-07-13 at 11 47 37](https://user-images.githubusercontent.com/4493366/125430930-89f2f90a-5de8-4f6f-a9c3-9c261dff4784.png)
![Screen Shot 2021-07-13 at 11 47 27](https://user-images.githubusercontent.com/4493366/125430938-330a972e-3334-4b09-babe-7e1ee111b12d.png)
![Screen Shot 2021-07-13 at 11 47 14](https://user-images.githubusercontent.com/4493366/125430945-c215e2df-dcd6-4ad7-b52f-100697153583.png)

**Comment by lucaderi** [comment]
Use nprobe --stress-test ... to put pressure on ntopng

**Comment by simonemainardi** [comment]
Interface page now shows at most two nProbes

![image](https://user-images.githubusercontent.com/3397663/125812190-86dcf28e-0edf-4da5-ae15-fe81165b027b.png)

Then a summary page is accessible with the whole list

![image](https://user-images.githubusercontent.com/3397663/125812295-72cd8454-1626-4056-b94f-8fb1b630329c.png)

**Comment by simonemainardi** [comment]
As per the bounds:

- The number of nProbe instances identified with `source_id` is limited to 255 due to the `u_int8_t` used as map key.
- The number of flow devices (*collectors*) handled (regardless of how many nProbe are sending them) has been set to `MAX_NUM_OBSERVATION_POINTS` (pro commit c6845461945ecb2fbfeedab4a4f72ca1cce5d39c)
- The number of sFlow devices handled is already limited by `NUM_IFACE_STATS_HASH`

**Comment by lucaderi** [comment]
Verified as fixed
