### ISSUE TITLE
Infrastructure Monitoring is Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5672]
With the latest version of ntopng, infrastructure monitoring is no longer working

![image](https://user-images.githubusercontent.com/4493366/125437880-cdca7b47-3b1a-4275-8dac-0b6697d736bc.png)

Empty page clickign on a chart
![Screen Shot 2021-07-13 at 12 35 04](https://user-images.githubusercontent.com/4493366/125437906-3df839a9-6cf9-45ff-b473-4f26864c4445.png)

**Comment by lucaderi** [comment]
Possible regression of #5417 ?

**Comment by simonemainardi** [comment]
Issue is due to infrastructure instances having the REST API version hardcoded in the key.

This means infrastructure instances added with version v1/ are not visible under version v2/. Similarly, version v2/ works only with version v2.

For the time being, compatibility has been ensured by using version v1/ which will work also under stable 5.0. Then, by release 5.2, we will remove this hardcoded version.

**Comment by lucaderi** [comment]
Verified as fixed. @simonemainardi next time let me close the ticket I open after reviewing it. Thanks
