### ISSUE TITLE
Invalid Traffic Totals

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5683]
In this picture, this host in a year has made 10 GB

![image](https://user-images.githubusercontent.com/4493366/125942858-2146f115-0b13-4ea5-b530-f773b0cf37f3.jpeg)

whereas in the last week 56 GB. This is not possible
![image](https://user-images.githubusercontent.com/4493366/125942890-21aca78b-a325-4e7a-b924-efe787f47414.jpeg)

The timeseries backend is RRD

**Comment by simonemainardi** [comment]
Fixed but honestly the modified code is almost completely unreadable and without comments so we should really consider throwing it in favor of something simple and manageable.

**Comment by simonemainardi** [comment]
still bugged for applications:

![image](https://user-images.githubusercontent.com/3397663/126301592-f13590ff-419a-4112-9b16-00a89a047eeb.png)

![image](https://user-images.githubusercontent.com/3397663/126301657-ea0ffa2e-c842-4a83-825b-a2c29879f16b.png)

**Comment by simonemainardi** [comment]
This seems to be an artifact of RRD when showing timeseries with almost no data. Please review.

**Comment by simonemainardi** [comment]
I went on and can also say this is due to the loss of precision RRD when going back in time.

For example, this is what I get when querying monthly and yearly data, respectively

![image](https://user-images.githubusercontent.com/3397663/126648705-df6846a6-424e-4081-9e8a-ccb8a87f1792.png)

![image](https://user-images.githubusercontent.com/3397663/126648809-7d26a16c-4994-4150-9fac-832657300a44.png)

Behind the scenes, when fetching the YEAR, RRD returns only ONE non-nan point:

```
$ sudo rrdtool fetch /var/lib/ntopng/8/rrd/bytes.rrd AVERAGE -s 1595425271 -e 1626961271 | grep -v nan
                            num

1626958800: 8.6102784523e+05
```

That multiplied by the step (3600) gives the shown result.

**Comment by lucaderi** [comment]
Please add a warning in the chart that reports a possible loss of accuracy with large time intervals, and close this ticket.
