### ISSUE TITLE
Invalid Hostname Resolution

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5706]
![Screen Shot 2021-07-22 at 19 02 45](https://user-images.githubusercontent.com/4493366/126679291-057b566b-bd52-4ecf-9011-c6d01a91f960.png)

**Comment by lucaderi** [comment]
![Screen Shot 2021-07-22 at 19 04 14](https://user-images.githubusercontent.com/4493366/126679499-1efeaf7b-fe5e-4e2f-9c50-d9f05a50fe17.png)

Also here
deri@Lucas-iMac.local 201> host 192.168.1.178
Host 178.1.168.192.in-addr.arpa. not found: 3(NXDOMAIN)

**Comment by simonemainardi** [comment]
Several things that may have caused the reported behavior have been addresses so possibly the issue is now fixed.

Specifically:

- It looks like your 'google' LAN host has only flows as server so my guess is that ntopng has only seen partial traffic. I have modified the behavior to set the name only when we are sure about the server host, i.e., no swap heuristic https://github.com/ntop/ntopng/commit/678369d969b87e20db09df41ebed3587ce90f19e
- There were issues where TLS names were sometimes wrongly set https://github.com/ntop/ntopng/commit/f41faab5da0a53a8783c11aa881d8e54cc083b9c
- Other issues have been fixed in the referenced commits

Please, stop ntopng, flush all possibly serialized hosts with

```
redis-cli --scan --pattern *serialized_hosts* | xargs redis-cli del
```

Start over, and report.

**Comment by lucaderi** [comment]
Still bugged

$ redis-cli --scan --pattern *serialized_hosts* | xargs redis-cli del
redis-cli: No match.

![Screen Shot 2021-08-02 at 10 27 09](https://user-images.githubusercontent.com/4493366/127829701-f021d8a5-534c-4fb2-a5a6-ac9af4ba5d7c.png)

This localhost has accessed wp.net so that domain name has to be bound to the server and not to the client 

![Screen Shot 2021-08-02 at 10 35 32](https://user-images.githubusercontent.com/4493366/127830340-c9cc1352-a286-4aa8-b516-f270c485331c.png)

**Comment by simonemainardi** [comment]
Said that the host shown above has only flows initiated 'as server' and this makes me think you are only seeing partial traffic

![image](https://user-images.githubusercontent.com/3397663/127892431-3eb46496-2a64-47e3-826e-2af53d5c522f.png)

I was able to reproduce the issue by artificially throwing the first packet (with the SYN) of a TCP session

![image](https://user-images.githubusercontent.com/3397663/127892569-81597138-8682-4dab-91f8-c49704c3572f.png)

Committed fix referenced above should solve the issue. Please, update, redo

```
redis-cli --scan --pattern *serialized_hosts* | xargs redis-cli del
```

And report.

**Comment by lucaderi** [comment]
![Screen Shot 2021-08-04 at 16 34 40](https://user-images.githubusercontent.com/4493366/128200263-03fbbe64-fd32-473b-9dbf-03e0763af943.png)
Still bugged

deri@Lucas-iMac.local 214> redis-cli --scan --pattern *serialized_hosts* | xargs redis-cli del
redis-cli: No match.

(this is my router)
![Screen Shot 2021-08-04 at 16 29 41](https://user-images.githubusercontent.com/4493366/128199368-8958e664-5424-4972-9363-f31da5269b59.png)

![Screen Shot 2021-08-04 at 16 30 46](https://user-images.githubusercontent.com/4493366/128199439-482b8f67-bd9f-417f-81fe-546e57e46105.png)

**Comment by lucaderi** [comment]
Not able to reproduce it now, it seems to be fixed
