### ISSUE TITLE
ntopng traffic (HTTP on port 3000) can't be secure

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5733]
![image](https://user-images.githubusercontent.com/4493366/128223514-37560f96-5d94-4d68-af34-653fba232797.png)

**Comment by simonemainardi** [comment]
The breed is read from nDPI. Please make `ndpi_get_proto_breed` with the same fingerprint of `ndpi_get_proto_category`. Indeed, it would be desirable to pass the whole `ndpi_protocol` to the function so that nDPI can check both the master and app protocols before deciding on the breed.

**Comment by cardigliano** [comment]
The lock icon is now used only for encrypted protocols, thumb up is used otherwise.
<img width="618" alt="Screen Shot 2021-08-06 at 10 26 58" src="https://user-images.githubusercontent.com/7548711/128481416-8c3d16cb-d94a-4578-9085-ca13722d9524.png">
<img width="731" alt="Screen Shot 2021-08-06 at 10 29 00" src="https://user-images.githubusercontent.com/7548711/128481442-4a6ab116-1a6d-4049-a465-50d05def981a.png">
