### ISSUE TITLE
Suboptimal throughout calculation 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5768]
Since https://github.com/ntop/ntopng/commit/1d65185fd3ca0b476ed7ebf1a774d6396f6f823d throughput is not working smoothly as it should be. In this setup there are two nProbes sending flows to ntopng that will then aggregate them with a view interface (viee:all). The individual probes have an idle timeout of 30 sec and lifetime of 120 sec.

Since the start of ntopng:
 - the first throughput update in the upper bar is performed after 4:06 since start
![Screen Shot 2021-08-16 at 08 39 55](https://user-images.githubusercontent.com/4493366/129521595-cf31a995-7386-4825-87b5-6f4504e87f75.png)
- the dashboard is first updated  after 2:46 since start
![Screen Shot 2021-08-16 at 08 40 25](https://user-images.githubusercontent.com/4493366/129521686-bbf37411-b3af-470f-b8fd-f570f1d94f7a.png)
- the second throughput in the upper bar is performed after 6:06 since start
- in the dashboard some entries flip every few seconds from the symbolic to the numeric label with the same throughput
![image](https://user-images.githubusercontent.com/4493366/129522223-dbf9ae1d-c8ab-4524-8efc-458f4fd9c27c.png)
![image](https://user-images.githubusercontent.com/4493366/129522245-072633b7-b513-4131-a039-fdfa582c64f9.png)

In essence:
- the interface throughput cannot be updated so slowly. It has nothing to do with the flow duration. 
- it must be clear to the user how the refresh rate is working based on the configuration of the collection probes.
- the name flipping has to be fixed
- if the throughput is upated so seldom, the top thrpughput graph must also be reworked and updated ore slowly, as it is a flat line
![Screen Shot 2021-08-16 at 08 50 19](https://user-images.githubusercontent.com/4493366/129522664-de97a50e-cb82-4b2d-9176-5bf1086150c5.png)

**Comment by simonemainardi** [comment]
Addressed in the referenced commit and in the companion pro commit `163898ea9111ce83d6826b75bf84fc25204778e8`.

Following things have been changed to address the highlighted issues.

- This global preference has been removed. Housekeeping frequency is not 5 seconds (fixed) for packet interfaces and it is dynamically calculated for ZMQ interfaces using nProbe timeouts

![image](https://user-images.githubusercontent.com/3397663/129562471-e0b6fad0-cbda-481f-8f1e-0045a86f30f3.png)

- This interface preference has been removed. UI refresh is calculated dynamically as above and there is no need to have it configurable by the user.

![image](https://user-images.githubusercontent.com/3397663/129562563-2461654d-deae-4e64-bf1a-4ca46bd3afb0.png)

- During startup, ntopng needs two refresh cycles before showing meaningful data as it calculates throughputs as differences between consecutive updates. As via ZMQ this can take up to 4 minutes after startup, a message is shown rather than an empty dashboard

![image](https://user-images.githubusercontent.com/3397663/129562809-7a57ad9d-70a6-402e-aa15-56809333c768.png)

**Comment by simonemainardi** [comment]
Also improved the update frequency of the top load charts. Now the frequency is chosen according to the interface refresh rate, but is capped to 15 seconds to make it look smoother and more consistent with other header elements

![image](https://user-images.githubusercontent.com/3397663/129566708-f22114a6-3f46-4048-b12a-dc35e9c1f7d5.png)

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/129592578-009a6284-c3f7-4d70-9df3-f7c0471401f7.png)

**Comment by lucaderi** [comment]
Please modify the message adding a HREF that points to the documentation where @simonemainardi explains how the throughput is computed.

**Comment by simonemainardi** [comment]
Changes message

![image](https://user-images.githubusercontent.com/3397663/129751535-7f246f1e-c7ab-47f6-8211-0b4c43b3426e.png)

Bringing to the doc page

![image](https://user-images.githubusercontent.com/3397663/129751614-e43a1410-323c-4025-920b-7b2d092aafca.png)

**Comment by lucaderi** [comment]
Implemented as requested
