### ISSUE TITLE
MAC Address Based Traffic Directions not working

### ISSUE THREAD

**Issue by 612wong** [ntop/ntopng#5788]
Version: ntopng Enterprise M v.5.1.210820
Setup:
- switch mirrors WAN interface traffic (both directions) to a dedicated NIC (et2) on the host running ntopng
- on ntopng, interface setting, the MAC address of WAN interface on the remote WAN device was entered
- ntopng was restarted and traffic direction is still showing one-way only (the little graph next to the interface name at the top left corner)
<img width="1398" alt="Screen Shot 2021-08-23 at 12 22 19 pm" src="https://user-images.githubusercontent.com/58540705/130381340-dc77f956-8a27-4044-ac90-91538dea0dc2.png">

**Comment by simonemainardi** [comment]
CI and lab tests are giving me proper behavior.

To clarify, the expected behavior in your case is that every time an Ethernet frame is seen with 64:f6... as destination MAC, the packet is considered egress, i.e., upload (arrow up in the top chart).

Please, make sure the mirror is actually sending both directions. Also check the TX-RX chart.

For example, this is what I get by changing the MAC for traffic directions (see the change between sent and received)

![image](https://user-images.githubusercontent.com/3397663/130415379-e282c6e0-6421-4eb8-b184-7b2a19e813db.png)

**Comment by 612wong** [comment]
Thanks for looking into it. I have re-installed the ntopng latest stable build and restored the configuration.
Now the MAC address based traffic direction works nicely.
<img width="1687" alt="Screen Shot 2021-08-23 at 9 29 56 pm" src="https://user-images.githubusercontent.com/58540705/130440199-5c7a3ca2-f5ce-470c-a37a-f964c8b569eb.png">
