### ISSUE TITLE
Dropped alerts Increasing at a high rate after moving to nightly build

### ISSUE THREAD

**Issue by lkjom** [ntop/ntopng#5847]
Hello

I'm am seeing an issue recently after moving to Nightly from stable  where the Dropped alerts increases at a very fast rate , a few days after InfluxDB will stop running and refuse to start . I have cleared all time series data and recreated the wal data and meta folders even purged the old Influx config however although it fixes it for a few days eventually influx will die and the dropped alerts continue to skyrocket

I have updated and rebooted the Probes and Ntopng instance around 15 minutes ago and as you can see there is already a high amount of dropped alerts
![image](https://user-images.githubusercontent.com/87376849/132335621-f0052bfb-de17-4547-bb82-e43d8c13dbd2.png)

we have 2 probes running the same version and one instance of ntopng sitting elsewhere in the network
nprobe/unknown,now 9.7.210907-7464 amd64 [installed]
ntopng/unknown,now 5.1.210907-15456 amd64 [installed]

Pervious issue where we upgraded to nightly was "[ntop/ntopng] Unable to Add Recipient (#5674)"

Thanks in advance !

**Comment by simonemainardi** [comment]
Hi, dropped alerts mean recipients are too slow to keep up with them.

Check under page recipients, then uses. To mitigate, you can open a recipient, and increase the minimum severity, to avoid getting notices or minor things delivered.

The influx issue is not connected with dropped alerts nor with the version of ntopng. A dying influxdb can be due to high cardinality of data. Try and reduce the amount of timeseries written from the Preferences->timeseries page. In particular, it will be beneficial to set local hosts timeseries to Light, and avoid saving their applications.

**Comment by lkjom** [comment]
Hello Simone

I only had builtin for end/notif , but I was unable to change the severity , I have since reset the configuration for Endpoints and Recipients and was able to change the level
I am still getting some drops but significantly less . Side note to this it seems to have fixed another issue I had editing existing host pools

Feel free to close the git case
Thanks
