### ISSUE TITLE
Obsolete TLS: Missing version

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5860]
![image](https://user-images.githubusercontent.com/4493366/132702559-8982e3c6-394e-4378-8a41-b3d7c4a258aa.png)

**Comment by simonemainardi** [comment]
Issue was due to the TLS version IE not sent in the default ZMQ template. We have decided not to add it to the default template to keep it as small as possible. However, we have modified the error message to still tell the maximum version for the error.

![image](https://user-images.githubusercontent.com/3397663/133048809-bacc7349-e4e1-432f-b189-c7b1d1107899.png)

**Comment by lucaderi** [comment]
Verified as fixed
