### ISSUE TITLE
Missing HTTP Method from alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5988]
![Screen Shot 2021-10-16 at 08 45 10](https://user-images.githubusercontent.com/4493366/137576958-a2410786-9204-4318-b44f-19b1b5cf3150.png)

In HTTP alerts like the one above the method (e.g. POST) is missing. This is very important info to know for troubleshooting attacks or similar.

**Comment by MatteoBiscosi** [comment]
As requested, now alerts having HTTP protocols, are going to have, if available, the last HTTP method as shown in the screenshot below

![Screenshot from 2021-10-19 11-13-26](https://user-images.githubusercontent.com/49585191/137880378-62da48dc-1499-491a-bf84-272618b66220.png)

**Comment by lucaderi** [comment]
![Screen Shot 2021-10-20 at 21 26 00](https://user-images.githubusercontent.com/4493366/138158806-945f5c65-45a8-4215-8524-ebeb79dddd5e.png)
Still bugged

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi 
That is very helpful, if you could add the server status code, e.g. 200 as well?
Thank you!

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu , sure, if available I'm going to add it!

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu, as requested the Status Code has been added to the HTTP alerts, however it seems there is a bug with nProbe flows and ntopng is not receiving HTTP stats (status code, ecc.) so right now if you capture flows from a non-nProbe interface is working correctly, otherwise no HTTP stats is showing up. I'm working on fixing it
