### ISSUE TITLE
Missing Flow context from all flow alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5989]
![Screen Shot 2021-10-16 at 08 45 10](https://user-images.githubusercontent.com/4493366/137577011-c388b41e-1dd2-4985-955f-23824f37b967.png)

In alerts (see the one above but this request is for *ALL* flow alerts) it would be nice to have some context such as the number of bytes per direction (cli->srv and src->cli) or if not possible, at least the predominant direction (upload vs download). I am aware that the flow might still be ongoing when the alert is emitted and thus counter can still increase (so make sure you specify this info well in the flow) but having the flow direction will help understanding who is the downloader and who is the uploader in particular with POST messages.

**Comment by MatteoBiscosi** [comment]
As shown in the screenshot below, a description reporting the predominant direction has been added. Due to the issue mentioned by you above i preferred adding a "generic" description ('Download' or 'Upload') instead of the specific number of bytes to avoid a misleading description.

![Screenshot from 2021-10-19 11-53-01](https://user-images.githubusercontent.com/49585191/137886789-04e6795b-1d49-48b3-993a-0e84f49395d2.png)

**Comment by lucaderi** [comment]
![Screen Shot 2021-10-20 at 21 23 21](https://user-images.githubusercontent.com/4493366/138158459-2f39d947-e348-402e-ba79-d9aaba3db8d9.png)
Still bugged: missing HTTP method

**Comment by MatteoBiscosi** [comment]
Added the predominant direction even to 'Other issues' section

**Comment by lucaderi** [comment]
Verified as fixed
