### ISSUE TITLE
too long to get history

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#599]
hi
I use ntop with a "-F" to save in mysql database and it works well
but when I try to get a host history for one week... I have to wait around 10 minutes to get the result
database size is about 50 GB right now
is it caused by no SSD disk usage ? 
what do you advise ? send data to ELK ?

thanks

Niko

**Comment by lucaderi** [comment]
The problem is the DB. You need to tune it, check the disk configuration, see if you have so much data that you better need a cluster etc. How many records you have extracted in one week of traffic of a single host?
ELK is a toy IMHO: good for small setups, for large ones you need a distributed configuration that jeopardised the idea of having a simple DB.
We're working at a new database, written from scratch, that will likely solve performance hogs. We need time, so do not expect it before fall or so.

**Comment by alberk8** [comment]
Hi,

I am sorry to ask questions on a closed issue.  But this is an interesting subject to me.  I have the following questions.
1)  Will you maintain the existing MySQL options when the new DB is made available?.
2) Will the new DB be made available to the community edition and/or Open Source?
3) Is the query to the new DB based on a new language or will it be compatible to MySQL query language?

Thank you.

**Comment by simonemainardi** [comment]
We still have to decide how to release the new db, however, existing MySQL options will be maintained and will work independently. Queries to the new db will not necessarily be compatible with MySQL.
