### ISSUE TITLE
Extend clear text credentials alert

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5994]
Hello ntop team
The http clear text is very helpful, not only in terms of security, also for communication / collaboration across departments. Would it be possible to extend the alert for other clear text protocols, like ftp, telnet, imap, pop3, smtp ? 
thank you

**Comment by lucaderi** [comment]
Hi Martin, it should be already there (I will add telnet in a moment)

ftp_control.c:    ndpi_set_risk(ndpi_struct, flow, NDPI_CLEAR_TEXT_CREDENTIALS);
http.c:    ndpi_set_risk(ndpi_struct, flow, NDPI_CLEAR_TEXT_CREDENTIALS);
mail_imap.c:	  ndpi_set_risk(ndpi_struct, flow, NDPI_CLEAR_TEXT_CREDENTIALS);
mail_pop.c:      ndpi_set_risk(ndpi_struct, flow, NDPI_CLEAR_TEXT_CREDENTIALS);
mail_pop.c:      ndpi_set_risk(ndpi_struct, flow, NDPI_CLEAR_TEXT_CREDENTIALS);
mail_smtp.c:		ndpi_set_risk(ndpi_struct, flow, NDPI_CLEAR_TEXT_CREDENTIALS);
mail_smtp.c:		ndpi_set_risk(ndpi_struct, flow, NDPI_CLEAR_TEXT_CREDENTIALS);

Note that we do NOT set the alert unless we see the login. Meaning that the alert is bound to the flow content rather than on the protocol. This means that if you see a HTTP flow with no credential, the alert is not raised. Hope this is the correct behaviour you expect.

**Comment by lucaderi** [comment]
https://github.com/ntop/nDPI/commit/06f13fd2de45237b0643b2a26c76f57967b8e93e

**Comment by martinscheu** [comment]
Hi Luca,
Yes perfect, that is the correct behavior. 
Thank you
