### ISSUE TITLE
Select hosts based on location

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6010]
Please implement the ability to filter client or server hosts based on their location (local or remote).
![Screen Shot 2021-10-25 at 16 11 27](https://user-images.githubusercontent.com/4493366/138711526-83c9440f-983e-4d12-a02d-825ea2e5ee7f.png)
Example:
- select all flows from remote hosts using SSH as application protocol

**Comment by MatteoBiscosi** [comment]
Implemented as requested; other then that added the badge icon representing the location of the host instead of a new column
![Screenshot from 2021-11-23 10-59-00](https://user-images.githubusercontent.com/49585191/143004148-c8a3c566-7848-4698-885f-070a1963e643.png)

![Screenshot from 2021-11-23 10-58-50](https://user-images.githubusercontent.com/49585191/143004156-da6008f0-4b1d-4ff9-bdbe-a8cf7204023a.png)

**Comment by lucaderi** [comment]
Verified as fixed
