### ISSUE TITLE
Flow risk is not formatted properly

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6011]
![Screen Shot 2021-10-25 at 16 12 50](https://user-images.githubusercontent.com/4493366/138711813-47763999-eeca-442d-8a64-00941732c7e9.png)

**Comment by lucaderi** [comment]
See also #5998

**Comment by simonemainardi** [comment]
Implemented under pro, along with query functionalities. Flow risks are now stored as a bitmap.

Example

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/3397663/139093340-ea1b5719-ecdc-4cdd-90e5-4914c7db6908.png">

**Comment by simonemainardi** [comment]
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/3397663/139093432-780020d1-128d-495c-85e6-715f4c047507.png">


multiple statuses are supported too and shown as a CSV list.

**Comment by lucaderi** [comment]
The fix has introduced a new bug
- the risk is too short, in particular when several flow risks are reported. As of today it kind of useless
![Screen Shot 2021-11-04 at 09 16 13](https://user-images.githubusercontent.com/4493366/140279916-204a528f-326c-415c-a8a1-2e6977729695.png)
- Clicking in the info (?) leads to a wrong page (https://www.ntop.org/guides/nDPI/flow_risks.html#risk-039) for another risk.

**Comment by simonemainardi** [comment]
- Flow risks are now not ellipsized
- Can't use the newline to show multiple risks at it breaks the layout when flow risks are not shown as spillover columns
- Hyperlink leads to the right page but since the risk is at the bottom of the page, the browser don't let the page scroll that far. Would you like to add empty space at the bottom of the nDPI docs page as workaround?

![image](https://user-images.githubusercontent.com/3397663/141502567-14e34ce6-39da-456a-90e9-5e22a1e83d51.png)

**Comment by lucaderi** [comment]
Verified as fixed. We'll open a new ticket for cosmetics
