### ISSUE TITLE
Code mix in Clickhouse HostFlows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6044]
Open a host and click on the link

![image](https://user-images.githubusercontent.com/4493366/140284877-cc16d437-8a03-47a7-a3a9-2710a0c7753a.png)

this is what I see

![image](https://user-images.githubusercontent.com/4493366/140285022-e977bf9f-44f4-4ffd-81be-9be2a526c6ac.png)

The bottom filter is not working and using clickhouse it MUST move to the historical explorer to avoid writing similar code too many times.

The above tabs are all broken and I have no clue why they are there
![Screen Shot 2021-11-04 at 09 53 43](https://user-images.githubusercontent.com/4493366/140285181-cc74e4cf-c54e-4e68-afa7-ad56f4d8e4e0.png)

**Comment by MatteoBiscosi** [comment]
Removed flows, talkers and apps tabs due to the fact that those pages are not supported by clickhouse. Now when clicking onto the lens to get the alerted flows, the user is going to be redirected to the 'Historical Flow Explorer'. At the same time fixed the issue where when clicking 'Raw Flows' the user was redirected to the old nIndex Historical Explorer.
Please report if new wrong redirections have been found.

**Comment by lucaderi** [comment]
The above problem is fixed but now there is a new bug introduced with an invalid filter

![image](https://user-images.githubusercontent.com/4493366/140396243-28d4763c-a3b4-40f4-ae3d-d69d78189f1b.png)

**Comment by cardigliano** [comment]
It seems status 46 was hardcoded in the url for some reason. Fixed.

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
