### ISSUE TITLE
DNS name resolution as pornhub on many hosts

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#6064]
Hello;

Can someone explain to me how name resolution is done on Host page ? 

My company does web hosting and this morning someone looked in ntop and saw that our machines were showing up as pornhub.com in the Host section.
What is bizarre is that some servers have a name and others do not.

If I understand correctly this is how that work
An host have an IP and this IP can be name resolved as DNS or TLS.
- If there is none of those resolution (only the IP is visible in DNS Resolution), no information is showed up.
- If there is only TLS resolution, that is this information that is showed up in the main page. 
- If there is a TLS resolution and a DNS resolution, that is the DNS information that is showed up in the main page.

So I need to understand why there is a resolution on DNS or TLS, why some host have both and especially why they are displayed on my interface as pornhub.com

Here is just an example of all of them
![image](https://user-images.githubusercontent.com/86605223/141082451-4e9d207a-c813-4f55-a387-6e9e75ee1385.png)

Here is the host information for .78
![image](https://user-images.githubusercontent.com/86605223/141082483-43356517-d036-4c25-a3e3-fa5834e86585.png)

Here is the host information for .81 who don't have a DNS resolution so the use in main hosts is the TLS name. 
![image](https://user-images.githubusercontent.com/86605223/141082650-7437ed9c-9f57-469f-b237-6ca6d7d79124.png)

Here is the host information for .89 who doesn't have a DNS resolution and no TLS name so there is no information showed up in main Hosts window.
![image](https://user-images.githubusercontent.com/86605223/141082869-b36c0907-3be2-4d88-9da3-c52f5e56923b.png)

**Comment by MatteoBiscosi** [comment]
Hi @thomasbruchet  the name resolution is done using various protocols: DNS, MDNS, DHCP, NETBIOS, TLS and HTTP.
If none of this protocols resolved the name then the ip is going to show up otherwise the resolved name is going to show up; regarding your issue with (e.g.) ip 109.3.168.81 is really strange, the name resolved should be shown up in the host page with the protocol that detected it. Would it be possibile to have a small pcap capture of that particular host? In this way I'll try to reproduce the same behavior. If yes, please drop the pcap at `biscosi at ntop.org` (The pcap is going to be used just for debugging and dropped after the resolution of the issue)

**Comment by thomasbruchet** [comment]
Hello,

The problem seems to be self resolved after some upgrade of ntopng.
![image](https://user-images.githubusercontent.com/86605223/143412205-17f6cfe2-52df-44cb-adfc-e93f7c79507a.png)


I'have just restarted ntopng, so I will do a new check in few days before close the issue.

**Comment by MatteoBiscosi** [comment]
Alright @thomasbruchet great; i'll wait for your update.

**Comment by MatteoBiscosi** [comment]
Hi @thomasbruchet is there some update on this issue?

**Comment by thomasbruchet** [comment]
Hello, 

I think the issue can be closed,, the DNS name did not reappear.

Thant you for your support.
