### ISSUE TITLE
Huge Increase in CPU Usage in 5.x ntopng

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#6091]
I have 2 VM both configured the same running on a Host system one is running ntopng-5.0.210927-14747.x86_64 the other running
ntopng-5.0.211108-14756.x86_64 the first one top shows single digit cpu usage the second one show cpu usage over 100%. Below are the details.
V990002:~
CentOS Linux release 7.9.2009 (Core)
**ntopng-5.0.210927-14747.x86_64**
ntopng -l 0 -e -U ntopng -ieth1 -d/var/lib/ntopng -w 3000 -n 1 -m 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12 --community
top - 07:49:50 up 9 min,  2 users,  load average: 0.42, 1.61, 1.10
Threads: 355 total,   2 running, 353 sleeping,   0 stopped,   0 zombie
%Cpu0  :  8.7 us, 12.7 sy,  0.0 ni, 78.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  6.7 us, 12.0 sy,  0.0 ni, 81.0 id,  0.3 wa,  0.0 hi,  0.0 si,  0.0 st
top - 07:51:50 up 11 min,  2 users,  load average: 0.08, 1.09, 0.97
Tasks: 226 total,   1 running, 225 sleeping,   0 stopped,   0 zombie
%Cpu0  :  0.7 us,  0.7 sy,  0.0 ni, 98.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  0.7 us,  1.0 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  1882176 total,    89828 free,   752524 used,  1039824 buff/cache
KiB Swap:  3905532 total,  3310676 free,   594856 used.   273032 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND             
 7226 ntopng    20   0 1782168 265256 129908 S   2.0 14.1   0:21.57 ntopng

**over 100% cpu**
Fri Nov 19 07:51:51 EST 2021
V990001:~
CentOS Linux release 7.9.2009 (Core)
**ntopng-5.0.211108-14756.x86_64**
ntopng -l 0 -e -U ntopng -ieth1 -d/var/lib/ntopng -w 3000 -n 1 -m 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12 --community
top - 07:51:48 up 18:12,  1 user,  load average: 1.84, 2.48, 2.61
Tasks: 182 total,   1 running, 181 sleeping,   0 stopped,   0 zombie
%Cpu0  : 48.3 us,  3.3 sy,  0.0 ni, 48.0 id,  0.3 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  : 50.0 us,  5.0 sy,  0.0 ni, 44.7 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem :  1882176 total,   160460 free,   673396 used,  1048320 buff/cache
KiB Swap:  3905532 total,  3901436 free,     4096 used.   969768 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                     
12534 ntopng    20   0 1677124 196356  15288 S 104.6 10.4   1017:41 ntopng

**Comment by lucaderi** [comment]
Extra comment 

ntopng-5.0.210927-14747.x86_64
and
ntopng-5.0.211108-14756.x86_64

cpu usage went from 210927 being:
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                      
  589 nobody    20   0 1816004 308460  31228 S  1.6  7.9 150:24.60 ntopng                       
  590 nobody    20   0 1816004 308460  31228 S  1.6  7.9 152:03.58 ntopng                       
  591 nobody    20   0 1816004 308460  31228 S  1.6  7.9 150:17.51 ntopng                       
14993 root      20   0  162404   2572   1600 R  1.3  0.1   0:04.92 top                          
  578 nobody    20   0 1816004 308460  31228 S  0.7  7.9  80:57.80 second.lua                   
15188 root      20   0  162204   2364   1580 S  0.7  0.1   0:02.42 top                          
  552 nobody    20   0 1816004 308460  31228 S  0.3  7.9   1:43.76 ntopng                       
  585 nobody    20   0 1816004 308460  31228 S  0.3  7.9  20:28.69 notifications.l

to on 211108
12606 ntopng    20   0 1668936 179032  14940 S 29.4  9.5   2:17.72 timeseries.lua       
12600 ntopng    20   0 1668936 179032  14940 S 25.7  9.5   2:12.39 second.lua           
12570 ntopng    20   0 1668936 179032  14940 S 13.9  9.5   0:24.64 ntopng               
12568 ntopng    20   0 1668936 179032  14940 S 12.2  9.5   0:25.75 ntopng               
12594 ntopng    20   0 1668936 179032  14940 S 11.9  9.5   1:01.39 notifications.l      
12596 ntopng    20   0 1668936 179032  14940 S 11.6  9.5   0:36.00 discover.lua         
12590 ntopng    20   0 1668936 179032  14940 R 10.6  9.5   0:17.90 stats_update.lu      
12595 ntopng    20   0 1668936 179032  14940 R  9.2  9.5   0:40.34 periodic_checks      
12611 ntopng    20   0 1668936 179032  14940 S  2.0  9.5   0:10.17 ntopng


As of the CPU jump this is due to the fact that we have removed Lua VMs reuse as this was causing crashes. This means that every time we spawn a Lua VM we reload the files and thus the load. In particular for high-frequency tasks as the second (a new VM is created every second) you will see this jump). We plan to address this problem.

**Comment by lucaderi** [comment]
@sclark46 Can you please check if the performance is now improved?

**Comment by ghost** [comment]
Hi Luca, I have been using the stable-yum-repo for my tests, and have not been self compiling. When will it be available?

**Comment by ghost** [comment]
Luca, I am trying to build the dev version according to the instructions at https://github.com/ntop/ntopng/blob/dev/doc/README.compilation
and I get the following error from configure:
checking for ntopng professional edition... not found
checking for pcap_open_live in -lpcap... no
Please install libpcap(-dev) (http://tcpdump.org)

I have the latest - and it doesn't have that symbol - I also have the pfring version in 
/usr/local/lib/libpcap.so.1.9.1 that has that symbol - but can't figure out how to tell configure to use that libpcap.

this is on CentOS 7 - CentOS Linux release 7.9.2009 (Core)

**Comment by lucaderi** [comment]
I have put the code in the dev branch until is validated. As of the dependencies I have updated https://github.com/ntop/ntopng/blob/dev/doc/README.compilation. I suggest to install libpcap-dev anyway

**Comment by ghost** [comment]
Hi Luca, I have 
V990001:~
$ rpm -qa|egrep '(pfring|libpcap)'
libpcap-devel-1.5.3-12.el7.x86_64
pfring-8.0.0-7085.x86_64
pfring-dkms-8.0.0.7085-7085.noarch
libpcap-1.5.3-12.el7.x86_64

but stil get the error I listed above when doing ./configure
is there a configure option that I can use to indicate where to find the corrrect libpcap ?

**Comment by ghost** [comment]
Hi Luca,
would the changes be in the nightly build? If so I can just install and test that version.

**Comment by ghost** [comment]
Hi Luca, I just installed the nightly build and I don't see the huge increase in cpu usage it appears to be gone.

**Comment by ghost** [comment]
nightly build top output - ntopng only 2.6% of cpu

top - 08:48:22 up 5 days, 19:09,  2 users,  load average: 0.21, 0.13, 0.19
Threads: 259 total,   1 running, 258 sleeping,   0 stopped,   0 zombie
%Cpu0  :  1.0 us,  1.3 sy,  0.0 ni, 97.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  1.3 us,  1.0 sy,  0.0 ni, 97.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
top - 08:49:43 up 5 days, 19:10,  2 users,  load average: 0.09, 0.12, 0.18
Tasks: 183 total,   1 running, 182 sleeping,   0 stopped,   0 zombie
%Cpu0  :  1.0 us,  1.3 sy,  0.0 ni, 97.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  0.7 us,  1.0 sy,  0.0 ni, 98.0 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem :  1882176 total,   119068 free,   491756 used,  1271352 buff/cache
KiB Swap:  3905532 total,  3676668 free,   228864 used.  1074612 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                               
21335 ntopng    20   0 1657172 129724  15136 S   2.6  6.9   5:28.37 ntopng

**Comment by lucaderi** [comment]
Verified as fixed

**Comment by playday3008** [comment]
Guess at what moment I turned on the ntopng)
![image](https://user-images.githubusercontent.com/18056374/144315506-220c2297-eace-4e1d-acdf-22add64f0726.png)

**Comment by ghost** [comment]
Any idea when these fixes will make it into 5.0.x stable ?

**Comment by ghost** [comment]
I guess these fixes aren't going into 5.0.x stable - how about when will 5.1.x stable be released ?
