### ISSUE TITLE
ClickHouse Ingress Reports Errors

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6121]
![Screen Shot 2021-12-07 at 20 23 27](https://user-images.githubusercontent.com/4493366/145092953-739fd2e4-4aa2-4665-85a5-99dd67e1f1c3.png)

**Comment by simonemainardi** [comment]
By looking at the error I can see that the offending file is pretty old (loot at the epoch 1638893405 is Dec 7th).

Looking at the current execution, there is no export drop and this also confirm the file is old and belonging to a previous execution.

![image](https://user-images.githubusercontent.com/3397663/145175605-c92af767-0d52-419e-8d18-d455b813b929.png)

Likely this is due to the columns format change.

Temorarily, you can try and cleanup old files under /var/tmp but we should also design a mechanism to clean them automatically.

**Comment by simonemainardi** [comment]
Resolved in the latest build.

**Comment by lucaderi** [comment]
![Screen Shot 2021-12-20 at 10 02 57](https://user-images.githubusercontent.com/4493366/146741003-46d1f090-2338-44a4-a057-82043ee418fd.png)
Still bugged: no indication of the error that has been experienced

**Comment by simonemainardi** [comment]
Errors are written inside ClickHouse table `system.errors` and there is no way to map the number to the actual error using the system call `system`. For example, your `210` means

```
│ NETWORK_ERROR                       │  210 │     1 │ 2021-12-08 10:43:56 │ Connection reset by peer, while reading from socket (127.0.0.1:41786)                                                                                                                                                                                      │ [155499994,277942286,155749329,277938752,294795252,341032751,341039546,342294009,342278282,140241824368314,140241817199901]
```

What I am doing now is querying the `system.errors` table and exposing it under the system interface, ClickHouse health.

**Comment by simonemainardi** [comment]
Pro commit 8ef2678feba2eef158b49b39dc80ee8909479726 adds errors with detailed trace under the internals page

![image](https://user-images.githubusercontent.com/3397663/146919765-691cacb8-b8f5-4ab3-b191-8791123483b0.png)

**Comment by simonemainardi** [comment]
Pro commit bc6d2ad7176d20423c2a09fd534851ceca799937 intercepts errors using `popen` and forwards them to the trace so they can be inspected and troubleshoot properly


![image](https://user-images.githubusercontent.com/3397663/146925439-38b76a30-9223-47eb-88c2-a9e2ab17b098.png)

**Comment by lucaderi** [comment]
Verified as fixed
