### ISSUE TITLE
List Checks Interface Type

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6129]
Not all checks are available for all interface types. For instance "Zero TCP Window" is not available for ZMQ interfaces.

This is to request in the page below, to add a new column that shows on what interface type (packet or ZMQ) a given check is effective.
![Screen Shot 2021-12-09 at 14 14 24](https://user-images.githubusercontent.com/4493366/145403128-e9506a33-82bc-4f1d-a08e-9ded2180adba.png)

**Comment by simonemainardi** [comment]
Added

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/3397663/146556412-7b14fd02-3728-43fb-9b78-053be166a818.png">

**Comment by simonemainardi** [comment]
Currently, column is shown for all families although only strictly necessary for hosts, local networks, and flows. This is due to DataTable which seems to be ignoring `visible` (https://datatables.net/forums/discussion/24035/columndefs-visible-false-not-working). Otherwise I would have selectively hidden the column depending on the family.

**Comment by lucaderi** [comment]
Verified as fixed
