### ISSUE TITLE
[FR] Problem with values of statistic (chart)

### ISSUE THREAD

**Issue by Urkioma** [ntop/ntopng#615]
Hi,

First, sorry for my bad English, I'm French but I'll try to explain you my problem, and I wish you'll could resolve it ... 

I don't know why but when I see the statistic chart the value of the max change when I choose an another time series. For 1 hour the max is less than for 10 mins ... 

For 10 mins : Max is 90.16 mbit
![20160615-162613_1280x1024](https://cloud.githubusercontent.com/assets/19954756/16084555/903cdc54-3319-11e6-841e-ed464bf2ce91.png)

For 1 hours : Max is  65.4 mbit .... 
![20160615-162622_1280x1024](https://cloud.githubusercontent.com/assets/19954756/16084596/ba11aa0a-3319-11e6-8126-1e276fa47ade.png)

**Comment by simonemainardi** [comment]
hi @Urkioma 

Interface speed is sampled every second so it will be almost impossible to render interface speed charts without aggregations as the number of datapoints quickly becomes too high. Therefore, before rendering charts, in order to reduce the number of datapoints shown, we make some aggregations that average out multiple points into a single one.

Your 10-mins char has very steep peaks between 40 and 80 Mbps (see the stripes on the right)
![image](https://cloud.githubusercontent.com/assets/3397663/16224521/a50be70a-37a2-11e6-82f8-7ebae41fe040.png)

When you zoom out, these peaks are averaged out and indeed you get an averaged maximum of approx. 60Mbps, that is, the average between 40 and 80Mbps. Using this aggregation is is possible to properly render charts at any timescale.

Although it may be questionable, we decided to report the chart maximum in the rightmost table as it would be more confusing to show a value that cannot be seen in the leftmost chart.
