### ISSUE TITLE
Enterprise dashboard scaling of graphs

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6165]
Dear ntop team
Is this correct?
<img width="530" alt="Screenshot 2021-12-28 at 00 03 07" src="https://user-images.githubusercontent.com/38549755/147758868-6b04e2b1-de7e-4986-a065-faa0755ce232.png">
<img width="549" alt="Screenshot 2021-12-28 at 00 03 16" src="https://user-images.githubusercontent.com/38549755/147758911-edecb4e0-2678-474a-a2bb-640871c2c3ac.png">
light blue traffic is shown higher as dark blue traffic, but light blue traffic is like 10x less as dark blue traffic.
thank you.

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu, yes it's correct, because currently that chart has to be read in a "strange" way:
The sum of the two interfaces is (for example) 1.08 Gb/s, the NET one is doing 960 Mb/s and the NW-WGW is doing the remaining traffic.
Practically speaking you have to see the 0 of the y-axis as the end of the below chart.
Please let me know if I was clear enough or not

**Comment by martinscheu** [comment]
ok thanks @MatteoBiscosi. maybe cloud do a radio button with "Total Traffic" ?

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu , unfortunately the current dashboard does not permit this (a new layer, like a new interface, is going to be put on the chart and it's going to show up incorrect data), however we are planning in the near future to rework the ntopng dashboard.
Sorry for the trouble.
