### ISSUE TITLE
initial admin password issue

### ISSUE THREAD

**Issue by juniorUniv** [ntop/ntopng#6222]
ntopng ver: 4.2.210426 (14127) - Community Edition
platform: Debian bullseye/sid [x86_64][Ubuntu 20.04.1 LTS] - 64 bit
deloyed by docker container

same problem as was defined in:
[](https://github.com/ntop/ntopng/issues/5385)

![image](https://user-images.githubusercontent.com/55238022/150297002-5ea5ebdc-e464-49df-83e0-b1413840b765.png)

Q:
1. Is there any password length limitation (for users)?
Because it wasn't possible to use:
- 50 characters, nor 40
- tested with or w/o special characters (alphabet + numbers as base of the generated psw) ... no way to accept such long pswds

Subsequently, I gave up and entered the default admin/admin there and used the password change in User Settings. Again, it did not allow me to use a long password (40 or 50). I tried the special characters again, without success.
Special characters were used in line with your ISO limitation noted.

Only max 30 characters were accepted.

**Comment by MatteoBiscosi** [comment]
Hi @juniorUniv the max length set to 30 characters is standard and after internal discussion we decided to not change it for security reasons.
Regarding the special characters, this behavior is changed with version 5.1, so please update to the latest version because we don't support older versions. In a few days the new 5.2 stable version is going to be released so you can wait for that if you prefer.
