### ISSUE TITLE
Refresh interval of the graph

### ISSUE THREAD

**Issue by ryota2425-murakami** [ntop/ntopng#6326]
I am trying to monitor traffic, but I am having trouble seeing it only about every 5 minutes.
Is there a way to monitor and visualize the flow at a high frequency?
Thanks again for your help.

![image](https://user-images.githubusercontent.com/29476187/154408976-6ed3a561-02cb-4c11-9eb4-56c49cc98f3b.png)

**Comment by victorvillatoro323** [comment]
Hi, I wanted to add a possible hint at what this is could be. I am also trying to understand how to view 5m interval for Statistics host details and I realized that '5m' appears only when I enable the use of influxdb timeseries database. If this does not help, I tried. GL.

**Comment by MatteoBiscosi** [comment]
Hi @ryota2425 , we already considered this possibility, but due to the huge number of hosts in a large network and the overhead it would have, we decided to just put the frequency of 5 minutes and 1 minutes for local hosts in case the user decides to use influxdb but not while using rrd. So like @victorvillatoro323 suggested, if you want that frequency for local hosts, please migrate to influxdb
