### ISSUE TITLE
Labels Cut in Historical Flow Analysis

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6411]
![image](https://user-images.githubusercontent.com/4493366/158388539-26b2b8d5-6e19-4456-8100-55f78cc07522.png)

**Comment by MatteoBiscosi** [comment]
Added more space to the Y axis labels, however I cannot add more then the current one. Added both tooltip on the chart and on the label in order to avoid this issue.

![Screenshot from 2022-03-15 17-07-38](https://user-images.githubusercontent.com/49585191/158421284-4fd4cea8-42fb-4d06-8c78-22e330c5fab6.png)
![Screenshot from 2022-03-15 17-07-44](https://user-images.githubusercontent.com/49585191/158421290-d14003c2-f757-45c0-aea6-7542c303391b.png)

**Comment by lucaderi** [comment]
Better now
