### ISSUE TITLE
Ntop stuck "We're almost ready.." screen after every restart

### ISSUE THREAD

**Issue by Syl4r-v** [ntop/ntopng#6443]
**Environment**:
* OS name: RHEL 8
* OS version: 8.5
* Architecture: x86
* ntopng version/revision: v.5.2.220315

**What happened**:
Ntop stuck "We're almost ready.." screen after every restart. Can't seem to find any error messages from logs. Only thing that seems to help is to delete tmp folder inside ntopng data folder before starting the software, but that needs to be done every time. 

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @Syl4r-v could you please check from `journalctl -u ntopng -e` and `systemctl status ntopng` if there is some error?

**Comment by Syl4r-v** [comment]
I sent you logs via email @MatteoBiscosi

**Comment by MatteoBiscosi** [comment]
Hi @Syl4r-v I've seen the log you sent, but everything seems alright except for a warning, could you please send me the ntopng.conf file? (still via mail)

**Comment by MatteoBiscosi** [comment]
Like said via mail, currently this problem is not fixable in the stable version, the only way to fix it is to migrate to the dev version, due to some changes we did to ClickHouse in the dev version this issue is solved.
The issue is created by the huge quantity of log produced by ClickHouse into the `/ntopng/tmp` folder
