### ISSUE TITLE
Timezone Not in Sync with ntopng

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6492]
In the ntopng GUI, the timezone shown in the browser is not in sync with the ntopng server instance. Currently, data is reported in the timezone of the browser instead of being shown in the server timezone.

This needs to be fixed and the valid timezone is the server one. In ntop.getInfo() method all the timezone information is reported, however, if for some reason it is not present, the browser timezone can be used as a fallback.

This said all the time in ntopng is internally reported as UTC, and only the web display of time information is localized.

Please fix this issue in the historical flows and alarms. Later we'll decide how to propagate the fix to the rest of the tool.

**Comment by uccidibuti** [comment]
Historical Flows and Alarms are fixed and now show server timezone also in datetime-picker and chart components. In Others page components (except table) still show browser timezone.

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/165383034-d03ced27-7f67-47ad-9fb2-8e86eb64b872.png)
I think that these changes have broken the time picket that shows the date in UTC and not in localtime (+2h with respect to UTC in the picture)

**Comment by lucaderi** [comment]
Verified as fixed

**Comment by fbrunken** [comment]
![ntopng](https://user-images.githubusercontent.com/115578557/236635930-89199953-ad09-4b1a-a02c-790034e16585.png)
It seems that the fix was not for all the areas where time is displayed. But I am on the West Coast of the US (GMT-7) and the time is displayed 2x right, but 1x wrong, on the bottom of the graph on the active monitoring display. And when it is wrong, it is the GMT time.
