### ISSUE TITLE
pcap download on interface not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6553]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu
* OS version: [e.g. 18.04] 20.04
* Architecture: [e.g. amd64] x86_64
* ntopng version/revision: [e.g. 5.1.211223] ntopng Enterprise L v.5.3.220405 rev.17390 (Ubuntu 20.04.4 LTS) | 

**What happened**:
pcap download on interface for e.g. 5min is not working. Either download does not start or it stops after 1 or 2min

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
This seems to be expected in the current implementation when the socket used to download the traffic is not as fast as the network interface receiving the traffic to be monitored. In order to overcome this, a new implementation is required, supporting a buffer and adding a packet drop counter to warn the user about what is actually captured out of the original traffic.
Developer Ref: NetworkInterface::deliverLiveCapture
