### ISSUE TITLE
Alerts Drops Check is Duplicated 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6575]
![Screen Shot 2022-05-06 at 15 37 23](https://user-images.githubusercontent.com/4493366/167144000-3db44260-e3b5-4337-8d63-4e5a1dca1b2f.png)

These two checks are different but with the same name: this needs to be fixed.

**Comment by MatteoBiscosi** [comment]
Due to the way ntopng is structured, for an alert that needs to be triggered on all interfaces (System too), you need to develop 2 different alerts, one for the system one and one for the interface one, this is the reason why the alert is duplicated. To clear the misunderstanding i changed the alert name.
![Screenshot from 2022-05-09 11-47-17](https://user-images.githubusercontent.com/49585191/167385068-90ffda72-2214-494e-a476-7c106c6606d7.png)

**Comment by lucaderi** [comment]
Verified as fixed
