### ISSUE TITLE
TZNAME is not set

### ISSUE THREAD

**Issue by djstarfox** [ntop/ntopng#6605]
I keep seeing this in the ntopng.log file and in system messages as a WARNING:
May 17 09:00:20 pie3 ntopng: [LuaEngineNtop.cpp:3199] WARNING: tzname is not set
May 17 09:00:20 pie3 ntopng[29498]: 17/May/2022 09:00:20 [LuaEngineNtop.cpp:3199] WARNING: tzname is not set

But there is nowhere to set timezone anywhere in the NTOPNG web GUI.

Timezone is set correctly on the Linux operating system:
# timedatectl
               Local time: Tue 2022-05-17 12:17:11 EDT
           Universal time: Tue 2022-05-17 16:17:11 UTC
                 RTC time: Tue 2022-05-17 16:17:12
                Time zone: America/New_York (EDT, -0400)
                System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

# ntopng --version
Version:	5.3.220508 [Enterprise/Professional/Embedded build]

# uname -a
Linux pie3 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

**Comment by MatteoBiscosi** [comment]
Hi @djstarfox we set that in the cookies, however this error happens when the cookie is deleted but the ntopng web gui still is running. You should logout and re-login (for example on my pc happens when i close my pc still running and relogin after a couple of hours and whenever I try to navigate in ntopng web gui this error is gonna happear, however after a couple of navigation, you should be automatically redirected to the login page.
I'll try to fix it and let you know.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
