### ISSUE TITLE
Interface aggregation view hides hosts

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6639]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223] : ntopng Enterprise L v.5.3.220520 (Ubuntu 20.04.4 LTS)

**What happened**:
Wenn using the interface aggregation feature, like ntopng -i en0 -i en4 -i view:en0,en4 
and then viewing a single interface, the Host Menu in the left bar disappears:
![image](https://user-images.githubusercontent.com/38549755/170690860-18ffb778-a7bb-441f-8693-f67210d23256.png)

When using the aggregated view, it is ok:
![image](https://user-images.githubusercontent.com/38549755/170690956-004a9aa1-eb28-4a7f-8849-c6569a240f2d.png)

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu , this is normal, in viewed interfaces, there is no concept of hosts, if you want to find an host you have to check it in the view interface.
In fact if you go to the flow page of the viewed interface (`ens160`) you can see that there is not hyperlink to the host, instead if you go to the view interface there is.
This is developed in this way for two reasons:
- to not duplicate information (reduce memory usage).
- because if you have an aggregate view then this means that the user want to check this information aggregated not disaggregated (so there is no usage in checking hosts in the viewed interface).

Let me know if everything was clear :)
