### ISSUE TITLE
Score Threshold Exceeded provide context

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6714]
**What would you like to add or change?**:
The alert "Score Threshold Exceeded" is showing the score number of a host when passing over the limit:
<img width="1257" alt="Screenshot 2022-06-18 at 09 29 33" src="https://user-images.githubusercontent.com/38549755/174427781-dec62166-355b-4169-805e-9c1c563a42f4.png">

But no further context is available, like what issues / anomalies on that host lead to the high number.
If possible, please provide more context, hints what to search for on that host.
Thanks!

**Why do you and others need this?**:

**Comment by lucaderi** [comment]
In essence add the ability to filter host flows with score > 0

**Comment by NicoMaio** [comment]
Enhancement implemented. 
There are now two links in the description of the Score Threshold Exceeded alert: check live and check historical. Clicking on check live icon will redirect the user to the live flows page of the host that triggered the alert. Otherwise, by clicking on check historical icon, the user will be redirect to the historical flows page (with score > 0 which contributed to trigger the alert) of the host.

![Score Threshold Exceeded alert description](https://user-images.githubusercontent.com/55502486/217498695-85221d31-be04-4305-990b-fe51f1522a55.png)
