### ISSUE TITLE
Enterprise dashboard set time to host time

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6715]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223] ntopng Enterprise L v.5.3.220618 (Ubuntu 20.04.4 LTS) 

**What happened**:
Please set dashboard time to system time, so it is consistent with flow / historical flow.
thank you.

<img width="1034" alt="Screenshot 2022-06-18 at 15 43 20" src="https://user-images.githubusercontent.com/38549755/174440346-c8de45c9-2b94-4dd0-88da-c58e2d42cdb4.png">

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu could you please update and let me know, because as you can see in my system, everything works fine (I have a browser UTC +2 and a system UTC +5 and everything is printed in UTC +5)
![Screenshot from 2022-06-20 13-32-11](https://user-images.githubusercontent.com/49585191/174560219-98821fe1-3934-4859-bff1-f431d42957f1.png)

**Comment by martinscheu** [comment]
thanks @uccidibuti
