### ISSUE TITLE
Missing SysVInit Scripts in Debian Packages

### ISSUE THREAD

**Issue by Ryushin** [ntop/ntopng#6827]
Most of the Debian packages do not include a SysVInit script, including ntopng.  It would also be nice to see manual instructions to add the appropriate apt package source in the Download web page.  I run Devuan and the install script creates the wrong apt package source and I had to modify it manually.  Though actually seeing the apt location sources on the web site would have made my life easier.

**Comment by cardigliano** [comment]
@Ryushin we used to support init before, but with the adoption of systemd on all distributions we did the migration and decided to support a single mechanism as it was not really worth to support many.
If there are some changes required to support Devuan, please feel free to contribute (we appreciate PRs), as it's not one of the distributions we officially support. Thank you.

**Comment by Ryushin** [comment]
Debian supports and provides other init systems other than systemd.  Such as SysVinit, OpenRC, RunIT, etc.  
Please see: https://wiki.debian.org/Init
Since you are providing Debian packages, sysvinit scripts should also be provided.  Devuan uses something like 98% of the original packages from Debian.  Only certain packages are forked to provide better init compatibility and almost all of these are desktop UI related packages, not daemons.

Please support alternative init systems as Linux is about choice.

**Comment by lucaderi** [comment]
We're not super-experts of all these init systems, so please provide us a pull request so we can add them in out packages. Thanks you

**Comment by Ryushin** [comment]
Really to support SysV and OpenRC, just add the init scripts back.

**Comment by lucaderi** [comment]
We have decided not to support SysV init scripts as even debian 12 is also using systemd. If you want them back please send use a pull request

**Comment by Ryushin** [comment]
@lucaderi, Debian supports multiple init systems.  The default install uses systemd, but Debian does support OpenRC, Sysvinit, and Runit as well.

**Comment by procule** [comment]
@lucaderi I know I'm a bit late to this discussion, but I completely agree with @Ryushin.  

I understand that maintaining scripts for every init system is not feasible, but SysV init is a long-standing standard and remains widely used. In this case, retaining a minimal `/etc/init.d/ntopng` script would require little effort, as much of the necessary logic already exists in the Debian package scripts. This would ensure compatibility without significantly increasing maintenance overhead.  

For example, the `postinst` script still includes logic to handle SysV init:

```# Start service after upgrade/install
echo "(Re)Starting ntopng..."
if hash systemctl 2>/dev/null; then
    systemctl daemon-reload
    systemctl reset-failed

    # Enable service on first installation only
    if [ -z "$PREV_VERSION" ]; then
        if hash deb-systemd-invoke 2>/dev/null; then
            deb-systemd-invoke enable ntopng
        else
            systemctl enable ntopng
        fi
    fi

    # Start service if enabled
    if hash deb-systemd-invoke 2>/dev/null; then
        systemctl -q is-enabled ntopng && deb-systemd-invoke restart ntopng
    else
        systemctl -q is-enabled ntopng && systemctl restart ntopng
    fi
    systemctl restart 'ntopng@*' --all
elif [ -f /etc/init.d/ntopng ]; then
    if [ -z "$PREV_VERSION" ]; then
        update-rc.d ntopng defaults 93 >/dev/null
    fi

    # Restart service after upgrade/install
    /etc/init.d/ntopng restart
fi
```
This shows that the SysV init script was already integrated into the package and would only require minor updates to remain functional. However, despite this, it was removed in favor of a systemd service file that does not fully leverage systemd’s capabilities.

A closer look at the `ntopng.service` file reveals that it still relies on shell-based commands to manipulate configurations before execution:

```
[Service]
Type=simple

Environment=UNIT_NAME=%N


ExecStartPre=/bin/sh -c '/usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true'
ExecStartPre=/bin/sh -c '/bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw'
ExecStartPre=/bin/sh -c '/bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true'
ExecStartPre=/bin/sh -c '/bin/sed "/^[ ]*-e.*$\\|^[ ]*-G.*\\|^[ ]*--daemon.*\\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf'

ExecStart=/usr/bin/ntopng /run/ntopng.conf

ExecStopPost=-/bin/rm -rf /run/ntopng.conf /run/ntopng.conf.raw /run/ntopng.pid

Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
Alias=
```
This approach effectively recreates the logic of an init script, but in a more indirect and complex way. Instead of using systemd-native mechanisms, multiple `ExecStartPre` statements modify configuration files dynamically before starting the service.

Given that the previous SysV init script already existed and the systemd service file still depends on shell-based workarounds, maintaining a minimal `/etc/init.d/ntopng` script could still be beneficial. It would require little effort while ensuring broader compatibility for users running SysV init or alternative init systems.  

In fact, if the intent is to handle setup before launching `ntopng`, then instead of relying on multiple `ExecStartPre` steps, simply using:

```
ExecStart=/etc/init.d/ntopng start
ExecStop=/etc/init.d/ntopng stop
```

would achieve the exact same result, without introducing unnecessary complexity.

Additionally, if the SysV init script had been retained, enforcing these parameter restrictions could have been handled more naturally within the script itself, avoiding the need for a regex-based workaround in `ExecStartPre`. With SysV init, these checks could be implemented in a straightforward and transparent manner, making them easier to maintain and debug.  

Given this, it may be worth reconsidering whether keeping a lightweight SysV init script could actually streamline configuration handling while maintaining full systemd support.
