### ISSUE TITLE
Redis RRD timeseries corrupted? Cannot write data - timeseries.lua / rrd.lua fails

### ISSUE THREAD

**Issue by phantomski77** [ntop/ntopng#6828]
**Environment**:
* OS name: Debian
* OS version: 11.4 Bullseye
* Architecture: Raspberry Pi 4 - arm64
* ntopng version/revision: 5.5.220825

**What happened**:
Using timeseries driver RRD, whenever I have any timeseries enabled for writing in Settings / Timeseries, following types of errors are produced in the log (this one is for _Interfaces Timeseries_ enabled):
```
25/Aug/2022 10:14:51 [timeseries.lua:32] [rrd.lua:303] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/traffic_rxtx.rrd][1661422491:53220754:508020705] failed [reached EOF while loading header rrd->ds_def]
25/Aug/2022 10:14:33 [timeseries.lua:32] [rrd.lua:303] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/bytes.rrd][1661422473:561046692] failed [reached EOF while loading header rrd->ds_def]
25/Aug/2022 10:14:33 [timeseries.lua:32] [rrd.lua:303] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/packets_vs_drops.rrd][1661422473:528373:219040] failed [reached EOF while loading header rrd->ds_def]
```

**How did you reproduce it?**
Disable / Enable timeseries category in the Settings

**Additional Information**
I was using `/var/lib/ntopng` as a persistent data storage since version 5.1. It worked ok in versions 5.3, but started producing errors in 5.5. It is possible that either redis version or database architecture or access rights changed in between versions and now isn't compatible. If there's no way how to solve the issue while keeping the data, is there a way how to reset/clear the redis database?

**Comment by MatteoBiscosi** [comment]
Hi @phantomski77 sorry for the late response. We did a major change to the timeseries because they were wrongly created (Unfortunatly RRD timeseries cannot be modified), so you have to delete those timeseries and start anew.
To remove the timeseries database you have to delete the files directly from /var/lib/ntopng (in the specific case those corrupted).
Before removing them, stop ntopng, remove them (I suggest on removing one by one just the corrupted ones, otherwise you can directly remove `/var/lib/ntopng/*` but you might delete even non corrupted data) and then restart ntopng and you should not have problems.

**Comment by phantomski77** [comment]
Hi @MatteoBiscosi,
absolutely no problem, thank you for your response. After removal and restart everything seems to be working ok. New RRDs created, no error messages.
