### ISSUE TITLE
Allow to set interface "custom name" from command line

### ISSUE THREAD

**Issue by cjeanneret** [ntop/ntopng#686]
Hello,

It would be great if we could set the Custom Name label for the interface directly from the command line. Something like:

``` Bash
ntopng -i eth0=my_custom_name 
```

would be good (note: ":" is a reserved char, "," is already taken by ntopng and ";" might be confusing)

Doing so will avoid the need of going in the interface settings from the web interface, and directly provide a good display.

Thank you!

Cheers,

C.

**Comment by simonemainardi** [comment]
as a design choice -- in order to keep the arguments as simple as possible -- we do not allow the specification of any custom interface setting (e.g., sampling / speed / custom names etc) from the command line. All these settings must be specified from the web interface. As the "custom name" is another user-defined setting, we cannot accomodate this feature request.
