### ISSUE TITLE
ntopng -ndpi-protocols -p /var/lib/ntopng/protos.txt failed to parse lines

### ISSUE THREAD

**Issue by LennyV95** [ntop/ntopng#6933]
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 4.4.182-1.el7.elrepo.x86_64
Architecture: x86-64

ntopng version is 5.1.2.11018
nDPI: 4.1.0

APCON runs nTOP on our virtual desktop linux side for people to try it out. We have a customer who is trying our ntop community package running on our IntellaStore system and client really likes it. He wants to add custom ports. There seems to be an issue running the command to enable custom application list. We created the protos.txt file, stop ntopng service and run the command:

sudo systemctl start ntopng -ndpi-protocols -p /var/lib/ntopng/protos.txt

I get the ‘failed to parse lines dpi-protocols. The ntopng log file has nothing and /var/log/messages has nothing

the file has these two lines only:
tcp:9002@Elasticsearch
tcp:5601@Kibana

**Comment by MatteoBiscosi** [comment]
Hi @LennyV95 you have to update ntopng to the latest version (5.5 version) otherwise we cannot provide support. Other then that, to run ntopng, you don't have to pass command line options to the systemctl; you have to add these options to the ntopng configuration file.
You can find the configuration file in /etc/ntopng/ntopng.conf
for more info please follow the ntopng guide https://www.ntop.org/guides/ntopng/how_to_start/running_as_a_daemon.html
