### ISSUE TITLE
Invalid check load

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6989]
25/Nov/2022 16:16:10 [FlowChecksLoader.cpp:254] WARNING: Unable to find flow check 'potentially_dangerous': skipping it

**Comment by MatteoBiscosi** [comment]
The problem is the following: in a brief time, ntopng had this alert enabled but without a flow check implemented (due to an error).
in the recent time i fixed it, moving this no more used alert into the attic folder. However this print is still going to be printed on the output because this is going to take a look at the configuration, find this alert (no more present in ntopng) but not find the check.
The way to fix this is by doing a factory reset of ntopng checks (possible both from the `Checks` page or from the `Manage Configuration` page) and gracefully shutdown ntopng and then restart it.
After that the issue should not be printed again in the trace.

**Comment by lucaderi** [comment]
Ok let's leave it as is
