### ISSUE TITLE
unknown traffic in realtime graphs but not in live flows

### ISSUE THREAD

**Issue by 61swong** [ntop/ntopng#7006]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_86
* ntopng version/revision: v5.5.221205

**What happened**:
Master interface with two custom filters (ether host <MAC addr>) in order to disaggregate all traffic from the SPAN sessions on the switch. I noticed 'unknown' traffic which is shown in 'realtime' graphs but nothing is in the live flows.

**How did you reproduce it?**
Remove the custom filter.
Restart ntopng process.
Create the custom filter with a MAC address for traffic disaggregation.
Restart ntopng process.

**Debug Information**:
Screenshot can be provided by email if needed.

**Comment by MatteoBiscosi** [comment]
Hi @61swong sorry for the late response. The problem is the following: the realtime chart does not update the applications seen.
This causes your problem, there are many cases in which it can appear, for example, you wait for a minute at most in front of the chart, when the chart was loaded you have Unknown traffic, but now you have no more unknown traffic in the live flows, however the tag is still there.
An other way to show this problem is simply because when you take a look at the chart, you find Unknown traffic (because for example it's the first packet of a flow seen by ntopng), then you switch to the live flows and meanwhile ntopng recognized that traffic and you have no more Unknown traffic.
We are planning in the early next release (ntopng dev version) to renew the dashboard and change it, in that way the problem should no more pop up

**Comment by 612wong** [comment]
Hi @MatteoBiscosi we used MAC address based traffic disaggregation and hence I didn't expect traffic still being classified as unknown before the completion of DPI. Besides the live flow table shows nothing in the mean time which puzzled me if this is expected.
