### ISSUE TITLE
After server restart ntopng sometimes hang on startup

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7098]
CentOS 8 Stream
ntopng Enterprise L v.5.4.230112

What happened:
After server restart ntopng sometimes hang on startup.

Jan 12 23:00:17 ntopng systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Jan 12 23:00:17 ntopng systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Jan 12 23:00:17 ntopng ntopng[2274]: 12/Jan/2023 23:00:17 [Redis.cpp:151] Successfully connected to redis 127.0.0.1:6379@0
Jan 12 23:00:17 ntopng ntopng[2274]: 12/Jan/2023 23:00:17 [Redis.cpp:151] Successfully connected to redis 127.0.0.1:6379@0
Jan 12 23:00:17 ntopng ntopng[2274]: 12/Jan/2023 23:00:17 [NtopPro.cpp:315] [LICENSE] Reading license from /etc/ntopng.license
Jan 12 23:00:17 ntopng ntopng[2274]: 12/Jan/2023 23:00:17 [NtopPro.cpp:486] [LICENSE] /etc/ntopng.license: found valid Enterprise L license
Jan 12 23:00:24 ntopng ntopng[2274]: [boot.lua:24] WARNING: No connectivity detected, ntopng will run in offline mode
Jan 12 23:00:24 ntopng ntopng[2274]: 12/Jan/2023 23:00:24 [boot.lua:24] WARNING: No connectivity detected, ntopng will run in offline mode

After manual "systemctl restart ntopng" starts normally.

**Comment by MatteoBiscosi** [comment]
Hi @atemix , when this thing happens because you probably don't have the --offline option enabled, at startup ntopng tries to ping a remote configurable server (e.g. google.com) to understand if the machine has connection. When happens (like in your case above) that ntopng has no internet connection it waits a couple of minute for the response from the remote server and then starts.
So i suggest to add the --offline option to your configuration file.
If you already have it, then please send me the configuration file.

**Comment by atemix** [comment]
@MatteoBiscosi All instances configured for offline mode. Waiting 5+ minutes if its starts, but no result.
Send you conf file.

**Comment by MatteoBiscosi** [comment]
The issue should be fixed with update that is going to be available in a couple of hours, please let me know

**Comment by atemix** [comment]
@MatteoBiscosi fixed, thx
