### ISSUE TITLE
Record historical data also when ingesting pcap files

### ISSUE THREAD

**Issue by marcoreps** [ntop/ntopng#7180]
**What would you like to add or change?**:
I am using https://github.com/ntop/ntopng/blob/dev/tools/fritzdump.sh to extract pcap files from my router. Handing these over to ntopng via i.e. `-i /pcap/eth2` works great, but it seems like no timeseries data is recorded (I have only tried RRD, not InfluxDB). I am not seeing any errors in the logs, just a " No data found" or similar info whenever trying to access historical data in the web GUI. It makes sense because we are already looking at historical data in a file. But because the files created with this method are rather short-lived it would be great to have the option of recording timeseries data from pcap files.

**Why do you and others need this?**:
FritzBox routers are very common in Europe and capturing long term traffic metadata with this effortless direct interface would be tremendously useful for many

**Comment by MatteoBiscosi** [comment]
We disabled the recording of historical data when ingesting pcap files, simply because when we analyze the pcap, all the traffic is shown as live traffic, for this reason no historical data is recorded for pcaps, so no disk, ecc, is needed if everything is seen as live traffic.
We will discuss internally if we are able to find a solution.

**Comment by MatteoBiscosi** [comment]
After internal discussion, we decided to not save record historical data when ingesting pcap files

**Comment by hgw77** [comment]
I was also wondering why I couldn't see historical data. Can you explain why it was decided to disable this option? Because it would be useful for the `Fritzbox` use case. Is there a technical reason? Otherwise, it would be nice if the user could enable this feature when needed (disabled by default) :-)
