### ISSUE TITLE
apt full-upgrade issue on Raspberry Pi Lite OS

### ISSUE THREAD

**Issue by JenyaPaykin** [ntop/ntopng#7250]
Since last I week unable to perform apt full upgrade even after clean OS installed on SD card

E: Failed to fetch http://raspbian.mirror.net.in/raspbian/raspbian/pool/main/s/sudo/sudo_1.9.5p2-3+deb11u1_armhf.deb  Connection failed [IP: 103.195.68.3 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Any solution ?

**Comment by takenek** [comment]
"Connection failed [IP: 103.195.68.3 80]"

**Look:**
root@zabbix:~# nc -zv 103.195.68.3 80
Connection to 103.195.68.3 80 port [tcp/http] succeeded!

root@zabbix:~# wget http://raspbian.mirror.net.in/raspbian/raspbian/pool/main/s/sudo/sudo_1.9.5p2-3+deb11u1_armhf.deb -O /dev/null
--2023-02-22 15:32:19--  http://raspbian.mirror.net.in/raspbian/raspbian/pool/main/s/sudo/sudo_1.9.5p2-3+deb11u1_armhf.deb
Translacja raspbian.mirror.net.in (raspbian.mirror.net.in)... 103.195.68.3, 2001:df5:fc00:fffb::3
Łączenie się z raspbian.mirror.net.in (raspbian.mirror.net.in)|103.195.68.3|:80... połączono.
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 200 OK
Długość: 991976 (969K) [application/x-debian-package]
Zapis do: `/dev/null'

/dev/null                                                       100%[====================================================================================================================================================>] 968,73K  1,15MB/s     w 0,8s

2023-02-22 15:32:20 (1,15 MB/s) - zapisano `/dev/null' [991976/991976]



**Check Your internet connection because i can connect and download file ;-)
And one more are you sure this is properly place to report problem with Mirror of SUDO package :-)?**

**Comment by lucaderi** [comment]
Sorry to ask: why are you opening a ticket here for a problem you have with http://raspbian.mirror.net.in/
