### ISSUE TITLE
Errors during Clickhouse Alert Insert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7282]
01/Mar/2023 18:17:57 Cannot parse input: expected '\'' before: 'generateUUIDv4(), 24, 2, 4, \'x.x.x.x\', 0, \'\', \'US\', 1, 0, 1, 0, 1677690723, 1677691077, 5, 128, 60, 0, 65535, \'{"alert_generation": {"script_key":"custom_'

**Comment by MatteoBiscosi** [comment]
Despite the fact that this warning is displayed in the clickhouse system.errors table, it is not an error, in fact, the same exact alert that triggers this warning is inserted correctly in clickhouse.
Moreover from the clickhouse error logs (in ubuntu22 distro can be found in `/var/log/clickhouse-server/clickhouse-server.err.log`) no error of that type is displayed.
The problem rise up just by using the my_sql library and not the clickhouse-client.
So in order to remove this warning, all the alerts have to be inserted in the tables by using clickhouse-client (like for the flows, in fact no alert of that type arise when adding flows in the db).
An other warning that is displayed in the log is instead 
`2023.03.02 15:23:55.576437 [ 518941 ] {} <Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3.`
And this is most likely due to the huge number of flows inserted in batch into clickhouse.
This error is discussed in this clickhouse issue https://github.com/ClickHouse/ClickHouse/issues/23719 and this one https://github.com/ClickHouse/ClickHouse/issues/4959

**Comment by lucaderi** [comment]
Leaving as is for now
