### ISSUE TITLE
Feature Request:  Activities totals

### ISSUE THREAD

**Issue by DigiAngel** [ntop/ntopng#729]
Instead of just having 0.00 B it would be neat to have totals on the right side:

```
![screenshot from 2016-09-06 05-12-43](https://cloud.githubusercontent.com/assets/947191/18271820/6e2abc9e-73f1-11e6-9c85-3f7f8c26ff93.png)

Thank you.
```

**Comment by emanuele-f** [comment]
The values you read in the graph are referred to a specific time interval. When the mouse is outside graph area, last time interval is used.
The activity detection and graph is an experimental feature (right now you must use the --enable-flow-activity flag in order to enable it) and the front-end we use has some problems so I cannot agree to work on this feature.
I close this issue for now. Thank you for the feedback.
