### ISSUE TITLE
ntopng - "database schema is being updated..."

### ISSUE THREAD

**Issue by njcwotx** [ntop/ntopng#732]
After restarting ntopng, I get a message "The database schema is being updated to include the most recent changes. Please wait, this is normal.  You will be redirected as soon as the changes take effect."

At this point its been a few hours.  This happened a few days ago, but I deleted all the folders and started over.  We just purchased a pro license and applied yesterday.  If I blow away the folders again, I wonder what this does to the licensing as well. 

I looked in logs and find no errors.  Is there a way to fix this without blowing away all the history?

ntopng version 2.4.160908-1305.x86_64  installed from rpm
redis 2.8.19-2.l7.x86_64 installed from rpm
Centos 7

Update:
Commenting out the -F to send the historical data to mysql allows the web interface to work again.  I am clearing the history databases again to reset.  Lic info survives this so at least I was able to get it running again.  However, I hate to have to blow away history every few days.

**Comment by simonemainardi** [comment]
Hi,

What happened is that you updated ntopng to a new version that introduced some changes in the MySQL database schema. In these cases ntopng tries to automatically migrate the old schema to the new one and this is why you get the message _"The database schema is being updated to include the most recent changes. Please wait, this is normal. You will be redirected as soon as the changes take effect."_

Depending on the size of the existing MySQL database, this can be a (very) long operation. Also, it has nothing to do with the clearing of folders (it's just database). If you can't wait for the completion then, for example, you could start on a clean database and then re-import the old data with a manual query.

However, I have checked that no additional mysql schema changes have been applied since ntopng version 2.4.160908-1305.x86_64. so you won't have to undergo new schema migrations.

**Comment by njcwotx** [comment]
It has happened again this am.  Restarted ntopng and it reoocurred.  I didnt perform any upgrade until yesterday after the first 2 times it started and it had broken.  It was originally installed a few weeks ago fresh.  If I delete the ntopng mysql database for history, I can get it to start up again.

ntopng.log shows 3 lines at bottom of log.
MySQL schema update. Altering table flowsv4: renaming BYTES to IN_BYTES and adding OUT_BYTES
MySQL schema update. Altering table flowsv6: renaming BYTES to IN_BYTES and adding OUT_BYTES
MySQL schema update. Altering table flowsv4: changing engine from InnoDB to MyISAM.

as I was writing, it finally completed, but the mysql db with history was much smaller today.  Several more update messages appear in the logs before it started.  There was an 8 minute gap after the last line above before the next event in the mysql schema update.  DB was around 6.7G this am.  Yesterday it was 68G.

FYI, I just did a restart of the service and no update/upgrade of the software since removing the database and starting over yesterday.

At this point, I can work with it, but ill post if another restart stops it again.

**Comment by njcwotx** [comment]
Another restart of the ntopng.service today and another very long "MySQL schema update. Altering table flowsv4: changing engine from InnoDB to MyISAM." in the ntopng.log.

I did no software update, but every time I restart the service the historical database goes though a schema update.  The larger the database grows, the longer this takes.  It was at 52GB before the restart and took 58 minutes to do the schema update.  This was a 4-5 day old database, I can only imagine the size it will be after a month.   I set the history to 3 days for now, but I imagine I will have to set longer very soon.

As you mentioned, if there is no schema update in the version I am using, why does it have to update the schema after every restart?  I can understand one schema update after an upgrade, but each time I restart a service seems to me uneccesary.
