### ISSUE TITLE
No Click House Tab at Preferences

### ISSUE THREAD

**Issue by marcohueb** [ntop/ntopng#7579]
ntopng Enterprise L v.5.6.230531 rev.20531 (Debian GNU/Linux 11 (bullseye))

**What happened**:
I am using Click House on same machine but do not have the Click House Prefences shown in gui like in this bug https://github.com/ntop/ntopng/issues/7569

The problem is, that i have to adjust the data retention time to a lower value because the 1tb disk is full after 1 to 2 weeks (default value is 60 days)

clickhouse is integrated in ntopng.conf file with following commands: 
-F="clickhouse;127.0.0.1;ntopng;default;xxx"

Can you please verify if its a bug, that i dont see the Click House Preference Tab in GUI like the BUG Screenshot mentioned above.

**How did you reproduce it?**

**Debug Information**:

**Comment by lucaderi** [comment]
You need to update to a more recent ntopng version in order to see the clickhouse preference
As of the other question please set the data retention here 
<img width="1499" alt="Screenshot 2023-06-22 at 16 49 48" src="https://github.com/ntop/ntopng/assets/4493366/30dc0803-b410-4307-ac94-045644b8d23e">
