### ISSUE TITLE
Too many chart entries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7610]
In case you have too many (> 5) entries the chart is unreadable
<img width="1433" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/90486bc7-cf6a-4ea8-8fe4-c169a1e8dfc8">

In this case return the first 5 entries (those more popular) and add "other" that contains all the remaining manufacturers

**Comment by lucaderi** [comment]
Half fixed: other entry is missing
<img width="1378" alt="Screenshot 2023-07-10 at 21 42 14" src="https://github.com/ntop/ntopng/assets/4493366/5f265be5-a912-47bc-a81a-64eb65da8fdd">

**Comment by MatteoBiscosi** [comment]
This issue is not present, even in the screenshot above, the purple entry is for VMware and being lesser then 10 entries, no other label is needed, like for the other pages.
![image](https://github.com/ntop/ntopng/assets/49585191/eb6f5b54-fe25-4397-b0c1-434c7a32a5f9)
![image](https://github.com/ntop/ntopng/assets/49585191/cb06667e-1980-4e5c-8542-498b884c4ad2)
In case more then 10 entries are present, the tenth entry is going to be the "Others"

**Comment by lucaderi** [comment]
Verified as fixed
