### ISSUE TITLE
SNMP Chart Information is too long making it unreadable 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7634]
When moving the mouse over charts the dialog open has names way too long. For instance, the interface Alias is instead of the name (shorter) I used, labels are long (why add bps if the measurement is the unit?). The result is unreadable
<img width="299" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/0c0c1f71-f9b3-417d-a67d-fb860fb2f89d">
This is another example of oddness

<img width="1139" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/9cede731-2eec-4380-95ee-9bce55845fb7">

**Comment by lucaderi** [comment]
1. remove Units from info dialog and tables below
<img width="616" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/9bce7701-1683-4484-8f57-1ac79a4ae9a1">
2. Colors are basically alike and hard to distinguish. Please use a different palette. Also remove breaks in strings so they can go in the same line
<img width="595" alt="Screenshot 2023-07-10 at 21 33 56" src="https://github.com/ntop/ntopng/assets/4493366/73bb2f35-ffcc-44da-b394-6f1834bbb2f1">

**Comment by lucaderi** [comment]
Still broken
![Screenshot 2023-07-12 at 14 44 46](https://github.com/ntop/ntopng/assets/4493366/e15637dd-cbfd-4775-bb64-0728884a1553)

Also note that the device name can be shortened or omitted

Furthermore add a - or something (e.g. Iface X) to the interface name
![Screenshot 2023-07-12 at 14 45 35](https://github.com/ntop/ntopng/assets/4493366/86b723a5-4074-4333-8758-4dbcee9b7e49) as just the number is misleading

**Comment by MatteoBiscosi** [comment]
Unfortunately it is not possible to shorten the string or remove the device name (due to a possible misleading in other time-series) so the only possible way to do it is by adding a - between the interface and the device
![image](https://github.com/ntop/ntopng/assets/49585191/919a2941-be81-42f8-a632-adfb1d4c81c1)
Fixed the issue with the top table too
![image](https://github.com/ntop/ntopng/assets/49585191/816b6be5-0a97-47c9-adae-689fae1ddcbd)

**Comment by lucaderi** [comment]
Verified as fixed
