### ISSUE TITLE
Improve SNMP Host Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7640]
In this SNMP page I analyze a single SNMP device

<img width="952" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/ee93ad52-4087-4ba6-b069-876b5b77ffb9">

down the page I see a table 

<img width="1310" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/acba9d62-bbf7-4e39-91ab-b7c3b3c82146">

with various problems
- remove the interfaceId that is something "internal"
- Create two table columns: one for the name and one for the alias
- remove the redundancy in the dropdown menu

**Comment by MatteoBiscosi** [comment]
The name is already fixed
![image](https://github.com/ntop/ntopng/assets/49585191/7109342f-7134-442d-b644-ffa4035ee1db)

**Comment by MatteoBiscosi** [comment]
Separated the two columns, if alias and name are equals, just the name is going be shown; if no name is available then the interface id is going to be used
![image](https://github.com/ntop/ntopng/assets/49585191/e849924b-9ab2-4eb6-9463-f1145bad99ed)
The redundancy in the dropdown is not to be removed, because in case more timeseries with different Top Tables are going to be added, there could be some confusion with which entry shows what

**Comment by lucaderi** [comment]
Broken after the last changes
![Screenshot 2023-07-12 at 15 00 21](https://github.com/ntop/ntopng/assets/4493366/fd62f36c-4b60-40e6-9fb8-e4befaaf753c)

**Comment by MatteoBiscosi** [comment]
Issue fixed with the latest release

**Comment by lucaderi** [comment]
Verified as fixed
