### ISSUE TITLE
navigating back from flow info query is  re-executed on db

### ISSUE THREAD

**Issue by lucadistefano** [ntop/ntopng#765]
when you press the back arrow from info page of flow in historical data, the originating query is reexecuted instead to show the previous result.

![selection_470](https://cloud.githubusercontent.com/assets/1080723/18825897/d511e5ca-83ca-11e6-9b40-7fa75f7ffd6a.png)

**Comment by emanuele-f** [comment]
What you ask cannot be implemented in an easy way since HTTP protocol is stateless and historical data continuosly changes. Database caching should make your query run faster and you should not experience a significant delay.
If you still want to keep previous query results, please open the flow into another tab instead.
