### ISSUE TITLE
Missing Chat menu from Flow Exporters

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8118]
1. Take a flow exporter and click on the interface Id
<img width="1268" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/938ca66c-daca-4d00-89e2-5a448d6daa87">
2. In the new page the graph icon is missing from the top menubar
<img width="649" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/640122c0-8f16-49cd-ad18-c4154cf6d55d">

**Comment by MatteoBiscosi** [comment]
This behavior is correct, because, in the first screenshot the charts you have are regarding the Probe (exporter) in the second one, you are checking the SNMP.
Those two have two different charts.
![image](https://github.com/ntop/ntopng/assets/49585191/8b0b629b-4442-438d-a462-645b15fb64b5)
![image](https://github.com/ntop/ntopng/assets/49585191/a5219195-007f-4d90-9186-0bf2741888e4)
You need to enable both preferences if you have to access both charts
