### ISSUE TITLE
SNMP Alerts Engaged are not released

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#8178]
The SNMP alerts, triggered by the rules, are not released like other alerts. 
In the SNMP alert scenario, the method `ntop_release_triggered_alert` in `LuaEngineNtop.cpp` is called from `NetworkInterface.cpp` within the `processExternalAlertable` method and returns nil.

**Comment by MatteoBiscosi** [comment]
The issue seems working correctly now, as it's possible to see from the pictures, the alert correctly went from engaged to released:
![image](https://github.com/ntop/ntopng/assets/49585191/a7563b27-20d4-4036-b712-d805335d4bb1)
![image](https://github.com/ntop/ntopng/assets/49585191/22b70ef3-9d9f-45d9-872e-cf982bf84d24)
