### ISSUE TITLE
Host periodic/timeframe reports

### ISSUE THREAD

**Issue by james-shumba** [ntop/ntopng#825]
I would like to have host reports for individual hosts showing the realtime, daily, weekly,monthly and annual data specific to a selected host. At the moment clicking on home then reports gives a report with adjustable time frame but its not per host, its for all the traffic.

**Comment by emanuele-f** [comment]
Hi James, you can get the per-host report only for hosts in your local network. When starting ntopng, specify the -m parameter with the list of your local networks (e.g. ntopng -m "192.168.1.0/24,192.168.2.0/24"). Then, in the host page, you should see a "Local" label instead of "Remote". Click on the "report" icon at the top of the bar to get the host report.

![host_page](https://cloud.githubusercontent.com/assets/5488003/20351458/2e07bd10-ac13-11e6-9ae6-21ad5918031e.png)
![report_page](https://cloud.githubusercontent.com/assets/5488003/20351464/3205f06c-ac13-11e6-8244-b472b62801c5.png)

**Comment by james-shumba** [comment]
Hi, its running on windows and I dont seem to have those options available. see below

![capturexx](https://cloud.githubusercontent.com/assets/23502107/20351724/f07ab2fe-ac1c-11e6-9311-4e57421e3d15.JPG)

**Comment by emanuele-f** [comment]
You miss the -m parameter, either specify it from command line or modify you ntop service file

**Comment by james-shumba** [comment]
On the command line its not a recognized command.
Advise how i can go about changing the service

**Comment by emanuele-f** [comment]
Note that the per-host report page is fairly new in ntopng, and it is not currently available in the windows builds. Please consider switching to rolling development versions available for other platforms (Ubuntu http://packages.ntop.org/ubuntu/16.04/x64/ntopng/ for example).

Nevertheless, in order to access many host graphs and related feature, setting the -m flag is essential. 
The procedure is explained in the manual https://github.com/ntop/ntopng/blob/dev/doc/UserGuide.pdf

**Comment by harmane** [comment]
Is this available in the stable releases? I have both a pro version and community, both on apt-ntop-stable, that do not have this option. Local networks are set in ntopng.conf accordingly.

**Comment by emanuele-f** [comment]
@james-shumba and @harmane the per host report is currently available in the latest pro development version.
Please note that the feature is just a _trial_, we plan to move it to the new enterprise version of ntopng, with extended features like report pdf export and graphs. Please note that enterprise licence is not currently available in the shop, we only provide free trial versions, time limited, on request.

**Comment by james-shumba** [comment]
So even in Linux its not available using the -m flag option?

am currently installing Linux to that i get full features

**Comment by emanuele-f** [comment]
@james-shumba, since 17 November the per-host report has been moved to the enterprise edition. Please contact us to get a trial if interested. Thank you.

**Comment by james-shumba** [comment]
Thanks. Please give me the trial and advise what the upgrade entails from the current license I have
