### ISSUE TITLE
Fix link from live to historical flow

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#8337]
In the below example, clicking on the flow chart:
- the historical flow filter contains ports set to 0 as this is an icmp flow: ports should be omitted in this case
- it results in an empty table as the time interval is too short

<img width="1473" alt="Screenshot 2024-04-17 at 09 56 53" src="https://github.com/ntop/ntopng/assets/7548711/07be0d74-5bda-474b-a6c5-496b59e23d11">
<img width="1490" alt="Screenshot 2024-04-17 at 09 57 05" src="https://github.com/ntop/ntopng/assets/7548711/9500ae5f-d4b6-47eb-9e2b-391c9aab8667">

**Comment by MatteoBiscosi** [comment]
Fixed both filters with port 0 (the only exception is with ports) and the duration too, minimum duration is now 5 minutes, because like displayed in the screenshot, the flow is cut into multiple flows if the duration is higher than 5 minutes
![image](https://github.com/ntop/ntopng/assets/49585191/4e2ce8f5-5fdd-41b4-8efa-8c7a4e41832d)

**Comment by cardigliano** [comment]
I am still getting the Port 0 filters
