### ISSUE TITLE
packages.ntop.org ip address is mentioned in some blacklists

### ISSUE THREAD

**Issue by dodysw3** [ntop/ntopng#8344]
**Environment**:
All

**What happened**:
Visiting https://packages.ntop.org resulted in refused connection. ISP applies blacklists to ip address related to that domain.

**How did you reproduce it?**
```
$ ping packages.ntop.org
PING mail-digitalocean.ntop.org (167.99.215.164) 56(84) bytes of data.
From 172.16.11.12 (172.16.11.12) icmp_seq=1 Destination Net Prohibited
From 172.16.11.12 (172.16.11.12) icmp_seq=2 Destination Net Prohibited
From 172.16.11.12 (172.16.11.12) icmp_seq=3 Destination Net Prohibited
From 172.16.11.12 (172.16.11.12) icmp_seq=4 Destination Net Prohibited
```

**Debug Information**:

![image](https://github.com/ntop/ntopng/assets/74638001/b6a76b07-47e2-4c1e-9842-b8bac6f8dcb3)

**Comment by lucaderi** [comment]
We cannot do much against it. The host is hosted on DigitalOcean that unfortunately is not fighting enough against malware. The host is listed not because the host is a malware host, but because on the same /24 where it is hosted, some neighbours are malware hosts.
<img width="716" alt="Screenshot 2024-04-23 at 19 40 04" src="https://github.com/ntop/ntopng/assets/4493366/0953b279-b12f-4cdb-8d25-b7c4766a9f93">
