### ISSUE TITLE
Active Monitoring not sending notifications

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#8466]
**Environment**:
* ntopng version/revision: [ntopng Enterprise XL v.6.1.240623 (Ubuntu 22.04.4 LTS) ](https://www.ntop.org/products/traffic-analysis/ntop/)|

**What happened**:
When using Active Monitoring with continuous ICMP and Notifications only set for Active Monitoring, no alert is issued.

<img width="573" alt="Screenshot 2024-06-23 at 15 42 54" src="https://github.com/ntop/ntopng/assets/38549755/b7aee3be-efb5-4ec4-9fea-4ae1675743b3">
<img width="981" alt="Screenshot 2024-06-23 at 15 44 47" src="https://github.com/ntop/ntopng/assets/38549755/0b42c481-7561-4f28-b12b-70f8adaf54ef">

<img width="431" alt="Screenshot 2024-06-23 at 15 48 01" src="https://github.com/ntop/ntopng/assets/38549755/3d664ff6-aba6-4b52-bdce-f3b61f324c43">

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu the issue should now be fixed, in a couple of hours a new build should be available.
Maybe i'd suggest using just the active monitoring alert:
![image](https://github.com/ntop/ntopng/assets/49585191/4f812ace-417e-4ce7-9d74-4ade69748a62)

**Comment by martinscheu** [comment]
alright, thank you @MatteoBiscosi 
I will set Alerts accordingly.

**Comment by martinscheu** [comment]
I do get an alert, but somehow not in a periodic way. If I have a continuous ICMP and the IP is not reachable and I have disabled "Silence Duplicated Alerts" I assume I get an alert in a periodic way, e.g. every 30min or so?

**Comment by martinscheu** [comment]
Not sure if it is working correctly, @MatteoBiscosi 
I've added more IPs to the same recipient, but even 4 of the IPs, from which 3 of them I've put new, where never reachable, I only got an alert when restarting ntopng after auto update in the early morning:

<img width="1157" alt="Screenshot 2024-07-05 at 15 29 21" src="https://github.com/ntop/ntopng/assets/38549755/e5891051-bf1a-4edb-9a5d-1f31e2c99933">
<img width="1140" alt="Screenshot 2024-07-05 at 15 28 53" src="https://github.com/ntop/ntopng/assets/38549755/540af10d-2e5a-42ae-90e1-7728587962a0">
<img width="555" alt="Screenshot 2024-07-05 at 15 28 18" src="https://github.com/ntop/ntopng/assets/38549755/22ce1cb3-9b27-44da-aeba-f9717f9580a5">

**Comment by martinscheu** [comment]
I have disabled the "Silence Duplicated Alerts" but it seems alerts anyway get silenced

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu this is normal, the alert is sent just once per state (e.g. triggered). From what i'm understanding the alert is just emitted once (first time it is not reachable for example) in your case, right? If so, that's the expected output. We did so in order to not flood the user with alerts, consider that the active monitoring are checked every minute so if we did differently you'd receive an alert to your endpoint every minute.
Other than that are you receiving an alert per monitored device? or not?

**Comment by MatteoBiscosi** [comment]
Secondly, you received the other alerts after the startup probably because the alert of being unreachable was already triggered before adding the hosts to the new endpoint and in this case the alert is not delivered (because the state already changed).
You got notifications after the startup because at that point the situation starts anew and the endpoint was configured before the trigger of the alert

**Comment by MatteoBiscosi** [comment]
Please reopen if needed
