### ISSUE TITLE
Need help connecting to Mikrotik Router from Mac version of ntopng

### ISSUE THREAD

**Issue by abibleboy** [ntop/ntopng#855]
I need help connecting to my Mikrotik using its Traffic Flow. I have set up ntopng on my macbook. It seems to use something called a redis-server instead of nprob (i think). I have set my macbook as a target on the listening port of the redis-server. But all i get when i start the ntopng and look on the web interface is my local interfaces not the router board or any of its interfaces. What am i missing? There seems to be very little info on how to set up the mac version of ntopng so any pointers would be welcome.

**Comment by emanuele-f** [comment]
Hi @abibleboy, the redis-server is something not related to nprobe. What you really need in order to see the traffic of your Mikrotik is nProbe, which requires a paid licence but it's also available in a 10 minutes trial. Check out http://packages.ntop.org/ to install it and contact us via email if you need licence support.

In order to configure you Mikrotik setup, please refer to this guide http://www.ntop.org/ntopng/how-to-analyse-mikrotik-traffic-using-ntopng/

**Comment by abibleboy** [comment]
Thanks for the response.

I went and looked at the Packages , which one will work on my Mac ? I don't see an OS X link ... ... also what's the redis- server doing then ?

Thanks

**Comment by simonemainardi** [comment]
@abibleboy you can install ntopng on mac osx using `homebrew` (http://www.ntop.org/ndpi/running-ntopng-and-ndpi-on-macosx/) or by building it from sources. However, nProbe, that is required to collect flows from the mikrotik, is not available for os x. So you should plan to install it on a supported architecture.

redis server is used my ntopng as a cache and to store configurations and options. It's a dependency but you, as a user, won't need to interact with it.
