### ISSUE TITLE
Flow dropped due to limits to the license

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#8626]
**Environment**:
Ubuntu 22.04
ntopng 6.2.240814

**What happened**:

After upgrading to 6.2 ntopng show license error on start:
15/Aug/2024 12:56:58 [ParserInterface.cpp:104] Flow dropped due to limits to the license. Exporters limit: 32 | Exporters Interfaces limit: 2048

Enterprise XL license installed.

**Comment by lucaderi** [comment]
Can you please provide log/evidences about the number of monitored netflow interfaces and devices you have?

**Comment by zebinho20-belenus** [comment]
same here with 
ntopng Enterprise L v.6.2.240814 

16/Aug/2024 13:01:57 [ParserInterface.cpp:104] Flow dropped due to limits to the license. Exporters limit: 16 | Exporters Interfaces limit: 256


#######
same error with 

[ntopng Enterprise L v.6.3.240816 (Ubuntu 22.04.4 LTS)

16/Aug/2024 14:51:53 [ParserInterface.cpp:104] Flow dropped due to limits to the license. Exporters limit: 16 | Exporters Interfaces limit: 256

**Comment by atemix** [comment]
Hi @lucaderi 
We have 1 interface configured in ntopng.
![image](https://github.com/user-attachments/assets/e75352cd-ad4b-4074-8d62-6b73f6924f71)

1 ntopng collecting flows from 30 netflow / sflow nprobe's.
![image](https://github.com/user-attachments/assets/8da52480-c628-4b3d-95d5-bbc0b2763c6d)

About 80+ devices sending flows at this moment to nprobe's.

Most of traffic ignored by ntopng after 6.2 update.
![image](https://github.com/user-attachments/assets/c2fb4896-53c6-4e64-a757-fc67b877abb9)

**Comment by 612wong** [comment]
I have had a similar issue following the nightly builld upgrade from 6.1 to 6.3
I noticed the error message '20/Aug/2024 12:09:49 [ParserInterface.cpp:104] Flow dropped due to limits to the license. Exporters limit: 8 | Exporters Interfaces limit: 256' 
![image](https://github.com/user-attachments/assets/a7ec1cec-58da-40c6-9b35-7238cf88eea4)
In my region, I relies on flow collection a lot other than packet processing. Wonder if there is a feature to rollback to an older release.

**Comment by lucaderi** [comment]
This check was not enforced on previous versions. Unless you want to use a more capable software version, please distribute traffic across additional interfaces so you can avoid the block.

**Comment by 612wong** [comment]
I don't get it. The M license is supposed to have up to 16 interfaces. On my setup, there are less than 16 interfaces (including the virtual interface by the custom traffic disaggregation. I don't expect to have 32 or 64 interfaces. I just want to have what I paid.

**Comment by Westy-87** [comment]
The 'interfaces' limit is really deceiving. If you only monitor flows on one interface, but that interface is on a switch with 48 ports, it will record the ingress/egress interface ID of the traffic and so it can actually be recording 48 interfaces even though you're only monitoring 1 port on a switch
