### ISSUE TITLE
Invalid SYN Flood Error

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8631]
<img width="1690" alt="Screenshot 2024-08-18 at 11 07 13" src="https://github.com/user-attachments/assets/f57732d1-9e85-4f90-94da-fae751c76a66">

if a host makes many successful requests/sec they should not be accounted in the SYN flood check

**Comment by lucaderi** [comment]
You can replicate it sniffing traffic generated by tools such as

```wget --no-parent -r http://WEBSITE.com/```

that can traverse a HTTP server and recursively fetch data

**Comment by sulaimansuhas** [comment]
Hi @lucaderi,

To solve this bug we should keep track of half established TCP connections rather than the total number of SYN packets sent/received. I have 3 potential approaches to solve this issue and would love to have some input on which would be preferred:
1.  Similar to what is being done already we take samples every 1 second of the number of half established connections. Every 1 minute we take a sample of the highest number of established connections seen in a 1 second window.
2. We can keep an ongoing count of the open connections and sample the count every 1 minute.
3. We can keep an ongoing count of the open connections and trigger an alert whenever the threshold is exceeded.

**Comment by lucaderi** [comment]
This code overlaps with SYN scan that is enough for our needs
