### ISSUE TITLE
Host Alias not on Top Local Hosts 1 Week Ago

### ISSUE THREAD

**Issue by infinitynet2011** [ntop/ntopng#8688]
Hello, 

The Host Alias is showing only on "**Top Local Hosts**"  but not shown on "**Top Local Hosts 1 Week Ago**"

![image](https://github.com/user-attachments/assets/a98050d0-5a5d-4944-ab01-d8eaa802ff13)

Thanks,
Gabriel

**Comment by cardigliano** [comment]
@infinitynet2011 this seems to be working in our lab, a couple of questions:
- what ntopng version are you running?
- could you check the Historical Flows and make sure there was an alias for the host in the database for the past week?

**Comment by infinitynet2011** [comment]
Hello Alfredo,

ntopng Enterprise M v.6.3.240901 (Rocky Linux release 9.3)

![image](https://github.com/user-attachments/assets/6e076bdc-5b37-4bce-8d30-249d5561833d)


Before the 26 I dont have anything.

Thanks,
Gabriel

**Comment by MatteoBiscosi** [comment]
Hi @infinitynet2011 the issue should now be fixed, however the fix will apply to the new data, unfortunately i cannot  fix the issue with the old data, being that the src/dst label for old data misses the naming itself due to aggregation issues.
So please let me know with the new data if the issue persists

**Comment by infinitynet2011** [comment]
Yes, it's okay now, thank you.
