### ISSUE TITLE
Invalid SNMP MAC Formatting

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8698]
<img width="1186" alt="Screenshot 2024-09-04 at 16 56 36" src="https://github.com/user-attachments/assets/2e811bb0-7a40-4132-9ace-a585c6f314a9">

**Comment by cardigliano** [comment]
After digging a bit I found that the problem lies in the script.hooks.snmpDeviceInterface hook in snmp_device_interface_mac_detection.lua as the MAC address sometimes seems corrupted or not well formed.
A check on the MAC format has been added, with a debug trace with a traceback as this requires digging more on the data source.

**Comment by cardigliano** [comment]
Fixed in 6f1e9cf2cc8e96309a3711c1d836d4026a9e2adb (pro)

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, in case it is not please reopen the ticket
