### ISSUE TITLE
User Traffic Reset After Nedge Reboot

### ISSUE THREAD

**Issue by shabi61** [ntop/ntopng#8706]
Description:
If Nedge is rebooted while a user is connected, the user’s traffic from the previous session is reset to zero upon reconnection. 
This might be related to Issue ticket #8685, as both involve modifications to session traffic and time data during reconnection.

Expected Behavior:
After Nedge is rebooted, the user’s session traffic should persist and not be reset to zero.

Steps to Reproduce:

1- Reboot Nedge while a user is connected.
2- Reconnect the user.
3- Check the previous session’s traffic.

#Nedge+Radius

**Comment by lucaderi** [comment]
The current behaviour is correct. The Radius RFC has the interim update message to handle periodic billing from the radius client (nEdge) to the server. This update message is sent periodically (and not just at the end of the session) as it might be that one of the peers disconnects e.g. due to a restart. It is the responsibility of the billing application to handle these holes in billing. Unfortunately, as radius (nor nEdge) has no persistency (the would-be useless in edge cases such as crash) this behaviour is correct as is.
