### ISSUE TITLE
Timeseries Timepicker Month Change Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8862]
<img width="744" alt="image" src="https://github.com/user-attachments/assets/499cace0-02a9-446f-b238-d1771343965d">

Changing the month on the time picker (or anything else in the popup window) is broken

**Comment by MatteoBiscosi** [comment]
This issue is unfixable right now, the component works in the following way:
after changing the month the user has to click on a day to make the change applyable.
This is the behavior of the component and cannot be changed. Moreover after investigating all other well known websites have the same behavior (see Trivago or Booking).
