### ISSUE TITLE
Data issue when starting nProbe

### ISSUE THREAD

**Issue by ppoudrier** [ntop/ntopng#958]
Hello, using the latest version of nprobe and ntopng, I get strange behavior on the dashboard
![image4163](https://cloud.githubusercontent.com/assets/25464346/22480422/556c8f7e-e7bf-11e6-9387-bd5e739d4806.png)

I pointed the issues within the screenshot

1. The right graph in firefox stretch themself after some time (usualy aroung 2-5 minutes). I need to refresh the page to be able to show them the right size
2. When I restart nProbe, there is huge traffic spike (that is impossible due to the fact that the spike is largely over the maximum bandwidth. It seem to get stabilized after 1h
3. This seem to be the current Ingress traffic + Egress traffic combined but on my other monitoring tool, this is the current Ingress traffic only
4. I think that this must be the current Ingress/Egress traffic separated (which should match the amount in 3 but it's not.
5. The total speed on those host (which I left hidden for privacy) cannot be that high. I see sometime client that bandwidth is limited to 10Mbits doing over 300Mbits speed.

**Startup config for nprobe :**
--zmq "tcp://*:5556"
-i ens2f0
-n none
--local-networks="My Local Subnet"
--lru-cache-size=131072
-r
-u -1
-Q -1
-T "%IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_NEXT_HOP %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %IN_BYTES %OUT_BYTES %OUT_PKTS %DIRECTION %FLOW_START_SEC %FLOW_END_SEC %FIRST_SWITCHED %LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %L7_PROTO %RTP_IN_JITTER %RTP_OUT_JITTER %RTP_OUT_JITTER %RTP_OUT_PKT_LOST %RTP_IN_PKT_DROP %RTP_OUT_PKT_DROP %RTP_IN_MAX_DELTA %RTP_OUT_MAX_DELTA %RTP_SIP_CALL_ID %RTP_RTT %SIP_CALL_ID %SIP_CALLING_PARTY %SIP_CALLED_PARTY %SIP_RTP_CODECS %SIP_INVITE_TIME %SIP_TRYING_TIME %SIP_RINGING_TIME %SIP_INVITE_OK_TIME %SIP_INVITE_FAILURE_TIME %SIP_RESPONSE_CODE %SIP_REASON_CAUSE %SIP_C_IP %SIP_CALL_STATE"

Startup config for ntopng :
--pid=/var/tmp/ntopng.pid
--interface="tcp://127.0.0.1:5556"
--daemon=
--http-port=IP:3000
--redis=localhost:6379@2
# Do not resolve any names
--dns-mode=3
# Limit memory usage
--max-num-flows=900000
--max-num-hosts=500000
--sticky-hosts=none
--local-networks="My local network"

# Dump flows to MySQL
--dump-flows=mysql;localhost;ntopng;flows;ntopng;pwd

I hope it will help.

**Comment by lucaderi** [comment]
When you say the latest version, do you mean the latest development build correct?

**Comment by ppoudrier** [comment]
I mean the latest stable release. I didn't installed the development version as of now. I can do it if you consider it stable enough for me to test the application

**Comment by ppoudrier** [comment]
I tried the dev version and the problem is still here.

**Comment by simonemainardi** [comment]
@ppoudrier what problem? Please be more specific, you listed 5 different issues

also please post ntopng and nprobe version used

**Comment by ppoudrier** [comment]
Effectively, there is 5 issues on this screenshot. So I consider that the problem is about all of this.

nProbe v.7.5.170201 (r5628) on ubuntu
ntopng v.2.5.170201

I had the same problem with the latest release version (installed yesterday) which I can't find the current release. (it's 7.4.?? and 2.4.??)

**Comment by emanuele-f** [comment]
Please clarify the ntopng version you experience the issues on:
- *stable* one (ntopng 2.4, nprobe 7.4)
- *development* one (ntopng 2.5, nprobe 7.5)

What we really need to know is if you experience each of the 1-5 points in the *development* version

**Comment by simonemainardi** [comment]
hi @ppoudrier , I went analyzed all the issues you reported using the latest dev of both ntopng and nProbe. Please see below.

> 1. The right graph in firefox stretch themself after some time (usualy aroung 2-5 minutes). I need to refresh the page to be able to show them the right size

Tried with FF for more than one hour. Also tried to stretch the page but the charts always keep the same size. I can confirm this issue is fixed.

> 2. When I restart nProbe, there is huge traffic spike (that is impossible due to the fact that the spike is largely over the maximum bandwidth. It seem to get stabilized after 1h

nProbe, when shutting down, expires all the active flows it is currently processing and transmits them to the ntopng in a very short period of time. This explains the peak. Under normal activities, the flows won't expire together.

> 3. This seem to be the current Ingress traffic + Egress traffic combined but on my other monitoring tool, this is the current Ingress traffic only

I have made a fix.

> 4. I think that this must be the current Ingress/Egress traffic separated (which should match the amount in 3 but it's not.

No, this is the local-to-remote and remote-to-local traffic. In other words, it is the traffic that is originated from (destined to) addresses belonging to your local network.

> 5. The total speed on those host (which I left hidden for privacy) cannot be that high. I see sometime client that bandwidth is limited to 10Mbits doing over 300Mbits speed.

This is the way it works with flows. Flows, by definition, quantize network information. nProbe does periodic exports of active flows -- say every 2 minutes -- so the ntopng is not able to know what happened during the 2 minutes, it just receives the exported flow at the end of the period.
This phenomenon is more prominent for long-lived flows and should be negligible for short lived flows.

Mitigating these peaks would require more sophisticated stuff to compute second-by-second statistics for top hosts and top protocols directly on the nProbe.

**Comment by simonemainardi** [comment]
All the issues reported have been addressed and discussed above. Closing.
