### ISSUE TITLE
PSA: Unable to login with enabled NoScript AddOn (JS allowed)

### ISSUE THREAD

**Issue by vnznznz** [ntop/ntopng#969]
Hi,

Just a PSA, I don't think you have to fix anything.

* Installed ntopng ob Ubuntu 16.10 from office sources (apt install ntopng)
* Was unable to login with default credentials
* Tried everything with redis-cli  SET user.admin.passwod (md5hash) and redis-cli ntopng.admin etc...
* Purged ntopng from my system, reinstalled, still not able to login
* Disabled NoScript AddOn in my Firefox (JS was allowed for 127.0.0.1) -> Now I'm able to login. (default credentials)

There is probably a some overlap between security minded NoScript-Users and ntopng-Users, so this hopefully useful for someone.

Sorry for abusing your Issuetracker, I don't have the time to write a proper PR for your documentation.

Cheers,
Vinzenz

**Comment by emanuele-f** [comment]
Hi, I've just tried to run ntopng with noscript.
Without any additional setting, I'm able to login with default credentials (admin admin) but I'm not able to navigate. When I click "Allow 127.0.0.1" I'm able to navigate and use ntopng, but noscript still report "Scripts Partially Allowed" (it still blocks ghbtns and ripe for example).
So, in order to have full functionality on ntopng, you should allow both the localhost and the other external sites when propted.

**Comment by simonemainardi** [comment]
This is something that should be checked with NoScript devs.
